# scripts/diag_builders/create_tier5.py
import sys
from pathlib import Path

# We will construct tier5_toeic.py containing 25 subtopics * 10 questions = 250 items.
# IDs: diag-1001 to diag-1250.
# Target: 多益高分 (TOEIC B2)

OUTPUT_FILE = Path(__file__).resolve().parent / "tier5_toeic.py"

subtopics = [
    # 1. 商務合約簽訂與法律條款 (Contracts, Clauses & Compliance)
    ("商務合約簽訂與法律條款", "商務文法", "B2-U01", [
        ("The terms of the non-disclosure agreement are legally ___ on all participating parties.", "binding", "bind", "bounded", "binds", "該保密協議中的條款對所有簽署方均具備法律約束力。", "legally binding 為商務法律固定搭配，意為「具法律約束力的」。", "be legally binding on 構成固定用法。", "binding", "/ˈbaɪn.dɪŋ/", "具約束力的", "clause", "/klɑːz/", "條款條目"),
        ("Any breach of the contractual obligations will result in immediate ___ of the partnership.", "termination", "terminate", "terminating", "terminated", "任何違反合約義務之行為將導致雙方合作關係立即終止。", "介系詞 in 之後須接名詞 termination 作受詞。", "result in + 名詞 termination。", "breach", "/briːtʃ/", "違約違反", "termination", "/ˌtɝː.məˈneɪ.ʃən/", "終止結束"),
        ("The vendor must ___ with all statutory environmental safety regulations during construction.", "comply", "compliance", "compliant", "complied", "承包商在施工期間必須嚴格遵循所有法定環境安全法規。", "助動詞 must 後方接原形動詞 comply，搭配介系詞 with。", "must + 原形動詞 comply with。", "statutory", "/ˈstætʃ.ə.tɔːr.i/", "法定的", "comply", "/kəmˈplaɪ/", "遵循遵守"),
        ("The agreement will remain in ___ until the audit report is officially published next month.", "effect", "affect", "effective", "effectiveness", "該項協議將持續生效，直至下個月正式公布稽核報告為止。", "remain in effect 為商務常用固定搭配，意為「持續有效、生效中」。", "remain in effect 表持續有效。", "audit", "/ˈɑː.dɪt/", "查帳稽核", "effect", "/əˈfekt/", "效力生效"),
        ("The supplier failed to deliver the raw materials within the ___ timeframe specified in clause 4.", "stipulated", "stipulate", "stipulating", "stipulation", "供應商未能於合約第四條所規定的時限內交付原物料原料。", "過去分詞 stipulated 作形容詞，修飾名詞 timeframe，意為「規定的、明訂的」。", "形容詞修飾名詞選 stipulated。", "raw material", "/ˌrɑː məˈtɪr.i.əl/", "原物料", "stipulate", "/ˈstɪp.jə.leɪt/", "約定明訂"),
        ("All intellectual property rights arising from this project belong ___ to the client.", "exclusively", "exclusive", "exclusivity", "exclusion", "本專案所衍生之所有智慧財產權均獨家專屬歸客戶所有。", "副詞 exclusively 修飾動詞片語 belong to，意為「專屬地、獨佔地」。", "副詞修飾動詞選 exclusively。", "intellectual", "/ˌɪn.təlˈek.tʃu.əl/", "智力的", "exclusively", "/ɪkˈskluː.sɪv.li/", "專屬獨佔地"),
        ("In the event of a dispute, both companies agreed to seek binding ___ rather than litigation.", "arbitration", "arbitrate", "arbitrator", "arbitrary", "若發生爭端爭議，兩家公司同意尋求具約束力的仲裁而非走向訴訟程序。", "名詞 arbitration 意為「仲裁」，接在形容詞 binding 之後。", "binding arbitration 表具約束力仲裁。", "litigation", "/ˌlɪt̬.əˈɡeɪ.ʃən/", "訴訟程序", "arbitration", "/ˌɑːr.bəˈtreɪ.ʃən/", "仲裁公斷"),
        ("Either party may terminate this contract upon thirty days' written ___ to the other.", "notice", "notify", "notified", "notification", "任何一方在提前三十天給予對方書面通知後，均可終止本合約。", "written notice 為標準法律用語，意為「書面通知」。", "upon written notice 固定用法。", "written notice", "/ˌrɪt.ən ˈnoʊ.tɪs/", "書面通知", "party", "/ˈpɑːr.t̬i/", "當事方一方"),
        ("The contractor is held ___ for any structural damage caused by negligence during renovation.", "liable", "liability", "liably", "liaise", "承包商若在裝修期間因疏忽造成任何結構性損壞，須承擔法律責任。", "be held liable for 為固定法律搭配，意為「被認定對…負有責任」。", "be held liable for 負法律責任。", "negligence", "/ˈneɡ.lə.dʒəns/", "疏忽過失", "liable", "/ˈlaɪ.ə.bəl/", "負有責任的"),
        ("The confidentiality clause shall survive the ___ or expiration of this master agreement.", "termination", "terminate", "terminating", "terminated", "本保密條款在主合約終止或期滿之後，仍將繼續具備法律效力。", "對等連接詞 or 連接名詞 expiration，前方空格亦須為名詞 termination。", "名詞對等選 termination。", "confidentiality", "/ˌkɑːn.fəˌden.ʃiˈæl.ə.t̬i/", "保密機密性", "expiration", "/ˌek.spəˈreɪ.ʃən/", "到期滿期")
    ]),
    # 2. 跨國採購與供應鏈管理 (Procurement & Supply Chain Management)
    ("跨國採購與供應鏈管理", "商務文法", "B2-U02", [
        ("The procurement department has successfully negotiated a 15% discount for ___ orders.", "bulk", "bulky", "bulkiness", "bulks", "採購部門已成功為大宗大量訂單爭取到了八五折的優惠折扣。", "bulk orders 為商務採購固定名詞詞組，意為「大宗訂單、批量訂單」。", "大宗訂單搭配 bulk orders。", "procurement", "/prəˈkjʊr.mənt/", "採購取得", "bulk", "/bʌlk/", "大宗大量"),
        ("Due to unprecedented harbor congestion, international cargo shipments have experienced severe ___.", "delays", "delayed", "delaying", "delayable", "由於史無前例的港口壅塞，國際貨物運送遭遇了嚴重的延誤滯留。", "形容詞 severe 之後須接複數名詞 delays 作動詞 have experienced 之受詞。", "severe 修飾名詞 delays。", "congestion", "/kənˈdʒes.tʃən/", "壅塞堵塞", "cargo", "/ˈkɑːr.ɡoʊ/", "貨物船貨"),
        ("The logistics coordinator verified that all containers were loaded ___ onto the vessel.", "securely", "secure", "security", "securing", "物流協調員確認所有貨櫃均已牢固安全地裝載至貨輪上。", "副詞 securely 修飾被動動詞 were loaded，表示裝載方式。", "副詞修飾動詞選 securely。", "logistics", "/ləˈdʒɪs.tɪks/", "物流後勤", "securely", "/səˈkjʊr.li/", "牢固安全地"),
        ("To minimize inventory holding costs, the manufacturing plant adopted a ___-in-time strategy.", "just", "soon", "right", "quick", "為了最大限度降低庫存持有成本，該製造廠採納了即時庫存生產策略。", "just-in-time (JIT) 為全球供應鏈經典術語，意為「及時制、零庫存生產制」。", "供應鏈術語選 just-in-time。", "inventory", "/ˈɪn.vən.tɔːr.i/", "庫存盤存", "holding cost", "/ˈhoʊl.dɪŋ ˌkɑːst/", "庫存維持成本"),
        ("The freight forwarder is responsible for obtaining all requisite customs clearance ___.", "documentation", "documentary", "documented", "documenting", "貨運承攬代理商負責取得所有海關通關所需的必備文件資料。", "clearance documentation 為商務復合名詞，意為「通關文件」。", "名詞修飾選 documentation。", "freight", "/freɪt/", "貨運貨物", "requisite", "/ˈrek.wə.zɪt/", "必備的必不可少的"),
        ("All warehouse personnel must conduct a thorough physical stock check ___.", "quarterly", "quarters", "quartered", "quartering", "所有倉庫員工必須每季度定期執行一次徹底的實體庫存盤點工作。", "副詞 quarterly 作時間頻率副詞，意為「每季、按季度地」。", "頻率副詞修飾全句選 quarterly。", "personnel", "/ˌpɝː.sənˈel/", "全體員工", "quarterly", "/ˈkwɔːr.t̬ɚ.li/", "按季度的"),
        ("A sudden shortage of semiconductor chips has severely ___ automotive assembly worldwide.", "disrupted", "disruption", "disruptive", "disrupting", "半導體晶片的突發短缺嚴重打亂並中斷了全球汽車組裝生產作業。", "助動詞 has + 過去分詞 disrupted 構成現在完成式主動語態。", "完成式動詞選 disrupted。", "semiconductor", "/ˌsem.i.kənˈdʌk.tɚ/", "半導體", "disrupt", "/dɪsˈrʌpt/", "打亂中斷"),
        ("The electronic purchase order will be processed once credit approval has been ___.", "granted", "granting", "grants", "grant", "電子採購訂單將在信用額度審批獲得核准通過後立即受理處理。", "主詞 credit approval 與動詞 grant 為被動關係，使用 has been granted。", "完成式被動選 has been granted。", "purchase order", "/ˈpɝː.tʃəs ˌɔːr.dɚ/", "採購單", "grant", "/ɡrænt/", "核准授予"),
        ("The distributor maintains a safety stock of spare parts to prevent supply chain ___.", "interruptions", "interrupt", "interruptive", "interrupted", "該經銷商維持著備用零件的安全庫存量，以防範供應鏈中斷風險。", "名詞 interruptions 作介系詞 prevent... of/against 之後受詞。", "名詞受詞選 interruptions。", "distributor", "/dɪˈstrɪb.jə.t̬ɚ/", "經銷商分銷商", "interruption", "/ˌɪn.t̬əˈrʌp.ʃən/", "中斷中折"),
        ("We are currently seeking a reliable vendor capable of delivering components ___ schedule.", "ahead of", "front of", "prior", "beforehand", "我們目前正在尋求一家能夠提前於預定時程交付組件的可靠供應商。", "ahead of schedule 為商務常用固定成語，意為「進度超前、提前」。", "進度超前選 ahead of schedule。", "component", "/kəmˈpoʊ.nənt/", "組件零件", "ahead of", "/əˈhed əv/", "提前於超前於")
    ]),
    # 3. 財務會計與年度預算分析 (Financial Accounting & Budgetary Analysis)
    ("財務會計與年度預算分析", "商務文法", "B2-U03", [
        ("The chief financial officer presented the ___ revenue projections for the upcoming fiscal year.", "annual", "annually", "anniversary", "annuity", "財務長在會議中展示了即將到來的新財政年度之年度預估營收數據。", "形容詞 annual 修飾名詞 revenue projections，意為「全年的、年度的」。", "形容詞修飾名詞選 annual。", "revenue", "/ˈrev.ə.nuː/", "營收歲入", "fiscal year", "/ˌfɪs.kəl ˈjɪr/", "財政年度"),
        ("The board of directors voted unanimously to distribute a quarterly ___ to common shareholders.", "dividend", "divide", "division", "divisive", "董事會全體一致投票通過，決議向普通股股東發放季度股利股息。", "名詞 dividend 意為「股息、紅利」，作動詞 distribute 之受詞。", "發放股息名詞選 dividend。", "unanimously", "/juːˈnæn.ə.məs.li/", "無異議地一致地", "dividend", "/ˈdɪv.ə.dend/", "股息紅利"),
        ("External auditors were hired to examine the ledger accounts for any financial ___.", "discrepancies", "discrepant", "discrepantly", "discrepance", "公司聘請了外部獨立審計師，以徹底檢查帳簿帳目是否存在任何財務帳實不符或差異。", "形容詞 financial 後接複數名詞 discrepancies（不一致、出入、差異）。", "名詞受詞選 discrepancies。", "ledger", "/ˈledʒ.ɚ/", "總帳分類帳", "discrepancy", "/dɪˈskrep.ən.si/", "出入不符之處"),
        ("To avoid exceeding the departmental budget, all discretionary spending has been temporarily ___.", "suspended", "suspending", "suspension", "suspensive", "為免超出部門預算，所有非必要之自由支配支出目前已暫時凍結擱置。", "主詞 discretionary spending 被暫時中止，被動態 has been suspended。", "完成式被動選 suspended。", "discretionary", "/dɪˈskreʃ.ən.er.i/", "自由裁量的非必要的", "suspend", "/səˈspend/", "暫停中止"),
        ("The firm managed to turnaround its operating loss and achieve a modest net ___ in Q4.", "profit", "profitable", "profitably", "profitability", "該公司成功扭轉了營運虧損，並在第四季實現了小幅度的淨利潤。", "形容詞 modest net 修飾名詞 profit（淨利）。", "名詞搭配選 net profit。", "turnaround", "/ˈtɝːn.ə.raʊnd/", "轉虧為盈扭轉", "modest", "/ˈmɑː.dɪst/", "適度的小幅的"),
        ("All capital expenditure requests exceeding $50,000 require formal ___ from executive committee.", "authorization", "authorize", "authoritative", "authorized", "所有超過五萬美元之資本支出申請，均須取得執行委員會的正式核准授權。", "形容詞 formal 修飾名詞 authorization（授權核准）。", "形容詞修飾名詞選 authorization。", "expenditure", "/ɪkˈspen.də.tʃɚ/", "支出花費", "authorization", "/ˌɑː.θɚ.əˈzeɪ.ʃən/", "授權核准"),
        ("The corporation's debt-to-equity ratio has improved significantly over the past two ___ quarters.", "consecutive", "consecutively", "consequence", "consequent", "該企業的負債權益比在過去連續兩個季度中已獲得顯著改善。", "形容詞 consecutive 修飾名詞 quarters，意為「連續的」。", "連續季度選 consecutive quarters。", "debt-to-equity", "/ˌdet tuː ˈek.wə.t̬i/", "負債對權益比", "consecutive", "/kənˈsek.jə.t̬ɪv/", "連續的連貫的"),
        ("Tax regulations require that all business-related receipts be ___ for at least seven years.", "retained", "retaining", "retains", "retain", "稅法規章嚴格要求，所有與業務相關之收據憑證均須妥善保存至少七年。", "require that 後名詞子句省略 should，be 動詞後接被動過去分詞 retained。", "要求子句被動態選 retained。", "receipt", "/rɪˈsiːt/", "收據發票憑證", "retain", "/rɪˈteɪn/", "保留保存"),
        ("The depreciation of manufacturing equipment is accounted ___ on a straight-line basis.", "for", "with", "about", "to", "工廠生產製造設備之折舊是按照直線折舊法進行核算入帳的。", "動詞片語 account for 意為「核算、說明、占有比例」。", "固定動詞片語 account for。", "depreciation", "/dɪˌpriː.ʃiˈeɪ.ʃən/", "折舊貶值", "straight-line", "/ˈstreɪt.laɪn/", "直線的均勻的"),
        ("The company allocated a generous portion of its surplus to research and ___ initiatives.", "development", "developer", "developing", "developed", "該公司將其盈餘結餘的慷慨一部分提撥投入於研發新創專案之中。", "research and development (R&D) 為企業研究與開發之固定複合名詞。", "固定複合名詞選 development。", "surplus", "/ˈsɝː.pləs/", "盈餘過剩", "allocate", "/ˈæl.ə.keɪt/", "分配撥給")
    ]),
    # 4. 人力資源招聘與福利制度 (HR Recruitment, Compensation & Benefits)
    ("人力資源招聘與福利制度", "商務文法", "B2-U04", [
        ("The successful candidate will receive a competitive salary package commensurate ___ experience.", "with", "to", "for", "by", "錄取之理想人選將獲得與其工作資歷經驗完全相稱且具競爭力的薪酬待遇。", "be commensurate with 為高頻商務招聘慣用搭配，意為「與…相稱、符合」。", "固定搭配選 commensurate with。", "candidate", "/ˈkæn.dɪ.dət/", "候選人人選", "commensurate", "/kəˈmen.sjɚ.ət/", "相稱的相當的"),
        ("Prospective applicants are requested to submit three letters of ___ along with their résumé.", "recommendation", "recommend", "recommending", "recommended", "有意應徵之求職者請於寄送履歷表時，一併附上三封推薦信函。", "letters of recommendation 為固定名詞片語，意為「推薦信」。", "固定名詞片語 letters of recommendation。", "prospective", "/prəˈspek.tɪv/", "潛在的預期的", "résumé", "/ˈrez.ə.meɪ/", "履歷表"),
        ("The Human Resources department is actively ___ qualified applicants for senior engineering roles.", "recruiting", "recruited", "recruitment", "recruit", "人力資源部目前正在積極為高階資深工程師職缺招募合格求職人才。", "is actively recruiting 為現在進行式主動語態，修飾動態招募行為。", "現在進行式主動選 recruiting。", "recruitment", "/rɪˈkruːt.mənt/", "招募聘用", "actively", "/ˈæk.tɪv.li/", "積極地活躍地"),
        ("Full-time employees are eligible ___ comprehensive medical coverage after completing probation.", "for", "to", "with", "of", "全職員工在順利通過試用期考核後，即享有享有完整醫療保險之資格權益。", "be eligible for + 名詞 為高頻固定搭配，意為「有資格享有…」。", "固定資格搭配選 eligible for。", "probation", "/proʊˈbeɪ.ʃən/", "試用期審查期", "eligible", "/ˈel.ə.dʒə.bəl/", "符合資格的"),
        ("An objective performance appraisal is conducted annually to evaluate each employee's ___.", "productivity", "productive", "productively", "product", "公司每年定期進行客觀的績效考評，以評估每位員工之工作生產力與表現產出。", "名詞 productivity 作動詞 evaluate 之受詞。", "評估生產力名詞選 productivity。", "appraisal", "/əˈpreɪ.zəl/", "考評估價", "productivity", "/ˌproʊ.dʌkˈtɪv.ə.t̬i/", "生產力生產效率"),
        ("The company offers tuition ___ for employees pursuing job-related graduate degrees.", "reimbursement", "reimburse", "reimbursed", "reimbursing", "公司為攻讀與職能工作相關之研究所學位的員工提供學費報銷補助。", "tuition reimbursement 為福利制度固定名詞片語，意為「學費報銷補助」。", "固定名詞片語 tuition reimbursement。", "tuition", "/tuːˈɪʃ.ən/", "學費", "reimbursement", "/ˌriː.ɪmˈbɝːs.mənt/", "報銷退還款項"),
        ("Management announced that voluntary retirement packages would include substantial ___ pay.", "severance", "severe", "severely", "sever", "管理階層宣布，自願離退方案中將包含極具誠意之實質資遣退職金。", "severance pay 為標準商務人事術語，意為「資遣費、遣散費」。", "固定人事用語 severance pay。", "voluntary", "/ˈvɑː.lən.ter.i/", "自願的非強迫的", "severance", "/ˈsev.ɚ.əns/", "離職資遣分開"),
        ("Candidates who possess bilingual proficiency will be given preferential ___ during selection.", "consideration", "consider", "considerate", "considering", "具備流利雙語能力之應徵者，在遴選聘用審查過程中將獲得優先考量。", "preferential consideration 為商務人事常用片語，意為「優先考量審核」。", "固定搭配 preferential consideration。", "bilingual", "/baɪˈlɪŋ.ɡwəl/", "雙語的", "preferential", "/ˌpref.ərˈen.ʃəl/", "優惠的優先的"),
        ("The onboarding program ensures new hires transition ___ into the corporate culture.", "smoothly", "smooth", "smoothness", "smoothed", "這套新進員工入職培訓引導計畫，確保新人能順暢無縫融入企業組織文化之中。", "副詞 smoothly 修飾動詞 transition，表示轉銜適應之狀態。", "副詞修飾動詞選 smoothly。", "onboarding", "/ˈɑːnˌbɔːr.dɪŋ/", "入職引導新人培訓", "transition", "/trænˈzɪʃ.ən/", "過渡轉換"),
        ("Employees are encouraged to maintain a healthy work-life balance to avoid workplace ___.", "burnout", "burning", "burned", "burn", "公司鼓勵員工保持健康的工時與生活平衡，以避免在職場中產生職業倦怠枯竭。", "名詞 burnout 意為「身心俱疲、職業倦怠」，作介系詞 avoid 後之受詞。", "職業倦怠名詞選 burnout。", "workplace", "/ˈwɝːk.pleɪs/", "職場工作場所", "burnout", "/ˈbɝːn.aʊt/", "精疲力竭職業倦怠")
    ]),
    # 5. 產品行銷策劃與品牌推廣 (Marketing Campaigns & Brand Promotion)
    ("產品行銷策劃與品牌推廣", "商務文法", "B2-U05", [
        ("The new social media advertising campaign is aimed specifically ___ Gen Z consumers.", "at", "to", "for", "with", "這波全新的社群媒體廣告行銷活動，其目標族群明確鎖定於Z世代年輕消費者。", "be aimed at 為高頻行銷固定搭配，意為「以…為目標對象」。", "鎖定目標客群選 be aimed at。", "campaign", "/kæmˈpeɪn/", "行銷活動宣傳", "demographic", "/ˌdem.əˈɡræf.ɪk/", "受眾族群人口學特徵"),
        ("Innovative influencer partnerships have significantly elevated global brand ___.", "awareness", "aware", "awares", "awarenesses", "創新的網紅KOL合作模式，已大幅顯著提升了品牌在國際市場上的知名度。", "brand awareness 為行銷界經典核心專有名詞，意為「品牌知名度與認知度」。", "核心行銷名詞選 brand awareness。", "influencer", "/ˈɪn.flu.ən.sɚ/", "網紅意見領袖", "awareness", "/əˈwer.nəs/", "知曉度意識"),
        ("Market researchers conducted focus groups to identify emerging trends in consumer ___.", "behavior", "behave", "behavioral", "behaviors", "市場調研研究人員召開了多場焦點團體座談會，以精準掌握消費者行為之新興趨勢。", "consumer behavior 為市場營銷標準固定片語，意為「消費者行為」。", "固定行銷術語 consumer behavior。", "focus group", "/ˈfoʊ.kəs ˌɡruːp/", "焦點座談小組", "behavior", "/bɪˈheɪ.vjɚ/", "行為舉止"),
        ("The promotional launch was so successful that pre-orders exceeded initial ___ by 40%.", "projections", "project", "projecting", "projector", "此次新產品促銷發布極為成功，預購訂單數量甚至超出最初預估估計值達40%。", "initial projections 意為「初步預測數值、初期推估量」。", "名詞選 projections。", "promotional", "/prəˈmoʊ.ʃən.əl/", "促銷宣傳的", "projection", "/prəˈdʒek.ʃən/", "推測預測值"),
        ("The PR department issued a formal retraction after an advertisement drew public ___.", "criticism", "criticize", "critical", "critically", "在一則廣告內容引發廣泛社會公眾批評與非議後，公關部門正式發布了撤回聲明。", "drew public criticism 為動賓慣用搭配，意為「招致公眾批評反彈」。", "名詞受詞選 criticism。", "retraction", "/rɪˈtræk.ʃən/", "撤回撤銷聲明", "criticism", "/ˈkrɪt̬.ɪ.sɪ.zəm/", "批評評論"),
        ("Retailers offer substantial price discounts to clear out obsolete inventory and drive ___.", "volume", "voluminous", "volumize", "volumously", "零售商祭出大幅價格折價優惠，藉以出清過季過時存貨並有效拉抬銷售總量。", "drive volume 為商務銷售術語，意為「帶動銷售規模、衝高銷量」。", "衝高銷售量選 drive volume。", "obsolete", "/ˌɑːb.səˈliːt/", "過時淘汰的", "volume", "/ˈvɑːl.juːm/", "容量總量額度"),
        ("The marketing agency designed an interactive mobile app to boost customer ___.", "engagement", "engage", "engaging", "engaged", "行銷代理商特別設計了一款高互動性的行動應用程式，以提升顧客參與度與黏著度。", "customer engagement 為數位行銷核心名詞，意為「顧客互動參與度」。", "顧客參與名詞選 customer engagement。", "interactive", "/ˌɪn.t̬ɚˈæk.tɪv/", "互動式的", "engagement", "/ɪnˈɡeɪdʒ.mənt/", "參與投入互動"),
        ("Our product differentiation strategy ensures that our brand stands ___ from competitors.", "out", "by", "for", "up", "本公司之產品差異化競爭策略，確保了我們的品牌能夠在眾多競爭對手之中脫穎而出。", "stand out (from) 為高頻動詞片語，意為「顯眼突出、脫穎而出」。", "脫穎而出片語選 stand out。", "differentiation", "/ˌdɪf.ə.ren.ʃiˈeɪ.ʃən/", "差異化區隔", "competitor", "/kəmˈpet̬.ə.t̬ɚ/", "競爭者對手"),
        ("Consumers are increasingly drawn to eco-friendly products packaged in ___ materials.", "sustainable", "sustainably", "sustainability", "sustain", "現代消費者日益被採用環境友善與永續環保材料進行包裝的產品所吸引。", "形容詞 sustainable 修飾名詞 materials，意為「永續環保的」。", "形容詞修飾名詞選 sustainable。", "eco-friendly", "/ˌiː.koʊˈfrend.li/", "環保友善的", "sustainable", "/səˈsteɪ.nə.bəl/", "永續的能持久的"),
        ("By sponsoring major international sporting events, the brand maximized its global ___.", "exposure", "expose", "exposed", "exposing", "藉由冠名贊助多場重大國際體育賽事，該品牌實現了全球市場曝光度的最大化。", "名詞 exposure 作動詞 maximized 之受詞，意為「市場媒體曝光度」。", "媒體曝光名詞選 exposure。", "sponsor", "/ˈspɑːn.sɚ/", "贊助贊助商", "exposure", "/ɪkˈspoʊ.ʒɚ/", "曝光接觸面")
    ]),
    # 6. 國際貿易進出口與海關關稅 (International Trade, Tariffs & Customs)
    ("國際貿易進出口與海關關稅", "商務文法", "B2-U06", [
        ("The newly negotiated free trade agreement eliminates import tariffs ___ agricultural goods.", "on", "in", "at", "by", "這份新簽署生效的自由貿易協定，全面免除了針對農產品進口所課徵的進口關稅。", "tariffs on + 貨品品項 為固定介系詞搭配，表示「對…課徵之關稅」。", "關稅對象介系詞選 on。", "tariff", "/ˈter.ɪf/", "關稅稅則", "agricultural", "/ˌæɡ.rəˈkʌl.tʃɚ.əl/", "農業的"),
        ("Customs officials detained the shipment because the certificate of origin was ___.", "missing", "missed", "miss", "misses", "由於貨物原產地證明文件遺失不見，海關官員依法暫時查扣了整批貨櫃貨物。", "形容詞 missing 意為「不見的、遺失缺失的」，作主詞補語。", "主詞補語形容詞選 missing。", "detain", "/dɪˈteɪn/", "查扣扣留", "certificate of origin", "/sɚˈtɪf.ə.kət əv ˈɔːr.ə.dʒɪn/", "產地證明書"),
        ("Exporters must strictly adhere to international maritime dangerous goods ___.", "regulations", "regulate", "regulatory", "regulator", "出口商在進行海運外銷時，必須嚴格遵守國際海運危險品運送安全規範。", "名詞 regulations 作動詞片語 adhere to 之受詞。", "遵守法規名詞選 regulations。", "adhere to", "/ədˈhɪr tuː/", "堅守遵守", "maritime", "/ˈmer.ə.taɪm/", "海事的沿海海運的"),
        ("The imported merchandise was subject to rigorous inspection ___ entering domestic markets.", "prior to", "subsequent", "consequent", "according", "這批進口商品在進入國內銷售市場流通之前，均必須依法接受最嚴格的檢驗程序。", "prior to 為複合介系詞，意為「在…之前」，後接動名詞 entering。", "在…之前選 prior to。", "merchandise", "/ˈmɝː.tʃən.daɪs/", "商品貨品", "prior to", "/ˈpraɪ.ɚ tuː/", "在…之前"),
        ("The government imposed a strict trade ___ on luxury vehicle imports to curb deficit.", "embargo", "embarks", "embarking", "embarkation", "政府對進口豪華轎車實施了嚴格的貿易禁運限令，以遏制擴大之貿易逆差赤字。", "trade embargo 為國際貿易法術語，意為「貿易禁運限制」。", "貿易禁運名詞選 embargo。", "embargo", "/ɪmˈbɑːr.ɡoʊ/", "禁運禁止通商", "deficit", "/ˈdef.ə.sɪt/", "赤字逆差"),
        ("The bill of lading serves as definitive proof that the carrier has received the ___.", "consignment", "consign", "consigner", "consigning", "這份海運提單具有法律確定效力，足資證明運送人確實已收妥整批託運貨物。", "名詞 consignment 意為「託運貨物」，作動詞 received 之受詞。", "託運貨物名詞選 consignment。", "bill of lading", "/ˌbɪl əv ˈleɪ.dɪŋ/", "提單海運單據", "consignment", "/kənˈsaɪn.mənt/", "託運物委託代銷"),
        ("Due to fluctuations in foreign exchange rates, the profit margins on exports have ___.", "diminished", "diminish", "diminishing", "diminution", "由於外匯市場匯率劇烈波動起伏，該公司之外銷出口利潤空間已遭到嚴重壓縮萎縮。", "完成式助動詞 have + 過去分詞 diminished，意為「減少縮減」。", "完成式動詞選 diminished。", "fluctuation", "/ˌflʌk.tʃuˈeɪ.ʃən/", "波動起伏", "diminish", "/dɪˈmɪn.ɪʃ/", "減少縮小"),
        ("Importers are legally required to declare the exact commercial ___ of all imported parcels.", "value", "valuable", "valuably", "valuation", "進口商依法必須在海關申報單上，如實申報所有進口郵包包裹之精確商業價值金額。", "commercial value 為報關標準固定詞組，意為「商業申報價值」。", "名詞搭配選 commercial value。", "declare", "/dɪˈkler/", "申報宣稱", "parcel", "/ˈpɑːr.səl/", "包裹郵包"),
        ("The port authorities established a bonded warehouse where goods may be stored duty-___.", "free", "cost", "charge", "tax", "港務局特別設立了保稅免稅倉庫，使貨物在未完稅通關前得在此合法免稅儲存。", "duty-free 為固定複合形容詞/副詞，意為「免稅的、免繳關稅的」。", "免關稅選 duty-free。", "bonded warehouse", "/ˌbɑːn.dɪd ˈwer.haʊs/", "保稅倉庫", "duty-free", "/ˌduː.t̬iˈfriː/", "免稅的"),
        ("Multilateral trade negotiations stalled due to unresolved disputes over agricultural ___.", "subsidies", "subsidize", "subsidiary", "subsidizing", "多邊貿易協商談判因為各國在農業政府補貼問題上僵持不下，而陷入停滯僵局。", "名詞 subsidies 意為「政府補貼、津貼」，接在形容詞 agricultural 之後。", "政府補貼名詞選 subsidies。", "multilateral", "/ˌmʌl.tiˈlæt̬.ɚ.əl/", "多邊的多國的", "subsidy", "/ˈsʌb.sə.di/", "津貼補貼金")
    ]),
    # 7. 企業併購整合與組織架構調整 (Mergers, Acquisitions & Reorganization)
    ("企業併購整合與組織架構調整", "商務文法", "B2-U07", [
        ("The antitrust regulatory commission approved the proposed corporate merger without ___.", "conditions", "conditional", "conditionally", "conditioner", "反壟斷監管委員會在審查後，正式無條件全案通過了該項備受矚目的企業合併案。", "without conditions 意為「無條件地、不附帶任何保留條件」。", "無條件固定名詞選 conditions。", "antitrust", "/ˌæn.tiˈtrʌst/", "反托拉斯反壟斷的", "merger", "/ˈmɝː.dʒɚ/", "合併併購"),
        ("To eliminate operational redundancies, the merged conglomerate announced plans to ___ operations.", "streamline", "streamlined", "streamlining", "streamliner", "為徹底消除兩家組織重複之營運冗餘，新合併的大型跨國財團宣布精簡重整業務計畫。", "不定詞 to 之後接原形動詞 streamline，意為「簡化、精簡提升效率」。", "不定詞後接動詞原形 streamline。", "conglomerate", "/kənˈɡlɑː.mɚ.ət/", "企業集團企業托拉斯", "streamline", "/ˈstriːm.laɪn/", "精簡使效率化"),
        ("Shareholders voiced concerns regarding the high level of debt incurred during the ___.", "acquisition", "acquire", "acquired", "acquirer", "全體股東對於公司在執行敵意併購期間所背負產生之龐大高額債務深表擔憂與疑慮。", "名詞 acquisition 意為「併購收購」，接在介系詞 during 之後。", "併購名詞選 acquisition。", "incur", "/ɪnˈkɝː/", "遭受招致承擔", "acquisition", "/ˌæk.wəˈzɪʃ.ən/", "收購併購"),
        ("Following the restructuring, the regional offices will report ___ to the global headquarters.", "directly", "direct", "direction", "directness", "組織架構調整重組完畢後，所有各區域分公司將直接向全球總部匯報各項業務進展。", "副詞 directly 修飾動詞片語 report to，表示「直接地匯報」。", "副詞修飾動詞選 directly。", "restructuring", "/ˌriːˈstrʌk.tʃɚ.ɪŋ/", "組織改組重組", "directly", "/daɪˈrekt.li/", "直接地筆直地"),
        ("The newly formed joint venture will leverage both corporations' technological ___.", "expertise", "expert", "expertly", "expertism", "這家新成立的合資企業，將全面綜效槓桿兩大集團在尖端技術領域的專業深厚造詣。", "technological expertise 為高頻商務名詞片語，意為「技術專長專業知識」。", "專業名詞選 expertise。", "joint venture", "/ˌdʒɔɪnt ˈven.tʃɚ/", "合資企業合夥公司", "expertise", "/ˌek.spɝːˈtiːz/", "專門技術專業知識"),
        ("The sudden hostile takeover bid triggered an immediate emergency board ___.", "meeting", "meet", "met", "meetingly", "突如其來的敵意併購惡意收購要約，立即觸發了召開緊急董事會會議之法定程序。", "emergency board meeting 為固定複合名詞，意為「緊急董事會議」。", "複合名詞選 meeting。", "hostile takeover", "/ˌhɑː.staɪl ˈteɪkˌoʊ.vɚ/", "敵意併購惡意收購", "bid", "/bɪd/", "出價收購要約"),
        ("Corporate leadership emphasized that cultural integration is ___ to long-term merger success.", "crucial", "crucially", "crucialness", "crux", "企業最高領導高層反覆強調，組織文化深度融合是併購案長期獲致成功之不可或缺關鍵。", "形容詞 crucial 作主詞補語，搭配介系詞 to，意為「對…至關重要」。", "形容詞補語選 crucial。", "integration", "/ˌɪn.t̬əˈɡreɪ.ʃən/", "整合融入一體化", "crucial", "/ˈkruː.ʃəl/", "關鍵重大的"),
        ("Prior to finalizing the acquisition, the auditing team conducted comprehensive due ___.", "diligence", "diligent", "diligently", "diligences", "在正式敲定收購交易條款之前，會計審計團隊對目標標的企業進行了全面性的盡職調查。", "due diligence 為跨國併購核心法律專業詞組，意為「盡職調查、盡責查核」。", "盡職調查專有名詞選 diligence。", "finalize", "/ˈfaɪ.nəl.aɪz/", "敲定最後完成", "due diligence", "/ˌduː ˈdɪl.ə.dʒəns/", "盡職調查"),
        ("The parent company decided to spin ___ its unprofitable retail subsidiary next quarter.", "off", "up", "out", "in", "母公司董事會拍板定案，決議於下個季度正式將長年虧損不賺錢的零售子公司分割剝離出去。", "動詞片語 spin off 意為「將公司獨立分割出去、剝離成立獨立子公司」。", "分割子公司選 spin off。", "subsidiary", "/səbˈsɪd.i.er.i/", "子公司附屬公司", "spin off", "/ˈspɪn.ɑːf/", "分割拆分"),
        ("Synergy between the two engineering teams will yield unprecedented technological ___.", "breakthroughs", "breakthrough", "breakthroughly", "breaking", "兩支頂尖工程研發團隊之間的強大協同綜效，預料將催生創造出史無前例之重大技術突破。", "形容詞 technological 修飾複數名詞 breakthroughs（重大突破）。", "技術突破名詞選 breakthroughs。", "synergy", "/ˈsɪn.ɚ.dʒi/", "協同綜效協同作用", "breakthrough", "/ˈbreɪk.θruː/", "重大突破進展")
    ]),
    # 8. 客戶關係維繫與投訴爭議處理 (Customer Relations & Dispute Resolution)
    ("客戶關係維繫與投訴爭議處理", "商務文法", "B2-U08", [
        ("The customer support supervisor handled the dissatisfied client's grievance with extreme ___.", "diplomacy", "diplomatic", "diplomatically", "diplomat", "客服主管以極高超的外交圓融手腕與沉著耐心，妥善化解了該不滿客戶所提出的客訴抱怨。", "介系詞 with 之後接抽象名詞 diplomacy，意為「圓融手腕、交際手腕」。", "介系詞後接名詞 diplomacy。", "grievance", "/ˈɡriː.vəns/", "不滿抱怨冤情", "diplomacy", "/dɪˈploʊ.mə.si/", "交際手腕外交策略"),
        ("Our client retention rate has improved significantly since we introduced 24/7 technical ___.", "assistance", "assist", "assistant", "assisted", "自從我們全面導入全年無休的全天候技術支援熱線以來，客戶留存留任率獲得了顯著拉升。", "technical assistance 為商務客服固定複合名詞，意為「技術協助與支援」。", "複合名詞選 assistance。", "retention", "/rɪˈten.ʃən/", "保留留存", "assistance", "/əˈsɪs.təns/", "協助支援"),
        ("The airline offered flight vouchers as ___ for the passengers delayed by mechanical issues.", "compensation", "compensate", "compensatory", "compensating", "這家航空公司致贈全體旅客機票抵用券，作為對因機械故障延誤行程所提供之慰問補償。", "名詞 compensation 意為「補償金、補償」，接在介系詞 as 之後作受詞。", "補償名詞選 compensation。", "voucher", "/ˈvaʊ.tʃɚ/", "抵用券代金券", "compensation", "/ˌkɑːm.penˈseɪ.ʃən/", "補償賠償"),
        ("Customer satisfaction surveys reveal that prompt response time is considered ___ by clients.", "paramount", "paramountly", "paramounts", "paramountcy", "廣大客戶滿意度調查統計顯示，即時迅速的回應速度被廣大客戶認定為至高無上之關鍵首要指標。", "形容詞 paramount 作受詞補語，意為「至關緊要的、首要的、最重要的」。", "受詞補語形容詞選 paramount。", "survey", "/ˈsɝː.veɪ/", "問卷調查", "paramount", "/ˈper.ə.maʊnt/", "至上的極為重要的"),
        ("If an order arrives damaged, the purchaser is entitled ___ an immediate full refund.", "to", "with", "for", "by", "若收到的訂購包裹商品有任何破損受損，買受人均有合法權利要求立即全額退費退款。", "be entitled to + 名詞 為標準商務權利慣用搭配，意為「享有獲得…的權利」。", "固定權利搭配選 entitled to。", "purchaser", "/ˈpɝː.tʃə.sɚ/", "買方買受人", "entitled", "/ɪnˈtaɪ.t̬əld/", "享有權利的"),
        ("The hotel manager personally apologized to the guest for the ___ caused by the noise.", "inconvenience", "inconvenient", "inconveniently", "inconveniences", "飯店總經理親自當面向該位貴賓致歉，對於施工噪音所造成之種種生活不便深表由衷歉意。", "apologize for the inconvenience 為商務公關道歉經典名句，意為「因造成不便致歉」。", "商務道歉經典搭配選 inconvenience。", "apologize", "/əˈpɑː.lə.dʒaɪz/", "致歉賠罪", "inconvenience", "/ˌɪn.kənˈviː.njəns/", "不便打擾"),
        ("Our customer service representatives undergo rigorous training to resolve conflicts ___.", "amicably", "amicable", "amicableness", "amity", "我們的第一線客服代表均接受過嚴格專業培訓，致力於以心平氣和且和平友好的方式排解爭議。", "副詞 amicably 修飾動詞 resolve conflicts，意為「心平氣和地、友好圓滿地」。", "副詞修飾動詞選 amicably。", "representative", "/ˌrep.rɪˈzen.t̬ə.t̬ɪv/", "代表業務專員", "amicably", "/ˈæm.ɪ.kə.bli/", "友好和睦地"),
        ("A comprehensive warranty protects consumers against manufacturing ___ for up to two years.", "defects", "defective", "defectively", "defecting", "一份內容周延詳盡的原廠保固合約，保障消費者在長達兩年內免於承擔工廠製造瑕疵之風險。", "manufacturing defects 為產品質量與法規固定術語，意為「製造瑕疵缺陷」。", "製造瑕疵選 manufacturing defects。", "warranty", "/ˈwɔːr.ən.t̬i/", "原廠保固擔保", "defect", "/ˈdiː.fekt/", "瑕疵缺陷"),
        ("To expedite processing, please quote your ten-digit customer ___ when calling support.", "ID", "identify", "identification", "identical", "為大幅加快案件處理效率，致電技術客服中心時請主動出示告知您的十碼顧客會員編號。", "customer ID (identification number) 為身分識別固定用法。", "顧客身分代碼選 customer ID。", "expedite", "/ˈek.spə.daɪt/", "加快加速處理", "identification", "/aɪˌden.t̬ə.fəˈkeɪ.ʃən/", "身分證明身分識別"),
        ("The warranty becomes void if the electronic device is serviced by an ___ technician.", "unauthorized", "unauthorizing", "unauthorizedly", "unauthorization", "若此電子產品曾私自交由未經原廠合法授權之維修技師進行拆機拆修，原廠保固即刻失效作廢。", "形容詞 unauthorized 修飾名詞 technician，意為「未經原廠授權許可的」。", "形容詞修飾名詞選 unauthorized。", "void", "/vɔɪd/", "無效作廢的", "unauthorized", "/ʌnˈɑː.θɚ.aɪzd/", "未經授權的")
    ]),
    # 9. 辦公室資訊科技與網路系統維護 (IT Infrastructure & System Maintenance)
    ("辦公室資訊科技與網路系統維護", "商務文法", "B2-U09", [
        ("The IT department will conduct scheduled server maintenance to minimize system ___.", "downtime", "downside", "downpour", "downfall", "資訊技術部門將於非尖峰時段執行定期伺服器維護作業，藉以將系統當機停擺時間降至最低。", "system downtime 為資訊系統維運標準名詞片語，意為「系統停機時間」。", "停機時間專有名詞選 downtime。", "scheduled", "/ˈskedʒ.uːld/", "預定的按計畫的", "downtime", "/ˈdaʊn.taɪm/", "停機時間當機停擺"),
        ("All employees must regularly update their passwords to comply with cybersecurity ___.", "protocols", "protocol", "protocool", "protocoled", "所有全體同仁必須定期強制更換帳號密碼，以嚴格遵循公司最新制定之網路資訊安全協定規範。", "cybersecurity protocols 為固定科技名詞，意為「網路資訊安全規範協定」。", "名詞選 protocols。", "cybersecurity", "/ˌsaɪ.bɚ.səˈkjʊr.ə.t̬i/", "網路資訊安全", "protocol", "/ˈproʊ.t̬ə.kɑːl/", "協定規約議定書"),
        ("Cloud computing allows remote workers to access corporate databases from ___ location.", "any", "each", "every", "all", "雲端運算技術使遠距居家上班的員工，得以在世界上的任何地點隨時連線存取企業中央資料庫。", "from any location 為常見商務表述，修飾單數名詞 location，意為「任何地點」。", "修飾單數地點選 from any location。", "cloud computing", "/ˌklaʊd kəmˈpjuː.t̬ɪŋ/", "雲端運算", "remote", "/rɪˈmoʊt/", "遠距遙遠的"),
        ("Please verify that your operating system is fully ___ with the new enterprise software.", "compatible", "compatibility", "compatibly", "compatibleness", "在安裝前請務必確認您的電腦作業系統，是否與這套新導入之企業級管理軟體完全相容相適。", "be compatible with 為高頻科技IT固定搭配，意為「與…完全相容」。", "固定相容搭配選 compatible with。", "operating system", "/ˈɑː.pə.reɪ.t̬ɪŋ ˌsɪs.təm/", "作業系統", "compatible", "/kəmˈpæt̬.ə.bəl/", "相容適合的"),
        ("The automated backup routine ensures that vital financial data is ___ stored off-site.", "securely", "security", "secure", "securing", "系統每日夜間自動排程備份程序，確保了所有核心財務敏感數據均已安全加密存儲於異地機房。", "副詞 securely 修飾被動動詞 is stored，表示存儲之安全防護狀態。", "副詞修飾動詞選 securely。", "backup", "/ˈbæk.ʌp/", "備份備份檔", "securely", "/səˈkjʊr.li/", "安全地穩固地"),
        ("A severe malware infection caused an unanticipated outage across our regional ___.", "network", "networking", "networked", "networks", "一場嚴重的惡意勒索病毒感染，導致我們整個區域企業網路系統遭遇了意料之外的全面中斷停擺。", "名詞 network 作介系詞 across 之後受詞，意為「電腦通訊網路」。", "名詞受詞選 network。", "malware", "/ˈmæl.wer/", "惡意軟體", "outage", "/ˈaʊ.t̬ɪdʒ/", "中斷停電停擺"),
        ("The tech support team was able to troubleshoot the database glitch ___ two hours.", "within", "during", "at", "while", "資深技術支援工程師團隊展現專業能力，在不到兩小時的極短時間之內便排除了資料庫故障臭蟲。", "within two hours 為時間片語，意為「在兩小時之內完成」。", "在時限之內選 within。", "troubleshoot", "/ˈtrʌb.əl.ʃuːt/", "排除疑難排除故障", "glitch", "/ɡlɪtʃ/", "小故障突發錯誤"),
        ("Sensitive files should be encrypted before being transmitted across the public ___.", "Internet", "intern", "internal", "internally", "所有涉及公司最高機密之敏感檔案，在透過公共網際網路對外傳輸前均必須進行高強度加密處置。", "the public Internet 意為「公共網際網路」。", "網際網路專有名詞選 Internet。", "encrypt", "/ɪnˈkrɪpt/", "加密編碼", "transmit", "/trænzˈmɪt/", "傳送傳播傳輸"),
        ("Users experiencing technical difficulties are advised to contact the IT help ___ immediately.", "desk", "table", "chair", "bench", "若有任何同仁在電腦操作上遭遇突發技術障礙，建議立刻致電 IT 資訊求助服務台尋求專人協助。", "IT help desk 為標準商務辦公室用語，意為「IT 技術求助服務台」。", "技術求助台固定詞組選 help desk。", "difficulty", "/ˈdɪf.ə.kəl.ti/", "困難障礙", "help desk", "/ˈhelp ˌdesk/", "求助台技術諮詢台"),
        ("The upgrade of our corporate server infrastructure will take ___ during the upcoming holiday.", "place", "part", "time", "action", "本次企業級伺服器主機硬體架構之重大升級，將安排於即將到來的國定連續假期期間正式進行。", "take place 為高頻慣用語，意為「舉行、發生、正式展開進行」。", "舉行發生慣用語選 take place。", "upgrade", "/ˈʌp.ɡreɪd/", "升級換代", "take place", "/teɪk pleɪs/", "舉行發生")
    ]),
    # 10. 商務差旅與差旅報銷流程 (Business Travel & Expense Reimbursement)
    ("商務差旅與差旅報銷流程", "商務文法", "B2-U10", [
        ("The corporate travel agent arranged a detailed travel ___ for the delegation's trip to Tokyo.", "itinerary", "itinerant", "itineraries", "itinerating", "公司指定之商務旅行社，為本次參訪東京的經貿高級代表團擬定了極其詳盡精準的行程規畫表。", "名詞 itinerary 意為「行程計畫表、旅行路線表」，作 arranged 之受詞。", "行程表名詞選 itinerary。", "delegation", "/ˌdel.əˈɡeɪ.ʃən/", "代表團參訪團", "itinerary", "/aɪˈtɪn.ə.rer.i/", "行程計畫路線"),
        ("Employees traveling on official company business are entitled to a daily meal ___.", "allowance", "allow", "allowing", "allowable", "奉派外出洽公出差之全體員工，均有權依據公司規章領取定額之每日膳食膳雜費差旅補貼。", "daily meal allowance 為商務人資常用片語，意為「每日膳食津貼、生活補貼」。", "固定津貼詞組選 meal allowance。", "official business", "/əˌfɪʃ.əl ˈbɪz.nəs/", "公務出差", "allowance", "/əˈlaʊ.əns/", "津貼補助款"),
        ("All business expenses must be accompanied ___ original itemized receipts for reimbursement.", "by", "with", "to", "for", "所有申報之公務支出項目，在申請財務款項核銷時，均必須檢附載明各項明細之原始統一收據憑證。", "be accompanied by 為固定被動搭配，意為「伴隨有、隨附有…」。", "固定搭配選 accompanied by。", "itemized", "/ˈaɪ.t̬ə.maɪzd/", "逐項列出的列明細的", "accompany", "/əˈkʌm.pə.ni/", "隨附陪伴"),
        ("The flight was rescheduled due to adverse weather conditions, causing passengers to miss ___ connections.", "their", "them", "theirs", "they", "由於遭遇惡劣天候條件影響，班機被迫調整起飛時間，導致多數旅客錯過了預定之轉機航班。", "所有格代名詞 their 修飾名詞 connections（接駁轉機班機）。", "所有格修飾名詞選 their。", "adverse", "/ædˈvɝːs/", "逆向的惡劣不利的", "connection", "/kəˈnek.ʃən/", "接駁班機轉機"),
        ("Travel expense claim forms must be submitted within fourteen days of ___ from the business trip.", "returning", "returned", "return", "returns", "差旅費用代墊款項核銷申請單，必須在公務出差考察行程結束返國後十四天之法定時限內送審辦理。", "介系詞 of 後方接動名詞 returning，意為「自出差中返回」。", "介系詞後接動名詞 returning。", "claim form", "/ˈkleɪm ˌfɔːrm/", "報銷申報單", "return", "/rɪˈtɝːn/", "返回歸來"),
        ("The executive chose to travel in business class to prepare for the high-stakes ___.", "conference", "confer", "conferring", "conferment", "這名執行副總裁選擇搭乘商務艙出行，以便能在舒適安靜的環境中為這場高籌碼重要會議做好萬全準備。", "high-stakes conference 意為「關係重大的高階國際峰會會議」。", "名詞選 conference。", "high-stakes", "/ˈhaɪ.steɪks/", "高風險賭注大的", "conference", "/ˈkɑːn.fɚ.əns/", "研討會峰會"),
        ("Hotels booked through our corporate partner portal offer discounted room ___ to employees.", "rates", "ratings", "rated", "rate", "透過本公司特約企業合作夥伴預訂平台訂房之飯店，提供員工極具優惠之專屬特惠企業客房房價。", "discounted room rates 為飯店旅遊業標準詞組，意為「折價優惠房價」。", "客房定價複數名詞選 rates。", "portal", "/ˈpɔːr.t̬əl/", "入口網站入口管道", "rate", "/reɪt/", "費率房價價格"),
        ("Passengers traveling on long-haul international flights are advised to hydrate ___.", "frequently", "frequent", "frequency", "frequenting", "航空公司溫馨建議搭乘長程越洋國際航班之旅客，在機艙飛行途中應高頻率定期補充充足水分。", "副詞 frequently 修飾動詞 hydrate，表示「頻繁地補充水分」。", "副詞修飾動詞選 frequently。", "long-haul", "/ˈlɑːŋ.hɑːl/", "長途長程的", "frequently", "/ˈfriː.kwənt.li/", "頻繁地常常地"),
        ("The accounting department will disburse expense reimbursements via direct bank ___.", "deposit", "depository", "depositing", "deposited", "財務會計部門完成審核後，將會透過銀行直接轉帳匯款入帳之方式，迅速發放核銷之代墊款項。", "direct bank deposit 為銀行轉帳入帳之固定專業名詞詞組。", "銀行存款轉帳選 direct deposit。", "disburse", "/dɪsˈbɝːs/", "支付撥款", "deposit", "/dɪˈpɑː.zɪt/", "存款儲存"),
        ("Due to sudden passport expiration, the project manager had to ___ his planned overseas visit.", "postpone", "postponed", "postponing", "postponement", "由於護照效期突發過期失效，該專案經理不得不被迫將原定排程之海外考察出訪計畫予以延期。", "had to 後方必須接原形動詞 postpone，意為「延期推遲」。", "助動詞 had to 接動詞原形 postpone。", "expiration", "/ˌek.spəˈreɪ.ʃən/", "滿期屆期", "postpone", "/poʊstˈpoʊn/", "延後延緩推遲")
    ]),
    # 11. 敏捷專案管理與關鍵績效指標 (Agile Project Management & Milestone Tracking)
    ("敏捷專案管理與關鍵績效指標", "商務文法", "B2-U11", [
        ("The engineering team conducts a fifteen-minute daily standup to track sprint ___.", "progress", "progressed", "progressive", "progressing", "軟體工程開發團隊每日早晨準時召開十五分鐘的立會，以精準掌握敏捷衝刺週期的各項研發進展。", "名詞 progress 意為「進展進度」，作 track 之受詞。", "進展名詞選 progress。", "standup", "/ˈstænd.ʌp/", "立會站立會議", "progress", "/ˈprɑː.ɡres/", "進展進步"),
        ("Each cross-functional team member has clearly defined roles and core ___.", "responsibilities", "responsible", "responsibly", "responsiveness", "每位跨職能專案小組成員，在任務分工中均擁有界定極其分明的職掌角色與核心承擔職責。", "roles and responsibilities 為職場高頻搭配名詞對等短語，意為「角色與職責」。", "固定對等詞組選 responsibilities。", "cross-functional", "/ˌkrɑːsˈfʌŋk.ʃən.əl/", "跨職能跨部門的", "responsibility", "/rɪˌspɑːn.səˈbɪl.ə.t̬i/", "職責責任"),
        ("The project manager warned that missing next week's deadline would derail the entire ___.", "timeline", "timely", "timeliness", "timeless", "專案總監嚴正告誡，若未能如期趕上下週交付截止大限，將會徹底打亂整個專案的總體預定進度期程。", "the entire timeline 意為「整個專案時程表、推進時間線」。", "時間表名詞選 timeline。", "derail", "/dɪˈreɪl/", "出軌使脫軌破壞", "timeline", "/ˈtaɪm.laɪn/", "時程進度表時間線"),
        ("Key performance indicators (KPIs) were established to assess team efficiency ___.", "objectively", "objective", "objectivity", "object", "公司制定了清晰量化之關鍵績效指標(KPI)，以便能夠公正不偏頗地客觀評估各團隊之工作產出效能。", "副詞 objectively 修飾動詞 assess，意為「客觀地衡量評估」。", "副詞修飾動詞選 objectively。", "indicator", "/ˈɪn.də.keɪ.t̬ɚ/", "指標象徵", "objectively", "/əbˈdʒek.tɪv.li/", "客觀地大公無私地"),
        ("The product owner decided to ___ features based on customer feedback and market value.", "prioritize", "priority", "prioritized", "prioritization", "產品負責人在彙整廣大用戶回饋與評估市場商業價值後，果斷決定重新排列功能開發之優先順序。", "不定詞 to 之後接原形動詞 prioritize，意為「排定優先次序」。", "不定詞後接動詞原形 prioritize。", "feedback", "/ˈfiːd.bæk/", "意見反饋", "prioritize", "/praɪˈɔːr.ə.taɪz/", "按優先順序處理"),
        ("The agile sprint backlog must be reviewed and updated at the end of each ___.", "iteration", "iterate", "iterative", "iteratively", "敏捷開發工作待辦清單，必須在每一次循環迭代開發週期結束時進行嚴格審視與動態更新。", "名詞 iteration 意為「迭代、重複循環週期」，接在 each 之後作單數名詞受詞。", "敏捷專案迭代選 iteration。", "backlog", "/ˈbæk.lɑːɡ/", "積壓工作待辦清單", "iteration", "/ˌɪt̬.əˈreɪ.ʃən/", "迭代循環反覆"),
        ("Resource allocation bottlenecks have caused unexpected delays in software ___.", "deployment", "deploy", "deploying", "deployable", "人力與硬體資源分配產生的瓶頸限制，導致新版企業軟體系統的上線部署發生了意料之外的延宕。", "software deployment 為軟體工程標準專業詞組，意為「軟體上線部署發布」。", "軟體部署名詞選 deployment。", "bottleneck", "/ˈbɑː.t̬əl.nek/", "瓶頸礙障", "deployment", "/dɪˈplɔɪ.mənt/", "部署調配上線"),
        ("The client requested minor modifications to the user interface design ___.", "specifications", "specific", "specifically", "specify", "客戶在最後審查會議上，對使用者介面(UI)之設計技術規格書提出了數項微幅修改調整之要求。", "design specifications 意為「設計規格書、技術詳細規範標準」。", "規格名詞複數選 specifications。", "interface", "/ˈɪn.t̬ɚ.feɪs/", "介面互動介面", "specification", "/ˌspes.ə.fəˈkeɪ.ʃən/", "規格說明書"),
        ("To maintain high standards, peer code reviews are mandated before merging into the main ___.", "branch", "branched", "branching", "branches", "為維持軟體架構之最高品質標準，所有研發代碼在正式合併入主分支代碼庫前，均強制進行同行程式碼審查。", "the main branch 為軟體敏捷開發版本控制核心詞組，意為「主分支、主要主幹線」。", "版本控制主分支選 main branch。", "peer review", "/ˌpɪr rɪˈvjuː/", "同儕同行審查", "branch", "/bræntʃ/", "分支代碼庫分枝"),
        ("Successful completion of Phase 1 represents a major milestone in the product's life ___.", "cycle", "recycle", "cyclical", "cycling", "第一階段研發任務的圓滿成功達成，象徵著該項產品在其總體生命週期中跨越了一座關鍵之里程碑。", "product life cycle 為產品管理與市場行銷經典名詞短語，意為「產品生命週期」。", "固定專有名詞選 life cycle。", "milestone", "/ˈmaɪl.stoʊn/", "里程碑轉折點", "cycle", "/ˈsaɪ.kəl/", "週期循環")
    ]),
    # 12. 商業會議與議事規則 (Conferences, Agendas & Parliamentary Procedure)
    ("商業會議與議事規則", "商務文法", "B2-U12", [
        ("The chairperson called the annual general meeting to ___ at precisely nine o'clock.", "order", "ordering", "ordered", "orderly", "大會主席於上午九點整敲響議事木槌，正式宣布年度股東大會依序開議並遵守議事程序秩序。", "call the meeting to order 為標準議事規則經典法律固定短語，意為「宣布開會」。", "宣布開會固定短語選 call to order。", "chairperson", "/ˈtʃerˌpɝː.sən/", "主席座長", "order", "/ˈɔːr.dɚ/", "秩序條理程序"),
        ("A quorum must be present before any binding official vote can be ___.", "conducted", "conducting", "conducts", "conduct", "在召開董事會議進行任何具法律約束力之正式議案表決前，現場出席人數必須先行達到法定最低門檻人數。", "主詞 vote 與動詞 conduct 為被動關係，使用 can be conducted。", "情態助動詞被動選 can be conducted。", "quorum", "/ˈkwɔːr.əm/", "法定最低出席人數", "conduct", "/kənˈdʌkt/", "執行進行實施"),
        ("The corporate secretary circulated the detailed meeting ___ forty-eight hours in advance.", "agenda", "agendum", "agendas", "agent", "公司主任秘書提前整整四十八小時，將列載所有審議討論議題之詳細會議議程表分送至全體董事手中。", "meeting agenda 意為「會議議程表」，作 circulated 之受詞。", "會議議程名詞選 agenda。", "circulate", "/ˈsɝː.kjə.leɪt/", "傳閱分送流通", "agenda", "/əˈdʒen.dʌ/", "議程待議事項"),
        ("The motion to adopt the revised corporate governance guidelines passed ___.", "unanimously", "unanimous", "unanimity", "unanimousness", "這項旨在正式採納修訂後企業治理指導準則之議案，在全場熱烈掌聲中獲得全票無異議一致通過。", "副詞 unanimously 修飾動詞 passed，表示「全體一致地、無異議地」。", "副詞修飾動詞選 unanimously。", "governance", "/ˈɡʌv.ɚ.nəns/", "治理管轄統治", "unanimously", "/juːˈnæn.ə.məs.li/", "全體一致無異議地"),
        ("Due to prolonged debate on the budget deficit, the committee voted to ___ the session.", "adjourn", "adjourned", "adjourning", "adjournment", "由於針對預算赤字問題之辯論曠日持久，全體委員經表決後正式決議暫時宣布散會延會休會。", "不定詞 to 之後接原形動詞 adjourn，意為「宣布休會、延期休議」。", "不定詞後接動詞原形 adjourn。", "prolonged", "/prəˈlɑːŋd/", "延長拉長持久的", "adjourn", "/əˈdʒɝːn/", "休會散會延期"),
        ("The executive summary highlights the most salient points discussed during the ___.", "symposium", "symposia", "symposiums", "symposiast", "這份行政主管摘要精準彙整提煉了在此次高規格國際學術研討會期間，所深入研討之最核心重點精髓。", "名詞 symposium 意為「研討會、專題座談會」，接在 during 之後。", "研討會名詞選 symposium。", "salient", "/ˈseɪ.li.ənt/", "顯著突出的最重要的", "symposium", "/sɪmˈpoʊ.zi.əm/", "專題研討會座談會"),
        ("Meeting participants are requested to turn off mobile devices to prevent unnecessary ___.", "distractions", "distract", "distracted", "distractingly", "為確保議事專注品質，敬請全體與會來賓主動關閉手機通訊設備，以防範造成不必要的干擾分心。", "名詞 distractions 作 prevent 之受詞，意為「使人分心分神之人事物」。", "名詞受詞選 distractions。", "participant", "/pɑːrˈtɪs.ə.pənt/", "與會者參與者", "distraction", "/dɪˈstræk.ʃən/", "分心干擾分散注意力之事"),
        ("The recording secretary compiled thorough and accurate official ___ of the proceedings.", "minutes", "minute", "minutely", "minuteness", "大會會議記錄秘書為整個會議之辯論攻防與議事進程，編撰整理出詳盡且毫無遺漏之官方正式會議紀錄。", "official minutes 意為「正式官方會議紀錄」，作 compiled 之受詞（恆用複數）。", "會議紀錄恆用複數選 minutes。", "compilation", "/ˌkɑːm.pəˈleɪ.ʃən/", "編撰編輯", "minutes", "/ˈmɪn.ɪts/", "會議紀錄議事錄"),
        ("A prominent keynote speaker delivered an inspiring address on artificial ___ in healthcare.", "intelligence", "intelligent", "intelligently", "intelligentsia", "一位備受推崇的享譽國際重量級主講嘉賓，就人工智慧科技於當前醫療照護領域之突破應用發表激勵人心演說。", "artificial intelligence (AI) 為全球公認標準固定名詞片語，意為「人工智慧」。", "固定片語選 artificial intelligence。", "keynote speaker", "/ˈkiː.noʊt ˌspiː.kɚ/", "大會主講嘉賓", "intelligence", "/ɪnˈtel.ə.dʒəns/", "智慧智能靈性"),
        ("After extensive deliberation, the panel reached a broad ___ regarding the new expansion.", "consensus", "consensual", "consent", "consenting", "在歷經長達數小時之廣泛深思熟慮與研商後，審查委員會針對海外新擴建計畫終於達成了廣泛共識。", "reach a consensus 為高頻商務議事固定成語，意為「達成共識共鳴」。", "固定片語選 reach a consensus。", "deliberation", "/dɪˌlɪb.əˈreɪ.ʃən/", "深思熟慮研商評議", "consensus", "/kənˈsen.səs/", "共識共見")
    ]),
    # 13. 工業生產排程與品質檢驗保證 (Manufacturing Schedules & Quality Assurance)
    ("工業生產排程與品質檢驗保證", "商務文法", "B2-U13", [
        ("The newly installed robotic arms have boosted manufacturing output ___ twenty percent.", "by", "at", "to", "for", "這批最新引進安裝之全自動化工業機械手臂，已大幅拉抬工廠整體製造產能產出增幅達百分之二十。", "boost / increase output by + 百分比 為固定表示幅度差異之介系詞用法。", "表增加幅度介系詞選 by。", "robotic arm", "/roʊˈbɑː.t̬ɪk ˌɑːrm/", "機器手臂機械臂", "output", "/ˈaʊt.pʊt/", "產能產出產量"),
        ("Stringent quality control inspections are conducted at every stage of the ___ line.", "assembly", "assemble", "assembled", "assembling", "在現代化工廠裝配流水線生產線的每一道工序環節，均全面徹底落實最嚴格之品質管制檢驗標準。", "assembly line 為工業製造生產標準名詞片語，意為「組裝流水線、裝配線」。", "裝配線名詞片語選 assembly line。", "stringent", "/ˈstrɪn.dʒənt/", "嚴格嚴厲嚴密周全的", "assembly line", "/əˈsem.bli ˌlaɪn/", "裝配流水生產線"),
        ("Products that fail to satisfy regulatory benchmarks are discarded as ___ merchandise.", "defective", "defect", "defectively", "defection", "凡是未能完全達到政府官方公認安全與法規基準之瑕疵產品，均將依法作為不良品全數銷毀剔除。", "形容詞 defective 修飾名詞 merchandise，意為「有瑕疵缺陷的、不良的」。", "形容詞修飾名詞選 defective。", "benchmark", "/ˈbentʃ.mɑːrk/", "基準標準指標", "defective", "/dɪˈfek.tɪv/", "有瑕疵缺陷的不合格的"),
        ("The fabrication facility operates around the clock to meet surging seasonal ___.", "demand", "demanding", "demanded", "demands", "為全力滿足旺季期間市場急遽暴增之採購需求，這座晶圓晶片製造廠採取全天候二十四小時不間斷輪班運作。", "meet demand 為高頻商務動賓搭配，意為「滿足市場所需、應付市場需求」。", "滿足需求選 meet demand。", "around the clock", "/əˌraʊnd ðə ˈklɑːk/", "全天候日夜不停地", "demand", "/dɪˈmænd/", "需求量要求"),
        ("Implementing Six Sigma principles resulted in a dramatic reduction in product ___ rates.", "defect", "defective", "defectively", "defected", "引進導入精實六標準差管理方法論，使工廠產線上的產品不良率與瑕疵率獲得了極其驚人之大幅降低。", "defect rates 為工業工程與品管核心名詞詞組，意為「不良率、產品瑕疵率」。", "不良率固定名詞選 defect rates。", "Six Sigma", "/ˌsɪks ˈsɪɡ.mə/", "六標準差管理", "defect rate", "/ˈdiː.fekt ˌreɪt/", "不良率瑕疵率"),
        ("The factory obtained prestigious ISO 9001 certification for quality management ___.", "systems", "systematic", "systematically", "systemize", "該生產工廠憑藉卓越完善的工藝流程，正式榮獲了享譽國際之 ISO 9001 品質管理系統權威標準認證。", "quality management systems (QMS) 為國際標準化組織經典名詞組合。", "品質管理系統複數選 systems。", "certification", "/ˌsɝː.t̬ə.fəˈkeɪ.ʃən/", "認證檢驗核准證明", "prestigious", "/presˈtɪdʒ.əs/", "享譽盛名的聲名顯赫的"),
        ("Raw materials are subjected to rigorous metallurgical testing before entering ___.", "production", "produce", "productive", "productively", "所有採購之金屬礦物原物料在正式送入產線投料生產之前，均須歷經最嚴謹繁複之冶金金相檢驗程序。", "名詞 production 作動詞 entering 之受詞，意為「投產、正式生產階段」。", "進入投產名詞選 production。", "metallurgical", "/ˌmet̬.əlˈɝː.dʒɪ.kəl/", "冶金學的金屬冶煉的", "production", "/prəˈdʌk.ʃən/", "生產製造產量"),
        ("Preventative machinery maintenance is scheduled on Sunday nights to prevent operational ___.", "disruptions", "disrupt", "disruptive", "disruptively", "預防性機器機台設備保養作業固定排定於每週日夜間離峰時段實施，旨在防範引發重大營運中斷意外。", "名詞 disruptions 作動詞 prevent 之受詞，意為「營運干擾中斷」。", "營運中斷複數名詞選 disruptions。", "preventative", "/prɪˈven.t̬ə.tɪv/", "預防性的防患未然的", "disruption", "/dɪsˈrʌp.ʃən/", "中斷分裂干擾"),
        ("The plant manager implemented an automated tracking system to monitor real-time ___.", "throughput", "through", "throughout", "thru", "工廠廠長全面導入一套即時全自動化追蹤監控系統，藉以精確秒級掌握整條自動化產線之實時生產吞吐量。", "名詞 throughput 為工業工程專業術語，意為「生產吞吐量、物料處理周轉總量」。", "生產吞吐量專有名詞選 throughput。", "real-time", "/ˈriː.əl.taɪm/", "即時實時的", "throughput", "/ˈθruː.pʊt/", "吞吐量生產作業處理量"),
        ("All assembly line workers are required to wear personal protective ___ at all times.", "equipment", "equip", "equipped", "equipping", "所有在裝配流水線執勤之第一線操作作業員，在任何工作時段內均一律被強制配戴個人安全防護裝備。", "personal protective equipment (PPE) 為國際職業安全衛生標準核心術語（不可數名詞）。", "工安裝備選 equipment。", "mandatory", "/ˈmæn.də.tɔːr.i/", "強制的義務的", "equipment", "/ɪˈkwɪp.mənt/", "裝備配備器材")
    ]),
    # 14. 商業銀行信貸融資與外匯操作 (Commercial Banking, Credit Lines & FX)
    ("商業銀行信貸融資與外匯操作", "商務文法", "B2-U14", [
        ("The central bank unexpectedly raised the benchmark interest ___ by fifty basis points.", "rate", "rating", "rated", "rates", "中央銀行出乎全體金融市場意料之外，宣布將基準政策重貼現利率一口氣調升了五十個基點(二碼)。", "benchmark interest rate 為央行貨幣政策核心名詞，意為「基準利率」。", "基準利率單數片語選 rate。", "benchmark", "/ˈbentʃ.mɑːrk/", "基準參考點", "basis point", "/ˈbeɪ.sɪs ˌpɔɪnt/", "基點(萬分之一)"),
        ("The corporate borrower secured a five-million-dollar revolving line of ___ from the syndicate.", "credit", "credential", "credible", "creditably", "這家企業借款人成功自國際大型銀行主辦聯貸銀團手中，順利爭取取得了一筆五百萬美元的循環信用額度。", "line of credit 為銀行授信信貸核心金融名詞，意為「授信信用額度」。", "信用額度專用詞選 line of credit。", "syndicate", "/ˈsɪn.də.kət/", "聯貸銀團跨國財團", "line of credit", "/ˌlaɪn əv ˈkred.ɪt/", "信用貸款額度"),
        ("Commercial banks require commercial borrowers to pledge real estate assets as ___.", "collateral", "lateral", "collateralize", "collaterally", "商業銀行在辦理大額企金放款融資時，嚴格要求借款企業必須提供抵押土地不動產作為法定擔保擔保品。", "pledge... as collateral 為銀行融資經典法律術語，意為「質押…作為擔保抵押品」。", "擔保品名詞選 collateral。", "pledge", "/pledʒ/", "抵押質押擔保", "collateral", "/kəˈlæt̬.ɚ.əl/", "擔保品抵押物"),
        ("Treasury managers actively hedge against foreign currency fluctuations using forward ___.", "contracts", "contracting", "contractual", "contractor", "企業財務調度主管廣泛利用遠期外匯結匯合約衍生工具，積極避險以規避外國匯率劇烈波動之財務風險。", "forward contracts 為國際金融外匯衍生性商品核心名詞，意為「遠期外匯契約」。", "遠期合約複數名詞選 forward contracts。", "treasury", "/ˈtreʒ.ɚ.i/", "企業財務部國庫", "hedge", "/hedʒ/", "避險對沖"),
        ("The borrower must maintain sufficient liquid assets to service its outstanding ___.", "debt", "debts", "debtor", "debtless", "借款企業在合約期間必須隨時維持充裕之高流動性資產存量，以便能如期按月償付履行其未清償之債務負債。", "service debt 為金融專業固定動賓搭配，意為「按期還本付息、償付債務」。", "償債固定搭配選 service its debt。", "liquid assets", "/ˌlɪk.wɪd ˈæs.ets/", "流動資產變現資產", "service debt", "/ˌsɝː.vɪs ˈdet/", "償付債務利息"),
        ("The wire transfer was held up because the intermediary bank's SWIFT code was ___.", "incorrect", "incorrectly", "incorrectness", "incorrection", "該筆海外大額電匯之所以遭到暫時扣留延宕，主因在於轉匯中繼銀行所填載之國際SWIFT代碼有誤不正確。", "形容詞 incorrect 作主詞補語，意為「不正確的、錯誤的」。", "主詞補語形容詞選 incorrect。", "wire transfer", "/ˈwaɪr ˌtræns.fɝː/", "電匯銀行匯款", "intermediary", "/ˌɪn.t̬ɚˈmiː.di.er.i/", "中間的中繼的仲介的"),
        ("Credit rating agencies recently downgraded the corporation's credit ___ to BBB minus.", "rating", "rated", "rate", "ratings", "國際權威信用評等機構日前正式宣布，將該跨國集團之長期主體信用評級評等調降至 BBB- 垃圾債邊緣。", "credit rating 為金融信用評價標準名詞詞組，意為「信用評等評級」。", "信用評級專有名詞選 rating。", "downgrade", "/ˌdaʊnˈɡreɪd/", "降級調降評等", "credit rating", "/ˈkred.ɪt ˌreɪ.tɪŋ/", "信用評等評級"),
        ("The loan agreement contains strict covenants that restrict the company from taking on additional ___.", "liabilities", "liability", "liable", "liably", "這份聯貸合約中載有極其嚴格的保護性限制性條款，嚴正禁止該企業在未經許可下擅自承擔額外新增負債。", "名詞 liabilities 意為「會計負債債務」，作 taking on 之受詞。", "負債複數名詞選 liabilities。", "covenant", "/ˈkʌv.ə.nənt/", "約束條款盟約", "liability", "/ˌlaɪ.əˈbɪl.ə.t̬i/", "負債債務責任"),
        ("Due to tight monetary policy, regional lenders have significantly tightened their lending ___.", "standards", "standard", "standardize", "standardized", "受到中央銀行緊縮貨幣政策效應影響，各區域商業放款銀行已全面大幅拉高收緊其企業授信審查標準門檻。", "lending standards 為銀行信貸專門術語，意為「放款標準、授信審批門檻」。", "授信標準複數名詞選 standards。", "monetary policy", "/ˈmɑː.nə.ter.i ˌpɑː.lə.si/", "貨幣政策", "standards", "/ˈstæn.dɚdz/", "標準規範門檻"),
        ("Funds deposited in interest-bearing certificate of deposit accounts earn a fixed annual ___.", "yield", "yielding", "yielded", "yields", "存入固定期限附息定存單(CD)專戶中的投資資金，享有每年保證發放之固定年化實質收益率利息回報。", "名詞 yield 為金融投資核心專用詞彙，意為「殖利率、收益率、投報率」，接在 fixed annual 之後。", "投資收益率名詞選 yield。", "certificate of deposit", "/sɚˌtɪf.ə.kət əv dɪˈpɑː.zɪt/", "銀行定存單(CD)", "yield", "/jiːld/", "收益率孳息殖利率")
    ]),
    # 15. 商用不動產租賃與辦公空間規劃 (Commercial Real Estate & Facility Management)
    ("商用不動產租賃與辦公空間規劃", "商務文法", "B2-U15", [
        ("The lease agreement specifies that the tenant must vacate the premises upon ___.", "expiration", "expire", "expired", "expiring", "租賃合約書中明確以黑字載明，承租方房客在租賃期滿到期之時，必須全數騰空並返還租賃房屋場所標的物。", "名詞 expiration 接在介系詞 upon 之後，構成 upon expiration，意為「屆期期滿時」。", "介系詞後接名詞 expiration。", "tenant", "/ˈten.ənt/", "承租人房客", "premises", "/ˈprem.ə.sɪz/", "商用房產物業場所"),
        ("The corporation relocated its European headquarters to an eco-friendly Grade A office ___.", "complex", "complexly", "complexity", "complexion", "該跨國跨國集團日前正式將其歐洲營運總部，整體喬遷搬遷至一棟符合綠建築環保認證的頂級甲級寫字樓商辦園區大樓。", "office complex 為商用不動產標準專業名詞詞組，意為「辦公大樓綜合園區群」。", "商辦大樓園區選 complex。", "relocate", "/ˌriːˈloʊ.keɪt/", "重新安置喬遷搬遷", "complex", "/ˈkɑːm.pleks/", "綜合園區綜合大樓"),
        ("All prospective commercial tenants are required to provide a refundable security ___.", "deposit", "deposited", "depositing", "depositor", "所有有意洽租本商場店面之潛在商業承租戶，在簽署意向書時均被強制要求繳交一筆可退還之保證押金。", "security deposit 為房屋租賃標準法律用詞，意為「履約保證金、租屋押金」。", "租金押金專有名詞選 security deposit。", "prospective", "/prəˈspek.tɪv/", "潛在的有希望的", "deposit", "/dɪˈpɑː.zɪt/", "保證金押金存款"),
        ("The landlord agreed to finance the interior buildout under the negotiated tenant ___.", "allowance", "allow", "allowing", "allowable", "房東經友好雙邊協商談判後欣然同意，透過依約核給之租戶裝修工程補助預算額度，全額資助內部裝潢施工費。", "tenant allowance (TA) 為商業地產招商固定名詞術語，意為「房東提供給租客之裝修補助款」。", "裝修補助名詞選 tenant allowance。", "landlord", "/ˈlænd.lɔːrd/", "房東業主", "interior buildout", "/ɪnˌtɪr.i.ɚ ˈbɪld.aʊt/", "室內裝修隔間裝潢"),
        ("The newly constructed office tower features energy-efficient HVAC and lighting ___.", "systems", "systematic", "systematically", "systemize", "這座甫落成啟用之摩天辦公大樓，全棟全面標配超高能源使用效率之暖通空調與智慧感應照明系統架構。", "HVAC and lighting systems 為智慧建築機電設施固定複數名詞搭配。", "系統設施複數名詞選 systems。", "HVAC", "/ˈeɪtʃ.væk/", "暖通空調系統", "energy-efficient", "/ˌen.ɚ.dʒi.ɪˈfɪʃ.ənt/", "節能省電高能效的"),
        ("The lease clause grants the lessee the exclusive option to ___ the tenancy for three years.", "renew", "renewed", "renewing", "renewal", "本租約專屬特約條款賦予承租人專屬排他之排他優先承租選擇權，得在原約期滿後繼續優先續約三年。", "the option to renew 意為「續約權、優先續約選擇權」，不定詞 to 接原形動詞 renew。", "續約動詞原形選 renew。", "lessee", "/leˈsiː/", "承租人租賃方", "renew", "/rɪˈnuː/", "續約延長效期更新"),
        ("Subletting any portion of the rented commercial suite without written permission is strictly ___.", "prohibited", "prohibit", "prohibiting", "prohibition", "凡是未事先取得業主書面正式同意核准函，而擅自將所承租之商辦店面空間予以分租轉租者，一律嚴厲禁止。", "is strictly prohibited 為商務合約公告標準被動用語，意為「嚴格明令禁止」。", "被動態明令禁止選 prohibited。", "sublet", "/ˌsʌbˈlet/", "分租轉租", "prohibit", "/prəˈhɪb.ɪt/", "嚴禁禁止"),
        ("Facility managers conducted an exhaustive inspection to ensure total compliance with fire safety ___.", "codes", "codify", "coding", "coded", "大樓物業管理維護工程師團隊展開了地毯式全面檢查，以百分之百確保大樓全棟完全符合法定消防建築法規規範標準。", "fire safety codes 為建築營造與防災法規固定名詞片語，意為「消防安全法規標準條例」。", "法規標準複數名詞選 codes。", "compliance", "/kəmˈplaɪ.əns/", "合規遵循", "codes", "/koʊdz/", "法規規章條例"),
        ("The open-plan architectural layout was intentionally designed to foster interdepartmental ___.", "collaboration", "collaborate", "collaborative", "collaboratively", "這套採光通透的開放式無隔間建築空間格局配置，其設計初衷係專為促進各部門同仁間無界限之橫向溝通協同合作。", "名詞 collaboration 作動詞 foster 之受詞，意為「跨領域協同合作溝通」。", "名詞受詞選 collaboration。", "open-plan", "/ˌoʊ.pənˈplæn/", "開放式隔間的", "collaboration", "/kəˌlæb.əˈreɪ.ʃən/", "協同合作合作協作"),
        ("The lease stipulate that maintenance fees are adjusted annually based on the consumer price ___.", "index", "indices", "indexer", "indexing", "租約條文載明，大樓每月公共物業管理費費率，將依據政府每年定期公告之全國消費者物價指數定期連動調幅。", "consumer price index (CPI) 為全球公認標準固定經濟指標專有名詞，意為「消費者物價指數」。", "消費者物價指數選 index。", "stipulate", "/ˈstɪp.jə.leɪt/", "明定約定載明", "index", "/ˈɪn.deks/", "指數指標索引")
    ])
]

# We will generate tier5_toeic.py with 15 more subtopics to reach 25 subtopics (total 250 items).
print("Writing tier5_toeic.py generator...")
