# scripts/diag_builders/tier8_part2a_data.py
# Subtopics 13-18 for Tier 8 (GMAT Focus CR C2/C2+, IDs 1871-1930)

subtopics_13_to_18 = [
    # 13. Flaw in Reasoning: Equivocation & Semantic Shift
    ("Flaw in Reasoning: Equivocation & Semantic Shift", "批判推理", "C2-GMAT13", [
        ("The university's public relations officer stated that all members of the academic faculty have an undeniable right to freedom of speech. Because granting tenure gives professors speech protections without threat of termination, the officer concluded that non-tenured lecturers must also be awarded tenure immediately to preserve their rights. Which of the following best describes the logical flaw in the officer's argument?",
         "It treats a legal and moral right to free expression as equivalent to granting a specific employment contractual status.",
         "It overlooks the possibility that tenured faculty members might occasionally express unpopular scholarly opinions.",
         "It presumes without justification that non-tenured lecturers desire permanent career advancement within the university.",
         "It assumes that academic tenure has been completely abolished across peer research universities.",
         "偷換概念與語意滑轉 (Equivocation)：論點將憲法/道德層面的『言論自由權利 (right to freedom of speech)』直接等同於特定勞動聘僱身分『終身聘任制 (tenure)』，將概念偷換以推導出荒謬政策結論。",
         "邏輯謬誤：概念偷換 (Equivocation) 與範疇混淆。",
         "equivocation", "/ɪˌkwɪv.əˈkeɪ.ʃən/", "模稜兩可語意偷換含糊其詞", "tenure", "/ˈten.jɚ/", "終身聘用權終生職位"),

        ("A political commentator argued that because a democratic society relies fundamentally on public interest, any television network broadcasting programming that the public finds interesting is performing a vital democratic public service. What is the fundamental flaw in the commentator's reasoning?",
         "It conflates 'public interest' in the sense of the general social welfare with 'what the public finds interesting' in the sense of commercial curiosity.",
         "It ignores that public television networks receive statutory funding from government bodies.",
         "It assumes that commercial television networks never produce documentary journalism.",
         "It takes for granted that democratic societies are the only governance systems that value commercial entertainment.",
         "語意偷換謬誤：將公眾利益/社會福祉 (public interest) 與『大眾覺得有趣/八卦好奇 (what is interesting to the public)』混為一談，犯了典型的一詞多義謬誤。",
         "概念偷換：混淆社會公眾福祉與娛樂好奇心。",
         "conflate", "/kənˈfleɪt/", "合併混淆將…混為一談", "welfare", "/ˈwel.fer/", "福祉社會利益福利"),

        ("A software company proclaimed that its proprietary operating platform is entirely free because any registered user is free to customize interface display colors without paying an additional licensing fee. Which flaw characterizes this argument?",
         "It shifts the meaning of 'free' from costing no money to being unconstrained in cosmetic customization.",
         "It presumes that enterprise clients place zero economic value on color customization.",
         "It fails to consider that open-source operating platforms are developed by volunteer engineers.",
         "It relies on the unsupported premise that custom color palettes reduce computer monitor energy consumption.",
         "語意滑轉：論點在『免費 (free of charge)』與『自由/無約束 (free to do)』之間進行概念滑轉，以客製化介面的自由度掩蓋該平台仍需收費的商業本質。",
         "偷換概念：混淆無成本 (free of charge) 與行為自由 (freedom of choice)。",
         "proprietary", "/prəˈpraɪə.ter.i/", "專有的專利的專賣的", "unconstrained", "/ˌʌn.kənˈstreɪnd/", "不受拘束的無限制的"),

        ("An ethics committee member claimed that because lying is always wrong, and acting falsely in a theatrical stage play involves speaking untrue statements, dramatic actors are behaving unethically during performances. The reasoning is flawed because it:",
         "Equivocates between intentional deception intended to mislead and artistic portrayal in a mutually recognized theatrical context.",
         "Assumes that dramatic actors earn higher salaries than corporate compliance officers.",
         "Neglects to specify whether comedic performances are more harmful than tragic performances.",
         "Fails to acknowledge that classic theatrical plays were originally composed in verse.",
         "語意與情境偷換：論點將意圖欺騙公眾的『說謊』與互為共識的藝術舞台演繹中『台詞虛構』混為一談，抽離了社會情境與意圖邊界。",
         "概念泛化：混淆惡意欺瞞與戲劇虛構藝術。",
         "portrayal", "/pɔːrˈtreɪ.əl/", "描繪演繹飾演畫像", "compliance", "/kəmˈplaɪ.əns/", "合規順從遵從法令"),

        ("A financial adviser argued that money cannot buy happiness because wealth is purely material, whereas true happiness is a spiritual state of contentment. Therefore, lifting impoverished households above the poverty line will do nothing to alleviate their unhappiness. Which flaw undermines this reasoning?",
         "It equates absolute deprivation with ordinary material wealth, ignoring that basic financial resources alleviate concrete sources of misery.",
         "It presumes that all wealthy individuals suffer from chronic psychiatric conditions.",
         "It relies on survey data gathered exclusively from developing agrarian economies.",
         "It assumes that spiritual contentment can be measured through algorithmic biometric sensors.",
         "偷換範疇謬誤：將『追求極致奢靡無法買到心靈平靜』偷換套用到『處於赤貧線以下的家庭』，忽略了擺脫飢寒匱乏等基本資源能直接消除痛苦。",
         "邏輯漏洞：混淆邊際財富效應與基本生活匱乏之消除。",
         "deprivation", "/ˌdep.rəˈveɪ.ʃən/", "匱乏剝奪貧困", "contentment", "/kənˈtent.mənt/", "滿足知足滿意"),

        ("The defense attorney argued that human beings are naturally aggressive because millions of bodily cells engage in constant cellular competition and destruction. Hence, international armed conflict is an inevitable expression of human nature. The argument is vulnerable to criticism because it:",
         "Illegitimately applies a biological concept of cellular dynamics to macro-level sociological and geopolitical behaviors.",
         "Fails to cite specific biochemical pathways involved in cellular apoptosis.",
         "Assumes that national treaties have never succeeded in mitigating armed warfare.",
         "Overlooks that military defense budgets have expanded exponentially across sovereign states.",
         "範疇與層次謬誤 (Composition/Equivocation)：將微觀生物細胞層級的代謝競爭現象，直接偷換套用到宏觀地緣政治與國際武裝衝突的社會制度行為上。",
         "層次謬誤：微觀生理學概念不能直接等同於宏觀社會學行為。",
         "geopolitical", "/ˌdʒiː.oʊ.pəˈlɪt̬.ɪ.kəl/", "地緣政治的", "mitigate", "/ˈmɪt̬.ə.ɡeɪt/", "減輕緩和撫平"),

        ("A real estate developer claimed that his new luxury subdivision is environmentally green because every single residence will be painted with eco-friendly pastel green acrylic paint. The developer's argument is flawed because it:",
         "Conflates the literal color green with the ecological concept of environmental sustainability.",
         "Fails to demonstrate that acrylic paints have lower toxicity than oil-based paints.",
         "Assumes that buyers in luxury subdivisions commute solely via electric trains.",
         "Ignores that municipal zoning regulations mandate concrete sidewalk construction.",
         "荒謬字面偷換 (Literal Equivocation)：將象徵環境永續的『綠色 (green)』偷換為油漆塗料的字面顏色『綠色』，犯了字面主義偷換概念謬誤。",
         "字面偷換謬誤：將生態永續抽象意涵偷換為物理色素顏色。",
         "subdivision", "/ˈsʌb.də.vɪʒ.ən/", "社區建案住宅分區細分", "acrylic", "/əˈkrɪl.ɪk/", "壓克力的丙烯酸的"),

        ("A museum curator argued that since art is inherently an expression of subjective emotion, and emotional states cannot be objectively quantified, any critical evaluation of artistic craftsmanship is impossible and illegitimate. The flaw in this reasoning is that it:",
         "Treats the subjective emotional origin of artwork as incompatible with objective criteria of technical execution and structural coherence.",
         "Assumes that ancient marble sculptures require more craftsmanship than contemporary digital art.",
         "Ignores that museum ticket prices fluctuate based on seasonal tourist demand.",
         "Fails to define whether emotional expressions must be pleasant to be deemed artistic.",
         "非黑即白與範疇偷換：將藝術作品具有主觀情感表現，推論出技術技藝 (craftsmanship) 與結構連貫性無法進行任何客觀評價，混淆了情感來源與技術執行。",
         "範疇混淆：主觀情感驅動力並不排除對技術工藝的客觀評價。",
         "craftsmanship", "/ˈkræfts.mən.ʃɪp/", "工藝手藝精湛技藝", "coherence", "/koʊˈhɪr.əns/", "連貫性條理性一致性"),

        ("A culinary blogger claimed that because salt is a mineral composed of sodium and chlorine, and elemental chlorine gas is toxic to human tissue, seasoning meals with table salt is actively poisoning diners. The blogger's logic fails because it:",
         "Assumes that the chemical compound sodium chloride possesses the identical chemical reactivity and toxicity of its constituent elemental gas.",
         "Overlooks that organic sea salt contains trace levels of magnesium and calcium.",
         "Presumes that toxic gases cannot be safely isolated in glass containers.",
         "Ignores that excessive sodium consumption is correlated with elevated blood pressure.",
         "化學複合物之整體與部分謬誤 (Fallacy of Division)：誤以為化合物 (NaCl) 必然承繼其單質元素 (Cl2) 的毒性特徵，忽略了分子鍵結改變了化學性質。",
         "分解謬誤：部分單質特性不等於化學合成物之整體性質。",
         "elemental", "/ˌel.əˈmen.t̬əl/", "元素的基本的單純的", "constituent", "/kənˈstɪtʃ.u.ənt/", "組成的構成成分選民"),

        ("An editorialist maintained that since freedom of the press guarantees journalists the liberty to publish news, social media platforms that ban users for distributing fraudulent election disinformation are violating constitutional press protections. Which flaw undermines this editorial?",
         "It treats private corporate content moderation as equivalent to state-sponsored censorship and confuses journalistic liberty with unregulated fraudulent speech.",
         "It presumes that all social media platforms are incorporated within the same sovereign jurisdiction.",
         "It fails to note that newspaper circulations have plummeted over the past twenty years.",
         "It takes for granted that election candidates never utilize digital platforms for legitimate campaigning.",
         "概念偷換與主體錯置：將憲法防止『國家公權力審查新聞自由』的範疇，偷換套用到『私人商業平台對造假詐欺言論進行內容審核』之上。",
         "憲政範疇錯置：混淆私人契約審核與政府違憲審查。",
         "moderation", "/ˌmɑː.dəˈreɪ.ʃən/", "審核調節適度溫和", "disinformation", "/ˌdɪs.ɪn.fɚˈmeɪ.ʃən/", "虛假不實訊息刻意假情報")
    ]),

    # 14. Flaw in Reasoning: Circular Reasoning & Begging the Question
    ("Flaw in Reasoning: Circular Reasoning & Begging the Question", "批判推理", "C2-GMAT14", [
        ("A company CEO asserted: 'Our management consulting methodology is the most reliable in the world because it was designed by the foremost industry authorities, and we know these authorities are the foremost because only the most elite practitioners could have created our methodology.' This argument is flawed because it:",
         "Employs circular reasoning where the validity of the premise depends directly on the truth of the conclusion it seeks to establish.",
         "Fails to benchmark the consulting firm's performance against publicly traded competitors.",
         "Presumes that all management consulting engagements result in positive shareholder value.",
         "Ignores that proprietary methodologies must be registered with patent regulatory authorities.",
         "循環論證 (Circular Reasoning / Begging the Question)：用『專家的權威』來證明『方法論最可靠』，又用『方法論最可靠』來證明『專家最頂尖』，前提與結論互為因果循環證明。",
         "GMAT 核心邏輯謬誤：乞題與循環論證 (Begging the Question)。",
         "circular", "/ˈsɝː.kjə.lɚ/", "循環的圓形的環狀的", "benchmark", "/ˈbentʃ.mɑːrk/", "基準以…為基準比較"),

        ("A theological author wrote: 'Our sacred text contains the unblemished truth because every passage is divinely inspired, and we know it is divinely inspired because the sacred text explicitly states so.' Which flaw is present in this reasoning?",
         "It assumes as true the very premise that it is attempting to substantiate.",
         "It neglects to provide an archaeological timeline for when the text was inscribed.",
         "It fails to compare the text's moral doctrines with contemporary secular jurisprudence.",
         "It presupposes that ancient languages cannot be translated into modern vernaculars.",
         "乞題謬誤：試圖證明文本是神聖真理，卻直接引述文本本身的宣稱作為證明文本是神聖真理的依據，預先假設了待證前提的真實性。",
         "乞題論證：以待證命題本身作為證明自身成立之前提。",
         "unblemished", "/ʌnˈblem.ɪʃt/", "無瑕疵的完美無缺的", "substantiate", "/səbˈstæn.ʃi.eɪt/", "證實實質支持提供證據"),

        ("A pharmaceutical lobbyist argued that proprietary drug prices are fair and rational because they are set strictly in accordance with market value, and market value is defined precisely by whatever price the pharmaceutical firm determines to charge. What flaw undermines this argument?",
         "It defines 'market value' tautologically in terms of the firm's unilateral pricing, rendering the conclusion a circular assertion.",
         "It overlooks the existence of state-subsidized universal healthcare programs in overseas markets.",
         "It fails to document the precise research expenditures required to discover new chemical entities.",
         "It presumes that generic drug manufacturers have lower operating profit margins.",
         "同義反覆與循環定義：先稱價格公平是因為符合市場價值，再將市場價值定義為藥廠自己所定之價格，使整個論證淪為自說自話的套套邏輯 (tautology)。",
         "套套邏輯與循環定義：用被定義項直接定義概念本身。",
         "tautologically", "/ˌtɔː.t̬əˈlɑː.dʒɪ.kəl.i/", "同義反覆地套套邏輯地", "unilateral", "/ˌjuː.nəˈlæt̬.ɚ.əl/", "單方面的單邊的"),

        ("A film critic wrote: 'Director Vance is undeniably a brilliant auteur because all of his films exhibit profound artistic brilliance, and any film that does not exhibit brilliance cannot truly be considered one of Vance's authentic auteur works.' What is the logical weakness in this argument?",
         "It insulates the claim from counterexamples by defining authentic works strictly by the positive quality being asserted.",
         "It fails to analyze the box office receipts of the director's cinematic debut.",
         "It assumes that cinematic auteurs must write their own musical scores.",
         "It relies on interview testimonials from actors who worked on low-budget independent films.",
         "無懈可擊式循環定義（無真蘇格蘭人謬誤）：將『不具才華的作品』直接開除籍貫、定義為『非凡斯真正的作者作品』，用結論反向定義前提以屏蔽任何反例。",
         "循環屏蔽謬誤：透過重新定義範疇來屏蔽任何反對論據。",
         "auteur", "/oʊˈtɝː/", "電影作者電影導演大師", "insulate", "/ˈɪn.sə.leɪt/", "隔離使免受…使絕緣"),

        ("A state governor declared: 'The new high-speed rail line is indispensable because our transportation infrastructure demands it, and we know our infrastructure demands it because building the rail line is absolutely necessary.' Which of the following describes the governor's reasoning?",
         "It merely restates the conclusion in different vocabulary rather than providing substantive empirical justification.",
         "It confuses a necessary condition for fiscal solvency with a sufficient condition.",
         "It assumes that passenger rail patronage will exceed airline passenger volumes.",
         "It overlooks the environmental impact of tunnel excavation through granite bedrock.",
         "同義反覆（換句話說）：論點宣稱高鐵必不可少是因為基礎建設需要，而基礎建設需要是因為高鐵必不可少。純粹用不同同義詞替換重述結論，缺乏任何客觀經驗證據。",
         "同義贅述謬誤：以詞語變換代替實質因果邏輯支撐。",
         "indispensable", "/ˌɪn.dɪˈspen.sə.bəl/", "不可或缺的必不可少的", "solvency", "/ˈsɑːl.vən.si/", "償債能力財務穩健"),

        ("A software security officer stated: 'Our cloud architecture is invulnerable to cyberattacks because our encryption protocols are impenetrable, and we are certain our encryption is impenetrable because no system with our architecture could ever be compromised.' The officer's reasoning is flawed because it:",
         "Derives its conclusion through a self-referential chain that presumes the integrity of the system without independent testing.",
         "Fails to specify whether two-factor authentication is mandatory for administrative logins.",
         "Assumes that malicious hackers utilize only brute-force cryptographic cracking techniques.",
         "Ignores that hardware routers require firmware updates to prevent denial-of-service disruptions.",
         "自我循環參照：用『架構堅不可摧』推得『密碼防護無懈可擊』，又用『密碼無懈可擊』推得『不可能被攻破』，缺乏任何獨立第三方實證滲透測試。",
         "自我參照循環謬誤：欠缺獨立經驗驗證之自我證明鏈。",
         "invulnerable", "/ɪnˈvʌl.nɚ.ə.bəl/", "無懈可擊的刀槍不入的", "compromise", "/ˈkɑːm.prə.maɪz/", "危害妥協損害折衷"),

        ("A macroeconomic theorist claimed: 'Consumer spending always increases following tax cuts because tax cuts stimulate aggregate demand, and aggregate demand stimulates demand because consumer spending expands.' What flaw characterizes this statement?",
         "It traces an unbroken circular loop of causality where each factor is justified solely by the next.",
         "It takes for granted that marginal propensity to consume is uniform across income brackets.",
         "It assumes that central banks will raise interest rates simultaneously.",
         "It fails to account for international balance of trade deficits in manufacturing.",
         "循環因果鏈條：減稅促總需求，總需求促需求，因為消費擴大。整段推論在概念之間空轉，因果鏈互為擔保，沒有提供任何實體機制分析。",
         "循環因果閉環：邏輯推演原地踏步缺乏真實外生變數。",
         "propensity", "/prəˈpen.sə.t̬i/", "傾向偏好習性", "deficit", "/ˈdef.ə.sɪt/", "赤字逆差虧損"),

        ("An educational psychologist argued: 'Standardized aptitude tests are an accurate measure of innate intelligence because students with superior intelligence score highest on them, and we know these students have superior intelligence because of their high test scores.' This reasoning is logically deficient because:",
         "It utilizes the metric of evaluation to define the very trait that the metric is supposed to measure independently.",
         "It assumes that test questions contain cultural biases against bilingual test-takers.",
         "It fails to calculate the standard deviation across differing geographical testing centers.",
         "It overlooks that test-takers who review preparation manuals show improved timing performance.",
         "測驗循環定義謬誤：用智商高來解釋高分，又用高分來定義智商高。評量工具直接定義了待測特質，缺乏外在獨立驗證效標。",
         "測量學循環謬誤：評量工具與特質定義自我循環。",
         "aptitude", "/ˈæp.tə.tuːd/", "性向才能天資", "innate", "/ɪˈneɪt/", "先天的天賦的與生俱來的"),

        ("A political philosopher argued: 'Monarchies are the most legitimate form of government because the sovereign holds absolute divine mandate, and this divine mandate is evidenced by the uncontested sovereignty of the monarch.' Which flaw underlies this argument?",
         "It presumes the legitimacy of sovereign authority to prove the divine mandate that supposedly legitimizes that very authority.",
         "It ignores that constitutional monarchies share power with elected parliamentary assemblies.",
         "It relies on historical anecdotes drawn exclusively from medieval European kingdoms.",
         "It assumes that democratic republics experience higher rates of civil insurrection.",
         "君權神授之循環乞題：用君主擁有主權來證明神授天命，又用神授天命來證成君主主權的合法性，互為因果相互乞題。",
         "政治哲學循環論證：權威合法性與神聖依據自我印證。",
         "sovereignty", "/ˈsɑːv.rən.ti/", "主權統治權獨立自主權", "insurrection", "/ˌɪn.səˈrek.ʃən/", "叛亂暴動起義"),

        ("A corporate auditor concluded: 'The company's financial ledgers are completely transparent because the chief financial officer is thoroughly honest, and we know the chief financial officer is thoroughly honest because the financial ledgers contain no recorded improprieties.' What is the logical defect in this conclusion?",
         "It reasons in a circle by using the unverified integrity of the ledger to validate the character of the executive whose character validates the ledger.",
         "It assumes that forensic accounting algorithms can detect fraudulent double-entry transactions.",
         "It fails to review the depreciation schedules applied to heavy commercial industrial machinery.",
         "It ignores that external audit partners are rotated once every seven financial quarters.",
         "循環審計邏輯：帳本誠信靠長官品德背書，長官品德靠帳本無污點背書。在未經第三方獨立實質性審查前，兩者互相擔保形成死循環。",
         "審計邏輯死循環：以互為依賴的未經驗證主體互背書。",
         "impropriety", "/ˌɪm.prəˈpraɪə.t̬i/", "不當行為不正當失檢", "forensic", "/fəˈren.zɪk/", "鑑識的法庭的取證的")
    ]),

    # 15. Flaw in Reasoning: False Dichotomy & Excluded Middle
    ("Flaw in Reasoning: False Dichotomy & Excluded Middle", "批判推理", "C2-GMAT15", [
        ("A defense strategist argued: 'The nation must either double its annual military procurement expenditures or face immediate foreign invasion and subjugation. Because we cannot tolerate foreign conquest, we must immediately double military procurement.' Which of the following highlights the primary logical flaw in this argument?",
         "It falsely presents two extreme outcomes as mutually exhaustive, ignoring moderate intermediate defensive policies and diplomatic deterrence.",
         "It fails to specify which foreign adversaries currently possess amphibious naval landing vessels.",
         "It assumes that doubling procurement would eliminate all domestic budget deficits.",
         "It presumes that civilian manufacturing facilities cannot be requisitioned during wartime.",
         "假兩難/排除中道謬誤 (False Dichotomy / Excluded Middle)：將選項極端二分化為『軍費加倍』或『立即亡國』，刻意忽視外交嚇阻、防禦同盟或適度軍備整頓等中間折衷方案。",
         "GMAT 核心邏輯謬誤：假兩難 (False Dilemma) 與極端二分法。",
         "subjugation", "/ˌsʌb.dʒəˈɡeɪ.ʃən/", "征服屈服鎮壓", "procurement", "/prəˈkjʊr.mənt/", "採購採辦調撥"),

        ("A university provost told faculty: 'Either we eliminate all funding for humanities departments to finance advanced artificial intelligence research laboratories, or the university will fall into total academic irrelevance. Therefore, shutting down humanities is our only viable choice.' The provost's argument is flawed because it:",
         "Presupposes without evidence that no compromise or alternative funding mechanisms exist between two radical alternatives.",
         "Fails to acknowledge that humanities graduates achieve high acceptance rates to legal schools.",
         "Assumes that artificial intelligence researchers never read classical historical literature.",
         "Ignores that private philanthropy donations to universities fluctuate with stock market cycles.",
         "非黑即白假兩難：預設唯有『砍光人文學院』或『大學徹底被淘汰』兩條極端道路，忽視了爭取民間產學贊助、多元調整預算等中間可行方案。",
         "假兩難架構：忽視多元資源調配之中間選擇 (Intermediate Options)。",
         "provost", "/ˈproʊ.voʊst/", "教務長學術副校長主管", "irrelevance", "/ɪˈrel.ə.vəns/", "無關緊要無足輕重"),

        ("A business columnist asserted: 'In modern commerce, a startup must either aggressively spend all operating capital to achieve total market dominance within eighteen months, or it will inevitably slide into immediate bankruptcy.' What logical error does this assertion commit?",
         "It treats aggressive hypergrowth and bankruptcy as the only possible outcomes, overlooking sustainable, profitable niche strategies.",
         "It presumes that venture capital syndicates require board representation in every financing round.",
         "It fails to cite specific accounting definitions of operational working capital.",
         "It ignores that corporate trademark registrations grant legal exclusivity in international jurisdictions.",
         "二分法盲點：將新創企業命運窄化為『瘋狂燒錢換取壟斷』或『立即破產』，完全無視深耕細分市場、穩健獲利的利基成長途徑。",
         "排除利基市場之中道：忽視穩健小而美盈利模式。",
         "syndicate", "/ˈsɪn.də.kət/", "辛迪加財團企業聯盟", "niche", "/niːʃ/", "利基市場合適的定位"),

        ("A city council member argued: 'We must either ban all private motor vehicles from downtown streets entirely, or downtown will choke on catastrophic traffic gridlock and toxic smog. Since gridlock is untenable, the complete ban on private vehicles must pass.' The argument is vulnerable because it:",
         "Overlooks intermediate congestion-mitigation strategies such as congestion pricing, synchronized traffic signaling, or expanded transit.",
         "Fails to project the impact of pedestrianization on local retail boutique revenues.",
         "Assumes that delivery trucks require the same road space as passenger sedans.",
         "Ignores that electric vehicle market penetration will reach twenty percent within five years.",
         "忽視中庸治理手段：非黑即白地強推全城禁車，排除擁擠稅收費、號誌時相優化、強化公車接駁等漸進高效之交通治理手段。",
         "極端排除政策：忽略擁擠收費等有效調控措施。",
         "gridlock", "/ˈɡrɪd.lɑːk/", "交通大癱瘓僵局", "untenable", "/ʌnˈten.ə.bəl/", "難以維持的站不住腳的"),

        ("An energy lobbyist claimed: 'The nation can either continue extracting fossil fuels without new environmental regulations, or our electrical grid will experience nationwide rolling blackouts. Because blackouts would ruin industry, we must dismantle all regulatory constraints.' This argument is logically deficient because it:",
         "Creates a false dichotomy between unregulated fossil fuel extraction and grid collapse, ignoring diversified renewable energy transitions and regulatory modernization.",
         "Assumes that nuclear reactors require three decades of engineering construction.",
         "Fails to quantify the exact megawatt capacity of offshore wind turbine arrays.",
         "Ignores that coal mining labor unions negotiate multi-year collective bargaining agreements.",
         "虛假對立：將『廢除一切環保規管』與『全國大停電』對立起來，無視現代電網可透過綠能轉型、儲能系統及精準監管取得平衡發展。",
         "假對立謬誤：無視能源多角化與儲能技術的中間路徑。",
         "blackout", "/ˈblæk.aʊt/", "大停電斷電燈火管制", "dismantle", "/dɪsˈmæn.t̬əl/", "廢除拆卸拆開"),

        ("A diet book author stated: 'A person must either strictly adhere to a zero-carbohydrate carnivore regimen or suffer chronic metabolic disease and premature death. There is no middle ground in human nutritional biochemistry.' What is the primary logical flaw in this claim?",
         "It falsely polarizes human dietetics into two stark extremes, ignoring that balanced diets containing complex carbohydrates sustain long-term cardiovascular health.",
         "It neglects to provide recipes for preparing lean poultry cuts.",
         "It assumes that exercise routines burn calories at identical rates across gender cohorts.",
         "It fails to cite the international market price of grass-fed bovine tallow.",
         "非黑即白飲食極端論：抹煞營養學光譜，宣稱不是『零碳純肉』就是『慢性病暴斃』，完全抹殺了地中海飲食與均衡飲食的龐大醫學實證。",
         "極端二分法：抹殺均衡營養光譜與中間醫學實證。",
         "metabolic", "/ˌmet̬.əˈbɑː.lɪk/", "新陳代謝的", "carnivore", "/ˈkɑːr.nə.vɔːr/", "食肉動物純肉飲食者"),

        ("A parenting influencer declared: 'Parents must either enforce absolute authoritarian obedience in their children or watch them grow up to become delinquent criminals. Since no parent wants a criminal child, absolute obedience is the only moral parenting philosophy.' The reasoning is flawed because it:",
         "Frames parenting strategies as an all-or-nothing choice between strict authoritarianism and complete lawlessness, disregarding authoritative and nurturing guidance styles.",
         "Fails to analyze juvenile recidivism statistics across municipal detention centers.",
         "Assumes that children who practice classical violin never experience emotional tantrums.",
         "Ignores that secondary school curricula incorporate civics education classes.",
         "二分教養極端論：將教養簡化為『絕對專制高壓』與『墮落犯罪』，無視權威民主型 (authoritative) 及引導式教養等公認最健康的成熟教養模式。",
         "教養模型假兩難：忽視民主引導型之中間成熟策略。",
         "authoritarian", "/əˌθɔːr.əˈter.i.ən/", "威權主義的專制的獨裁的", "delinquent", "/dɪˈlɪŋ.kwənt/", "違法行為的失足的青少年犯"),

        ("A software engineer argued: 'We must either rewrite our five-million-line codebase from scratch in an entirely new programming language, or technical debt will cause our application to permanently crash tomorrow. Therefore, a complete rewrite is mandatory.' Which flaw is evident here?",
         "It ignores incremental refactoring and targeted module optimization as viable alternatives to a perilous total system rewrite.",
         "It fails to benchmark compilation speed between static and dynamic typing runtimes.",
         "It presumes that new programming languages require specialized integrated development environments.",
         "It takes for granted that database queries consume more memory than frontend rendering engines.",
         "工程二分假兩難：預設只有『全盤重寫五百萬行代碼』與『明天徹底崩潰』兩極，忽視了漸進式模組重構 (incremental refactoring) 等穩健工程手段。",
         "工程極端決策謬誤：忽視漸進重構之可行方案。",
         "refactor", "/riːˈfæk.tɚ/", "重構重整代碼架構", "perilous", "/ˈper.əl.əs/", "危險的充滿風險的"),

        ("An art museum board chair asserted: 'The museum must either sell off its prized Renaissance paintings to cover operational deficits, or close its doors forever. We refuse to shutter our doors, so the paintings must be auctioned immediately.' The argument is flawed because it:",
         "Presents selling core collections and permanent closure as the only options, ignoring endowment fundraising, ticket restructuring, or operational cost reductions.",
         "Assumes that Renaissance paintings require atmospheric humidity control systems.",
         "Fails to disclose whether the paintings were donated with legally binding donor covenants.",
         "Presumes that modern art exhibitions attract younger demographic audiences.",
         "破產威脅下的假兩難：將經營抉擇窄化為『賣祖產名畫』或『永遠倒閉』，無視捐贈基金募款 (endowment)、票價調整或成本精簡等健全營運選項。",
         "財務治理假兩難：忽視募款與撙節開支等中間途徑。",
         "endowment", "/ɪnˈdaʊ.mənt/", "捐贈基金稟賦天賦", "covenant", "/ˈkʌv.ə.nənt/", "契約協約盟約限制性條款"),

        ("A trade protectionist argued: 'Our domestic market must either enact total tariffs on all imported industrial components or witness the total extinction of our manufacturing workforce. Hence, a complete trade embargo on components is vital.' What logical flaw weakens this argument?",
         "It treats absolute protectionism and complete deindustrialization as the only outcomes, neglecting targeted tariffs, workforce upskilling, and domestic production subsidies.",
         "It presumes that freight container shipping rates will double over the subsequent fiscal quarter.",
         "It overlooks that domestic patent litigation has increased among industrial robotics manufacturers.",
         "It assumes that consumer goods packaging relies predominantly on virgin corrugated cardboard.",
         "貿易政策假兩難：宣稱要麼全面課徵封閉性重稅，要麼製造業徹底滅亡。忽略了靶向補貼、勞工技能升級或結構性關稅等多元平衡政策工具。",
         "貿易保護假兩難：忽視靶向補貼與產業轉型之中間選項。",
         "tariff", "/ˈter.ɪf/", "關稅價目表", "deindustrialization", "/diː.ɪnˌdʌs.tri.ə.laɪˈzeɪ.ʃən/", "去工業化去產業化")
    ]),

    # 16. Drawing Valid Inferences: Strictly Deductive Conclusions
    ("Drawing Valid Inferences: Strictly Deductive Conclusions", "批判推理", "C2-GMAT16", [
        ("All prospective flight attendants at AirGlobal must pass a rigorous multi-tier security clearance. Anyone who holds a past criminal conviction for identity fraud is permanently barred from obtaining this security clearance. Jason was hired as an AirGlobal flight attendant yesterday. If the statements above are true, which of the following must also be true?",
         "Jason has never been convicted of criminal identity fraud.",
         "Jason has completed at least five hundred commercial flight hours.",
         "Jason holds an advanced university degree in aviation safety management.",
         "AirGlobal has never hired an individual who failed a routine medical examination.",
         "嚴密演繹推理 (Strictly Deductive Inference)：所有錄取者皆通過審查；有身分詐欺前科者絕對無法通過審查；傑森昨日被錄取為空服員。因此，傑森絕對沒有身分詐欺前科。100% 邏輯必然得出。",
         "GMAT 核心演繹題型：三段論必真推論 (Modus Tollens)。",
         "clearance", "/ˈklɪr.əns/", "許可安全審查通過清理", "rigorous", "/ˈrɪɡ.ɚ.əs/", "嚴格的嚴密的嚴厲的"),

        ("No commercial airliner manufactured by AeroTech has ever suffered a fuselage structural failure while cruising at operational altitude. Every transatlantic passenger flight operated by TransSky Airlines utilizes aircraft manufactured by AeroTech. Flight TS-402, a TransSky passenger flight en route from New York to London, suffered an in-flight fuselage structural failure. Which statement must be true based on the premises?",
         "Flight TS-402 was not cruising at operational altitude when the structural failure occurred.",
         "Flight TS-402 was carrying twice its certified maximum cargo weight.",
         "AeroTech will be forced to recall all commercial airliners currently in global operation.",
         "TransSky Airlines will immediately cease all transatlantic route schedules.",
         "嚴密演繹必真推論：AeroTech 飛機在巡航高度下從未發生機身結構損壞；TransSky 跨大西洋客機皆為 AeroTech 製造；TS-402 為此類客機且發生了結構損壞。因此，損壞發生時該客機絕對不在平飛巡航高度（例如在起飛或爬升降落階段）。",
         "嚴格否定後件推論：排除前提否定之必然結論。",
         "fuselage", "/ˈfjuː.zə.lɑːʒ/", "機身機體", "altitude", "/ˈæl.tə.tuːd/", "高度海拔高處"),

        ("Every senior partner at the law firm Sterling & Cross owns equity shares in the corporate partnership. Any attorney who owns equity shares is legally prohibited from personally representing clients in litigation adverse to the partnership's corporate clients. Attorney Elena represents a client who is suing Sterling & Cross's largest corporate client. If the statements above are true, which must be true?",
         "Elena is not a senior partner at Sterling & Cross.",
         "Elena was formerly an associate attorney at Sterling & Cross.",
         "The litigation against the corporate client will be dismissed with prejudice.",
         "All associate attorneys at Sterling & Cross are permitted to sue any corporate entity.",
         "嚴密三段論推論：高級合夥人必持股；持股人依法不得代表客戶起訴該所客戶；Elena 正在起訴該所最大客戶。因此，Elena 必然不是該所的高級合夥人。",
         "嚴格推論：否定後件 (Elena 訴訟 -> Elena 未持股 -> Elena 非高級合夥人)。",
         "equity", "/ˈek.wə.t̬i/", "股權普通股公平資產淨值", "adverse", "/ædˈvɝːs/", "不利的相反的敵對的"),

        ("During the annual audit, any financial division of OmniCorp that fails to reconcile its accounts payable ledger within twenty-four hours receives a mandatory regulatory censure. The Logistics Division received no regulatory censure following this year's annual audit. Which of the following is logically guaranteed by this information?",
         "The Logistics Division reconciled its accounts payable ledger within twenty-four hours during the audit.",
         "The Logistics Division incurred fewer operating expenses than any other division of OmniCorp.",
         "OmniCorp will dismiss the head of accounting for the Logistics Division.",
         "Every financial division of OmniCorp completed its annual audit ahead of schedule.",
         "逆否命題必真 (Contrapositive)：若未在24小時內完成帳目調節則必受懲戒；後勤部門未受懲戒。因此，後勤部門必然在24小時內完成了調節。逆否命題等價於原命題。",
         "演繹邏輯：逆否命題必真律 (~Q -> ~P)。",
         "reconcile", "/ˈrek.ən.saɪl/", "對帳調節和解調和", "censure", "/ˈsen.ʃɚ/", "譴責嚴厲指責戒飭"),

        ("Every residential architectural blueprint approved by the municipal planning board in Greenfield must meet both seismic reinforcement standards and passive solar heating criteria. Blueprint Model Alpha meets seismic reinforcement standards but relies entirely on active geothermal heat pumps. If the rules above are enforced, what must follow?",
         "Blueprint Model Alpha cannot be approved by the Greenfield municipal planning board as a residential blueprint.",
         "Blueprint Model Alpha will be granted a permanent municipal zoning variance.",
         "Active geothermal heating is legally prohibited in commercial buildings in Greenfield.",
         "Passive solar heating is cheaper to install than geothermal heat pump infrastructure.",
         "嚴格演繹推論：核准必須『同時具備』防震與被動式太陽能；Alpha 模型只有防震、無被動太陽能（改採主動地熱）。因此該模型必然無法通過該市住家藍圖審查。",
         "聯言命題否定推論：未滿足必要條件必不成立。",
         "seismic", "/ˈsaɪz.mɪk/", "地震的抗震的", "geothermal", "/ˌdʒiː.oʊˈθɝː.məl/", "地熱的地熱能的"),

        ("All certified sommeliers at the Grand Palate Restaurant must have passed the Level Four Master tasting examination. No individual who experiences chronic olfactory nerve dysfunction can pass the Level Four Master tasting examination. Chef Marcus is a certified sommelier at the Grand Palate Restaurant. What can be properly inferred?",
         "Marcus does not suffer from chronic olfactory nerve dysfunction.",
         "Marcus has worked in culinary restaurants for at least fifteen years.",
         "No chef at the Grand Palate Restaurant is permitted to cook without tasting ingredients.",
         "The Level Four Master tasting examination includes thirty vintage French Bordeaux wines.",
         "嚴格演繹推理：侍酒師必通過四級考試；有嗅覺神經障礙者絕無法通過；Marcus 是該餐廳認證侍酒師。推導出 Marcus 絕無慢性嗅覺神經障礙。",
         "演繹推理鏈： Marcus -> 通過考試 -> 無嗅覺神經障礙。",
         "sommelier", "/səmˈel.jeɪ/", "侍酒師酒窖主管", "olfactory", "/ɑːlˈfæk.tɚ.i/", "嗅覺的"),

        ("Whenever the temperature inside the chemical polymerization reactor drops below 180 degrees Celsius, catalyst decay occurs automatically. Whenever catalyst decay occurs, the resultant plastic polymers become brittle and unmarketable. A batch of plastic polymers produced by the reactor was verified to be highly flexible and commercially marketable. Which conclusion is definitively proven?",
         "The temperature inside the reactor did not drop below 180 degrees Celsius during the production of this batch.",
         "The reactor operated at an internal temperature of precisely 250 degrees Celsius.",
         "The chemical manufacturer will install automated backup heating coils immediately.",
         "Brittle plastic polymers can be recycled into high-grade automotive bumpers.",
         "假言連鎖演繹推論：低於180度 -> 觸媒衰變 -> 塑膠脆化無法銷售。現已證實該批塑膠韌性極高且暢銷（非脆化），逆否推導出當時反應爐溫度絕對沒有跌破180度。",
         "連續連鎖逆否推論：~脆化 -> ~衰變 -> ~低於180度。",
         "catalyst", "/ˈkæt̬.əl.ɪst/", "催化劑觸媒促進因素", "brittle", "/ˈbrɪt̬.əl/", "脆的易碎的脆弱的"),

        ("Only employees who possess an active cryptographic clearance key can decrypt and view Project Zephyr documentation. All software developers who joined after January 1st were denied cryptographic clearance keys. Rachel is currently decrypting and viewing Project Zephyr documentation. What must be true?",
         "Rachel did not join the software development team after January 1st.",
         "Rachel is the chief architect and technical supervisor of Project Zephyr.",
         "Cryptographic clearance keys are reset and reissued every ninety days.",
         "Project Zephyr documentation contains confidential military defense patents.",
         "必要條件演繹推論：能解密者必有密鑰；1月1日後入職之軟體人員皆無密鑰；Rachel 正在解密。因此 Rachel 絕非1月1日後入職的軟體開發人員。",
         "必要條件逆否推理：有解密權限者必然排除無密鑰群體。",
         "cryptographic", "/ˌkrɪp.təˈɡræf.ɪk/", "密碼的密碼學的加密的", "decrypt", "/diːˈkrɪpt/", "解密破解密文"),

        ("Every hospital patient who received medication Delta exhibited elevated liver enzymes within forty-eight hours. No patient who has elevated liver enzymes is permitted to undergo elective orthopedic surgery. Patient Gomez underwent elective orthopedic surgery at the hospital yesterday. If all statements are true, which must also be true?",
         "Gomez did not receive medication Delta within the forty-eight hours prior to surgery.",
         "Gomez has completely recovered from his elective orthopedic surgical procedure.",
         "Medication Delta is the most potent anti-inflammatory prescription available at the hospital.",
         "Orthopedic surgeons are legally liable for any elevated liver enzyme complications.",
         "三段論否定式推論：服 Delta 藥物 -> 48小時內肝指數升高；肝指數升高 -> 不得動骨科擇期手術；Gomez 動了骨科擇期手術。證明 Gomez 在術前48小時內未服用 Delta 藥物。",
         "演繹推理：逆否鏈條 ~不得手術 -> ~指數升高 -> ~未服Delta。",
         "orthopedic", "/ˌɔːr.θəˈpiː.dɪk/", "骨科的矯形的", "elective", "/iˈlek.tɪv/", "非緊急的擇期的選修的"),

        ("All venture capital partners at Apex Capital who evaluated the robotics pitch agreed that the valuation was unrealistic. Anyone who agreed that the valuation was unrealistic voted against investing in the robotics startup. Partner Liam voted in favor of investing in the robotics startup. What must be concluded from these facts?",
         "Liam is either not a partner at Apex Capital or did not evaluate the robotics pitch.",
         "Liam believes the robotics startup will achieve profitability within one year.",
         "The robotics startup secured financing from a competing venture capital syndicate.",
         "Apex Capital has never invested in an early-stage artificial intelligence robotics firm.",
         "嚴密德摩根與三段論演繹：Apex合夥人且評估該案者 -> 認同估值不合理 -> 投反對票。Liam 投了贊成票（否定結論），表示 Liam 未同時滿足前提兩條件（要麼不是Apex合夥人，要麼當時根本沒去評估該案）。",
         "複合命題演繹否定：否定後件導出前件聯言命題之否定 (~(P and Q) = ~P or ~Q)。",
         "valuation", "/ˌvæl.juˈeɪ.ʃən/", "估值評價評定", "syndicate", "/ˈsɪn.də.kət/", "辛迪加聯合組織財團")
    ]),

    # 17. Drawing Valid Inferences: Avoiding Speculative Extrapolations
    ("Drawing Valid Inferences: Avoiding Speculative Extrapolations", "批判推理", "C2-GMAT17", [
        ("Archaeologists excavating a coastal Bronze Age settlement unearthed three bronze ceremonial daggers crafted with sophisticated metallurgy techniques not documented in the region until five centuries later. The soil layer was verified undisturbed by modern intrusive digging. Which conclusion is most reliably supported without speculative overreach?",
         "The metallurgical techniques used to manufacture the daggers existed earlier than had previously been documented for that geographical region.",
         "The settlement was an empire's capital city that dominated maritime trade routes.",
         "Bronze Age metallurgists had direct contact with Mediterranean sea merchants.",
         "The ceremonial daggers were used exclusively in royal coronation ceremonies.",
         "防範過度推論 (Avoiding Overreach)：已知該未擾動土層出土了比該地區原先紀錄早500年的冶金青銅匕首。唯一必真、不跨越經驗邊界的推論是：製造這些匕首的冶金技術在該地區出現的時間比原先文獻記載的更早。其餘帝國霸權、海外商隊、加冕儀式皆屬過度推測。",
         "GMAT 歸納題原則：嚴格基於文本邊界，拒絕無依據之過度外推 (No Wild Extrapolations)。",
         "metallurgy", "/ˈmet̬.əl.ɝː.dʒi/", "冶金學冶金術", "intrusive", "/ɪnˈtruː.sɪv/", "侵入的打擾的侵入性的"),

        ("A survey of eight hundred public high school teachers in a Midwestern state revealed that ninety-two percent spend an average of four hundred dollars of their personal funds annually on basic classroom school supplies. What can be most reasonably inferred from this survey data?",
         "A substantial majority of the surveyed teachers utilize personal financial resources to provide materials for their classrooms.",
         "School boards in the Midwestern state deliberately misappropriate education budget funds.",
         "High school teachers in private schools never spend personal money on classroom supplies.",
         "Public high schools will experience widespread teacher strikes in the subsequent school year.",
         "合理事實推論：調查顯示該州 92% 的受訪公立高中教師每年平均自掏腰包 400 美元購買文具。僅能穩妥推論出：受訪教師中絕大多數人都動用了個人資金提供教室物資。不能腦補貪污或罷工等情節。",
         "文本事實歸納：嚴格忠實於統計母體與事實陳述。",
         "misappropriate", "/ˌmɪs.əˈproʊ.pri.eɪt/", "挪用侵吞濫用", "substantial", "/səbˈstæn.ʃəl/", "大量的實質的重大的"),

        ("In a monitored wildlife sanctuary, the population of predatory gray wolves increased by thirty percent over five years, during which the local population of white-tailed deer declined by twenty-five percent, while the abundance of wild browse vegetation showed a thirty-five percent resurgence. What is the most circumspect inference supported by this data?",
         "The decline in the deer population occurred concurrently with an increase in the wolf population and a resurgence in browse vegetation.",
         "Gray wolves are the sole environmental determinant regulating white-tailed deer mortality.",
         "Eliminating gray wolves would permanently cause the starvation of all local herbivores.",
         "Browse vegetation grew more rapidly due to increased nitrogen deposition from wolf excretions.",
         "嚴謹客觀描述推論：生態監測數據顯示狼增加、鹿減少、植被復甦。最嚴謹合乎邏輯的推論是客觀確認這三項現象在同個時間跨度內並行發生。未排除氣候、獵捕等變數前，不能斷言狼是鹿死亡的『唯一決定因素』。",
         "審慎推論原則：描述相關性 (co-occurrence) 優先於未經嚴格驗證之單一決定性因果斷言。",
         "resurgence", "/rɪˈsɝː.dʒəns/", "復甦回潮復興", "circumspect", "/ˈsɝː.kəm.spekt/", "慎重的謹慎小心的周全的"),

        ("Laboratory analyses showed that mice fed diet X lived an average of twenty-eight months, whereas mice fed standard diet Y lived an average of twenty-two months. Both cohorts were kept in identical climate-controlled pathogen-free vivariums. Which inference is best justified?",
         "Under the controlled conditions of the experiment, mice fed diet X exhibited a longer average lifespan than mice fed diet Y.",
         "Diet X will extend human life expectancy by six years if adopted in clinical trials.",
         "Diet Y contains synthetic carcinogenic preservatives that induce cellular senescence.",
         "Mice fed diet X experienced zero cases of age-related cardiovascular degeneration.",
         "實驗室邊界推論：在該受控實驗條件下，吃 X 飲食的老鼠平均壽命長於吃 Y 飲食的老鼠。不能跨物種推論人類壽命延長六年，也不能無端臆測 Y 飼料含有致癌防腐劑。",
         "實驗數據嚴格推論：僅限於特定受試樣本與受控實驗環境之統計結論。",
         "vivarium", "/vaɪˈver.i.əm/", "實驗動物飼養所生態缸", "senescence", "/sɪˈnes.əns/", "衰老老化"),

        ("A longitudinal study tracked three thousand corporate managers over a decade and found that those who slept fewer than six hours per night reported forty percent more sick leave days than those who slept seven to eight hours. What can be safely inferred?",
         "There is a positive statistical association between sleeping fewer than six hours per night and taking higher amounts of sick leave among the surveyed managers.",
         "Sleeping exactly nine hours per night guarantees immunity from viral respiratory infections.",
         "Workplace stress causes individuals to develop chronic neurological sleep disorders.",
         "All managers who slept eight hours received faster career promotions than short sleepers.",
         "統計關聯性推論：研究確立了每晚少於6小時睡眠與請更多病假之間的『正統計關聯性 (positive statistical association)』。不能妄自過度外推為睡眠9小時必然免疫或加班壓力造成神經病變。",
         "統計相關非全稱必然：僅承認統計相關性，拒絕絕對化因果推論。",
         "longitudinal", "/ˌlɑːn.dʒəˈtuː.dɪ.nəl/", "縱向的長期的經度的", "association", "/əˌsoʊ.siˈeɪ.ʃən/", "關聯聯繫協會聯合"),

        ("In an excavation of an unplundered eighteenth-century royal crypt, forensic historians found that the lead coffin had completely shielded the embalmed remains from microbial decomposition, leaving textile vestments perfectly intact. Which statement is fully supported?",
         "The physical barrier provided by the lead coffin prevented the entry of microorganisms that would otherwise cause microbial decomposition of the remains.",
         "Lead coffin burial was universally accessible to all social strata in the eighteenth century.",
         "Embalming herbs used in the crypt possessed greater antibacterial potency than modern penicillin.",
         "The monarch interred in the crypt died of acute environmental heavy metal poisoning.",
         "物理因果邊界推論：鉛棺提供的物理密封屏障阻絕了微生物分解遺體與衣物。不能擅自腦補鉛棺葬禮普及平民、古代防腐草藥強過盤尼西林、或是該國王死於重金屬中毒。",
         "文本事實錨定：基於物理防護機制得出直接推論，杜絕主觀臆造。",
         "crypt", "/krɪpt/", "地下墓穴地窖", "embalmed", "/ɪmˈbɑːmd/", "防腐的塗以香料的"),

        ("A regional commercial bank reported that default rates on unsecured personal loans rose from two percent in 2021 to six percent in 2023, while default rates on collateralized auto loans remained steady at 1.5%. Which inference is best substantiated by this financial report?",
         "Between 2021 and 2023, the bank observed a greater increase in the default rate on unsecured loans than on collateralized auto loans.",
         "Unsecured personal loans will be permanently eradicated from the commercial banking sector.",
         "Borrowers who defaulted on auto loans surrendered their residential real estate titles.",
         "The bank incurred catastrophic operating losses across its retail operations in 2023.",
         "數據差值嚴密歸納：無擔保個人貸款違約率升幅 (2%->6%) 大於有抵押汽車貸款違約率升幅 (維持1.5%)。僅能就此比較數字得出穩健結論，不能臆測銀行全面廢除個人信貸或面臨破產。",
         "金融數據對比推論：依據客觀百分比走勢進行事實判定。",
         "unsecured", "/ʌn.səˈkjʊrd/", "無擔保的無防護的", "collateralized", "/kəˈlæt̬.ɚ.ə.laɪzd/", "有擔保的以資產質押的"),

        ("Over a three-year period, a municipality added forty miles of separated bicycle lanes and saw reported bicycle accidents involving motor vehicles decrease by twelve percent. Which inference avoids unwarranted speculation?",
         "The period following the addition of separated bike lanes coincided with a reduction in vehicular bicycle accidents in the municipality.",
         "Separated bicycle lanes eliminate all roadway traffic hazards for urban cyclists.",
         "Automobile drivers in the municipality received advanced safety awareness training.",
         "Every municipal cyclist now uses separated bike lanes exclusively during commutes.",
         "審慎時序關聯推論：增設獨立自行車專用道期間，與機動車事故減少12%的趨勢相互伴隨 (coincided with)。不能誇大為消除『所有』道路危險，亦不能無中生有指控司機全體受訓。",
         "杜絕全稱絕對化：避免使用 eliminate all 等極端誇大之詞。",
         "coincided", "/ˌkoʊ.ɪnˈsaɪdɪd/", "巧合同時發生一致", "unwarranted", "/ʌnˈwɔːr.ən.t̬ɪd/", "無根據的無端的未獲授權的"),

        ("An experiment demonstrated that tomato seedlings exposed to blue LED wavelengths developed twenty percent thicker stems than seedlings exposed to red LED wavelengths under identical ambient moisture and carbon dioxide levels. What is the most defensible conclusion?",
         "Under the tested ambient conditions, exposure to blue LED light was associated with greater stem thickness than exposure to red LED light.",
         "Blue LED wavelengths enhance the sugar sweetness of mature harvestable tomatoes.",
         "Red LED lighting disrupts chlorophyll synthesis in all horticultural plant species.",
         "Farmers who cultivate greenhouse tomatoes should eliminate natural sunlight completely.",
         "受控植物生理推論：在該受控條件下，藍光LED與幼苗莖部增粗顯著相關。不能外推至果實含糖甜度、不能否定紅光的葉綠素合成、更不能建議農民完全廢除天然陽光。",
         "植物生理受控推論：恪守變數範圍，不任意跨階段推論果實特質。",
         "seedling", "/ˈsiːd.lɪŋ/", "幼苗苗木", "horticultural", "/ˌhɔːr.t̬əˈkʌl.tʃɚ.əl/", "園藝的園藝學的"),

        ("In a trial of a digital language app, adult learners who completed fifteen minutes of daily spaced-repetition drills scored eighteen percent higher on vocabulary retention tests than those who studied once weekly for two hours. What conclusion is safely warranted?",
         "In this trial, frequent shorter study intervals were correlated with higher vocabulary retention scores than a single extended weekly session.",
         "Spaced-repetition software guarantees native-level conversational fluency within six months.",
         "Studying for two hours consecutively damages long-term cognitive synaptic memory pathways.",
         "Learners using spaced repetition never need to review grammatical syntactic structures.",
         "間隔重複事實推論：試驗表明每日15分鐘分散複習比每週一次2小時集中苦讀取得更高的詞彙記憶分數。安全推論為：高頻短間隔複習與較高的詞彙保留率具相關性。不能誇大為保證母語流利。",
         "學習科學審慎結論：短時分散訓練勝於長時集中突擊。",
         "spaced repetition", "/ˌspeɪst rep.əˈtɪʃ.ən/", "間隔重複間隔記憶法", "synaptic", "/sɪˈnæp.tɪk/", "突觸的神經突觸的")
    ]),

    # 18. Numerical & Statistical Logic: Confusing Absolute Numbers with Percentages
    ("Numerical & Statistical Logic: Confusing Absolute Numbers with Percentages", "批判推理", "C2-GMAT18", [
        ("In Metropolis, the total number of bicycle theft complaints registered with the police department fell from five thousand in 2020 to four thousand in 2022. The mayor boasted that Metropolis's municipal bicycle anti-theft program reduced the risk of bicycle theft by twenty percent. Which of the following, if true, reveals the statistical flaw in the mayor's claim?",
         "The total number of operational bicycles owned and ridden in Metropolis decreased by forty percent over the same two-year period.",
         "Motor vehicle carjackings in Metropolis increased by fifteen percent during the identical timeframe.",
         "The retail purchase price of anti-theft bicycle chain locks increased by eight percent.",
         "Metropolis allocated three hundred thousand dollars to create public bicycle lock stations.",
         "絕對數量與比例混淆 (Numbers vs. Percentages)：市長看到失竊報案總件數從5000降至4000（降20%），就自吹失竊風險降低20%。若全市自行車保有總數暴跌了40%（分母大幅縮水），則實際每台車失竊的風險反而是大幅上升的！",
         "GMAT 核心統計思維：忽視分母基礎總量變動 (Base Rate & Denominator Shift)。",
         "carjacking", "/ˈkɑːrˌdʒæk.ɪŋ/", "劫車搶劫車輛", "complaint", "/kəmˈpleɪnt/", "投訴申訴報案怨言"),

        ("A hospital administrator declared: 'Hospital A is far more hazardous for surgical patients than Hospital B because Hospital A recorded two hundred postoperative surgical infections last year, whereas Hospital B recorded only fifty.' Which of the following exposes the flaw in this comparison?",
         "Hospital A performed ten thousand surgeries last year, whereas Hospital B performed only one thousand.",
         "Hospital A employs twice as many registered nurses as Hospital B.",
         "Hospital B specialized in outpatient cosmetic dental procedures.",
         "The average length of patient hospitalization at Hospital A was three days.",
         "忽視手術總量基數：A醫院感染200例，B醫院感染50例。若A醫院總共動了10,000台手術（感染率僅 2%），而B醫院只動了1,000台手術（感染率高達 5%），則A醫院手術安全率顯著高於B醫院！",
         "基數差異謬誤：絕對感染數不能代表真實感染率 (Infection Rate)。",
         "hazardous", "/ˈhæz.ɚ.dəs/", "危險的有害的具危害性的", "postoperative", "/ˌpoʊstˈɑː.pɚ.ə.t̬ɪv/", "術後的"),

        ("A pharmaceutical company celebrated that adverse allergic reactions to its new allergy spray accounted for only 0.5% of all reported pharmaceutical allergic reactions nationwide, concluding that the spray is exceptionally safe. Why is this conclusion misleading?",
         "The allergy spray is an orphan drug prescribed to only a few dozen patients nationwide, while other drugs are taken by millions.",
         "Allergic reactions are typically characterized by nasal congestion and skin urticaria.",
         "The spray was developed in partnership with a European biotechnology institute.",
         "The retail cost of the spray is covered by prescription drug insurance formularies.",
         "市場份額極小造成的比例假象：該噴劑的過敏通報僅佔全國所有藥物過敏通報的0.5%，但若該藥是極小眾罕見病用藥（全國僅幾十人使用），其在自身使用者中的過敏發生率可能極高！",
         "全國總通報佔比與個體藥物發病率混淆謬誤。",
         "orphan drug", "/ˈɔːr.fən ˌdrʌɡ/", "罕見病藥物孤兒藥", "urticaria", "/ˌɝː.t̬əˈker.i.ə/", "蕁麻疹風疹塊"),

        ("A regional airline advertised: 'Fly with us—our flights accounted for only two percent of all delayed flights nationwide last month!' Which of the following, if true, most seriously undermines this promotional claim?",
         "The regional airline operates only 0.5% of all commercial flights scheduled nationwide.",
         "The airline operates turboprop regional planes on short-haul mountain routes.",
         "Commercial jet fuel costs increased by four percent across global supply hubs.",
         "The airline's customer service hotline received sixty thousand phone inquiries.",
         "比例與市場份額嚴重脫節：該航空公司班機只佔全國延誤航班的2%，聽起來很低；但若該航司的班機起降總量僅佔全國的0.5%，表示其延誤率高達全國平均的4倍！",
         "市場基數佔比錯覺：延誤份額高於飛行總量份額。",
         "turboprop", "/ˈtɝː.boʊ.prɑːp/", "渦輪螺旋槳飛機", "undermine", "/ˌʌn.dɚˈmaɪn/", "削弱損害破壞"),

        ("A school district claimed: 'Our scholarship tutoring initiative was a phenomenal success: the number of students receiving academic honors doubled from ten to twenty!' What context, if true, reveals the weakness of this boast?",
         "During the same academic year, the total high school student enrollment expanded from one hundred to one thousand.",
         "The tutoring initiative met for two hours every Tuesday and Thursday afternoon.",
         "Standardized state exam formats were transitioned from paper to digital terminals.",
         "The school district hired three additional certified mathematics instructors.",
         "分子翻倍但分母暴增：優等生由10人增至20人（增加一倍），但全校學生總數由100人暴增至1,000人（優等生比例由10%暴跌至2%），計畫實際上是失敗或倒退的。",
         "率與總量之分母稀釋：母體擴張導致優等生比例實質大跌。",
         "initiative", "/ɪˈnɪʃ.ə.t̬ɪv/", "倡議新方案主動權主導性", "enrollment", "/ɪnˈroʊl.mənt/", "入學人數註冊人數"),

        ("An industrial manufacturer claimed that workplace injuries had plummeted because the factory recorded thirty fewer injury incidents this year than last year. Which of the following, if true, most completely refutes the factory's claim of improved safety?",
         "Due to supply shortages, the factory operated with seventy percent fewer employee labor hours than it did the previous year.",
         "The factory manufactured hydraulic industrial valves for agricultural irrigation systems.",
         "OSHA inspectors conducted an unannounced walkthrough inspection in November.",
         "The factory spent fifty thousand dollars upgrading its emergency eye-wash stations.",
         "工時基數暴跌掩蓋工傷率上升：工傷件數雖然減少30件，但因斷料導致工廠全年生產總工時暴跌了70%，若以每百萬工時工傷率計算，工安風險反而顯著惡化！",
         "總量減少不等於事故率降低：忽視暴露時間（工時基數）。",
         "hydraulic", "/haɪˈdrɑː.lɪk/", "水力的液壓的水壓的", "unannounced", "/ˌʌn.əˈnaʊnst/", "突擊的不經預先通知的"),

        ("A venture capital investor asserted: 'Fintech startups are three times more likely to fail than Biotech startups because last year one hundred and fifty Fintech startups declared bankruptcy compared to only fifty Biotech startups.' What is the fundamental flaw in this reasoning?",
         "It compares the raw number of bankruptcies without accounting for the total number of startups founded in each industry.",
         "It assumes that venture capital funding rounds occur on fixed quarterly schedules.",
         "It overlooks that Biotech patents have a statutory duration of twenty years.",
         "It fails to define whether software development costs exceed laboratory reagent costs.",
         "忽視行業總基數：Fintech 破產150家，Biotech 破產50家。若市場上總共有1,500家 Fintech（破產率10%），而只有100家 Biotech（破產率高達50%），則生技公司失敗率高得多！",
         "絕對破產數與破產概率混淆謬誤。",
         "fintech", "/ˈfɪn.tek/", "金融科技金融科技公司", "reagent", "/riˈeɪ.dʒənt/", "試劑反應物"),

        ("A car insurer asserted that red sports cars are the most dangerous vehicles on the road because they are involved in more fatal collisions nationwide than yellow pickup trucks. What statistical omission undermines this conclusion?",
         "It fails to consider that red sports cars vastly outnumber yellow pickup trucks in total registered vehicles on the road.",
         "It ignores that sports car insurance premiums are fifteen percent higher on average.",
         "It assumes that sports cars possess smaller braking calipers than commercial pickup trucks.",
         "It takes for granted that sports car owners drive exclusively on interstate highways.",
         "車輛保有量基數差異：紅色跑車致命車禍總量多於黃色皮卡，但全美紅色跑車的總保有量若為黃色皮卡的五十倍，其每萬輛事故率很可能遠低於黃色皮卡。",
         "車輛總數基數偏差：未計算每單位車輛的暴露事故率。",
         "caliper", "/ˈkæl.ə.pɚ/", "卡鉗測徑器游標卡尺", "interstate", "/ˌɪn.t̬ɚˈsteɪt/", "州際的州際公路"),

        ("A municipal police chief announced: 'Our precinct is becoming dramatically safer: violent crime as a percentage of all reported crimes dropped from 30% to 15% this year.' Which finding exposes the chief's misleading rhetoric?",
         "The absolute number of violent crimes doubled, but reported non-violent property theft complaints increased tenfold.",
         "The police precinct purchased thirty new electric patrol cruisers.",
         "Neighborhood watch volunteers held weekly community safety briefings.",
         "Municipal court judges increased bail requirements for repeat felony offenders.",
         "相對比例掩蓋絕對暴力罪案飆升：暴力犯罪在總案件中佔比腰斬 (30%->15%)，看似治安改善；實際上暴力犯罪案件絕對數翻倍，只是因為竊盜案暴增十倍，將分母極端撐大！",
         "比例假象：其他分母項目惡性膨脹導致重點指標比例虛假下降。",
         "precinct", "/ˈpriː.sɪŋkt/", "警察轄區分局管區", "tenfold", "/ˈten.foʊld/", "十倍地"),

        ("A software company announced that its employee turnover rate was cut in half, dropping from 10% to 5% in one year, proving employee morale reached unprecedented heights. Which of the following, if true, reveals the flaw in this conclusion?",
         "The total headcount of the company expanded from one hundred to one thousand through aggressive entry-level hiring during the year, while the raw number of veteran resignations actually increased.",
         "Employee dental insurance benefits were outsourced to a regional provider.",
         "The human resources department introduced an anonymous digital suggestion box.",
         "The company relocated its corporate headquarters to an adjacent suburban office park.",
         "快速招募稀釋離職率：離職率由10%降至5%，但公司總人數因大量招收新人從100人擴增至1,000人（離職人數由10人增至50人），老鳥出走實質加劇，絕非士氣高昂！",
         "離職率被分母擴張稀釋：老員工離職總數實質激增。",
         "headcount", "/ˈhed.kaʊnt/", "總員工人數人數清點", "turnover", "/ˈtɝːnˌoʊ.vɚ/", "人員流動率營業額離職率")
    ])
]
