# scripts/diag_builders/tier7_part1_data.py
# Subtopics 1-13 for Tier 7 (GRE Verbal C1~C2, IDs 1501-1630)

subtopics_1_to_13 = [
    # 1. Semantic Clues: Contrast & Reversal Signals
    ("Semantic Clues: Contrast & Reversal", "語意邏輯", "C2-GRE01", [
        ("The diplomat’s outward veneer of affability ___ an unyielding, ruthless determination to impose harsh economic sanctions on his adversaries.", "belied", "corroborated", "presaged", "amplified", "這位外交官外表展現出親和友善的和藹面具，「掩蓋掩飾了」他對敵手實施嚴酷經濟制裁時那種毫不退讓、冷酷無情的冷酷決心。", "belie 意為「掩飾、使…產生錯覺、與…不符」，完美體現 outward veneer（表面偽裝）與 ruthless determination（冷酷內在）之間的強烈反差對比。", "GRE 核心轉折動詞：belie（掩蓋、證明…為虛假）。", "affability", "/ˌæf.əˈbɪl.ə.t̬i/", "和藹可親友善親切", "belie", "/bɪˈlaɪ/", "掩飾證明為虛假與…不符"),
        ("Far from being the ___ novice depicted in tabloid profiles, the young chess prodigy executed opening maneuvers with veteran calculating cunning.", "ingenuous", "sagacious", "mercenary", "pugnacious", "絕非小報花邊新聞所描繪的那般「天真單純無邪」，這位年輕的國際象棋神童以老牌大師般的精算老練狡黠，凌厲展開了開局佈局。", "Far from being... 提示反轉：後方為 veteran cunning（老練狡黠），前方空格必為反義詞 ingenuous（天真純樸的）。", "反義詞對立：veteran cunning 對應 ingenuous（純真無邪的）。", "ingenuous", "/ɪnˈdʒen.ju.əs/", "天真的單純純樸的坦白的", "sagacious", "/səˈɡeɪ.ʃəs/", "睿智的精明的有遠見的"),
        ("Although the literary critic’s review appeared outwardly complimentary, a careful reader could detect an undercurrent of ___ irony directed at the author’s pretension.", "caustic", "laudatory", "sycophantic", "deferential", "儘管該文學評論家的書評表面看似充滿溢美之辭，但細心的讀者卻能察覺其中暗藏著一股針對作者浮誇做作的「尖刻辛辣的」反諷潛流。", "Although appeared complimentary 轉折對立，空格需填負面尖酸詞 caustic（尖刻的、腐蝕性的）。", "讓步轉折反差：complimentary 對應 caustic irony。", "caustic", "/ˈkɑː.stɪk/", "尖刻辛辣的腐蝕性的", "pretension", "/prɪˈten.ʃən/", "做作自命不凡浮誇"),
        ("Rather than surrendering to the pervasive cynicism of his contemporaries, the philosopher maintained an ___ faith in humanity’s moral progress.", "unflagging", "ephemeral", "equivocal", "indolent", "這位哲學家並未屈服於同時代人普遍瀰漫的犬儒虛無主義，反而始終堅持著對人類道德進步「永不衰竭/堅定不移的」崇高信念。", "Rather than surrendering to cynicism 反轉對立，哲學家維持著 unflagging（不懈的、不衰退的）信念。", "轉折反向選詞：unflagging faith（堅定不移的信念）。", "cynicism", "/ˈsɪn.ə.sɪ.zəm/", "犬儒主義憤世嫉俗玩世不恭", "unflagging", "/ʌnˈflæɡ.ɪŋ/", "永不減弱的不懈的精力充沛的"),
        ("Despite his reputation for extreme parsimony in personal expenditures, the retired tycoon was remarkably ___ when endowing university research scholarships.", "munificent", "penurious", "frugal", "churlish", "儘管該退休大亨在個人日常生活開銷方面以極度吝嗇小氣聞名，但在資助成立大學科研獎學金時，卻顯得異常「慷慨解囊/揮金如土」。", "Despite parsimony（吝嗇小氣）讓步轉折，後方必填表示無私慷慨的褒義詞 munificent（極慷慨的）。", "強烈反義對比：parsimony 對應 munificent（極其慷慨的）。", "parsimony", "/ˈpɑːr.sə.moʊ.ni/", "吝嗇小氣過度節儉", "munificent", "/mjuːˈnɪf.ə.sənt/", "極其慷慨的豐厚的"),
        ("While the spokesperson insisted that the border troop mobilization was purely defensive, international observers interpreted the maneuvers as an ___ prelude to an invasion.", "unmistakable", "ambiguous", "anodyne", "inadvertent", "儘管官方發言人堅稱邊境軍隊集結純屬防禦性質，但國際軍事觀察家卻將該演習舉動解讀為一場入侵即將爆發的「昭然若揭/無可置疑的」前奏序曲。", "While insisted defensive 對比轉折，觀察家解讀為毫不掩飾的侵略信號，選 unmistakable（昭然若揭的、清晰無誤的）。", "轉折對立選 unmistakable（昭然若揭的）。", "anodyne", "/ˈæn.oʊ.daɪn/", "止痛劑平淡無奇的溫和的", "prelude", "/ˈprel.juːd/", "前奏序曲預兆"),
        ("The archival discovery did not refute the orthodox historical consensus; ___, it supplied corroborating documentary evidence that solidified the thesis.", "on the contrary", "inconsequentially", "superficially", "sporadically", "這項檔案歷史文獻的新發現非但沒有推翻正統的史學共識；「恰恰相反」，它提供了進一步佐證的文獻證據，使原論點更加牢不可破。", "did not refute... on the contrary supplied corroborating... 否定後強力反向遞進轉折，選 on the contrary。", "否定逆轉銜接詞選 on the contrary。", "corroborate", "/kəˈrɑː.bə.reɪt/", "證實支持確證", "refute", "/rɪˈfjuːt/", "反駁駁斥"),
        ("The monarch’s seemingly benevolent concessions were not motivated by altruism, but were rather ___ ploys intended to fracture the united coalition of dissenting nobles.", "Machiavellian", "seraphic", "quixotic", "magnanimous", "君王表面上看似仁慈的政治讓步絕非出於無私利他主義，反而是意在分化瓦解反對派貴族同盟的「馬基維利式權謀詭詐的」陰險手段。", "not altruism but rather... 對立轉折，排除利他，指向權術心計 Machiavellian（不擇手段權謀的）。", "語意對立：not altruism but Machiavellian ploys。", "altruism", "/ˈæl.tru.ɪ.zəm/", "利他主義無私奉獻", "Machiavellian", "/ˌmæk.i.əˈvel.i.ən/", "馬基維利式的狡猾權謀的"),
        ("Far from presenting a unified front, the parliamentary caucus was notoriously ___, fractured by bitter ideological schisms and personal feuds.", "fractious", "monolithic", "harmonious", "placid", "該議會黨團非但沒有展現團結一致的陣容，反而以「狂躁易怒/派系紛爭不斷的」惡名昭彰，被深層的意識形態分裂與私人恩怨撕裂得四分五裂。", "Far from unified front 提示反義，fractured by schisms 提示填 fractious（易怒爭吵不合的）。", "反義詞選定：unified 對應 fractious（搞分裂的、難駕馭的）。", "fractious", "/ˈfræk.ʃəs/", "易怒暴躁的搞分裂的難對付的", "monolithic", "/ˌmɑː.nəˈlɪθ.ɪk/", "鐵板一塊的龐大單一的"),
        ("Despite the company’s glowing quarterly earnings report, savvy equity analysts suspected that the stellar margins were largely ___ and concealed looming insolvency.", "illusory", "verifiable", "sustainable", "tangible", "儘管該公司公布了令人炫目的季度盈餘財報，但精明的證券分析師卻懷疑其亮眼利潤率多半是「虛幻泡影的」，掩蓋了迫在眉睫的破產危機。", "Despite glowing report... concealed looming insolvency，利潤率實為虛假，選 illusory（虛幻的、虛假的）。", "表象與本質轉折對比：glowing vs illusory。", "insolvency", "/ɪnˈsɑːl.vən.si/", "無償債能力破產", "illusory", "/ɪˈluː.sɚ.i/", "虛幻的幻覺的不切實際的")
    ]),
    # 2. Semantic Clues: Cause, Effect & Reinforcement Signals
    ("Semantic Clues: Cause, Effect & Reinforcement", "語意邏輯", "C2-GRE02", [
        ("The sudden collapse of the regional agricultural harvest was ___ by an unprecedented combination of multi-year drought and insect infestation.", "engendered", "precluded", "mitigated", "repudiated", "該地區農作物收成的突然全面崩潰瓦解，是由多年持續乾旱與毀滅性蟲害史無前例的雙重夾擊所「催生引發的」。", "engender 意為「產生、引起、催生」，精準表述災害因素促成崩潰之因果必然性。", "GRE 核心因果動詞：engender（引起、產生、催生）。", "infestation", "/ˌɪn.fesˈteɪ.ʃən/", "蟲害大批滋生侵擾", "engender", "/ɪnˈdʒen.dɚ/", "引起產生催生"),
        ("Because the archival record was notoriously fragmentary, the biographer had to exercise immense imaginative empathy to ___ the obscure motivations of the hermit poet.", "delineate", "obfuscate", "dissemble", "abrogate", "由於歷史檔案文獻極其殘缺零碎，傳記作家不得不發揮深厚的想像同理心，以「描摹勾勒出」這位隱士詩人晦澀隱密的心理動機。", "delineate 意為「生動描繪、精準刻劃勾勒」，呼應作家重塑詩人動機的學術努力。", "因果目的動詞選 delineate（精確描摹）。", "fragmentary", "/ˈfræɡ.mən.ter.i/", "殘缺不全的片段的", "delineate", "/dɪˈlɪn.i.eɪt/", "勾勒描繪畫出輪廓"),
        ("The discovery of deep-sea hydrothermal vents ___ long-standing geochemical dogma and catalyzed a total paradigm shift across marine biology.", "subverted", "buttressed", "vindicated", "enshrined", "深海地熱噴口的驚人發現，徹底「顛覆瓦解了」長久以來的地球化學傳統教條，並在整個海洋生物學領域催生引發了一場徹底的典範轉移。", "subvert（顛覆）呼應後方 catalyzed a total paradigm shift（催生典範轉移），強化對舊教條的打擊。", "強化因果動詞選 subverted（顛覆傳統教條）。", "dogma", "/ˈdɑːɡ.mə/", "教條信條", "subvert", "/səbˈvɝːt/", "顛覆推翻瓦解"),
        ("The governor's reckless deregulation of the municipal water authority effectively ___ the catastrophic lead contamination crisis.", "precipitated", "obviated", "ameliorated", "stifled", "州長對市屬供水管理局魯莽輕率的撤銷監管鬆綁政策，直接「導致促成引發了」災難性的重金屬鉛水污染公衛危機。", "precipitate 意為「促成、加速引發（災難等）」，為因果邏輯核心動詞。", "因果加速促成動詞選 precipitated（加速促發危機）。", "deregulation", "/diːˌreɡ.jəˈleɪ.ʃən/", "撤銷管制放鬆管制", "precipitate", "/prɪˈsɪp.ə.teɪt/", "加速促成沉澱猛然降下"),
        ("By meticulously documenting systemic bribery across municipal ministries, the investigative journalist’s exposé ___ widespread public outrage.", "galvanized", "quelled", "pacified", "attenuated", "藉由巨細靡遺地詳實記錄市政各部會系統性行賄受賄醜聞，這名調查記者的揭弊深度報導一舉「激發喚醒了」社會大眾普遍的憤怒浪潮。", "galvanize 意為「激勵、激起、使受電擊般震動驚醒」，接 public outrage 為經典同義強化搭配。", "激發公眾情緒動詞選 galvanized。", "exposé", "/ek.spoʊˈzeɪ/", "揭弊報導揭發真相的陳述", "galvanize", "/ˈɡæl.və.naɪz/", "刺激激勵通電鍍鋅"),
        ("The newly unearthed epigraphic inscriptions perfectly ___ the controversial thesis that the Bronze Age trading network extended into the Baltic.", "corroborated", "gainsaid", "debunked", "impugned", "這批新出土的古代銘刻碑文，完美地「證實佐證了」青銅時代海上貿易網絡曾一路延伸至波羅的海這項曾飽受爭議的假說。", "corroborate 意為「證實、提供支持證據」，加強論點正向真實性。", "強化證實動詞選 corroborated。", "epigraphic", "/ˌep.əˈɡræf.ɪk/", "銘文的碑文的", "corroborate", "/kəˈrɑː.bə.reɪt/", "證實支持確證"),
        ("Because the pharmaceutical compound exhibited extreme instability at room temperature, chemical engineers formulated an ___ polymer coating to protect its potency.", "impervious", "porous", "ephemeral", "osmotic", "由於該醫藥化合物在室溫條件下表現出極端不穩定性，化學工程師精心調配了一種「不可滲透的/密封絕緣的」聚合物保護塗層以捍衛其藥效活性。", "Because exhibited instability... 採取保護措施，塗層需具備隔離防滲透性，選 impervious。", "因果保護對應選 impervious（防滲透的）。", "potency", "/ˈpoʊ.tən.si/", "效力藥力潛力", "impervious", "/ɪmˈpɝː.vi.əs/", "不能滲透的不受影響的"),
        ("The sheer ubiquity of algorithmic surveillance in modern urban spaces has ___ a profound erosion of civil privacy expectations.", "fostered", "thwarted", "forestalled", "preempted", "現代城市空間中演算法無孔不入的普遍監控監聽，直接「助長促成了」公民對隱私保護預期心理的深層侵蝕淪喪。", "foster 意為「促進、助長、培養」，在此作為因果連結動詞。", "因果助長動詞選 fostered。", "ubiquity", "/juːˈbɪk.wə.t̬i/", "無所不在到處存在", "foster", "/ˈfɑː.stɚ/", "促進培養收養"),
        ("The decisive victory of the unionized workforce in the national strike ___ similar labor mobilization campaigns across industrial sectors.", "instigated", "deterred", "paralyzed", "suppressed", "工會勞工在全國大罷工中所取得的決定性重大勝利，「激發引發帶動了」其他各工業部門展開類似的勞工動員抗爭運動。", "instigate 意為「發起、促成、煽動引發」，強化首創勝利對後續抗爭的推動作用。", "因果帶動發起動詞選 instigated。", "mobilization", "/ˌmoʊ.bəl.əˈzeɪ.ʃən/", "動員動員行動", "instigate", "/ˈɪn.stə.ɡeɪt/", "發起煽動促成"),
        ("The sudden influx of cheap overseas textiles inevitably ___ domestic artisanal weavers, driving centuries-old handicraft guilds into bankruptcy.", "devastated", "bolstered", "subsidized", "rehabilitated", "廉價海外紡織品的突發大量湧入，無可避免地「重創摧毀了」本土傳統手工織布業者，迫使擁有數百年傳承的手工藝行會走向破產破亡。", "driving guilds into bankruptcy 提示前句結果之慘烈，選 devastated（毀滅、摧毀）。", "因果惡性後果動詞選 devastated。", "artisanal", "/ɑːrˈtɪz.ən.əl/", "手工藝的手工製作的", "devastate", "/ˈdev.ə.steɪt/", "毀滅重創徹底破壞")
    ]),
    # 3. Semantic Clues: Qualification, Concession & Paradoxical Truth
    ("Semantic Clues: Qualification & Paradox", "語意邏輯", "C2-GRE03", [
        ("The treatise was undeniably erudite; ___, its author’s refusal to engage with contemporary feminist scholarship rendered its conclusions strikingly dated.", "yet", "moreover", "consequently", "similarly", "該專著無可否認地博大精深且博雅宏富；「然而/儘管如此」，其作者斷然拒絕與當代女性主義學術進行對話，使其結論顯得驚人地陳舊過時。", "前句誇獎極其博學 (undeniably erudite)，後句指出致命盲點 (dated conclusions)，極致讓步轉折選 yet。", "學術讓步資格限定選 yet。", "erudite", "/ˈer.jə.daɪt/", "博學的博雅深奧的", "dated", "/ˈdeɪ.t̬ɪd/", "過時的陳舊的"),
        ("The physicist’s formulation, while mathematically ___, was predicated on an unverified physical assumption regarding extra spatial dimensions.", "impeccable", "shoddy", "pedestrian", "meretricious", "該物理學家的公式推導在數學邏輯層面上雖然「無懈可擊/完美無瑕」，但其基礎卻建立在一個有關額外空間維度的未經驗證物理假定之上。", "while 引導讓步：後方轉折指出前提未經驗證，空格必為對數學純熟度的最高讚譽褒義詞 impeccable（無懈可擊的）。", "讓步褒貶對立：while mathematically impeccable, predicated on unverified assumption...", "impeccable", "/ɪmˈpek.ə.bəl/", "無懈可擊的完美的", "meretricious", "/ˌmer.əˈtrɪʃ.əs/", "華而不實的金玉其外的"),
        ("It is a profound historical paradox that the monarch’s most ___ policies—intended to suppress dissent—actually accelerated the republican revolution.", "repressive", "conciliatory", "lax", "magnanimous", "歷史上一個深刻的諷刺悖論在於，這位君王所推行之最為「高壓專制鎮壓的」政治政策——原本意在壓制異議——實際上卻反而加速了共和革命的徹底爆發。", "intended to suppress dissent 呼應 repressive（鎮壓殘暴的），與加速革命構成歷史悖論。", "悖論特徵詞選 repressive（高壓鎮壓的）。", "paradox", "/ˈper.ə.dɑːks/", "悖論反諷矛盾", "repressive", "/rɪˈpres.ɪv/", "鎮壓的壓制的苛刻的"),
        ("While the novelist’s prose is undeniably dense and at times opaque, persistent readers will find its intellectual rewards far from ___.", "inconsequential", "monumental", "profound", "formidable", "儘管該小說家的散文文筆無可否認地晦澀繁密且時而令人費解，但堅持讀下去的讀者將會發現其精神思想回報「絕非無足輕重/絕非微不足道」。", "far from inconsequential (雙重否定表強烈肯定)，呼應前面的 intellectual rewards。", "雙重否定修辭：far from inconsequential（意義重大深遠）。", "opaque", "/oʊˈpeɪk/", "不透明的晦澀難懂的", "inconsequential", "/ɪnˌkɑːn.səˈkwen.ʃəl/", "無關緊要的微不足道的"),
        ("The politician’s speech was marked by an artful ___, allowing divergent factions to project their own conflicting agendas onto his ambiguous words.", "equivocation", "candor", "forthrightness", "pedantry", "這位政客的演說以巧妙的「模稜兩可含糊其辭」為特徵，使得不同對立派系得以將各自衝突的政治訴求投射到其模稜兩可的措辭之中。", "allowing divergent factions... ambiguous words 提示特質必為說話含糊不表態的 equivocation（模稜兩可）。", "語意特徵匹配：ambiguous words 呼應 equivocation。", "equivocation", "/ɪˌkwɪv.əˈkeɪ.ʃən/", "含糊其辭模稜兩可躲閃推諉", "candor", "/ˈkæn.dɚ/", "坦率真誠坦白"),
        ("Although the museum retrospective was promoted as comprehensive, scholars noted that the artist's controversial political murals were ___ excluded.", "conspicuously", "inadvertently", "negligibly", "imperceptibly", "儘管該美術館回顧展被宣傳為全面性的完整展覽，但學者敏銳注意到，該藝術家最具爭議性的政治壁畫作品卻被「顯眼醒目地/令人矚目地」刻意排除在外。", "promoted as comprehensive vs excluded 構成諷刺對立，且是顯而易見的刻意排除，選 conspicuously（引人注目地）。", "諷刺限定副詞選 conspicuously excluded。", "conspicuously", "/kənˈspɪk.ju.əs.li/", "顯眼地引人注目地", "retrospective", "/ˌret.rəˈspek.tɪv/", "回顧展"),
        ("The revolutionary manifesto combined fiery radical rhetoric with surprisingly ___ fiscal and administrative proposals.", "orthodox", "anarchic", "subversive", "iconoclastic", "這份革命宣言將慷慨激昂的激進激進修辭口號，與令人驚訝的「極其保守正統的」財政與行政管理提案巧妙混雜在一起。", "combined fiery radical rhetoric with surprisingly... 構成激進與保守之強烈悖論反差，選 orthodox（正統保守的）。", "悖論反差選詞：radical 搭配 orthodox。", "manifesto", "/ˌmæn.əˈfes.toʊ/", "宣言聲明", "orthodox", "/ˈɔːr.θə.dɑːks/", "正統的傳統的公認的"),
        ("The archaeological artifact was an ___: a bronze timepiece recovered from a stratum firmly dated to three centuries before clockwork was invented.", "anachronism", "epiphany", "apotheosis", "exemplar", "這件出土考古文物簡直是一項「時代錯置物/年代矛盾奇物」：這是一隻在被牢固斷代為發條鐘錶發明前三百年之古老地層中所挖掘出的青銅計時器械。", "recovered from strata 3 centuries before invented 完美符合 anachronism（時代錯置、年代不合時宜之物）的定義。", "年代錯置核心詞：anachronism。", "anachronism", "/əˈnæk.rə.nɪ.zəm/", "時代錯置不合時代之事物", "stratum", "/ˈstreɪ.t̬əm/", "地層岩層階層"),
        ("Though the theory possesses undeniable intuitive appeal, rigorous empirical testing has revealed it to be largely ___.", "specious", "irrefutable", "axiomatic", "incontestable", "儘管該理論在直覺認知上具備不可否認的吸引力，但嚴謹的實證科學檢驗卻揭示出它在很大程度上「似是而非/華而不實虛假的」。", "intuitive appeal vs empirical testing has revealed... 揭露真相為假象，選 specious（似是而非的、外表合理實則虛假的）。", "表象與實質反差：specious（似是而非的）。", "specious", "/ˈspiː.ʃəs/", "似是而非的徒有其表的華而不實的", "axiomatic", "/ˌæk.si.əˈmæt̬.ɪk/", "不言自明的公理的"),
        ("The memoirist paints a portrait of her grandfather that is far from hagiographic; on the contrary, she chronicles his foibles with ___ candor.", "unsparing", "deferential", "sanctimonious", "sycophantic", "這位回憶錄作者為其祖父所刻畫的形象絕非聖徒傳記式的歌功頌德；恰恰相反，她以「毫不留情不加掩飾的」坦率真誠，詳加記錄了他生前的種種怪癖與人性弱點。", "far from hagiographic (聖徒傳般的諂媚) -> chronicles his foibles with unsparing candor (毫不留情的坦誠)。", "反義強化搭配：unsparing candor（毫不避諱的直率）。", "hagiographic", "/ˌhæɡ.i.əˈɡræf.ɪk/", "聖徒傳的過度崇拜美化的", "unsparing", "/ʌnˈsper.ɪŋ/", "毫不留情的嚴酷的無情的"),
    ]),
    # 4. Intricate Polarity: Positive vs. Pejorative Scholarly Attributions
    ("Intricate Polarity: Scholarly Attributions", "語意邏輯", "C2-GRE04", [
        ("The defense attorney’s closing argument degenerated into a venomous ___ against the integrity of the prosecution witnesses.", "diatribe", "panegyric", "encomium", "accolade", "辯護律師的結案辯詞墮落演變成了一場針對檢方證人個人品格操守的惡毒「漫罵誹謗/嚴厲抨擊」。", "venomous（惡毒的）修飾負面名詞 diatribe（抨擊、痛罵長篇大論）；其他三項皆為歌頌讚美褒義詞。", "極端負向極性詞選 diatribe（痛罵誹謗）。", "diatribe", "/ˈdaɪ.ə.traɪb/", "謾罵痛斥抨擊長篇大論", "panegyric", "/ˌpæn.əˈdʒɪr.ɪk/", "頌詞頌文推崇之詞"),
        ("Far from offering an objective historiography, the court scribe produced a shameless ___ that elevated the despotic emperor to a demigod.", "panegyric", "jeremiad", "invective", "indictment", "朝廷史官非但沒有提供客觀公正的史學編撰，反而炮製出了一篇將殘暴專制皇帝神化為半神的不知羞恥的「阿諛奉承頌文/讚歌」。", "elevated the despotic emperor to a demigod 提示極端崇拜讚美，選 panegyric（頌歌、讚辭）。", "極端讚揚極性詞選 panegyric。", "despotic", "/desˈpɑː.t̬ɪk/", "暴虐的專制的專橫的", "panegyric", "/ˌpæn.əˈdʒɪr.ɪk/", "頌文讚辭讚美"),
        ("Critics roundly condemned the documentary for its ___ portrayal of historical events, arguing that it deliberately omitted counter-evidence to advance an ideological agenda.", "tendentious", "dispassionate", "equitable", "unbiased", "各界影評人對該紀錄片針對歷史事件所採取的「帶偏向性/有蓄意傾向的」片面描繪發出了齊聲嚴厲譴責，指責其蓄意隱匿反面證據以推動特定意識形態訴求。", "deliberately omitted counter-evidence 說明其帶有極端偏見與傾向性，選 tendentious（有偏向的、有特定宣傳目的的）。", "學術負向極性詞選 tendentious。", "tendentious", "/tenˈden.ʃəs/", "有偏見的有傾向性的蓄意偏袒的", "dispassionate", "/dɪsˈpæʃ.ən.ət/", "客觀冷靜的"),
        ("The newly appointed director delivered an ___ address praising the frontline healthcare workers for their selfless heroism during the pandemic.", "encomium", "diatribe", "animadversion", "stricture", "新任總監發表了一篇熱情洋溢的「崇高頌文/盛讚之詞」，盛讚第一線醫療人員在疫情肆虐期間所展現出的無私英雄主義氣概。", "praising... for selfless heroism 提示填高度讚美的名詞 encomium（讚頌、頌詞）。", "正向高度讚美詞選 encomium。", "encomium", "/enˈkoʊ.mi.əm/", "頌詞讚辭盛讚", "animadversion", "/ˌæn.ɪ.mædˈvɝː.ʒən/", "批評譴責非難"),
        ("The investigative report offered a blistering ___ of the regulatory agency's systemic cronyism and failure to enforce environmental laws.", "indictment", "eulogy", "homage", "sanction", "這份調查深度報告，針對監管機構內部的系統性裙帶官僚風氣以及其執法不力之失職，提出了一份措辭極其嚴厲的「控訴譴責/定罪控書」。", "blistering（尖銳猛烈的）搭配負向譴責名詞 indictment（控訴、譴責）。", "嚴厲譴責名詞選 indictment。", "indictment", "/ɪnˈdaɪt.mənt/", "控訴起訴指控嚴厲批評", "cronyism", "/ˈkroʊ.ni.ɪ.zəm/", "任人唯親裙帶關係"),
        ("The senator dismissed the opposition's claims as mere partisan ___, devoid of substantive factual corroboration.", "invective", "plaudits", "tribute", "approbation", "參議員對反對派的指控斥之以鼻，斥責其純屬政黨惡鬥的「惡毒漫罵攻擊」，完全缺乏任何實質的事實依據佐證。", "mere partisan... devoid of fact 提示強烈負面辱罵之詞，選 invective（漫罵、惡言痛斥）。", "政治負向漫罵詞選 invective。", "invective", "/ɪnˈvek.tɪv/", "漫罵痛罵惡言侮辱", "approbation", "/ˌæp.rəˈbeɪ.ʃən/", "讚許認可批准"),
        ("The retiring professor was deeply moved by the outpouring of ___ delivered by her former doctoral students at the commemorative gala.", "accolades", "calumnies", "reproaches", "denouncements", "在榮退紀念晚宴上，這位退休老教授被其昔日指導之博士生們所齊聲獻上的真摯「崇高讚譽與褒獎」深深感動。", "commemorative gala honoring a professor 應為正向讚頌，選 accolades（讚賞、榮譽讚譽）。", "正向榮譽褒揚詞選 accolades。", "accolade", "/ˈæk.ə.leɪd/", "讚賞榮譽嘉獎", "calumny", "/ˈkæl.əm.ni/", "中傷誹謗誣衊"),
        ("The author’s latest novel is a ___ lament for the lost innocence of rural agricultural life in the shadow of relentless industrialization.", "poignant", "facetious", "flippant", "callous", "這位作家最新出版的小說，是一曲在無情工業化巨浪陰影下，為鄉村農業社會已逝去之純真質樸所譜寫的「令人心酸悽楚的/深刻感人的」悲愴哀歌。", "lament for lost innocence 提示深沉哀傷感人，選 poignant（深刻心酸的、觸動人心的）。", "文學情感極性選 poignant（淒美感人的）。", "poignant", "/ˈpɔɪ.njənt/", "令人心酸的深刻感人的痛苦的", "facetious", "/fəˈsiː.ʃəs/", "開玩笑的滑稽不合時宜的"),
        ("The anonymous pamphlet was a cowardly piece of ___, filled with fabricated scandals aimed at destroying the minister's public standing.", "calumny", "eulogy", "panegyric", "commendation", "那份匿名黑函小冊子是一篇卑鄙懦弱的「惡意中傷誣衊/誹謗文章」，充斥著旨在摧毀該部長公眾政治聲望的蓄意捏造醜聞。", "cowardly, filled with fabricated scandals 提示填惡毒誣陷名詞 calumny（誹謗、中傷）。", "誹謗中傷專用詞選 calumny。", "calumny", "/ˈkæl.əm.ni/", "誣衊誹謗中傷", "commendation", "/ˌkɑː.menˈdeɪ.ʃən/", "表揚讚揚稱讚"),
        ("The young violinist received universal ___ from the notoriously demanding music critics of Vienna following her virtuoso performance.", "approbation", "animadversion", "censure", "disapprobation", "在這場堪稱宗師級的大師演奏會之後，這位年輕的小提琴家贏得了維也納出了名挑剔苛刻之音樂評論家們一致的「由衷讚許/認可褒揚」。", "universal... following virtuoso performance 提示極致讚揚，選 approbation（認可、讚許）。", "正向讚賞詞選 approbation。", "approbation", "/ˌæp.rəˈbeɪ.ʃən/", "讚許稱許認可批准", "animadversion", "/ˌæn.ɪ.mædˈvɝː.ʒən/", "嚴厲批評非難批評")
    ]),
    # 5. Text Completion: High-Register Scholarly Diction & Nuance
    ("Text Completion: Scholarly Diction & Nuance", "語意邏輯", "C2-GRE05", [
        ("The new evidence presented by the defense attorney was so ___ that even the most skeptical jurors were persuaded of the defendant’s innocence.", "compelling", "conjectural", "dubious", "specious", "辯護律師所提出的新物證是如此「具有壓倒性說服力的」，以致於連法庭上最生性多疑的陪審員也被徹底說服確信被告無罪。", "單選考點分析：由 jurors were persuaded（陪審員被說服）強烈提示該證據具備無可置疑的證明力，唯一正解為 compelling（令人信服的）。其餘選項中，conjectural（推測性的）、dubious（可疑的）、specious（似是而非的）皆表不確定或負向，與文意相悖。", "單選精準考點：鎖定具有壓倒性說服力之形容詞 compelling。", "compelling", "/kəmˈpel.ɪŋ/", "令人信服的引人注目的強制的", "conjectural", "/kənˈdʒek.tʃɚ.əl/", "推測的揣摩的推論的"),
        ("Rather than embracing a single school of thought, the philosopher adopted an ___ approach, synthesizing tenets from divergent traditions.", "eclectic", "parochial", "insular", "dogmatic", "該哲學家並未獨尊某一特定學派，而是採取了一種「兼收並蓄多元折衷的」綜合方法，將不同流派的核心信條融會貫通。", "單選考點分析：由 Rather than embracing a single school（而非獨尊單一派別）與 synthesizing tenets from divergent traditions（整合不同傳統）可知，此方法具備博採眾長之特點，唯一正解為 eclectic（折衷的、兼容並蓄的）。parochial（狹隘的）、insular（偏狹的）、dogmatic（教條頑固的）皆表示排他與封閉，與句意完全相反。", "單選精準考點：博採各家之長選用 eclectic。", "eclectic", "/ekˈlek.tɪk/", "折衷的相容並蓄的多元的", "parochial", "/pəˈroʊ.ki.əl/", "狹隘的教區的偏狹的"),
        ("The minister's private diary revealed a temperament marked by sudden ___ swings, alternating unpredictably between ecstatic exuberance and profound melancholia.", "mercurial", "stolid", "equable", "phlegmatic", "該部長的私人日記揭示了一種以劇烈突發的「善變多變/捉摸不定」為特徵的性格，毫無規律地在狂喜激昂與深沉憂鬱之間反覆橫跳。", "單選考點分析：線索在於 alternating unpredictably between ecstatic exuberance and profound melancholia（在極度狂喜與深淵抑鬱間無規律擺盪），唯有 mercurial（善變的、反覆無常的）精準表達此情緒極端跳躍。其餘干擾選項 stolid（麻木遲鈍的）、equable（溫和穩定的）、phlegmatic（冷靜淡漠的）皆強調心境不起波瀾，與文意完全相悖。", "單選精準考點：情緒劇烈擺盪善變選 mercurial。", "mercurial", "/mɝːˈkjʊr.i.əl/", "善變的反覆無常的水銀的", "stolid", "/ˈstɑː.lɪd/", "麻木的遲鈍的淡漠的"),
        ("Far from presenting a revolutionary breakthrough, the research paper merely offered a ___ rehash of established sociological models.", "pedestrian", "esoteric", "groundbreaking", "provocative", "該研究論文非但沒有提出任何革命性的突破創新，反而只不過是對已確立之社會學模型進行了一場「平庸乏味毫無新意的」炒冷飯。", "單選考點分析：句首 Far from presenting a revolutionary breakthrough（遠非革命性突破）與 mere rehash（純屬炒冷飯）決定空格必須填入表達平庸、老套、缺乏創見的負向形容詞，唯一正選為 pedestrian（平庸乏味的、毫無想像力的）。groundbreaking（開創性的）與 provocative（啟發性的）與文意相反；esoteric（深奧難懂的）偏離平庸主旨。", "單選精準考點：缺乏新意炒冷飯選 pedestrian。", "pedestrian", "/pəˈdes.tri.ən/", "平庸乏味的毫無想像力的徒步的", "esoteric", "/ˌes.əˈter.ɪk/", "深奧的難解的圈內人懂的"),
        ("The newly unearthed legal codex is of ___ importance to epigraphers, as it represents the earliest extant documentation of Babylonian contract law.", "paramount", "inconsequential", "peripheral", "trifling", "這部新出土的古代法律抄本對銘文專家而言具有「至高無上/最為重大」的非凡意義，因為它是巴比倫契約法現存最早的第一本文獻紀錄。", "單選考點分析：由 earliest extant documentation（現存最早紀錄）可知該典籍在學術史上具有極致的核心地位，唯一正確為 paramount（至高無上的、首要的）。其餘干擾項 inconsequential（無關緊要的）、peripheral（邊緣次要的）、trifling（微不足道的）皆與文意強烈衝突。", "單選精準考點：至關重大首要地位選 paramount。", "paramount", "/ˈper.ə.maʊnt/", "至高無上的最重要的首要的", "inconsequential", "/ɪnˌkɑːn.səˈkwen.ʃəl/", "無足輕重的微不足道的"),
        ("The literary biographer’s portrayal of the poet was criticized for being excessively ___, glossing over his notorious interpersonal cruelty in order to preserve his heroic mythos.", "hagiographic", "trenchant", "scathing", "derisive", "這位文學傳記作家對該詩人的刻畫描寫遭到了廣泛嚴厲抨擊，被指責為「過度美化吹捧/聖徒傳式的神化」，刻意粉飾了他生前惡名昭彰的人際殘酷行徑以維護其英雄神話。", "單選考點分析：關鍵線索為 glossing over his cruelty in order to preserve his heroic mythos（粉飾殘酷以維繫英雄神話），說明該傳記並非客觀記述，而是進行盲目崇拜的美化神化，唯一正解為 hagiographic（聖徒傳式的、過分諂媚神化的）。trenchant（犀利深刻的）、scathing（嚴厲抨擊的）、derisive（嘲弄譏諷的）皆為批判性詞彙，與過度美化神化完全相反。", "單選精準考點：粉飾缺點過分美化選 hagiographic。", "hagiographic", "/ˌhæɡ.i.əˈɡræf.ɪk/", "聖徒傳記的美化的神化吹捧的", "trenchant", "/ˈtren.tʃənt/", "尖銳的犀利的深刻有力的"),
        ("The diplomat’s statement was intentionally ___, calculated to reassure domestic constituents while committing the administration to no specific military action.", "ambiguous", "lucid", "unambiguous", "categorical", "該外交官發表的聲明經過精心推敲，故意顯得「模稜兩可/含糊其辭」，旨在安撫國內選民的同時，不讓政府承擔任何具體軍事行動的實質義務。", "單選考點分析：語境表明外交官一方面要安撫民眾，另一方面卻不願意被任何具體軍事承諾綁死（committing to no specific action），故其言辭必然具備刻意製造的彈性與模糊空間，唯一正選為 ambiguous（含糊不清的、模稜兩可的）。干擾選項 lucid（明晰清晰的）、unambiguous（毫不含糊的）、categorical（斷然明確的）皆為反義詞。", "單選精準考點：故意不作承諾之含糊措辭選 ambiguous。", "ambiguous", "/æmˈbɪɡ.ju.əs/", "模稜兩可的含糊不清的曖昧的", "lucid", "/ˈluː.sɪd/", "清晰透明的清澈的頭腦清醒的"),
        ("Despite the arid conditions of the desert plateau, certain succulent plant species manage to ___ in rocky fissures where condensation collects.", "thrive", "languish", "wither", "perish", "儘管沙漠高原氣候條件極端乾旱貧瘠，某些多肉植物依然能夠在聚集凝結水氣的岩石縫隙之中「繁茂茁壯生長」。", "單選考點分析：句首 Despite the arid conditions（儘管條件嚴酷）引導讓步轉折，表示植物不但沒有枯死，反而克服惡劣逆境成功繁衍生長，唯一正解為 thrive（茁壯生長、繁榮興旺）。反向干擾項 languish（凋零衰弱）、wither（枯萎萎縮）、perish（死亡消亡）均與讓步轉折方向相反。", "單選精準考點：逆境中成功茁壯繁榮選 thrive。", "thrive", "/θraɪv/", "繁榮茂盛茁壯生長", "languish", "/ˈlæŋ.ɡwɪʃ/", "憔悴凋零衰弱受折磨"),
        ("The CEO’s decision to liquidate the unprofitable foreign subsidiary was widely praised as a ___ move that safeguarded the firm’s core balance sheet.", "judicious", "impetuous", "reckless", "precipitous", "執行長將長期虧損的外國子公司進行清算裁撤的決斷，被各界普遍讚譽為一記「審慎明智的」高明之舉，成功捍衛了集團的核心資產負債表健全。", "單選考點分析：由 widely praised（廣受稱讚）與 safeguarded the firm's core balance sheet（捍衛了核心資產健全）可知，該決策受到極高之肯定，形容詞必為褒義，唯一正選為 judicious（審慎明智的、有見識的）。干擾項 impetuous（衝動魯莽的）、reckless（肆無忌憚的）、precipitous（倉促輕率的）皆為負面貶義詞，無法搭配 praised。", "單選精準考點：廣受稱讚之明智審慎決策選 judicious。", "judicious", "/dʒuːˈdɪʃ.əs/", "明智的審慎的有見識的", "impetuous", "/ɪmˈpetʃ.u.əs/", "魯莽的衝動的狂烈的"),
        ("The academic dean’s address was notoriously ___, meandering for nearly two hours through irrelevant historical anecdotes without ever arriving at a coherent point.", "rambling", "pointed", "laconic", "succinct", "這位學術院長的大會致詞以「漫無邊際/東拉西扯冗長離題」而惡名昭彰，在無關痛癢的歷史軼事中兜兜轉轉了將近兩個小時，始終未能切入任何連貫的中心論點。", "單選考點分析：線索在於 notoriously（惡名昭彰地）與 meandering through irrelevant anecdotes without arriving at a coherent point（在無關軼事中漫遊離題兩小時且無中心論點），形容詞必為負面離題冗長之意，唯一正選為 rambling（漫無邊際東拉西扯的、冗長的）。干擾選項 pointed（針鋒相對尖銳直接的）、laconic（言簡意賅的）、succinct（簡短扼要的）皆為反義詞。", "單選精準考點：冗長漫無邊際不著重點選 rambling。", "rambling", "/ˈræm.blɪŋ/", "漫無邊際的東拉西扯的雜亂的", "pointed", "/ˈpɔɪn.t̬ɪd/", "尖銳的針對性強的尖利的")
    ]),
    # 6. Lexical Stylometry: Laconic Brevity vs. Prolix Loquacity
    ("Lexical Stylometry: Brevity vs. Prolixity", "語意邏輯", "C2-GRE06", [
        ("Renowned among colleagues for his extreme ___, the senior jurist rarely spoke during appellate oral arguments, yet his concise written opinions carried supreme authority.", "taciturnity", "loquacity", "effusiveness", "verbosity", "在司法同仁心目中以極度「沉默寡言/言簡意賅」而聞名，這位資深大法官在上訴法庭口頭辯論期間極少開口，然而其精練至極的書面裁判書卻享有至高無上的權威。", "rarely spoke 提示沉默寡言，名詞 taciturnity（沉默寡言、寡言少語）完美符合句意。", "沉默寡言核心名詞選 taciturnity。", "taciturnity", "/ˌtæs.əˈtɝː.nə.t̬i/", "沉默寡言寡言沉靜", "loquacity", "/loʊˈkwæs.ə.t̬i/", "多話喋喋不休健談"),
        ("The senator’s speech was marred by an insufferable ___; what could have been communicated in a concise five-minute briefing stretched into a tedious two-hour filibuster.", "prolixity", "brevity", "succinctness", "economy", "參議員的演說因令人難以忍受的「冗長囉唆廢話連篇」而遭到毀損；原本只需五分鐘簡報即可言簡意賅傳達的內容，竟被硬生生拉長成一場長達兩小時的枯燥議事拖延演說。", "what could have been concise... stretched into two hours 提示冗長囉唆，選 prolixity（冗長囉唆）。", "冗長囉唆名詞選 prolixity。", "prolixity", "/proʊˈlɪk.sə.t̬i/", "冗長囉唆囉嗦散漫", "brevity", "/ˈbrev.ə.t̬i/", "簡潔短暫簡明"),
        ("Spartan diplomatic envoys were legendary throughout classical Greece for their ___ responses, famously answering long-winded Macedonian threats with a single monosyllable: 'If.'", "laconic", "garrulous", "voluble", "circumlocutory", "斯巴達外交特使在全希臘歷史上以其「言簡意賅/字字如金的」極簡回答而名垂青史，最著名者莫過於以一個單音節字『若』，斷然回擊馬其頓王國長篇大論的威脅恐嚇。", "answering long-winded threats with a single word 提示極簡冷淡風格，選經典詞 laconic（簡短俐落的、斯巴達式的）。", "言簡意賅經典代表詞：laconic。", "laconic", "/ləˈkɑː.nɪk/", "言簡意賅的寡言的簡約的", "garrulous", "/ˈɡær.əl.əs/", "喋喋不休的多嘴的饒舌的"),
        ("The elderly innkeeper was a notoriously ___ conversationalist, eager to recount long, rambling anecdotes to any traveler unfortunate enough to ask for directions.", "garrulous", "reticent", "curt", "laconic", "這位老酒館掌櫃是個出了名「喋喋不休嘮叨多話的」健談者，極其熱衷於向任何不幸開口問路的外地旅客，巨細靡遺講述冗長散漫的陳年往事軼聞。", "eager to recount long rambling anecdotes 提示多話愛嘮叨，選 garrulous（喋喋不休的、多嘴的）。", "多嘴多話形容詞選 garrulous。", "garrulous", "/ˈɡær.əl.əs/", "喋喋不休的嘮叨的多嘴的", "reticent", "/ˈret̬.ə.sənt/", "沉默寡言的含蓄的保留的"),
        ("The editor praised the debut essayist for her prose style, noting that every paragraph displayed admirable verbal ___, devoid of decorative filler or empty padding.", "economy", "prodigality", "superfluity", "tautology", "主編盛讚這位初試啼聲之專欄作家的散文風格，指出其每一個段落均展現出令人欽佩的文字「精準精練/凝練克制」，完全沒有任何浮誇的裝飾性贅詞或空洞填塞物。", "devoid of decorative filler 提示字句精練克制，選 verbal economy（語言的凝練經濟）。", "語言精練名詞選 economy。", "economy", "/iˈkɑː.nə.mi/", "節約凝練經濟節省", "prodigality", "/ˌprɑː.dəˈɡæl.ə.t̬i/", "揮霍浪費鋪張"),
        ("In stark contrast to his predecessor’s famously ___ press briefings, the new press secretary provided brisk, two-sentence statements that offered zero elaboration.", "voluble", "laconic", "terse", "pithy", "與其前任官員出名的「口若懸河滔滔不絕」的記者會風格形成鮮明對比，新任發言人僅提供簡短冷峻的兩句話聲明，絲毫不提供任何額外闡述補充。", "In stark contrast to brisk, two-sentence statements，前任必定是話多滔滔不絕，選 voluble（健談的、滔滔不絕的）。", "對照選詞：與 terse 對立選 voluble（滔滔不絕的）。", "voluble", "/ˈvɑːl.jə.bəl/", "健談的口若懸河的滔滔不絕的", "terse", "/tɝːs/", "簡短生硬的簡約的"),
        ("Legal briefs filed before the Supreme Court must adhere to strict word counts, compelling attorneys to present arguments with maximum ___.", "succinctness", "circumlocution", "grandiloquence", "diffuseness", "呈遞給聯邦最高法院的訴訟辯護狀必須嚴格遵守字數上限規定，這迫使上訴律師必須以最高程度的「簡潔扼要/精確凝練」來陳述法律論點。", "strict word counts 迫使律師追求簡短凝練，選 succinctness（簡潔扼要）。", "簡潔扼要名詞選 succinctness。", "succinctness", "/səkˈsɪŋkt.nəs/", "簡明簡潔扼要", "circumlocution", "/ˌsɝː.kəm.loʊˈkjuː.ʃən/", "迂迴曲折說法婉轉累贅的措辭"),
        ("Rather than providing a straightforward answer to the auditor's question, the corporate CFO resorted to evasive ___.", "circumlocution", "candor", "forthrightness", "brevity", "面對審計會計師的直接提問，該企業財務長並未給出直截了當的正面回答，反而訴諸閃爍其詞的「迂迴掩飾措辭/拐彎抹角」。", "Rather than straightforward answer... resorted to evasive... 提示拐彎抹角繞圈子，選 circumlocution（迂迴說法、拐彎抹角）。", "迂迴掩飾名詞選 circumlocution。", "circumlocution", "/ˌsɝː.kəm.loʊˈkjuː.ʃən/", "迂迴累贅的話拐彎抹角", "candor", "/ˈkæn.dɚ/", "直率坦誠"),
        ("The poet’s aphorisms are celebrated for their ___ wisdom, packing profound philosophical truths into single memorable lines.", "pithy", "prolix", "tedious", "convoluted", "這位詩人的格言警句以其「精練警策/微言大義的」智慧而廣受讚譽，能夠將深刻的哲學真理濃縮在單一令人難忘的詩行之中。", "packing profound truths into single lines 提示微言大義精辟，選 pithy（簡練有力的、精闢深刻的）。", "言簡意深形容詞選 pithy。", "pithy", "/ˈpɪθ.i/", "簡練有力的有深意的精闢的", "convoluted", "/ˈkɑːn.və.luː.t̬ɪd/", "盤繞曲折的費解複雜的"),
        ("The defense witness’s testimony was notoriously ___, wandering endlessly through extraneous irrelevancies until the presiding judge intervened.", "diffuse", "compact", "concise", "pithy", "辯方證人的法庭證詞以「散漫冗長離題」而惡名昭彰，在無關緊要的枝微末節中無休止地漫談飄移，直到審判法長當庭強制介入制止。", "wandering endlessly through irrelevancies 提示散漫冗長不著邊際，選 diffuse（散漫冗長的、擴散的）。", "散漫離題形容詞選 diffuse。", "diffuse", "/dɪˈfjuːs/", "散漫冗長的擴散的傳播", "extraneous", "/ɪkˈstreɪ.ni.əs/", "無關的外部的無直接關係的")
    ]),
    # 7. Epistemology & Philosophy: Skepticism, Dogmatism & Empiricism
    ("Epistemology: Skepticism & Empiricism", "語意邏輯", "C2-GRE07", [
        ("The radical epistemologist advanced a form of extreme ___, contending that the self can verify nothing beyond the subjective contents of its own consciousness.", "solipsism", "empiricism", "pragmatism", "positivism", "這位激進的認識論哲學家提出了一種極端形式的「唯我論/唯我主義」，堅稱自我除了自身主觀意識的內容之外，在根本上無法驗證客觀外部世界的任何實體存在。", "the self can verify nothing beyond its own consciousness 完美契合哲學術語 solipsism（唯我論）之嚴密定義。", "哲學唯我論專有名詞：solipsism。", "solipsism", "/ˈsɑː.lɪp.sɪ.zəm/", "唯我論唯我主義", "empiricism", "/emˈpɪr.ə.sɪ.zəm/", "經驗主義經驗論"),
        ("Rejecting pure *a priori* rationalist deductions, Francis Bacon insisted that genuine scientific progress must be grounded in rigorous ___ observation.", "empirical", "metaphysical", "speculative", "intuitive", "法蘭西斯·培根斷然摒棄純粹的先驗唯理主義演繹法，嚴正堅持指出真正的科學進步必須牢固奠基於嚴謹的「實證經驗主義/實地觀測」之上。", "Rejecting a priori rationalist deductions 提示對立面，後方必填強調感官數據實證的 empirical（實證經驗主義的）。", "經驗實證哲學形容詞選 empirical。", "a priori", "/ˌeɪ praɪˈɔːr.aɪ/", "先驗的演繹的", "empirical", "/emˈpɪr.ɪ.kəl/", "實證的經驗主義的"),
        ("The dogmatic theologian was entirely ___ to arguments based on scientific empirical discoveries, treating scriptural literalism as infallible truth.", "impervious", "amenable", "receptive", "susceptible", "這位信奉教條的神學家對建立在科學實證發現基礎上的理性論據「完全免疫/油鹽不進不為所動」，將經文的字面解釋奉為絕無謬誤的至高真理。", "treating literalism as infallible 說明其完全不接受反對意見，選 impervious（不受影響的、無動於衷的）。", "冥頑不化形容詞選 impervious to arguments。", "theologian", "/ˌθiː.əˈloʊ.dʒən/", "神學家", "impervious", "/ɪmˈpɝː.vi.əs/", "不受影響的無動於衷的不能滲透的"),
        ("David Hume famously challenged induction by arguing that our belief in causal necessity is not rationally justified, but merely a psychological ___ habit.", "habitual", "transcendental", "categorical", "axiomatic", "大衛·休謨向歸納法發起了著名的哲學挑戰，論證指出我們對因果必然性的信念在理性上並無充分正當依據，只不過是一種心理上的「習慣性」習慣反應罷了。", "belief is not rationally justified but merely a psychological habit 呼應習慣歸納心理，選 habitual。", "休謨因果懷疑論選詞：habitual / psychological habit。", "induction", "/ɪnˈdʌk.ʃən/", "歸納法歸納推理", "habitual", "/həˈbɪtʃ.u.əl/", "習慣性的習以為常的"),
        ("Philosophical pragmatists like William James evaluate the 'truth' of a belief not by its correspondence to an abstract reality, but by its practical ___ consequences.", "experiential", "speculative", "transcendental", "metaphysical", "威廉·詹姆斯等哲學實用主義者在評價某一信念是否為『真理』時，並非衡量其是否契合某種抽象實體，而是審視其在現實行動中所帶來的實質「經驗性實踐/具體可感之」結果。", "pragmatists evaluate truth by practical consequences 提示與抽象相對之具體經驗產出，選 experiential（經驗上的、實踐體驗的）。", "實用主義經驗核心詞選 experiential。", "pragmatism", "/ˈpræɡ.mə.tɪ.zəm/", "實用主義", "experiential", "/ɪkˌspɪr.iˈen.ʃəl/", "經驗的體驗的實踐的"),
        ("In his *Meditations*, Descartes employed radical methodological ___ to systematically doubt every belief until finding an indubitable bedrock: the *cogito*.", "skepticism", "dogmatism", "complacency", "orthodoxy", "笛卡兒在其《第一哲學沉思錄》中運用了激進的方法論「懷疑主義/懷疑論」，系統性地懷疑質疑每一項既有信念，直到尋獲那無可動搖的認知基石：『我思故我在』。", "systematically doubt every belief until finding indubitable bedrock 完美定義 Descartes's methodological skepticism（笛卡兒方法懷疑論）。", "懷疑論核心專用詞選 skepticism。", "indubitable", "/ɪnˈduː.bɪ.t̬ə.bəl/", "無可懷疑的不容置疑的確鑿的", "skepticism", "/ˈskep.tə.sɪ.zəm/", "懷疑論懷疑主義"),
        ("The logical positivists of the Vienna Circle insisted on the strict verificationist principle, dismissing metaphysical statements as literally ___.", "meaningless", "profound", "infallible", "axiomatic", "維也納學派的邏輯實證主義者嚴格堅持經驗可證實性原則，將一切無法經由感官經驗驗證的形上學命題直接斥為字面意義上的「毫無意義之囈語」。", "logical positivists dismissed metaphysics as meaningless（邏輯實證主義將形上學判定為無意義命題）。", "實證主義哲學常考判定詞選 meaningless。", "positivism", "/ˈpɑː.zə.t̬ɪ.vɪ.zəm/", "實證主義", "meaningless", "/ˈmiː.nɪŋ.ləs/", "無意義的無價值的"),
        ("The German philosopher Kant sought to reconcile empiricism and rationalism by proposing that synthetic *a priori* concepts necessarily ___ our sensory experience.", "structure", "annihilate", "falsify", "dissolve", "德國哲學家康德力圖調和經驗主義與理性主義的百年紛爭，提出先驗綜合判斷概念必然會在先驗框架中「結構化構造形成」我們的感官知覺經驗。", "Kant argued that pure categories structure sensory experience（先驗知性範疇結構化感官經驗）。", "康德認識論核心動詞選 structure（構成、賦予結構）。", "synthetic", "/sɪnˈθet̬.ɪk/", "綜合的先驗綜合的合成的", "structure", "/ˈstrʌk.tʃɚ/", "構成組織賦予結構"),
        ("The epistemologist cautioned that equating subjective certitude with objective epistemic validity is an elementary cognitive ___.", "fallacy", "triumph", "virtue", "mandate", "這位認識論學者嚴正警告，將主觀的堅信不疑與客觀的認識論有效性混為一談，乃是一種極其初級的認知「謬誤/邏輯謬論」。", "equating subjective certitude with objective validity is a fallacy（混淆主觀確信與客觀有效性為典型謬誤）。", "哲學邏輯謬誤名詞選 fallacy。", "certitude", "/ˈsɝː.t̬ə.tuːd/", "確信確定無疑", "fallacy", "/ˈfæl.ə.si/", "謬誤謬論錯誤觀念"),
        ("The skeptic maintained a state of *epoché*—a deliberate ___ of judgment regarding the ultimate metaphysical nature of the universe.", "suspension", "affirmation", "declaration", "imposition", "古希臘懷疑論者始終維持著一種被稱為 *epoché* 的心靈懸擱狀態——即對宇宙最終形上學本質刻意保持判斷的「暫停中止/懸置不予置評」。", "epoché is the deliberate suspension of judgment（懸擱判斷為懷疑論經典定義）。", "懷疑論專用術語選 suspension of judgment。", "epoché", "/ˌep.əˈkiː/", "懸置判斷中止評判", "suspension", "/səˈspen.ʃən/", "暫停中止懸擱懸掛")
    ]),
    # 8. Aesthetic & Art Criticism: Avant-garde, Derivative, & Sublime
    ("Aesthetic & Art Criticism: Avant-garde & Sublime", "語意邏輯", "C2-GRE08", [
        ("The art critic dismissed the painter’s latest gallery exhibition as hopelessly ___, arguing that its motifs were mere uninspired copies of 1960s pop art icons.", "derivative", "iconoclastic", "seminal", "revolutionary", "該藝術評論家對這位畫家最新畫廊個展不屑一顧，斥責其毫無救藥地「缺乏原創性/抄襲衍生的」，指責其視覺圖騰只不過是對一九六○年代普普藝術符號毫無靈感的拙劣抄襲複製品。", "mere uninspired copies 提示毫無原創性，選 derivative（衍生的、缺乏獨創性的、抄襲的）。", "藝術批評貶義詞選 derivative。", "derivative", "/dɪˈrɪv.ə.t̬ɪv/", "衍生的缺乏獨創性的派生的", "iconoclastic", "/aɪˌkɑː.nəˈklæs.tɪk/", "破除偶像的反傳統的打破舊習的"),
        ("In his aesthetic treatise on the sublime, Edmund Burke argued that true artistic sublimity is generated not by pleasant symmetry, but by a sense of awe mingled with ___.", "terror", "boredom", "mirth", "complacency", "艾德蒙·伯克在其論『崇高』的美學經典名著中論證指出，真正的藝術崇高感絕非源自令人愉悅的對稱和諧，而是源自一種夾雜著「恐怖戰慄/敬畏恐懼」的震撼威懾感。", "Burke: sublime is produced by awe mingled with terror/pain（崇高源於敬畏與恐懼的交織）。", "美學崇高論核心名詞選 terror。", "sublimity", "/səˈblɪm.ə.t̬i/", "崇高莊嚴超絕", "terror", "/ˈter.ɚ/", "恐懼驚恐恐怖"),
        ("The avant-garde composer’s radical polytonal symphony was designed specifically to ___ the audience's comfortable bourgeois expectations.", "shatter", "validate", "reinforce", "codify", "這位前衛先鋒派作曲家所創作之激進的多調性交響樂，其設計初衷係專為「粉碎打破」中產階級觀眾安逸舒適之傳統審美期待。", "avant-garde radical polytonal designed to shatter bourgeois expectations（前衛藝術粉碎資產階級期待）。", "前衛藝術批判動詞選 shatter（打碎、粉碎）。", "avant-garde", "/ˌæv.ɑːŋˈɡɑːrd/", "前衛的前衛派的先鋒的", "bourgeois", "/ˈbʊrʒ.wɑː/", "中產階級的中庸平庸的資產階級的"),
        ("Far from being a servile imitator of classical antiquity, Michelangelo was a fiercely ___ sculptor who defied traditional anatomical proportions to intensify emotional drama.", "iconoclastic", "derivative", "slavish", "subservient", "米開朗基羅絕非古典古代藝術的奴性臨摹者，而是一位極其「敢於打破傳統偶像舊習的」先鋒雕塑家，他大膽顛覆傳統解剖學比例以強化雕像的情感戲劇張力。", "Far from servile imitator... defied traditional proportions 提示敢於反傳統破舊習，選 iconoclastic。", "反傳統開創性形容詞選 iconoclastic。", "servile", "/ˈsɝː.vaɪl/", "奴性的卑屈的盲從的", "iconoclastic", "/aɪˌkɑː.nəˈklæs.tɪk/", "打破舊習的反叛傳統的破除偶像的"),
        ("The installation artist created a pastiche of recycled commercial logos, producing a work that was simultaneously a celebration of pop consumerism and a scathing ___ thereof.", "critique", "panegyric", "endorsement", "homage", "這位裝置藝術家將回收的商業品牌標誌拼貼組裝成一件諷刺拼貼作品，使其既是對大眾消費主義的狂歡慶祝，同時又是對其一場體無完膚的尖銳「批判控訴」。", "simultaneously a celebration... and a scathing critique（既是慶祝又是尖銳批判的雙重性）。", "批判名詞選 critique。", "pastiche", "/pæsˈtiːʃ/", "拼貼畫大雜燴仿作", "scathing", "/ˈskeɪ.ðɪŋ/", "嚴厲尖刻的體無完膚的"),
        ("The poet’s verses capture the ___ beauty of autumn leaves, celebrating a fragile visual splendor that dissolves with the first winter frost.", "ephemeral", "immutable", "perennial", "interminable", "這位詩人的詩行捕捉到了秋日落葉那種「轉瞬即逝短暫曇花一現的」淒美，讚美了一種伴隨著初冬第一道嚴霜降臨便煙消雲散的脆弱視覺璀璨。", "fragile visual splendor that dissolves 提示短暫短命，選 ephemeral（短暫的、轉瞬即逝的）。", "短暫之美經典形容詞選 ephemeral。", "ephemeral", "/əˈfem.ɚ.əl/", "短暫的轉瞬即逝的曇花一現的", "splendor", "/ˈsplen.dɚ/", "壯麗光輝璀璨"),
        ("The architecture of the brutalist courthouse, with its massive unadorned concrete pylons, exudes an austere, forbidding ___.", "monumentality", "frivolity", "delicacy", "whimsicality", "這座粗獷主義風格法院建築憑藉其巍峨厚重、毫無多餘修飾的清水混凝土巨柱，散發出一種嚴酷冷峻、令人望而生畏的「宏偉莊嚴感/紀念碑式的威嚴肅穆」。", "massive unadorned concrete exudes forbidding monumentality（粗獷建築散發肅穆厚重的宏偉感）。", "宏偉莊重名詞選 monumentality。", "brutalist", "/ˈbruː.t̬əl.ɪst/", "粗獷主義建築風格的", "monumentality", "/ˌmɑːn.jə.menˈtæl.ə.t̬i/", "不朽宏偉紀念碑性質"),
        ("The critic lauded the director’s cinematography as an exercise in visual ___, where every camera angle and shadow was stripped of superfluous distraction.", "asceticism", "hedonism", "luxuriance", "prodigality", "影評人盛讚該導演的電影攝影堪稱一場極致視覺「苦行禁欲主義/極簡極克制」的藝術實踐，每一個運鏡角度與陰影對比都被徹底剝離了任何多餘的感官干擾。", "stripped of superfluous distraction 提示禁欲克制極簡，選 visual asceticism（視覺苦修極簡主義）。", "禁欲極簡名詞選 asceticism。", "asceticism", "/əˈset̬.ə.sɪ.zəm/", "苦行禁欲主義清心寡欲", "cinematography", "/ˌsɪn.ə.məˈtɑː.ɡrə.fi/", "電影攝影術"),
        ("The novelist’s florid prose was condemned by modernists for its excessive ___, stuffed with archaic metaphors and baroque embellishments.", "ornamentation", "austerity", "brevity", "economy", "現代主義文人對這位小說家過度華麗繁複的散文文風予以無情譴責，痛斥其過度充斥著「雕琢裝飾/堆砌修飾」，塞滿了晦澀陳舊的隱喻與巴洛克式的多餘粉飾。", "stuffed with archaic metaphors and baroque embellishments 提示過度修飾，選 ornamentation。", "裝飾堆砌名詞選 ornamentation。", "florid", "/ˈflɔːr.ɪd/", "過分華麗的氣色紅潤的炫麗的", "ornamentation", "/ˌɔːr.nə.menˈteɪ.ʃən/", "裝飾修飾裝點"),
        ("Romantic painters sought to elicit a sense of the sublime by juxtaposing diminutive human figures against ___ natural landscapes.", "colossal", "microscopic", "pedestrian", "domestic", "浪漫主義風景畫家試圖藉由將渺小微不足道的人類身影，與雄奇無垠、巍峨險峻的「無比巨大的/磅礡宏偉的」自然景觀並列並置，藉以激發出強烈的崇高震撼感。", "juxtaposing diminutive figures against colossal landscapes（將微小人類置於浩瀚巨大的自然之中）。", "宏大自然修飾形容詞選 colossal。", "diminutive", "/dɪˈmɪn.jə.t̬ɪv/", "微小的矮小的極小的", "colossal", "/kəˈlɑː.səl/", "龐大的巨大的極大的")
    ]),
    # 9. Historiography: Revisionist, Orthodox & Teleological Interpretations
    ("Historiography: Revisionist & Teleological", "語意邏輯", "C2-GRE09", [
        ("Whig historiography has been widely discredited for its naive ___ bias, which interprets past centuries as a continuous, triumphant march toward liberal democracy.", "teleological", "anachronistic", "synchronic", "relativistic", "輝格史學因其天真幼稚的「目的論式」偏見而遭到當代學術界的廣泛摒棄，這種偏向將過去漫長世紀化約詮釋為一場必然走向自由民主勝利凱旋的線性推進歷程。", "interprets past as continuous march toward a goal 完美定義了 teleological（目的論的、由終點結果倒推的）。", "史學目的論核心專有名詞選 teleological。", "historiography", "/hɪˌstɔːr.iˈɑː.ɡrə.fi/", "史學史歷史編撰學", "teleological", "/ˌtiː.li.əˈlɑː.dʒɪ.kəl/", "目的論的目的論式的"),
        ("The revisionist historian challenged the conventional ___ of the founding fathers, portraying them not as infallible demigods, but as flawed, self-interested landed elites.", "hagiography", "iconoclasm", "scandal", "diatribe", "這位修正派歷史學家向針對建國先父們的傳統「聖徒傳式吹捧美化」發起挑戰，將他們還原為有缺陷且自私自利的莊園地主精英，而非絕無過失的完美半神。", "portraying them not as demigods challenges hagiography（挑戰把歷史人物神化為聖人的吹捧史學）。", "史學聖徒神化批判詞選 hagiography。", "revisionist", "/rɪˈvɪʒ.ən.ɪst/", "修正派的修正主義的", "hagiography", "/ˌhæɡ.iˈɑː.ɡrə.fi/", "聖徒傳過分諂媚的傳記神化"),
        ("Rather than treating historical events as inevitable outcomes of broad socioeconomic currents, the narrative historian stressed the decisive role of contingency and individual human ___.", "agency", "passivity", "inertia", "fatality", "這位敘事史學家並未將重大歷史事件視為宏觀社會經濟潮流下的必然宿命產物，而是著重強調了歷史的偶然性以及個別歷史人物的決定性主觀「能動性/自主行動權」。", "contingency and individual human agency（偶然性與個人的主體能動性）是史學理論經典對稱概念。", "歷史主體能動性專用術語選 agency。", "contingency", "/kənˈtɪn.dʒən.si/", "偶然性偶然事件意外狀況", "agency", "/ˈeɪ.dʒən.si/", "能動性代理自主力量機構"),
        ("Marxist historians interpret political revolutions not as ideological disputes, but as the inevitable friction arising from systemic conflicts between economic classes over the means of ___.", "production", "consumption", "distribution", "communication", "馬克思主義歷史學家將政治革命詮釋為各經濟階級圍繞著掌握控制「生產」資料與工具所爆發之系統性衝突所引發的必然階級摩擦，而非單純的意識形態分歧。", "means of production（生產資料、生產工具）為歷史唯物主義政治經濟學之核心標準固定詞組。", "政治經濟學核心專有名詞選 means of production。", "ideological", "/ˌaɪ.di.əˈlɑː.dʒɪ.kəl/", "意識形態的", "production", "/prəˈdʌk.ʃən/", "生產生產成果製作"),
        ("Post-colonial historians have sought to 'provincialize Europe,' arguing that Eurocentric narratives systematically ___ the intellectual and technological achievements of the Global South.", "marginalize", "venerate", "canonize", "aggrandize", "後殖民史學家力圖推行『歐洲地方化』理論，論證歐洲中心主義的歷史敘事長期以來系統性地「邊緣化貶低了」全球南方在思想哲學與科技文明上的卓越成就。", "Eurocentric narratives systematically marginalize achievements of Global South（歐洲中心主義邊緣化南方成就）。", "後殖民批判動詞選 marginalize。", "Eurocentric", "/ˌjʊr.oʊˈsen.trɪk/", "歐洲中心主義的", "marginalize", "/ˈmɑːr.dʒɪ.nəl.aɪz/", "邊緣化排擠貶低"),
        ("The chronicler’s account must be interpreted with extreme caution, as court scribes were routinely pressured to produce ___ chronicles praising their royal patrons.", "sycophantic", "subversive", "iconoclastic", "dispassionate", "對這位宮廷編年史官的記錄文獻必須保持極度審慎批判的態度，因為御用文人常年被迫撰寫巴結阿諛、極盡歌功頌德之能事的「諂媚討好的」編年史以取悅其王室金主。", "pressured to praise royal patrons 提示填諁媚奉承的 sycophantic（阿諛奉承的、諂媚的）。", "諂媚奉承形容詞選 sycophantic。", "chronicler", "/ˈkrɑː.nɪ.klɚ/", "編年史編撰者記錄者", "sycophantic", "/ˌsɪk.əˈfæn.tɪk/", "阿諛奉承的諂媚的溜鬚拍馬的"),
        ("Annales school historians famously shifted historical focus away from the short-term 'event' toward the *longue durée*—the slow, nearly imperceptible evolution of geographical and environmental ___.", "structures", "catastrophes", "revolutions", "crises", "法國年鑑學派史學家著名地將歷史研究的焦點，從短期的偶發『政治事件』轉向了『長時段』——即地理環境與生態氣候「結構體系」極其緩慢、近乎難以察覺的深層演變歷程。", "evolution of geographical and environmental structures（地理環境結構演進為長時段核心）。", "年鑑學派長時段名詞選 structures。", "Annales", "/æˈnɑːl/", "年鑑學派(法國史學流派)", "structure", "/ˈstrʌk.tʃɚ/", "結構體系構造體"),
        ("The biographical study was praised for avoiding the common pitfall of 'presentism'—the erroneous tendency to judge past actors using contemporary moral and political ___.", "standards", "chronologies", "technologies", "languages", "這部人物傳記研究備受學術界推崇，因其成功規避了『當下主義』的常見史學陷阱——即用當代現代人的道德與政治「價值標準/審判準則」去苛責歷史古人的錯誤傾向。", "presentism is judging past actors using contemporary standards（用現代標準評判歷史人物）。", "當下主義評判標準名詞選 standards。", "presentism", "/ˈprez.ən.tɪ.zəm/", "當下主義以現代眼光看歷史", "standard", "/ˈstæn.dɚd/", "標準規範水準"),
        ("Archaeological evidence from pre-dynastic Egypt demonstrates that social stratification and wealth inequality emerged long before the official unification of the ___.", "realm", "tribe", "commune", "nomad", "來自前王朝時期古埃及的考古實質發掘出土物證顯示，社會階層化分化與貧富懸殊不平等現象，早在那場官方將南北埃及實現統治版圖政治「王國/國土疆界」統一之前便早已成形。", "unification of the realm（王國/疆域之政治統一）為古代史標準詞組。", "古代王國疆域選 realm。", "stratification", "/ˌstræt̬.ə.fəˈkeɪ.ʃən/", "階層化分層結構", "realm", "/relm/", "王國領域疆土界"),
        ("The historian’s archival research revealed that the peasant rebellion was not a chaotic mob riot, but a highly organized protest guided by an intricate moral ___.", "economy", "deficit", "bankruptcy", "collapse", "該歷史學家的檔案深度考證踢爆，那場看似無序的農民起義絕非烏合之眾的混亂暴動，而是一場受到精密且深層的傳統『道德「經濟」倫理』所引導的高組織度抗爭行動。", "guided by a moral economy（由道德經濟理念所引導為著名史學家 E.P. Thompson 經典概念）。", "史學經典詞組選 moral economy。", "peasant", "/ˈpez.ənt/", "農民佃農小農", "economy", "/iˈkɑː.nə.mi/", "經濟體系節約倫理機制")
    ]),
    # 10. Political Economy & Sociology: Hegemony, Stratification & Bureaucracy
    ("Political Economy & Sociology: Hegemony", "語意邏輯", "C2-GRE10", [
        ("Antonio Gramsci argued that ruling classes maintain dominance not solely through physical coercion, but through cultural ___—engineering spontaneous consent among the subaltern masses.", "hegemony", "anarchy", "insurgency", "pluralism", "安東尼奧·葛蘭西論證指出，統治統治階級維繫其權力支配地位絕非單純依賴武力強制暴力，而是透過文化「霸權/文化領導權」——在底層被統治大眾心目中精巧塑造出心甘情願的自發贊同。", "Gramsci: cultural hegemony engineering spontaneous consent（葛蘭西文化霸權理論）。", "政治社會學核心概念選 hegemony（霸權）。", "hegemony", "/hɪˈdʒem.ə.ni/", "霸權領導權支配地位", "subaltern", "/ˈsʌb.əl.tɝːn/", "底層的附屬的下層階級"),
        ("Max Weber famously observed that the defining attribute of the modern bureaucratic state is its claimed monopoly on the legitimate use of physical ___.", "force", "persuasion", "wealth", "taxation", "馬克思·韋伯極具影響力地指出，現代官僚科層制國家最本質的核心標誌特徵，在於其宣稱對合法「武力/暴力手段」之行使擁有唯一的壟斷權利。", "Weber's definition of the state: monopoly on the legitimate use of physical force。", "韋伯國家定義核心名詞選 force。", "bureaucratic", "/ˌbjʊr.əˈkræt̬.ɪk/", "官僚的科層制的官僚體系的", "force", "/fɔːrs/", "武力暴力力量"),
        ("In his critique of global capitalism, the sociologist warned that pervasive neoliberal austerity policies serve to further ___ already vulnerable working-class communities.", "disenfranchise", "ennoble", "emancipate", "vindicate", "在其對全球資本主義體系的深刻批判中，該社會學家嚴正警告，普遍推行的新自由主義財政緊縮政策，只會進一步在經濟與政治上「剝奪邊緣化/剝奪權利」本就脆弱不堪的勞工階級社區。", "austerity policies further disenfranchise vulnerable communities（緊縮政策進一步剝奪弱勢權利）。", "批判剝奪權利動詞選 disenfranchise。", "neoliberal", "/ˌniː.oʊˈlɪb.ɚ.əl/", "新自由主義的新自由學派的", "disenfranchise", "/ˌdɪs.ɪnˈfræn.tʃaɪz/", "剝奪公民權剝奪權利使無權"),
        ("Pierre Bourdieu’s sociological framework demonstrates how the intergenerational transmission of cultural ___ perpetuates existing social hierarchies under the guise of meritocracy.", "capital", "deficit", "anarchy", "stagnation", "皮埃爾·布迪厄的社會學理論體系深刻揭示了，文化「資本」在世代之間的隱蔽傳承，如何在精英任人唯賢功績主義的虛偽幌子下，永續鞏固並再生產既有的階級社會分層結構。", "Bourdieu's theory: transmission of cultural capital perpetuates social hierarchies。", "布迪厄社會學核心專用詞選 capital（文化資本）。", "meritocracy", "/ˌmer.əˈtɑː.krə.si/", "精英體制功績主義能者統治", "capital", "/ˈkæp.ə.t̬əl/", "資本資產首府大寫"),
        ("The iron law of oligarchy, formulated by Robert Michels, posits that all complex democratic organizations inevitably succumb to internal rule by an elite ___.", "minority", "plebiscite", "consensus", "majority", "由羅伯特·米歇爾斯所提出的著名的『寡頭鐵律』假定指出，一切複雜龐大的民主組織最終均無可避免地在內部屈服走向由極少數精英「小集團/少數派」所實施的集權寡頭統治。", "iron law of oligarchy: organizations inevitably ruled by an elite minority。", "寡頭統治本質選 minority（少數寡頭）。", "oligarchy", "/ˈɑː.lə.ɡɑːr.ki/", "寡頭政治寡頭統治集團", "minority", "/maɪˈnɔːr.ə.t̬i/", "少數少數派少數群體"),
        ("Sociologists describe systemic institutional discrimination as being embedded within structural procedures rather than driven solely by individual personal ___.", "prejudice", "tolerance", "benevolence", "altruism", "社會學家將系統性體制性歧視定義為深嵌於整體制度程序架構之中的結構性障礙，而非單純由個別個人的主觀心理「偏見歧視」所驅使引發。", "structural procedures rather than individual prejudice（結構程序而非個人偏見）。", "偏見名詞選 prejudice。", "institutional", "/ˌɪn.stəˈtuː.ʃən.əl/", "體制的制度的機構的", "prejudice", "/ˈpredʒ.ə.dɪs/", "偏見歧視成見"),
        ("The shift from manufacturing to a financialized service economy has exacerbated the ___ between hyper-compensated technical elites and precarious gig workers.", "disparity", "solidarity", "harmony", "congruence", "自實體製造業向高度金融化服務型經濟的轉型演變，大幅進一步拉大並加劇了高薪技術精英階層與身陷朝不保夕就業困境之零工勞動者之間的鴻溝「巨大差距/懸殊不平等」。", "exacerbated the disparity between elites and gig workers（加劇貧富分化差距）。", "懸殊差距名詞選 disparity。", "precarious", "/prɪˈker.i.əs/", "不穩定的危險的朝不保夕的", "disparity", "/dɪˈspær.ə.t̬i/", "不平等懸殊巨大差異"),
        ("Michel Foucault analyzed modern prisons and panopticons to demonstrate how disciplinary power operates by cultivating internalized ___ among the subjugated population.", "surveillance", "defiance", "rebellion", "mutiny", "米歇爾·傅柯深入剖析現代監獄制度與圓形全景敞視建築，旨在揭示訓誡規訓權力如何透過在被統治受壓迫人群心靈深處植入內化之「自我監控/監視意識」來發揮統治效力。", "Foucault: panopticon cultivates internalized surveillance（全景敞視內化自我監控）。", "傅柯規訓哲學核心名詞選 surveillance。", "panopticon", "/pænˈɑːp.tɪ.kɑːn/", "圓形全景敞視監獄", "surveillance", "/sɚˈveɪ.ləns/", "監視監控盯梢"),
        ("Thorstein Veblen coined the concept of 'conspicuous consumption' to describe how wealthy social classes purchase extravagant luxury goods primarily to publicly advertise their pecuniary ___.", "prowess", "humility", "bankruptcy", "destitution", "托斯丹·范伯倫創造了『炫耀性消費』這一劃時代經濟社會學概念，深刻揭示富裕有產階級之所以採購奢華奢侈品，首要動機在於向公眾高調宣示炫耀其雄厚的金錢財政「實力/經濟威力」。", "Veblen: conspicuous consumption advertises pecuniary prowess/power。", "金錢實力專用名詞選 prowess（實力、超凡技藝能力）。", "pecuniary", "/pɪˈkjuː.ni.er.i/", "金錢的金錢上的財政的", "prowess", "/ˈpraʊ.es/", "超凡實力高超技藝英勇"),
        ("Urban sociologists observe that the process of gentrification frequently leads to the involuntary ___ of long-standing low-income residents.", "displacement", "aggrandizement", "empowerment", "enfranchisement", "都市社會學家敏銳觀察指出，社區中產階級化/仕紳化改造進程，往往直接導致長期在此生息之弱勢低收入世居居民遭遇被迫無奈之「被驅離迫遷/流離失所」。", "gentrification leads to involuntary displacement（仕紳化導致弱勢居民被迫搬遷）。", "迫遷流離失所專有名詞選 displacement。", "gentrification", "/ˌdʒen.trə.fəˈkeɪ.ʃən/", "仕紳化中產階級化", "displacement", "/dɪsˈpleɪs.mənt/", "迫遷流離失所位移取代")
    ]),
    # 11. Biological & Evolutionary Debates: Adaptation, Teleology & Spandrels
    ("Evolutionary Biology: Adaptation & Spandrels", "語意邏輯", "C2-GRE11", [
        ("Stephen Jay Gould and Richard Lewontin warned against adaptationist 'just-so stories,' introducing the architectural term 'spandrel' to describe phenotypic traits that are non-adaptive side effects of other structural ___.", "constraints", "intentions", "desires", "teleologies", "史蒂芬·古爾德與理查·勒旺廷嚴正警告各界切勿陷入泛適應論的『天方夜譚』泥淖，創新引進建築學術語『拱肩(spandrel)』，專門用以描繪那些純屬其他解剖結構「約束/限制條件」之副產物、而非直接由天擇篩選形成的非適應性表型特徵。", "spandrel describes traits that are side effects of structural constraints（拱肩是結構約束的副產物）。", "演化生物學核心名詞選 constraints（結構約束）。", "phenotypic", "/ˌfiː.noʊˈtɪp.ɪk/", "表型的表現型的", "constraint", "/kənˈstreɪnt/", "限制約束約束條件"),
        ("Evolutionary biologists strictly avoid ___ explanations, emphasizing that natural selection operates mechanically without foresight, purpose, or conscious intention.", "teleological", "empirical", "mechanistic", "materialistic", "現代演化生物學家在學術論述中嚴格摒棄「目的論式的/終極意圖性的」解釋模型，反覆強調自然選擇純粹是一套機械化盲目運作的演化篩選機制，絕無任何前瞻預見、預設目的或自覺意識意圖。", "avoid teleological explanations: selection operates without purpose or intention。", "目的論演化學形容詞選 teleological。", "foresight", "/ˈfɔːr.saɪt/", "先見深謀遠慮遠見", "teleological", "/ˌtiː.li.əˈlɑː.dʒɪ.kəl/", "目的論的目的論式的"),
        ("The mammalian inner ear bones—the malleus and incus—are evolutionary examples of ___, having been co-opted from ancestral reptilian jaw hinge bones to serve an entirely novel auditory function.", "exaptation", "stagnation", "atavism", "involution", "哺乳動物的中耳聽小骨——錘骨與砧骨——乃是演化生物學中『外適應/功能轉移(exaptation)』的經典代表範例，它們原本係自古爬蟲類下頜鉸鏈骨骼演化改造而來，進而承擔了截然不同的全新聽覺傳導功能。", "co-opted for a novel function 完美定義了 exaptation（外適應、功能轉用）。", "演化功能轉移專有名詞選 exaptation。", "exaptation", "/ˌek.sæpˈteɪ.ʃən/", "外適應預適應功能挪用轉向適應", "auditory", "/ˈɑː.də.tɔːr.i/", "聽覺的耳朵的"),
        ("Rather than maintaining a constant evolutionary tempo, fossil records frequently exhibit 'punctuated equilibrium,' characterized by extended epochs of evolutionary stasis interrupted by rapid bursts of ___.", "speciation", "ossification", "extinction", "regression", "化石地層記錄並未展現出勻速穩定的演化節奏，反而高頻率地呈現出『斷續平衡』特徵，其典型表徵為漫長的地質時期演化停滯停頓，其間穿插著短暫急遽暴發的「物種形成/新種分化」脈衝期。", "punctuated equilibrium: stasis interrupted by bursts of speciation（物種形成爆發）。", "物種形成專用術語選 speciation。", "speciation", "/ˌspiː.ʃiˈeɪ.ʃən/", "物種形成新種分化", "stasis", "/ˈsteɪ.sɪs/", "停滯停頓停滯狀態"),
        ("Biologists studying sexual selection caution that runaway selection can drive the evolution of extravagant male ornamentation to the point of being a severe survival ___.", "handicap", "panacea", "benefit", "catalyst", "深入研究性選擇理論的生物學家提出警告，失控費雪性選擇可能驅使雄性過度演化出極度奢華誇張的求偶裝飾特徵，甚至演變成為一項威脅生存安全的嚴重「負擔障礙/不利累贅」。", "drive ornamentation to the point of being a survival handicap（生存劣勢障礙）。", "演化劣勢障礙名詞選 handicap（不利條件、負擔累贅）。", "extravagant", "/ɪkˈstræv.ə.ɡənt/", "奢華的過分的誇張的", "handicap", "/ˈhæn.di.kæp/", "障礙不利條件殘疾"),
        ("The genetic drift observed in small island populations demonstrates that allele frequencies can change over generations due entirely to random ___ rather than adaptive natural selection.", "stochasticity", "deliberation", "foresight", "intention", "在孤立小型島嶼族群中所觀測到的基因漂變現象雄辯地證明，等位基因頻率在世代交替中的更迭變化，完全可能是由盲目隨機的「隨機性/隨機機率漲落」所驅動，而非必然出於適應性自然選擇。", "genetic drift is driven by random stochasticity（隨機性、機率波動）。", "統計隨機性高階詞彙選 stochasticity。", "drift", "/drɪft/", "漂變漂移漂流", "stochasticity", "/stoʊˌkæsˈtɪs.ə.t̬i/", "隨機性機率性隨機過程"),
        ("The remarkable morphological resemblance between the placental wolf and the extinct marsupial thylacine represents a textbook case of ___ evolution.", "convergent", "divergent", "regressive", "vestigial", "胎盤類真獸狼與已滅絕的有袋類袋狼之間在解剖骨骼外觀上驚人的一致相似性，乃是演化生物學中「趨同演化」的教科書級經典範例。", "resemblance between unrelated placental and marsupial species is convergent evolution。", "趨同演化標準術語選 convergent evolution。", "marsupial", "/mɑːrˈsuː.pi.əl/", "有袋動物有袋類的", "convergent", "/kənˈvɝː.dʒənt/", "趨同的匯聚的一致的"),
        ("Anatomists point to the human coccyx and flightless cormorant wing bones as ___ structures that have lost their ancestral primary utility.", "vestigial", "nascent", "functional", "essential", "解剖學家明確指出，人類的尾椎骨以及加拉巴哥不能飛行的鸕鶿的翅膀骨骼，均屬已完全喪失其原始主要生存功用的「退化殘留/痕跡性」解剖構造。", "structures that have lost their primary utility are vestigial structures（痕跡器官、退化器官）。", "退化器官專用形容詞選 vestigial。", "cormorant", "/ˈkɔːr.mɚ.ənt/", "鸕鶿水老鴉", "vestigial", "/vesˈtɪdʒ.i.əl/", "退化的殘留的痕跡的"),
        ("Evolutionary altruism among eusocial insects is explained by W.D. Hamilton's theory of inclusive fitness, which posits that an individual will sacrifice itself if the genetic benefit to ___ exceeds the cost.", "kin", "strangers", "predators", "competitors", "真社會性昆蟲族群內部所普遍存在的演化利他主義行為，由漢彌爾頓的廣義親適度理論給出了嚴密解答，該理論假定，若利他行為對自身「親族血親」所帶來的遺傳獲益大於犧牲代價，個體將甘願犧牲自我。", "Hamilton's rule: altruism evolves if benefit to kin exceeds cost（親緣選擇）。", "親族血統專有名詞選 kin。", "eusocial", "/juːˈsoʊ.ʃəl/", "真社會性的真社會群居的", "kin", "/kɪn/", "親屬親戚家屬血親"),
        ("The fossil specimen was hailed as a critical ___ fossil, bridging the anatomical evolutionary transition between lobe-finned fish and early tetrapods.", "transitional", "anomalous", "regressive", "vestigial", "這具保存完好的遠古化石標本被學術界譽為極其關鍵的「過渡性/過渡形態」化石，在肉鰭魚類與早期登陸四足動物的解剖演化轉折過渡環節中架起了一座關鍵橋樑。", "bridging the evolutionary transition 提示填 transitional fossil（過渡化石）。", "演化過渡化石專用詞選 transitional。", "tetrapod", "/ˈtet.rə.pɑːd/", "四足動物四足類", "transitional", "/trænˈzɪʃ.ən.əl/", "過渡的過渡期的過渡性質的")
    ]),
    # 12. Psychological Paradoxes: Altruism, Self-Interest & Cognitive Bias
    ("Psychological Paradoxes & Cognitive Bias", "語意邏輯", "C2-GRE12", [
        ("The 'confirmation bias' refers to the pervasive psychological tendency to uncritically embrace data that verifies preexisting convictions while stubbornly ___ contradictory evidence.", "discounting", "corroborating", "amplifying", "fabricating", "所謂『確認偏誤』，係指人類心理上普遍存在的一種認知傾向：盲目毫無批判性地全盤接納能夠證實自身既有信念的數據，同時卻頑固地「貶低忽視/無視排除」任何相牴觸的反面實證。", "embrace confirming data while stubbornly discounting contradictory evidence（擁抱正面忽視反面）。", "對照選詞：embrace 對應 discounting（忽視、打折扣、低估）。", "conviction", "/kənˈvɪk.ʃən/", "信念定罪確信", "discount", "/ˈdɪs.kaʊnt/", "低估打折扣忽視不予理會"),
        ("Behavioral economists demonstrated the power of the 'endowment effect,' whereby experimental subjects demanded substantially higher payments to sell an item than they were willing to ___ to acquire it in the first place.", "disburse", "hoard", "retain", "confiscate", "行為經濟學家生動證實了『稟賦效應』的巨大心理威力：受試者賣掉一件自己已擁有之物品時所開出的索賠金額，遠遠高於他們最初為了購買獲取該物品時所願意「支付掏出」的購買價金。", "demanded higher payment to sell than willing to pay/disburse to acquire（賣價遠高於買入願付款額）。", "支付支出動詞選 disburse（支付、撥付）。", "endowment", "/ɪnˈdaʊ.mənt/", "賦予捐贈稟賦", "disburse", "/dɪsˈbɝːs/", "支付撥款付出"),
        ("Cognitive dissonance theory posits that when individuals encounter irreconcilable discrepancies between their core ethical beliefs and their actual conduct, they experience profound psychological ___.", "discomfort", "complacency", "euphoria", "indifference", "認知失調理論假定指出，當個體在自身核心道德信念與其真實實際行為舉止之間遭遇無法調和之重大矛盾出入時，內心會產生極其深層的心理「不適與焦躁痛苦痛苦感」。", "discrepancies between belief and conduct cause cognitive discomfort/tension。", "認知失調痛苦名詞選 discomfort。", "dissonance", "/ˈdɪs.ə.nəns/", "失調不和諧不一致", "discomfort", "/dɪˈskʌm.fɚt/", "不安不適焦躁困擾"),
        ("The psychological phenomenon known as the 'Dunning-Kruger effect' describes how individuals with minimal competence in a given intellectual domain exhibit gross ___ regarding their own mastery.", "presumption", "diffidence", "circumspection", "humility", "被稱為『達克效應』的認知心理學現象深入剖析了，在某一特定知識領域中實際能力極其匱乏底層的個體，往往對自身的精通造詣抱持著極度荒謬誇大的「自負狂妄/盲目自大」。", "individuals with minimal competence exhibit gross presumption/overconfidence。", "盲目自負名詞選 presumption（狂妄、自負）。", "competence", "/ˈkɑːm.pə.t̬əns/", "能力勝任才能", "presumption", "/prɪˈzʌmp.ʃən/", "自負狂妄冒昧假定推定"),
        ("Psychologists investigating the 'bystander effect' established that as the number of witnesses to an emergency escalates, the probability that any single individual will intervene ___ precipitously.", "diminishes", "escalates", "stabilizes", "rebounds", "深入探討『旁觀者效應』的社會心理學家確立指出，隨著突發緊急事故現場圍觀目擊者人數的急遽攀升，任何單一獨立個體挺身而出進行施救介入的機率反而會隨之「急遽暴跌萎縮」。", "as number of witnesses escalates, probability of intervention diminishes precipitously（人數越多施救機率越低）。", "旁觀者效應反比動詞選 diminishes。", "bystander", "/ˈbaɪˌstæn.dɚ/", "旁觀者局外人", "precipitously", "/prɪˈsɪp.ə.t̬əs.li/", "急遽地斷崖式地陡峭地"),
        ("Rather than acting as purely altruistic benefactors, historical philanthropists frequently donated to civic institutions to acquire social prestige and secure political ___.", "influence", "penury", "anonymity", "oblivion", "與其說是純粹無私奉獻的慈善家，歷史上的富豪行善捐助者往往是透過向公共公民機構大額捐款，以獲取顯赫的社會聲望並牢牢鞏固自身在朝野中的政治「實質影響力與話語權」。", "donated to acquire prestige and secure political influence（獲取聲望並鞏固政治影響力）。", "政治權能名詞選 influence。", "philanthropist", "/fɪˈlæn.θrə.pɪst/", "慈善家樂善好施者", "influence", "/ˈɪn.flu.əns/", "影響力勢力作用"),
        ("The 'fundamental attribution error' leads people to attribute others' moral transgressions to internal character flaws while excusing their own identical missteps as the result of external situational ___.", "pressures", "virtues", "intentions", "merits", "『基本歸因謬誤』促使人們普遍將他人的道德越軌失足全盤歸咎於其內在品格缺陷，而將自己犯下的完全相同之錯誤，狡辯開脫為外部客觀情境「環境壓力與脅迫」所致。", "excusing own missteps as external situational pressures（將自身過失歸咎於外部環境壓力）。", "環境壓力名詞選 pressures。", "attribution", "/ˌæt.rɪˈbjuː.ʃən/", "歸因歸屬屬性", "transgression", "/trænzˈɡreʃ.ən/", "違犯越軌罪過過錯"),
        ("Social psychologists demonstrated that an individual's conscious moral evaluations are frequently overridden by subconscious, fast-acting ___ emotional responses.", "visceral", "cerebral", "deliberative", "pedantic", "社會心理學家透過實證實驗證實，人類個體有意識的道德理性評判，往往會在分秒之間被下意識且快速啟動之深層「發自肺腑本能的/直覺性的」情緒反應所強行壓制覆蓋。", "fast-acting, overriding conscious deliberation 提示本能直覺情緒，選 visceral（發自內心深處的、本能直覺的）。", "本能直覺情緒形容詞選 visceral。", "visceral", "/ˈvɪs.ɚ.əl/", "發自內心的本能的內臟的直覺的", "cerebral", "/səˈriː.brəl/", "大腦的理智的理性的"),
        ("The 'hedonic treadmill' hypothesis posits that following major life milestones, whether windfalls or tragedies, an individual’s subjective baseline of happiness quickly returns to a relatively ___ set point.", "stable", "volatile", "erratic", "fluctuating", "『享樂適應踏車』假說指出，在經歷了人生的重大里程碑事件之後（無論是天降橫財抑或是飛來橫禍），個體主觀上的幸福感基準線很快便會重新回歸到一個相對「穩定不變的」預設基準點。", "hedonic treadmill posits that happiness returns to a stable set point（幸福感回歸穩定恆定點）。", "恆定穩定形容詞選 stable。", "hedonic", "/hiːˈdɑː.nɪk/", "享樂的快樂的快感的", "milestone", "/ˈmaɪl.stoʊn/", "里程碑重大轉折點"),
        ("In studies of risk perception, subjects displayed profound 'loss aversion,' exhibiting an emotional agony from losing a sum of money that was psychologically twice as intense as the ___ derived from winning an equivalent amount.", "joy", "grief", "remorse", "despair", "在針對風險知覺進行的系列行為科學實驗中，受試者表現出了極其深刻的『損失厭惡』傾向：損失一筆特定金額款項所承受之內心痛苦折磨，在心理強度上整整相當於贏得同等金額所獲得之「喜悅狂喜」的兩倍之多。", "loss aversion: agony from losing is twice as intense as joy from winning（痛苦兩倍於喜悅）。", "對照喜悅名詞選 joy。", "agony", "/ˈæɡ.ə.ni/", "極度痛苦折磨", "aversion", "/əˈvɝː.ʒən/", "厭惡反感迴避")
    ]),
    # 13. Literature & Hermeneutics: Ambiguity, Polysemy & Canonical Readings
    ("Literature & Hermeneutics: Canonical Polysemy", "語意邏輯", "C2-GRE13", [
        ("Post-structuralist literary theorists reject the notion of a single authoritative meaning, celebrating the inherent ___ of literary texts whose signifiers can generate infinite interpretative possibilities.", "polysemy", "monolith", "literalism", "univalence", "後結構主義文學理論家堅決摒棄文本存在單一權威終極意涵的傳統觀念，極力讚美文學文本固有的「多義性/一詞多義的豐富性」，主張文本中的符號能孕育催生出無窮無盡的解讀可能性。", "reject single meaning, celebrating infinite possibilities 完美對應 polysemy（多義性、多重意涵）。", "符號學多義性專用術語選 polysemy。", "polysemy", "/pəˈlɪs.ə.mi/", "多義性一詞多義多重意義", "signifier", "/ˈsɪɡ.nə.faɪ.ɚ/", "能指符號形式"),
        ("The hermeneutic circle illustrates that comprehending an individual sentence within a classic novel requires understanding the work as a whole, which in turn can only be grasped by analyzing its constituent ___.", "parts", "critics", "printers", "editions", "詮釋學循環深刻揭示出：欲透徹領會一部古典小說中的某個個別單一語句，必須以理解作品總體全貌為先決條件；而這座全貌整體，又只能透過逐一拆解分析其各個具體構成「局部組件/部分」方能得以真正掌握。", "hermeneutic circle: whole understood through parts, parts understood through whole。", "詮釋學整體與部分對應名詞選 parts。", "hermeneutic", "/ˌhɝː.mənˈjuː.t̬ɪk/", "詮釋學的解釋學的", "constituent", "/kənˈstɪtʃ.u.ənt/", "組成的構成的成分"),
        ("New Critics insisted on the absolute autonomy of the literary artifact, arguing that appealing to an author’s private biographical intentions is a critical ___.", "fallacy", "imperative", "obligation", "triumph", "新批評派學者強烈堅持文學藝術品的絕對獨立自足性，論證指出將批評訴諸作者私人傳記生平創作意圖的做法，乃是犯下了嚴重的評論界「謬誤/意圖謬誤」。", "appealing to author's intentions is the intentional fallacy（意圖謬誤）。", "文學批評經典名詞選 fallacy（謬誤）。", "autonomy", "/ɑːˈtɑː.nə.mi/", "自主性自治獨立性", "fallacy", "/ˈfæl.ə.si/", "謬誤謬論錯誤假定"),
        ("The modernist novel's fragmented chronology and stream-of-consciousness syntax deliberately evoke the psychological ___ of the shell-shocked postwar generation.", "disillusionment", "euphoria", "complacency", "tranquility", "這部現代主義小說破碎的非線性時間序與意識流句法，有意識地生動喚起了飽受彈震症摧殘的戰後迷惘世代心靈深處那種「幻滅/理想破滅的心灰意冷」。", "shell-shocked postwar generation 呼應 disillusionment（幻滅、破滅）。", "戰後迷惘世代核心詞選 disillusionment。", "chronology", "/krəˈnɑː.lə.dʒi/", "年表年代順序年代學", "disillusionment", "/ˌdɪs.ɪˈluː.ʒən.mənt/", "幻滅覺醒破滅的痛苦"),
        ("Biblical scholars utilizing historical-critical exegesis seek to uncover the original meaning of ancient Hebrew and Greek manuscripts within their historical ___.", "milieu", "vacuum", "future", "mythology", "運用歷史-批判考據法進行文獻釋經學研究的聖經學者，力求在古代希伯來文與希臘文手抄本所深植之原始歷史「社會時代背景/文化氛圍」之中，還原其最原汁原味的歷史原義。", "understanding manuscripts within their historical milieu（時代背景、社會氛圍）。", "歷史文化氛圍專用高階法語借詞選 milieu。", "exegesis", "/ˌek.səˈdʒiː.sɪs/", "釋經註釋批判性闡述", "milieu", "/miːlˈjɜː/", "周圍環境社會背景社會氛圍"),
        ("The deconstructive critic demonstrated how the philosophical text undermines its own central thesis through internal semantic ___.", "contradictions", "unifications", "harmonies", "truisms", "解構主義批評家抽絲剝繭地論證展示了，該哲學經典文獻如何在其內部語言符號的自我解構中，透過其自身內在語意上無法調和的「矛盾衝突/抵觸悖論」親手拆毀了自己的核心論點。", "deconstruction shows how a text undermines itself through internal contradictions。", "解構矛盾名詞選 contradictions。", "deconstructive", "/ˌdiː.kənˈstrʌk.tɪv/", "解構的解構主義的", "contradiction", "/ˌkɑːn.trəˈdɪk.ʃən/", "矛盾反駁抵觸不一致"),
        ("The inclusion of ambiguous ethical dilemmas in Shakespearean tragedy elevates the plays above simplistic moralizing, transforming them into profound meditations on human ___.", "frailty", "perfection", "infallibility", "omnipotence", "莎士比亞悲劇中深邃模糊的道德困境設置，使這些戲劇作品徹底超越了膚淺說教的低層次層面，將其昇華為對人類深層人性「脆弱/道德軟弱與缺陷」的深刻哲學省思沉思。", "elevates above moralizing into meditations on human frailty（對人類脆弱性的深沉反思）。", "人性軟弱名詞選 frailty。", "moralizing", "/ˈmɔːr.əl.aɪ.zɪŋ/", "說教道德說教", "frailty", "/ˈfreɪl.t̬i/", "脆弱軟弱虛弱道德弱點"),
        ("The narrator’s reliability is compromised throughout the gothic novella, forcing the reader to view all narrated events with growing ___.", "skepticism", "credulity", "conviction", "indifference", "在這部哥德式中篇小說中，敘事者的客觀可靠性始終存疑動搖，迫使讀者不得不以日益加劇的「懷疑態度/審慎質疑的眼光」來審視書中所描寫的一切敘述事件。", "unreliable narrator forces reader to view events with skepticism（不可靠敘事者引發懷疑）。", "懷疑態度名詞選 skepticism。", "novella", "/nəˈvel.ə/", "中篇小說", "skepticism", "/ˈskep.tə.sɪ.zəm/", "懷疑態度懷疑論"),
        ("Bakhtin's concept of the 'carnivalesque' describes how medieval folk festivities provided a temporary, subversive liberation from the rigid social hierarchies of ecclesiastical ___.", "orthodoxy", "anarchy", "chaos", "secularism", "巴赫汀的『狂歡化』文論概念深刻揭示了，中世紀民間節慶歡愉如何為廣大底層民眾提供了一種短暫但具顛覆性的精神狂歡解脫，得以逃脫教會宗教「正統教條/專制正統」刻板森嚴的階層禁錮。", "liberation from rigid hierarchies of ecclesiastical orthodoxy（逃脫教會正統教條）。", "教會正統名詞選 orthodoxy。", "carnivalesque", "/ˌkɑːr.nə.vəlˈesk/", "狂歡化的嘉年華式的", "orthodoxy", "/ˈɔːr.θə.dɑːk.si/", "正統觀念正統信仰正教"),
        ("Literary critics celebrated the novel’s stylistic ___, noting that its complex blend of magic realism and historical realism opened new frontiers in contemporary fiction.", "hybridity", "purity", "monotony", "uniformity", "文學評論界盛讚這部小說在敘事風格上的「雜揉多元融合性/混合雜交風格」，盛讚其將魔幻寫實主義與歷史實證寫實主義精妙融為一爐，開拓了當代長篇小說的全新疆界。", "blend of magic and historical realism 提示多元融合，選 hybridity（雜合性、混融性）。", "風格混融名詞選 hybridity。", "hybridity", "/haɪˈbrɪd.ə.t̬i/", "雜合性混血性混合風格", "realism", "/ˈriː.ə.lɪ.zəm/", "寫實主義現實主義")
    ])
]
