# scripts/diag_builders/tier6_part1_data.py
# Subtopics 1-13 for Tier 6 (Digital SAT C1, IDs 1251-1380)

subtopics_1_to_13 = [
    # 1. Words in Context: Academic Precision & Contextual Nuance
    ("Words in Context: Academic Precision", "學術思維", "C1-SAT01", [
        ("While the preliminary findings seemed promising, the lead researcher urged caution, noting that the data remained ___ until verified by peer review.", "provisional", "absolute", "negligible", "obsolete", "儘管初步研究結果看似令人鼓舞，但首席研究員仍敦促各界保持審慎，強調在未經同行審查驗證前，該數據仍屬「暫定的」。", "provisional 意為「暫時的、暫定的」，精準呼應後方 until verified by peer review。", "考查學術語境詞義：provisional（暫定的）。", "provisional", "/prəˈvɪʒ.ən.əl/", "暫時的臨時的", "verification", "/ˌver.ə.fəˈkeɪ.ʃən/", "驗證核實"),
        ("The historian argued that the monarch's public declarations were not sincere expressions of piety, but rather ___ strategies designed to placate rebellious nobles.", "calculated", "reckless", "spontaneous", "accidental", "該歷史學家主張，這位君主公開發表的虔誠宣言並非發自內心的真誠表露，而是旨在安撫叛亂貴族的「精心策劃的」政治策略。", "calculated 意為「精心策劃的、預謀的」，與 sincere 形成鮮明對比。", "語意對比選 calculated（精算的、有計畫的）。", "piety", "/ˈpaɪ.ə.t̬i/", "虔誠孝順", "placate", "/plæˈkeɪt/", "平息安撫平叛"),
        ("Far from being a passive observer, the documentary filmmaker adopted a ___ stance, actively intervening in the socio-political debates she chronicled.", "partisan", "neutral", "detached", "lethargic", "該紀錄片導演絕非被動的旁觀者，而是採取了「堅定黨派色彩的/帶偏向性的」立場，積極介入她所記錄的社會政治論辯之中。", "Far from being passive/neutral 提示反義，partisan 表示「有偏向立場的、黨派性的」。", "轉折提示詞 Far from 指向反義 partisan。", "partisan", "/ˈpɑːr.t̬ə.zən/", "偏袒的黨派性的", "chronicle", "/ˈkrɑː.nɪ.kəl/", "載入編年史記錄"),
        ("The architect sought to design a structure that would not ___ upon the natural topography of the alpine sanctuary.", "encroach", "enhance", "elevate", "radiate", "建築師力求設計出一座不會對高山自然保護區之原始天然地貌造成「侵蝕或侵佔侵犯」的建築結構物。", "encroach upon 為固定學術搭配，意為「侵佔、蠶食、侵犯」。", "固定動賓介系詞搭配選 encroach upon。", "encroach", "/ɪnˈkroʊtʃ/", "侵蝕侵佔蠶食", "topography", "/təˈpɑː.ɡrə.fi/", "地形地貌學"),
        ("Despite the author's extensive revisions, several critics contended that the novel's thematic coherence remained ___.", "tenuous", "robust", "indisputable", "monumental", "儘管作者進行了廣泛大幅的修訂，數位文學評論家仍堅稱，該部小說的主題連貫性依然相當「薄弱牽強」。", "Despite 修飾對比，修訂過但連貫性仍很 tenuous（脆弱的、薄弱的）。", "轉折讓步選 tenuous（薄弱的）。", "tenuous", "/ˈten.ju.əs/", "脆弱的薄弱的微弱的", "coherence", "/koʊˈhɪr.əns/", "連貫性條理性"),
        ("The newly excavated manuscript provides an ___ account of daily life in the imperial court during the late Tang dynasty.", "intimate", "aloof", "anonymous", "incomprehensible", "這部最新出土的古手稿，為晚唐時期宮廷內部之真實日常生活提供了極其「詳實親近的/深入細緻的」第一手生動描述。", "intimate account 在學術英語中意為「深入細緻的、親歷生動的記述」。", "學術語境修飾語選 intimate。", "excavate", "/ˈek.skə.veɪt/", "發掘挖掘出土", "intimate", "/ˈɪn.t̬ə.mət/", "詳盡深刻的親密的"),
        ("The economist noted that excessive liquidity in the market can ___ speculative bubbles rather than foster genuine productive investment.", "fuel", "stifle", "extinguish", "counteract", "該經濟學家指出，市場中過度充沛之流動性資金往往會「助長刺激」投機泡沫，而非促進實質生產性投資。", "fuel speculative bubbles 為經濟學高頻動賓搭配，意為「助長推動泡沫」。", "搭配詞選 fuel（助長加劇）。", "liquidity", "/lɪˈkwɪd.ə.t̬i/", "流動性資產變現能力", "fuel", "/fjuː.əl/", "激起助長刺激"),
        ("Rather than maintaining a single dogmatic philosophy, the Renaissance polymath embraced an ___ approach that synthesized classical antiquity with contemporary empirical science.", "eclectic", "orthodox", "insular", "uniform", "這位文藝復興時期的通才博學家並未堅持單一僵化的教條哲學，而是採取了一種將古典哲學與當代實證科學融會貫通的「兼收並蓄的/折衷多樣的」方法論。", "synthesized... 提示融合各派，eclectic 意為「兼收並蓄的、多元折衷的」。", "兼收並蓄各派選 eclectic。", "polymath", "/ˈpɑː.li.mæθ/", "通才博學者", "eclectic", "/ekˈlek.tɪk/", "折衷的兼收並蓄的多元的"),
        ("Because the fossil specimen was heavily damaged during extraction, paleontologists found its classification highly ___.", "problematic", "irrefutable", "definitive", "routine", "由於該古生物化石標本在挖掘採集過程中遭受嚴重損壞，古生物學家們發現對其進行分類歸類極其「棘手且成問題」。", "heavily damaged 導致分類具有高度爭議問題，選 problematic。", "原因結果邏輯選 problematic。", "paleontologist", "/ˌpeɪ.li.ɑːnˈtɑː.lə.dʒɪst/", "古生物學家", "problematic", "/ˌprɑː.bləˈmæt̬.ɪk/", "成問題的疑難棘手的"),
        ("The soprano delivered a performance that was technically flawless yet emotionally ___, failing to move the audience.", "sterile", "passionate", "vibrant", "evocative", "該女高音的演唱在演唱技巧層面上無懈可擊，但在情感表現上卻顯得十分「空洞冷漠/缺乏感染力」，因而未能打動現場聽眾。", "yet 提示轉折：技術完美 (flawless) 但感情空洞，選 sterile。", "技巧與感情反差選 sterile（枯燥冷漠的）。", "soprano", "/səˈpræn.oʊ/", "女高音歌手", "sterile", "/ˈster.əl/", "缺乏想像力的枯燥的不毛的")
    ]),
    # 2. Transitions: Contrast & Concession (however, nonetheless, conversely, on the contrary...)
    ("Transitions: Contrast & Concession", "學術思維", "C1-SAT02", [
        ("Traditional economic models assume that consumers always act rationally to maximize utility; ___, empirical behavioral studies reveal that emotional biases routinely dictate financial decisions.", "however", "therefore", "furthermore", "similarly", "傳統經濟學模型假設消費者始終會理性行動以追求效用極大化；「然而」，實證行為科學研究卻揭示，情緒偏誤往往決定了金融財務決策。", "前後分句為「古典理性假設」與「實證偏誤發現」之強烈對比轉折，選 however。", "語意轉折連詞選 however。", "utility", "/juːˈtɪl.ə.t̬i/", "效用實用性", "rationally", "/ˈræʃ.ən.əl.i/", "理性地理智地"),
        ("Early cosmologists posited that the expansion rate of the universe would decelerate over time. ___, observations of distant Type Ia supernovae in 1998 proved that cosmic acceleration is actually occurring.", "Nonetheless", "Accordingly", "In addition", "For instance", "早期宇宙學家曾假定宇宙的膨脹速率將隨時間逐漸減緩。「儘管如此/然而」，一九九八年對遙遠 Ia 型超新星的觀測證實，宇宙實際上正在加速膨脹。", "前句假定減速，後句證實加速，構成對立轉折，選 Nonetheless。", "轉折讓步過渡詞選 Nonetheless。", "cosmologist", "/kɑːzˈmɑː.lə.dʒɪst/", "宇宙學家", "decelerate", "/ˌdiːˈsel.ə.reɪt/", "減速放緩"),
        ("Some scholars argue that technological automation will cause widespread permanent unemployment; ___, others contend that it will catalyze novel industries and generate net job growth.", "conversely", "consequently", "likewise", "namely", "部分學者主張科技自動化將導致普遍且永久性的失業潮；「相反地」，其他學者則堅稱自動化將催生全新產業並帶動就業淨成長。", "Two opposing views of scholars: conversely（相反地）。", "雙邊學術對立選 conversely。", "automation", "/ˌɑː.t̬əˈmeɪ.ʃən/", "自動化", "conversely", "/ˈkɑːn.vɝːs.li/", "相反地反過來說"),
        ("Critics claimed that the urban renewal project would displace marginalized communities. The municipality, ___, maintained that affordable housing quotas would be strictly enforced.", "however", "therefore", "moreover", "as a result", "批評者指責該都市更新計畫將迫使邊緣化弱勢群體流離失所。市府當局「然而」堅稱，平價公營住宅配額將受到最嚴格的落實保障。", "插入語表示批評觀點與市府官方主張之轉折對立，選 however。", "句中插入轉折副詞選 however。", "displace", "/dɪsˈpleɪs/", "迫使遷離取代", "marginalized", "/ˈmɑːr.dʒɪ.nəl.aɪzd/", "邊緣化的邊緣群體的"),
        ("Proponents argued that the dam would supply abundant hydroelectric energy; the environmental impact, ___, proved devastating to endemic freshwater fauna.", "nonetheless", "furthermore", "similarly", "consequently", "支持者辯稱該水壩將提供豐沛的水力發電能源；「儘管如此」，其對環境生態所造成的衝擊，對當地特有淡水動物群而言卻被證實是毀滅性的。", "正面利益 vs 負面生態代價之讓步轉折，選 nonetheless。", "讓步轉折插入語選 nonetheless。", "hydroelectric", "/ˌhaɪ.droʊ.ɪˈlek.trɪk/", "水力發電的水電的", "endemic", "/enˈdem.ɪk/", "特有的當地的"),
        ("The government did not diminish its scientific research funding in response to the deficit. ___, it augmented the budget by fifteen percent to accelerate technological innovation.", "On the contrary", "Consequently", "In summary", "Likewise", "政府非但沒有因應財政赤字而縮減科研經費。「恰恰相反」，政府甚至將預算追加擴充了百分之十五，以全力加速科技創新。", "前句否定 not diminish，後句反而追加，選 On the contrary（恰恰相反）。", "否定修正轉折選 On the contrary。", "deficit", "/ˈdef.ə.sɪt/", "赤字虧損", "augment", "/ɑːɡˈment/", "增加擴充增大"),
        ("The ancient text was long assumed to be an astrological almanac; ___, recent paleographic analysis indicates that it served primarily as a pharmacological manual.", "in fact", "as a result", "for example", "similarly", "這份古代文獻長期以來被想當然地認定為占星曆書；「但事實上/然而」，近期的古文字學分析顯示，其主要用途實為一本藥理學手冊。", "修正長期誤解之真相轉折，選 in fact（事實上其實）。", "語意修正強調選 in fact。", "paleographic", "/ˌpeɪ.li.əˈɡræf.ɪk/", "古文字學的古書體學的", "pharmacological", "/ˌfɑːr.mə.kəˈlɑː.dʒɪ.kəl/", "藥理學的"),
        ("Skeptics derided the prototype electric vehicle as an impractical novelty. ___, the vehicle broke endurance records and ignited a global market revolution.", "Still", "Hence", "Specifically", "Accordingly", "質疑者譏諷這款原型電動車只不過是個不切實際的新奇玩意。「即便如此/然而」，該車款打破了耐力世界紀錄，並點燃了全球市場革命。", "質疑嘲諷 vs 打破紀錄之強烈轉折，選 Still。", "強烈轉折副詞選 Still（然而、即便如此）。", "deride", "/dɪˈraɪd/", "譏諷嘲笑", "novelty", "/ˈnɑː.vəl.t̬i/", "新奇事物新奇玩意"),
        ("The experimental medication caused minor fatigue in a fraction of participants; ___, its efficacy in halting tumor progression was extraordinarily pronounced.", "nevertheless", "furthermore", "subsequently", "likewise", "該實驗性藥物在少數受試者身上引起了輕微疲憊；「然而/儘管如此」，其在遏止腫瘤惡化方面的療效卻極為顯著卓越。", "輕微副作用 vs 卓越療效之讓步轉折，選 nevertheless。", "讓步轉折副詞選 nevertheless。", "fatigue", "/fəˈtiːɡ/", "疲勞倦怠", "efficacy", "/ˈef.ə.kə.si/", "功效療效有效性"),
        ("The committee did not sanction the proposed high-speed rail corridor. ___, it recommended redirecting infrastructural capital toward municipal bus rapid transit.", "Instead", "Consequently", "Besides", "Thus", "委員會並未核准擬議中的高鐵建設走廊。「反而/取而代之的是」，委員會建議將基礎建設資金轉向投入於市區快捷公車系統。", "not sanction 之後銜接替代方案，選 Instead。", "否定後替代銜接詞選 Instead。", "sanction", "/ˈsæŋk.ʃən/", "認可批准制裁", "corridor", "/ˈkɔːr.ə.dɚ/", "走廊交通幹線走廊")
    ]),
    # 3. Transitions: Causation, Consequence & Inference (consequently, therefore, accordingly, thus...)
    ("Transitions: Causation & Consequence", "學術思維", "C1-SAT03", [
        ("Glacial retreat accelerated dramatically due to rising summer temperatures; ___, downstream river basins experienced catastrophic seasonal flooding.", "consequently", "conversely", "nevertheless", "similarly", "由於夏季氣溫攀升，冰川融化消退急遽加速；「結果/因此」，下游河流流域遭遇了災難性的季節性洪澇災害。", "因果關係：冰川融化加速 (原因) -> 下游洪災 (結果)，選 consequently。", "因果轉折副詞選 consequently。", "glacial", "/ˈɡleɪ.ʃəl/", "冰川的冰河的", "catastrophic", "/ˌkæt̬.əˈstrɑː.fɪk/", "災難性的慘重的"),
        ("The island nation lacks substantial fossil fuel reserves; ___, its government has invested heavily in offshore geothermal and wind infrastructure.", "therefore", "however", "furthermore", "in contrast", "該島國嚴重缺乏實質的化石燃料儲備；「因此」，其政府大力投資發展離岸地熱與風能基礎建設。", "缺乏能源儲備 -> 投資綠能，因果邏輯關係選 therefore。", "因果推導詞選 therefore。", "geothermal", "/ˌdʒiː.oʊˈθɝː.məl/", "地熱的地熱能的", "reserve", "/rɪˈzɝːv/", "儲備儲量"),
        ("The archaeological expedition unearthed bilingual inscriptions in Greek and Aramaic; ___, epigraphers were finally able to decipher the previously obscure dialect.", "accordingly", "on the other hand", "instead", "similarly", "該考古考察隊挖掘出希臘語與阿拉姆語的雙語石刻碑文；「於是/從而」，銘文專家們終於得以破譯先前晦澀不明的古代方言。", "獲得雙語碑文 -> 專家得以破譯，選 accordingly（從而、於是乎）。", "因果承接副詞選 accordingly。", "expedition", "/ˌek.spəˈdɪʃ.ən/", "考察隊探險考察", "decipher", "/dɪˈsaɪ.fɚ/", "破譯解讀"),
        ("The rare earth element possesses an extremely high melting point and resistance to oxidation; ___, it is ideally suited for aerospace propulsion components.", "thus", "nevertheless", "meanwhile", "alternatively", "該稀土元素具備極高的熔點與卓越的抗氧化性；「因而/由此」，它極其適合作為航空航太推進動力組件。", "材料優越物理特性 -> 適合航太用途，選 thus。", "因果結論詞選 thus。", "oxidation", "/ˌɑːk.səˈdeɪ.ʃən/", "氧化氧化作用", "propulsion", "/prəˈpʌl.ʃən/", "推進推進力"),
        ("Agricultural runoff contaminated the regional watershed with nitrogen and phosphorus. ___, massive toxic algal blooms proliferated across the estuary.", "As a result", "By comparison", "Conversely", "In addition", "農業污水逕流將氮與磷排放污染了區域集水區流域。「結果」，大規模有毒藻華在河口灣地區迅速滋生蔓延。", "水質優養化污染 -> 藻華爆發，選 As a result。", "因果關係短語選 As a result。", "runoff", "/ˈrʌn.ɑːf/", "地表逕流水土流失", "estuary", "/ˈes.tu.er.i/", "河口灣港灣"),
        ("The newly formulated ceramic alloy expands negligibly under intense thermal stress. It is, ___, considered an indispensable material for spacecraft heat shields.", "hence", "though", "nevertheless", "instead", "這種新配方陶瓷合金在極端熱應力下膨脹極其微小。它「因此」被公認為太空載具防熱隔熱罩不可或缺的理想材料。", "耐熱膨脹特性 -> 獲選防熱罩材料，因果插入語選 hence。", "因果推導插入語選 hence。", "negligibly", "/ˈneɡ.lə.dʒə.bli/", "微不足道地可忽略地", "thermal", "/ˈθɝː.məl/", "熱的熱力的"),
        ("Deforestation fragmented the contiguous forest habitat. ___, the endemic arboreal marsupials suffered severe population declines.", "Consequently", "On the other hand", "However", "In contrast", "森林砍伐將原本連綿完整的森林棲息地割裂破碎化。「結果」，當地特有的樹棲有袋類動物遭遇了族群數量的嚴重銳減。", "棲地破碎化 (因) -> 族群暴跌 (果)，選 Consequently。", "因果副詞選 Consequently。", "contiguous", "/kənˈtɪɡ.ju.əs/", "相鄰的連續的未間斷的", "marsupial", "/mɑːrˈsuː.pi.əl/", "有袋類動物"),
        ("The clinical trial demonstrated that the monoclonal antibody neutralizes the viral spike protein effectively; ___, regulators expedited emergency approval.", "thereby", "meanwhile", "however", "similarly", "臨床試驗證實該單株抗體能有效中和病毒棘蛋白；監管機構「因此/據此」加速了緊急使用授權審批程序。", "有效試驗數據 -> 監管核准，選 thereby 或因果副詞。", "因果關聯選 thereby。", "monoclonal", "/ˌmɑː.nəˈkloʊ.nəl/", "單株的單株抗體的", "neutralize", "/ˈnuː.trə.laɪz/", "中和使無效"),
        ("The microchip architecture eliminates redundant bus wiring; ___, overall energy dissipation decreases by thirty-five percent.", "in turn", "in contrast", "nonetheless", "conversely", "該微晶片架構消除了多餘的匯流排線路；「進而/從而」，整體能源耗散降低了百分之三十五。", "消除冗餘線路 -> 進而降低耗能，選 in turn（進而、轉而）。", "連鎖因果承接詞選 in turn。", "dissipation", "/ˌdɪs.əˈpeɪ.ʃən/", "耗散浪費消散", "architecture", "/ˈɑːr.kə.tek.tʃɚ/", "架構體系結構"),
        ("The central bank exhausted all conventional interest rate cuts. ___, policymakers resorted to unconventional quantitative easing measures.", "Accordingly", "In contrast", "Conversely", "Nevertheless", "中央銀行已窮盡所有傳統降息工具空間。「因此/相應地」，政策制定者轉而訴諸非傳統的量化寬鬆政策措施。", "傳統手段用盡 -> 採非常規手段，選 Accordingly。", "因果相應副詞選 Accordingly。", "conventional", "/kənˈven.ʃən.əl/", "傳統的常規的", "quantitative easing", "/ˌkwɑːn.t̬ə.teɪ.t̬ɪv ˈiː.zɪŋ/", "量化寬鬆")
    ]),
    # 4. Transitions: Addition, Elaboration & Amplification
    ("Transitions: Addition & Elaboration", "學術思維", "C1-SAT04", [
        ("The novel accurately captures the linguistic idioms of nineteenth-century London; ___, it offers profound sociological insight into Victorian class stratification.", "furthermore", "however", "instead", "conversely", "該小說精準捕捉了十九世紀倫理倫敦的語言習慣語；「此外/而且」，它亦對維多利亞時代的階級分層提供了深刻的社會學洞察。", "捕捉語言特色 (正面論點1) + 提供階級洞察 (正面論點2)，遞進補充選 furthermore。", "遞進補充連詞選 furthermore。", "idiom", "/ˈɪd.i.əm/", "成語習慣用語", "stratification", "/ˌstræt̬.ə.fəˈkeɪ.ʃən/", "階層化分層結構"),
        ("The newly discovered deep-sea trench ecosystem thrives without sunlight. ___, the organisms synthesize carbohydrates via chemosynthesis driven by hydrothermal vents.", "Specifically", "In contrast", "Nonetheless", "Accordingly", "這處新發現的深海海溝生態系統在毫無陽光的環境下繁衍生息。「具體而言」，這些生物係藉由熱液噴口所驅動的化能合成作用來合成碳水化合物。", "對上一句「無需陽光繁衍」進行具體科學機制之闡述說明，選 Specifically。", "具體闡述副詞選 Specifically。", "trench", "/trentʃ/", "海溝溝渠", "chemosynthesis", "/ˌkiː.moʊˈsɪn.θə.sɪs/", "化能合成"),
        ("Urban canopy cover reduces ambient temperatures through shading; ___, it mitigates air pollution by filtering particulate matter.", "moreover", "on the other hand", "consequently", "whereas", "城市樹冠覆蓋能藉由遮蔭來降低環境周遭氣溫；「此外」，它還能藉由過濾懸浮微粒來減緩空氣污染。", "降低氣溫 (優點1) + 減緩空污 (優點2)，追加並列選 moreover。", "遞進並列副詞選 moreover。", "canopy", "/ˈkæn.ə.pi/", "樹冠樹蔭天篷", "particulate", "/pɑːrˈtɪk.jə.lət/", "微粒顆粒狀的"),
        ("The candidate demonstrated extensive proficiency in multivariate calculus. ___, she had published empirical econometric papers in top-tier journals.", "In addition", "Nevertheless", "Alternatively", "In summary", "該候選人展現了在多變量微積分領域的深厚造詣。「此外」，她還曾在頂尖學術期刊上發表過實證計量經濟學論文。", "數學造詣 (優點1) + 發表頂刊 (優點2)，追加補充選 In addition。", "追加並列短語選 In addition。", "multivariate", "/ˌmʌl.tiˈver.i.ət/", "多變量的多元的", "econometric", "/iˌkɑː.nəˈmet.rɪk/", "計量經濟學的"),
        ("The migratory monarch butterflies travel thousands of miles to their overwintering grounds in Mexico. ___, they congregate in the exact same oyamel fir groves used by their ancestors.", "Remarkably", "Conversely", "Thus", "In contrast", "這些遷徙的黑脈金斑蝶跋涉數千英里前往墨西哥的越冬棲息地。「引人矚目的是/令人稱奇的是」，牠們竟聚集在與祖輩所使用完全相同的冷杉樹林中。", "強化驚嘆細節之遞進評論副詞，選 Remarkably。", "情感加強評註副詞選 Remarkably。", "congregate", "/ˈkɑːŋ.ɡrə.ɡeɪt/", "聚集集合", "ancestor", "/ˈæn.ses.tɚ/", "祖先祖輩"),
        ("The museum’s retrospective highlights the sculptor’s minimalist metalworks; ___, it showcases rare preliminary graphite sketches from his early Paris period.", "similarly", "however", "therefore", "instead", "該博物館的回顧展重點突出了這位雕塑家的極簡主義金屬工藝作品；「同樣地」，它亦展出了其早年在巴黎時期罕見的鉛筆草圖手稿。", "同類藝術展品之並列呈現，選 similarly 或 additionally。", "並列呈現副詞選 similarly。", "retrospective", "/ˌret.rəˈspek.tɪv/", "回顧展追溯的", "sculptor", "/ˈskʌlp.tɚ/", "雕塑家"),
        ("Sustainable forestry practices prevent soil degradation; ___, they preserve the biodiversity of the underlying understory flora.", "furthermore", "nonetheless", "otherwise", "conversely", "永續林業實踐能夠有效防範土壤退化；「此外」，它們亦能維護底層林下植被的生物多樣性。", "防止退化 + 維護多樣性，遞進選 furthermore。", "遞進關係選 furthermore。", "degradation", "/ˌdeɡ.rəˈdeɪ.ʃən/", "退化墮落損耗", "understory", "/ˈʌn.dɚˌstɔːr.i/", "林下植物下層植被"),
        ("The cognitive assessment measures abstract pattern recognition; ___, it gauges the subject’s processing speed under strict time constraints.", "likewise", "nevertheless", "instead", "whereas", "這項認知能力測驗衡量了受試者的抽象模式辨識能力；「同樣地」，它亦測量了受試者在嚴格時間限制下的訊息處理速度。", "並列衡量面向，選 likewise（同樣地）。", "並列連鎖詞選 likewise。", "cognitive", "/ˈkɑːɡ.nə.tɪv/", "認知的認識的", "constraint", "/kənˈstreɪnt/", "限制約束"),
        ("The author does not merely describe historical events chronologically; ___, she contextualizes each milestone within broader socioeconomic currents.", "rather", "however", "consequently", "similarly", "作者並非僅僅按時間順序平鋪直敘歷史事件；「而是/相反地」，她將每一個重大里程碑均置於更宏觀的社會經濟思潮背景中加以脈絡化詮釋。", "not merely... but rather 的經典變體，選 rather（而是）。", "否定修正闡述詞選 rather。", "chronologically", "/ˌkrɑː.nəˈlɑː.dʒɪ.kəl.i/", "按年代時序地", "contextualize", "/kənˈteks.tʃu.ə.laɪz/", "置於脈絡中詮釋"),
        ("The architectural design maximizes passive solar heating. ___, south-facing floor-to-ceiling double-glazed windows trap thermal energy during winter months.", "For instance", "However", "In contrast", "Nevertheless", "這項建築設計最大限度地利用了被動式太陽能採暖。「舉例而言」，朝南的落地雙層中空玻璃窗在冬季月份能有效捕捉儲存熱能。", "對上一句「被動太陽能設計」提供具體建築構件實例，選 For instance。", "舉例說明短語選 For instance。", "passive", "/ˈpæs.ɪv/", "被動的消極的", "double-glazed", "/ˌdʌb.əlˈɡleɪzd/", "雙層玻璃的")
    ]),
    # 5. Rhetorical Synthesis: Synthesizing Bulleted Field Research Notes
    ("Rhetorical Synthesis: Research Notes", "學術思維", "C1-SAT05", [
        ("The student wants to emphasize a similarity between the two hominid species. Which choice most effectively accomplishes this goal? \nNotes:\n• Homo neanderthalensis crafted complex Mousterian stone tools.\n• Homo sapiens in the Upper Paleolithic fabricated intricate Aurignacian blades.\n• Both species utilized pigments for symbolic ritual ornamentation.", "Both Homo neanderthalensis and Homo sapiens engaged in symbolic behavior through the use of ornamental pigments.", "While Neanderthals made Mousterian tools, Homo sapiens made Aurignacian blades.", "Homo sapiens inhabited Europe during the Upper Paleolithic.", "Neanderthals developed sophisticated lithic traditions.", "學生想要強調兩種古人類物種之間的「相似性之處」。選項中唯有直接點出兩者均使用顏料進行儀式象徵裝飾之選項達成此目標。", "修辭合成：鎖定目標 (emphasize a similarity) -> 選項含 Both species utilized pigments。", "修辭綜合題：鎖定目標提示詞 Both... engaged in symbolic behavior。", "hominid", "/ˈhɑː.mə.nɪd/", "原始人類人科動物", "ornamentation", "/ˌɔːr.nə.menˈteɪ.ʃən/", "裝飾裝潢修飾"),
        ("The student wants to introduce the Mayan city of Tikal to an audience unfamiliar with the civilization. Which choice most effectively accomplishes this goal?", "Tikal, a prominent urban center of the ancient Maya civilization in modern-day Guatemala, flourished as a major political and economic hub from 200 to 900 CE.", "Tikal's Temple IV stands over sixty-five meters high in the jungle canopy.", "Excavations at Tikal revealed stelae inscribed with hieroglyphic king lists.", "The decline of Tikal coincided with the broader Classic Maya collapse.", "學生希望向對馬雅文明不熟悉的聽眾「介紹提卡爾城」。唯有清楚交代其地理位置、文明歸屬與繁榮時代之選項最適合初學者背景介紹。", "向陌生讀者介紹整體背景：包含文明、地理位置 (Guatemala) 與繁榮時期。", "背景介紹功能句首選包含身分定位之同位語定義句。", "flourish", "/ˈflɝː.ɪʃ/", "繁榮昌盛", "stelae", "/ˈstiː.laɪ/", "石碑銘文石柱"),
        ("The student wants to highlight a contrast between the two geothermal power plants. Which choice most effectively accomplishes this goal?", "Unlike the Geysers facility, which harnesses dry steam, the Nesjavellir plant utilizes high-temperature flash steam to generate electricity.", "The Geysers is located in California, whereas renewable energy is expanding globally.", "Both facilities generate baseload electricity with zero carbon emissions.", "The Nesjavellir plant was constructed to supply district heating to Reykjavik.", "學生希望凸顯兩座地熱發電廠之間的「鮮明對比 (contrast)」。選項唯有以 Unlike 開頭對比兩者使用的蒸氣技術類型 (dry steam vs. flash steam) 達標。", "修辭合成：對比 (contrast) -> Unlike A, B utilizes...", "對比修辭結構選 Unlike X, Y utilizes...", "geothermal", "/ˌdʒiː.oʊˈθɝː.məl/", "地熱的", "harness", "/ˈhɑːr.nəs/", "駕馭利用治理"),
        ("The student wants to present the primary research finding of Dr. Lin’s oceanographic expedition. Which choice most effectively accomplishes this goal?", "Dr. Lin’s team demonstrated that deep-sea benthic organisms rely on hydrothermal vent chemosynthesis rather than photosynthetic surface debris for nourishment.", "Dr. Lin led a three-month research cruise aboard the RV Atlantis.", "The team deployed autonomous underwater vehicles to depths exceeding four thousand meters.", "Samples of seawater were collected at twelve distinct hydrothermal sites.", "學生希望陳述林博士海洋考察隊的「主要研究發現 (primary research finding)」。選項中唯有總結生物營養來源機制之結論句達成目標。", "陳述研究發現 (research finding) -> demonstrated that...", "研究發現陳述選動詞 demonstrated that...", "benthic", "/ˈben.θɪk/", "底棲的深海底的", "debris", "/dəˈbriː/", "碎屑殘骸碎片"),
        ("The student wants to provide an explanation for the sudden population rebound of the Iberian lynx. Which choice most effectively accomplishes this goal?", "Intensive captive breeding combined with the ecological restoration of rabbit prey populations catalyzed the Iberian lynx’s dramatic demographic recovery.", "The Iberian lynx is an apex feline predator native to the Mediterranean woodland.", "By 2002, fewer than one hundred individual lynxes remained in Andalusia.", "Conservationists released tracking collars to monitor juvenile lynx dispersal patterns.", "學生希望為伊比利亞猞猁族群的突然復甦提供「科學解釋 (explanation)」。選項中明確指出了人工繁殖結合獵物兔子生態復育的雙重機制。", "解釋族群復甦原因 (explanation for the rebound) -> captive breeding + ecological restoration。", "解釋機制句選含因果動詞 catalyzed recovery 之選項。", "lynx", "/lɪŋks/", "山貓猞猁", "demographic", "/ˌdem.əˈɡræf.ɪk/", "族群統計的人口學的")
    ], [
        # 5 continued
        ("The student wants to emphasize the artistic significance of Edmonia Lewis's sculpture *The Death of Cleopatra*. Which choice most effectively accomplishes this goal?", "By portraying Cleopatra with unsparing realism rather than idealized serenity, Lewis challenged contemporary neoclassical conventions and cemented her reputation as a pioneering sculptor.", "Edmonia Lewis completed the monumental marble sculpture *The Death of Cleopatra* in 1876.", "The sculpture was exhibited at the Centennial Exposition in Philadelphia before disappearing for decades.", "Carved from Italian Carrara marble, the statue weighs over two tons.", "學生希望強調艾德莫尼亞·路易斯之雕塑作品《克麗奧佩脫拉之死》的「藝術意義 (artistic significance)」。選項指出了其挑戰新古典主義慣例並奠定其開創性地位。", "藝術重要性 (artistic significance) -> challenged conventions and cemented reputation。", "藝術價值評論句選挑戰慣例之深入闡述。", "unsparing", "/ʌnˈsper.ɪŋ/", "不留情面的嚴酷的", "neoclassical", "/ˌniː.oʊˈklæs.ɪ.kəl/", "新古典主義的"),
        ("The student wants to specify the methodological innovation introduced in Dr. Alvarez’s study. Which choice most effectively accomplishes this goal?", "Rather than relying on destructive radiocarbon assays, Dr. Alvarez developed a non-invasive multispectral imaging technique to analyze ancient parchment inks.", "Dr. Alvarez examined twelve medieval codices housed in the Vatican Library.", "The study was published in the *Journal of Cultural Heritage* in autumn 2023.", "Medieval inks frequently contained iron gall and oak extracts.", "學生希望具體說明阿爾瓦雷斯博士研究中所引進的「方法論創新 (methodological innovation)」。選項明確點出非侵入式多光譜成像技術對傳統破壞性檢測的革新。", "方法論創新 (methodological innovation) -> non-invasive multispectral imaging technique。", "方法革新句選非破壞性技術對比之選項。", "non-invasive", "/ˌnɑːn.ɪnˈveɪ.sɪv/", "非侵入性的無創的", "parchment", "/ˈpɑːrtʃ.mənt/", "羊皮紙羊皮文獻"),
        ("The student wants to introduce the concept of 'acoustic crypsis' to an audience of biology students. Which choice most effectively accomplishes this goal?", "Acoustic crypsis is an evolutionary adaptation whereby certain nocturnal tiger moths emit ultrasonic clicks that jam the echolocating sonar of predatory bats.", "Predatory bats hunt nocturnally using high-frequency echolocation calls.", "Tiger moths belong to the family Erebidae and exhibit vibrant wing pigmentation.", "Ultrasound frequencies exceed twenty kilohertz, beyond human auditory perception.", "學生希望向生物系學生介紹「聲學隱蔽 (acoustic crypsis)」的概念。選項直接給出了定義、演化適應機制及其對蝙蝠聲納的干擾原理。", "概念定義 (introduce the concept) -> Acoustic crypsis is an evolutionary adaptation whereby...", "概念定義句以 is an evolutionary adaptation whereby... 起手。", "acoustic", "/əˈkuː.stɪk/", "聲學的聲音的", "crypsis", "/ˈkrɪp.sɪs/", "隱匿保護色假死"),
        ("The student wants to emphasize how the author’s background influenced her literary style. Which choice most effectively accomplishes this goal?", "Drawing directly upon her bilingual upbringing in bilingual Montreal, the novelist infused her prose with rhythmic code-switching between French syntax and English vernacular.", "The novelist was born in Montreal in 1968 and attended McGill University.", "Her debut novel received the Governor General’s Award for Fiction in 2004.", "She frequently lectures on modern North American diaspora narratives.", "學生希望強調作者的成長背景如何「深刻影響了其文學風格」。選項點出了雙語成長背景與其作品法語句法及英語俚語節奏交替風格的因果關係。", "背景影響風格 (background influenced style) -> bilingual upbringing infused prose with code-switching。", "背景與風格連結句選 Drawing upon upbringing, infused prose with...", "code-switching", "/ˈkoʊdˌswɪtʃ.ɪŋ/", "語碼轉換語言切換", "vernacular", "/vɚˈnæk.jə.lɚ/", "白話方言本地話"),
        ("The student wants to contrast the atmospheric composition of Mars with that of Venus. Which choice most effectively accomplishes this goal?", "While both planets possess carbon-dioxide-dominated atmospheres, Venus's surface pressure is ninety times greater than Earth's, whereas Mars's atmospheric density is less than one percent of our own.", "Mars has polar ice caps composed of water and frozen carbon dioxide.", "Venus experiences a runaway greenhouse effect resulting in surface temperatures exceeding 450 degrees Celsius.", "Planetary scientists utilize orbiter spectrometers to analyze atmospheric gases across the solar system.", "學生希望「對比 (contrast)」火星與金星的大氣組成與物理特徵。選項精準點出兩者均以二氧化碳為主，但表面氣壓密度存在九十倍對比不到百分之一的巨大懸殊。", "大氣對比 (contrast atmospheric composition/pressure) -> While both... Venus's pressure... whereas Mars's density...", "對比句選 While both..., X is..., whereas Y is...", "spectrometer", "/spekˈtrɑː.mə.t̬ɚ/", "光譜儀分光計", "runaway", "/ˈrʌn.ə.weɪ/", "失控的逃跑的")
    ]),
    # 6. Boundaries: Independent Clauses & Semicolons
    ("Boundaries: Independent Clauses & Semicolons", "學術思維", "C1-SAT06", [
        ("The team’s archaeological hypothesis was controversial; ___, subsequent isotopic testing of the recovered pottery sherds corroborated their chronologies.", "nevertheless", "furthermore", "therefore", "similarly", "該研究團隊的考古學假說原先充滿爭議；「然而」，隨後對出土陶片進行的同位素檢測，證實了他們所推斷之年代序列的正確性。", "分號加逗號連接兩完整獨立子句，前句為爭議，後句為證實，轉折選 nevertheless。", "標點符號與獨立子句連接：分號 + nevertheless + 逗號。", "isotopic", "/ˌaɪ.səˈtɑː.pɪk/", "同位素的", "corroborate", "/kəˈrɑː.bə.reɪt/", "證實支持確證"),
        ("Marine biologists tracked the migratory route of the humpback ___ discovered that several breeding pods ventured unusually close to the Antarctic ice shelf.", "whales and", "whales, and", "whales; and", "whales, they", "海洋生物學家追蹤了座頭鯨的遷徙路線，「並且」發現數個繁育鯨群異常接近南極冰架。", "動詞 tracked 與 discovered 為同一主詞 (Marine biologists) 之並列雙謂語，無需逗號或分號分隔，選 whales and。", "並列複合謂語動詞，中間無逗號直接用 and 連接。", "humpback", "/ˈhʌmp.bæk/", "座頭鯨駝背", "pod", "/pɑːd/", "鯨魚群豆莢"),
        ("The Renaissance fresco suffered extensive water damage over the ___ conservators utilized delicate laser ablation techniques to restore the underlying pigments.", "centuries; consequently,", "centuries, consequently", "centuries, consequently,", "centuries; consequently", "這幅文藝復興時期的濕壁畫在數個世紀以來遭受了嚴重的受潮損害；「結果」，文物修復專家運用精密的雷射微剝技術來還原底層的顏料彩繪。", "兩獨立子句需要分號隔開，副詞 consequently 之後需有逗號：; consequently,。", "獨立子句連接標點標準形式：分號 + 副詞 + 逗號。", "fresco", "/ˈfres.koʊ/", "濕壁畫壁畫", "ablation", "/æbˈleɪ.ʃən/", "切除消融微剝"),
        ("The laboratory lacked sufficient funding to purchase a cryo-electron ___ researchers relied on external university consortia to collect structural datasets.", "microscope; thus,", "microscope, thus,", "microscope thus", "microscope; thus", "該實驗室缺乏充裕經費購置冷凍電子顯微鏡；「因而」，研究人員仰賴外部大學聯盟機構來採集蛋白質結構數據集。", "兩獨立完整子句連接，需用分號 + thus + 逗號：; thus,。", "分號 + thus, 連接獨立完整子句。", "cryo-electron", "/ˌkraɪ.oʊ.iˈlek.trɑːn/", "冷凍電子的", "consortium", "/kənˈsɔːr.ti.əm/", "聯盟聯合企業財團"),
        ("The orbital observatory captured high-resolution infrared images of the stellar ___ revealed unprecedented detail regarding protoplanetary disk formation.", "nursery, which", "nursery; which", "nursery which", "nursery, that", "這座太空軌道天文台捕捉到了恆星育嬰室的高解析度紅外線影像，這「為原行星盤的形成提供了前所未見的詳細資訊」。", "非限定關係子句修飾前面的影像或景象，用逗號 + which，不可用 that 或分號。", "非限定關係子句標點選 , which。", "stellar", "/ˈstel.ɚ/", "恆星的星球的傑出的", "protoplanetary", "/ˌproʊ.t̬oʊˈplæn.ə.ter.i/", "原行星的原行星盤的"),
        ("The ancient city walls were reinforced with mortar and kiln-fired ___ structural integrity enabled them to withstand seismic shocks for millennia.", "bricks; their", "bricks, their", "bricks their", "bricks, and their", "這座古城牆是以灰泥與窯燒磚塊加固而成；「它們的」結構完整性使其得以抵禦數千年來的地震衝擊波。", "兩獨立句 (walls were reinforced... / their integrity enabled...) 需用分號連接或加對等連詞，選 bricks; their。", "兩獨立子句防範Comma Splice，選分號 bricks; their。", "kiln-fired", "/ˈkɪln.faɪrd/", "窯燒的耐火的", "seismic", "/ˈsaɪz.mɪk/", "地震的受地震影響的"),
        ("The linguistics professor analyzed the phonological shifts of Vulgar ___ she traced the divergence of Western Romance dialects.", "Latin; specifically,", "Latin, specifically", "Latin, specifically,", "Latin; specifically", "這位語言學教授深入分析了通俗拉丁語的語音音變現象；「具體而言」，她梳理了西羅曼語族各方言的分化脈絡。", "兩獨立子句需分號分隔：; specifically,。", "分號 + specifically, 銜接獨立子句。", "phonological", "/ˌfoʊ.nəˈlɑː.dʒɪ.kəl/", "音韻學的語音系統的", "divergence", "/daɪˈvɝː.dʒəns/", "分歧分化背離"),
        ("The superconductor demonstrates zero electrical resistance below critical ___ engineers anticipate revolutionary advances in magnetic levitation transport.", "temperatures; accordingly,", "temperatures, accordingly,", "temperatures; accordingly", "temperatures accordingly", "該超導體在臨界溫度以下展現出零電阻特性；「因此/相應地」，工程師預期這將為磁浮交通運輸帶來革命性的重大飛躍。", "獨立子句連接選 ; accordingly,。", "分號 + accordingly, 連接獨立子句。", "superconductor", "/ˌsuː.pɚ.kənˈdʌk.tɚ/", "超導體超導材料", "levitation", "/ˌlev.əˈteɪ.ʃən/", "懸浮升空空中漂浮"),
        ("Botanists collected specimens of rare montane orchids during the ___ dried plant samples were subsequently cataloged in the herbarium archive.", "monsoon; the", "monsoon, the", "monsoon the", "monsoon; and the", "植物學家在季風季節採集了珍稀山地蘭花的植物標本；「這些」乾燥植物樣本隨後被登錄歸檔於植物標本館檔案庫中。", "兩獨立主謂結構連接，用分號隔開：monsoon; the。", "獨立子句連接選分號 monsoon; the。", "montane", "/ˈmɑːn.teɪn/", "山地的山地森林的", "herbarium", "/hɝːˈber.i.əm/", "植物標本館植物標本集"),
        ("The poet discarded the rigid metrical constraints of the Italian ___ she composed free-form verses that captured modern psychological dissonance.", "sonnet; instead,", "sonnet, instead,", "sonnet; instead", "sonnet instead,", "這位詩人摒棄了義大利十四行詩嚴格刻板的格律束縛；「取而代之的是/反而」，她創作了捕捉現代人心理不協調感的自由體詩篇。", "獨立子句連接選 ; instead,。", "分號 + instead, 標點選 ; instead,。", "sonnet", "/ˈsɑː.nət/", "十四行詩商籟體", "dissonance", "/ˈdɪs.ə.nəns/", "不協調不和諧不一致")
    ]),
    # 7. Boundaries: Nonessential Elements & Relative Clauses
    ("Boundaries: Nonessential Elements", "學術思維", "C1-SAT07", [
        ("Dr. Aris Thorne, a biochemist at the Max Planck ___, received the Nobel Prize for discovering the catalytic properties of ribozymes.", "Institute", "Institute,", "Institute;", "Institute—", "馬克斯·普朗克研究所的生物化學家阿里斯·索恩博士，因發現核酶的催化特性而榮獲諾貝爾獎。", "a biochemist at the Max Planck Institute 為主詞 Dr. Aris Thorne 的同位語插入語，前後需成對逗號：Institute,。", "非限定同位語成對逗號閉合：Institute,。", "catalytic", "/ˌkæt̬.əlˈɪt.ɪk/", "催化的起催化作用的", "ribozyme", "/ˈraɪ.bə.zaɪm/", "核酶具有催化活性的RNA"),
        ("The Hubble Space Telescope, which was deployed into low Earth orbit in ___ revolutionized observational astronomy by providing unobstructed views of the cosmos.", "1990,", "1990", "1990;", "1990—", "於一九九○年發射部署於近地軌道的哈伯太空望遠鏡，藉由提供不受遮蔽的宇宙視野，徹底革新了觀測天文學。", "非限定關係子句 which was deployed into... in 1990 需用成對逗號封閉，選 1990,。", "關係子句封閉逗號選 1990,。", "unobstructed", "/ˌʌn.əbˈstrʌk.tɪd/", "暢通無阻的不受妨礙的", "observational", "/ˌɑːb.zɚˈveɪ.ʃən.əl/", "觀測的觀察的"),
        ("The newly deciphered clay tablets, inscribed with cuneiform legal codes during the reign of Hammurabi, ___ unprecedented insight into ancient Babylonian jurisprudence.", "provide", "provides", "providing", "to provide", "在漢摩拉比統治時期以楔形文字銘刻法律條文的最新出土破譯泥板，為古代巴比倫法學提供了前所未有的深刻洞察。", "主詞為複數名詞 tablets，中間有過去分詞片語插入語，主要動詞需用複數現在式 provide。", "主謂一致：The clay tablets [修飾語] provide...", "cuneiform", "/kjuːˈneɪ.ə.fɔːrm/", "楔形文字楔形的", "jurisprudence", "/ˌdʒʊr.ɪsˈpruː.dəns/", "法學法理學法律哲學"),
        ("The monarch butterfly's multi-generational migration—an extraordinary navigational feat that spans thousands of ___ continues to baffle behavioral biologists.", "miles—", "miles,", "miles;", "miles", "黑脈金斑蝶跨越多個世代的遷徙——一項橫跨數千英里的非凡導航壯舉——持續讓行為生物學家感到驚奇與困惑。", "前面使用了長破折號 (—)，插入語結尾必須使用對稱的長破折號閉合：miles—。", "破折號插入語成對使用：miles—。", "baffle", "/ˈbæf.əl/", "使困惑難倒", "navigational", "/ˌnæv.əˈɡeɪ.ʃən.əl/", "導航的定向的"),
        ("The restoration of the Gothic cathedral's stained glass windows, a painstaking endeavor overseen by Master Artisan Jean ___ required three decades to complete.", "Luc,", "Luc", "Luc;", "Luc—", "這座哥德式大教堂彩色玻璃花窗的修復工程——由彩繪玻璃大師尚·盧克親自督導的一項極其艱辛的浩大工程——歷時整整三十年方告竣工。", "主詞同位語插入語 (a painstaking endeavor overseen by Master Artisan Jean Luc) 結尾需用逗號閉合：Luc,。", "同位語插入語逗號閉合選 Luc,。", "painstaking", "/ˈpeɪnˌsteɪ.kɪŋ/", "煞費苦心的極其細緻艱辛的", "endeavor", "/enˈdev.ɚ/", "努力浩大事業企圖"),
        ("Ants, which communicate primarily through specialized pheromone ___ coordinate complex foraging behaviors across subterranean supercolonies.", "trails,", "trails", "trails;", "trails—", "主要透過特定費洛蒙氣味蹤跡進行溝通交流的螞蟻，能夠在龐大的地下超級蟻群之間協調複雜的覓食行為。", "非限定關係子句 which communicate primarily through... trails 結尾需用逗號閉合：trails,。", "關係子句成對逗號選 trails,。", "pheromone", "/ˈfer.ə.moʊn/", "費洛蒙外激素", "subterranean", "/ˌsʌb.təˈreɪ.ni.ən/", "地下的隱密的"),
        ("The philosopher’s core premise—that human ethical behavior originates from innate empathy rather than calculated ___ challenged the utilitarian tenets of his era.", "self-interest—", "self-interest,", "self-interest;", "self-interest", "這位哲學家的核心前提——即人類道德行為源於天生的同理心而非精打細算的自私自利——向他所處時代的功利主義教條發起了強力挑戰。", "破折號插入語需對稱閉合：self-interest—。", "破折號成對閉合選 self-interest—。", "innate", "/ɪˈneɪt/", "天生的與生俱來的", "utilitarian", "/juːˌtɪl.əˈter.i.ən/", "功利主義的實用主義的"),
        ("The volcanic archipelago, isolated from the continental mainland for millions of ___ harbors hundreds of endemic floral species found nowhere else on Earth.", "years,", "years", "years;", "years—", "與大陸板塊隔絕長達數百萬年的這座火山群島，孕育了數百種在地球其他任何地方都未曾發現的特有植物物種。", "過去分詞片語形容詞插入語 isolated from... for millions of years 結尾需用逗號閉合：years,。", "分詞插入語成對逗號選 years,。", "archipelago", "/ˌɑːr.kəˈpel.ə.ɡoʊ/", "群島列島", "endemic", "/enˈdem.ɪk/", "特有的當地的"),
        ("Professor Evelyn Vance, whose field research in the Kalahari overturned orthodox models of hunter-gatherer ___ delivered the keynote symposium address.", "mobility,", "mobility", "mobility;", "mobility—", "在喀拉哈里沙漠的田野調查推翻了採集狩獵民族移動性傳統模型的伊芙琳·萬斯教授，在國際研討會上發表了開幕主題演講。", "所有格關係子句 whose field research... overturned models of mobility 結尾需逗號閉合：mobility,。", "關係子句成對逗號閉合選 mobility,。", "orthodox", "/ˈɔːr.θə.dɑːks/", "正統的傳統公認的", "mobility", "/moʊˈbɪl.ə.t̬i/", "流動性移動能力"),
        ("The Great Barrier Reef, a delicate marine ecosystem composed of billions of tiny coral ___ faces unprecedented bleaching events due to rising sea temperatures.", "polyps,", "polyps", "polyps;", "polyps—", "由數十億隻微小珊瑚蟲組成的脆弱海洋生態系統——大堡礁，因海水溫度上升正遭遇著史無前例的珊瑚白化危機事件。", "同位語 a delicate marine ecosystem composed of... polyps 需逗號閉合：polyps,。", "同位語插入語成對逗號選 polyps,。", "polyp", "/ˈpɑːl.ɪp/", "珊瑚蟲水螅體息肉", "bleaching", "/ˈbliː.tʃɪŋ/", "白化漂白")
    ]),
    # 8. Boundaries: Supplementary Parenthetical Dashes & Appositives
    ("Boundaries: Supplementary Dashes", "學術思維", "C1-SAT08", [
        ("The geneticist isolated three distinct regulatory proteins—activator, repressor, and ___ mapped their binding sites across the eukaryotic genome.", "inducer—and", "inducer, and", "inducer; and", "inducer and", "遺傳學家分離出了三種截然不同的調控蛋白質——激活蛋白、阻遏蛋白與誘導蛋白——並繪製了它們在真核生物基因組中的結合位點地圖。", "插入語由破折號開始，列舉完三種蛋白質後需以破折號閉合，再接主要動詞 mapped：inducer—and。", "破折號成對插入語：inducer—and mapped...", "eukaryotic", "/juːˌkær.iˈɑː.t̬ɪk/", "真核生物的", "repressor", "/rɪˈpres.ɚ/", "阻遏物阻遏蛋白"),
        ("The expedition traversed the Taklamakan Desert—a hyper-arid expanse of shifting sand dunes ___ water sources were virtually non-existent.", "where", "where,", "where;", "which", "考察隊橫越了塔克拉瑪干沙漠——一片流動沙丘綿延、水源幾乎完全不存在的極度乾旱荒漠。", "關係副詞 where 修飾前方地點 expanse，子句內部無需逗號打斷，選 where。", "關係副詞引導定語子句選 where。", "hyper-arid", "/ˌhaɪ.pɚˈer.ɪd/", "極度乾旱的極度貧瘠的", "dune", "/duːn/", "沙丘"),
        ("The quantum computing prototype operates at cryogenic temperatures—conditions colder than deep ___ avoid decoherence of its superconducting qubits.", "space—to", "space, to", "space; to", "space to", "該量子計算原型機在極低溫條件下運作——比深太空更為嚴寒的環境條件——藉以防範其超導量子位元發生退相干現象。", "成對破折號閉合插入語，後接不定詞表示目的：space—to。", "破折號插入語成對閉合選 space—to。", "cryogenic", "/ˌkraɪ.oʊˈdʒen.ɪk/", "極低溫的低溫學的", "qubit", "/ˈkjuː.bɪt/", "量子位元量子比特"),
        ("The novelist’s recurring motifs—alienation, unrequited devotion, and spiritual ___ reflect the profound disillusionment of the post-war era.", "malaise—", "malaise,", "malaise;", "malaise", "該小說家反覆出現的主題意象——疏離孤獨、得不到回報的付出以及精神萎靡頹廢——深刻反映了戰後世代的幻滅心境。", "主詞與動詞 reflect 之間為破折號成對插入語，結尾選 malaise—。", "破折號成對閉合選 malaise—。", "unrequited", "/ˌʌn.rɪˈkwaɪ.t̬ɪd/", "未獲回報的單相思的", "malaise", "/mæˈleɪz/", "萎靡不振微恙頹廢"),
        ("The astrophysicist analyzed fast radio bursts—mysterious millisecond-duration pulses of extragalactic ___ origin remains a subject of intense scientific inquiry.", "radiation whose", "radiation, whose", "radiation; whose", "radiation—whose", "這位天體物理學家分析了快速電波爆發——神秘的毫秒級河外輻射脈衝，其物理起源至今仍是激烈科學探索研討的焦點課題。", "radiation whose origin remains... 非限定修飾 radiation 的所有格關係子句，選 radiation whose。", "關係所有格代詞選 whose。", "astrophysicist", "/ˌæs.troʊˈfɪz.ə.sɪst/", "天體物理學家", "extragalactic", "/ˌek.strə.ɡəˈlæk.tɪk/", "河外星系的銀河系外的"),
        ("The archaeological strata revealed three occupational layers—Neolithic, Bronze Age, and ___ each characterized by distinctive ceramic typology.", "Hellenistic—", "Hellenistic,", "Hellenistic;", "Hellenistic", "該考古地層揭露了三個居住聚落時期地層——新石器時代、青銅時代以及希臘化時代——每一地層皆以獨特分明的陶瓷類型學特徵為標誌。", "成對破折號閉合列舉插入語，選 Hellenistic—。", "破折號插入語成對閉合選 Hellenistic—。", "strata", "/ˈstreɪ.t̬ə/", "地層岩層階層", "typology", "/taɪˈpɑː.lə.dʒi/", "類型學分類學"),
        ("The ancient irrigation system—a subterranean network of gravity-fed aqueducts known as ___ sustained desert agriculture for over two millennia.", "qanats—", "qanats,", "qanats;", "qanats", "這座古代灌溉水利系統——一處利用重力引水、被稱為坎兒井的地下引水渠網絡——在超過兩千年的歲月裡支撐了沙漠農業的發展繁榮。", "主詞與主要謂語動詞 sustained 之間以成對破折號插入，選 qanats—。", "破折號閉合同位語選 qanats—。", "aqueduct", "/ˈæk.wə.dʌkt/", "引水渠高架渠水利設施", "subterranean", "/ˌsʌb.təˈreɪ.ni.ən/", "地下的"),
        ("The migratory birds rely on specific staging wetlands—habitats critically endangered by agricultural ___ complete their transcontinental journey.", "drainage—to", "drainage, to", "drainage; to", "drainage to", "候鳥高度仰賴特定的遷徙中繼濕地——因農業排水開墾而面臨嚴重瀕危的生態棲地——來完成牠們跨越洲際大陸的壯麗旅程。", "破折號成對閉合插入語，後接不定詞 to complete：drainage—to。", "破折號閉合後接目的不定詞選 drainage—to。", "wetland", "/ˈwet.lænd/", "濕地沼澤地", "transcontinental", "/ˌtrænz.kɑːn.təˈnen.t̬əl/", "跨大陸的橫跨大洲的"),
        ("The Renaissance master’s sfumato technique—the subtle blending of colors and tones without perceptible ___ imparted an ethereal luminescence to his portraits.", "transitions—", "transitions,", "transitions;", "transitions", "文藝復興大師的暈塗漸層法——在沒有任何突兀生硬可察覺轉折的狀態下將色彩與色調進行細微交融——賦予了他的肖像畫一種超凡脫俗的柔和光澤。", "主詞與主要動詞 imparted 之間為破折號同位語說明，選 transitions—。", "破折號成對閉合選 transitions—。", "sfumato", "/sfuːˈmɑː.toʊ/", "暈塗法暈色法", "ethereal", "/iˈθɪr.i.əl/", "超凡脫俗的空靈的飄渺的"),
        ("The economic theorist challenged traditional equilibrium assumptions—axioms predicated on perfect information and unconstrained ___ arguing that cognitive friction dominates markets.", "rationality—", "rationality,", "rationality;", "rationality", "這位經濟理論家向傳統的市場均衡假定發起挑戰——即那些建立在完全信息與無約束理性基礎上的公理假說——論證指出認知摩擦在市場中佔據主導地位。", "名詞同位語插入語以成對破折號封閉，選 rationality—。", "成對破折號閉合選 rationality—。", "equilibrium", "/ˌiː.kwəˈlɪb.ri.əm/", "均衡平衡", "rationality", "/ˌræʃ.ənˈæl.ə.t̬i/", "理性合理性")
    ]),
    # 9. Subject-Verb Agreement: Inverted Syntax & Complex Prepositional Interrupters
    ("Subject-Verb Agreement: Inverted Syntax", "學術思維", "C1-SAT09", [
        ("Beneath the dense forest canopy of the Amazon basin ___ hundreds of unexcavated geoglyphs that challenge assumptions about pre-Columbian urbanism.", "lie", "lies", "lying", "to lie", "在亞馬遜盆地茂密的熱帶雨林樹冠之下，「坐落著」數百處尚未出土發掘的巨型幾何地面圖形，向傳統有關前哥倫布時期都市文明的假說提出了挑戰。", "倒裝句：地點介系詞片語置於句首，真正主詞為後方的複數名詞 hundreds of unexcavated geoglyphs，動詞使用複數形 lie。", "倒裝句主謂一致：主詞為複數 geoglyphs，動詞選 lie。", "geoglyph", "/ˈdʒiː.oʊ.ɡlɪf/", "地畫大地景觀圖形", "canopy", "/ˈkæn.ə.pi/", "樹冠森林頂層"),
        ("The identification of migratory flyways and stopover wetlands ___ essential for designing effective multinational conservation treaties.", "is", "are", "being", "were", "對於擬定具有實質成效的跨國生態保育條約而言，對候鳥遷徙通道與中繼濕地的辨識確認「至關重要」。", "主詞為單數核心名詞 The identification（辨識確認），後接介系詞片語，謂語動詞使用單數 is。", "主謂一致：核心主詞為單數 identification，動詞選 is。", "flyway", "/ˈflaɪ.weɪ/", "飛行通道鳥類遷徙路線", "stopover", "/ˈstɑːpˌoʊ.vɚ/", "中途停留中途站"),
        ("Among the most formidable challenges facing deep-sea submersibles ___ the immense hydrostatic pressure encountered at abyssal depths.", "is", "are", "being", "to be", "在深海潛水艇所面臨之最艱鉅嚴酷的挑戰之中，「是」在深淵海底所遭遇到的龐大流體靜力水壓。", "倒裝句：介系詞片語置於句首，真正主詞為後方的單數名詞 pressure，謂語動詞使用單數 is。", "倒裝句主謂一致：真正主詞為單數 pressure，動詞選 is。", "hydrostatic", "/ˌhaɪ.droʊˈstæt̬.ɪk/", "流體靜力學的靜水力學的", "abyssal", "/əˈbɪs.əl/", "深淵的深海的"),
        ("Neither the historical accuracy of the chronicles nor the linguistic authenticity of the royal decrees ___ in doubt among contemporary medievalists.", "is", "are", "were", "being", "在當代中世紀史學家心目中，無論是編年史的歷史準確性，抑或是皇家詔書的語言真實性，都「不容」置疑。", "Neither A nor B 結構，動詞依就近原則 (proximity rule) 與 B 一致：B (authenticity) 為單數，選 is。", "就近原則：the linguistic authenticity 為單數，選 is。", "chronicle", "/ˈkrɑː.nɪ.kəl/", "編年史編年紀事", "authenticity", "/ˌɑː.θenˈtɪs.ə.t̬i/", "真實性真確性"),
        ("Surrounding the ancient temple complex ___ a series of concentric defensive moats engineered to deter hostile incursions.", "was", "were", "being", "to be", "圍繞在這座古老神廟建築複合體周圍的，「是」一系列旨在威懾抵禦敵意入侵而精心修建的同心防禦護城河壕溝。", "倒裝句：現在分詞片語置於句首，真正主詞為 a series（系列），在正式學術語境中 a series of + 複數名詞可接單數 was 或複數 were，此處核心主詞為 a series，標準書面語使用單數 was。", "倒裝句核心主詞 a series 搭配單數 was。", "concentric", "/kənˈsen.trɪk/", "同心的同軸的", "incursion", "/ɪnˈkɝː.ʒən/", "侵入侵犯襲擊"),
        ("The discovery of extremophile bacteria thriving in geothermal vents ___ long-standing assumptions about the biological boundaries of life.", "contradicts", "contradict", "contradicting", "to contradict", "在高溫地熱噴口繁衍生息的嗜極端菌的發現，「推翻牴觸了」長期以來有關生命生物邊界的傳統假定。", "主詞為單數名詞 The discovery，後接介系詞片語修飾，謂語動詞使用第三人稱單數 contradicts。", "主謂一致：主詞為單數 discovery，動詞選 contradicts。", "extremophile", "/ɪkˈstriː.mə.faɪl/", "嗜極生物嗜極菌", "thrive", "/θraɪv/", "繁榮茂盛茁壯"),
        ("Hidden within the ice cores retrieved from Greenland glaciers ___ atmospheric air bubbles trapped during the last interglacial period.", "are", "is", "being", "to be", "深藏在從格陵蘭冰川中所鑽取採集之冰芯內部的，「是」在上一次間冰期期間被封裝凍結的遠古大氣氣泡。", "倒裝句：真正主詞為後方複數名詞 atmospheric air bubbles，動詞選複數 are。", "倒裝句主謂一致：主詞為複數 bubbles，動詞選 are。", "glacier", "/ˈɡleɪ.ʃɚ/", "冰川冰河", "interglacial", "/ˌɪn.t̬ɚˈɡleɪ.ʃəl/", "間冰期的間冰期的時代"),
        ("A catalog of illuminated manuscripts and liturgical scrolls from the ninth century ___ compiled by the monastery archivists.", "was", "were", "being", "to be", "一份收錄九世紀彩繪手抄本與禮拜儀式羊皮紙卷軸的詳盡目錄清單，由修道院檔案保管員悉心編纂而成。", "核心主詞為單數名詞 A catalog，後接 of... 介系詞片語，謂語動詞使用單數 was。", "主謂一致：核心主詞為單數 catalog，動詞選 was。", "illuminated", "/ɪˈluː.mə.neɪ.t̬ɪd/", "彩繪裝飾的手抄本彩繪的", "liturgical", "/lɪˈtɝː.dʒɪ.kəl/", "禮拜儀式的宗教儀式的"),
        ("Embedded within the petrified amber ___ the fossilized antennae of an extinct Cretaceous wasp species.", "were", "was", "being", "to be", "鑲嵌嵌在石化琥珀內部的，「是」一種已絕滅白堊紀黃蜂物種的石化觸角標本。", "倒裝句：真正主詞為複數名詞 the fossilized antennae（antenna 的複數為 antennae），動詞使用複數 were。", "倒裝句主謂一致：主詞為複數 antennae，動詞選 were。", "amber", "/ˈæm.bɚ/", "琥珀琥珀色", "antennae", "/ænˈten.iː/", "觸角觸鬚天線"),
        ("Neither the high price of platinum catalysts nor the technical volatility of the chemical reaction ___ researchers from developing green hydrogen.", "deters", "deter", "deterring", "to deter", "無論是鉑金催化劑的昂貴價格，抑或是化學反應本身的技術不穩定性，都「無法阻擋」研究人員致力於開發綠氫的堅定步伐。", "Neither... nor... 就近原則：the technical volatility 為單數名詞，動詞選 deters。", "就近原則：volatility 為單數，選 deters。", "catalyst", "/ˈkæt̬.əl.ɪst/", "催化劑觸媒促成者", "volatility", "/ˌvɑː.ləˈtɪl.ə.t̬i/", "不穩定性揮發性")
    ]),
    # 10. Verb Tense & Aspect: Historical Past vs. Counterfactual Past Perfect
    ("Verb Tense & Aspect: Past vs. Past Perfect", "學術思維", "C1-SAT10", [
        ("Long before modern plate tectonics theory was formally accepted in the 1960s, Alfred Wegener ___ the continental drift hypothesis in 1912.", "had proposed", "proposes", "has proposed", "was proposing", "早在現代板塊構造學說於一九六○年代獲得學術界正式採納的漫長歲月之前，阿爾弗雷德·韋格納便早已於一九一二年「提出了」大陸漂移假說。", "動作發生在過去某一時間點 (1960s) 之前，且有 Long before 引導，使用過去完成式 had proposed。", "過去完成式：強調發生在過去某動作之前的動作，選 had proposed。", "plate tectonics", "/ˌpleɪt tekˈtɑː.nɪks/", "板塊構造論板塊構造學", "continental drift", "/ˌkɑːn.tə.nen.t̬əl ˈdrɪft/", "大陸漂移"),
        ("By the time the imperial delegation arrived in Samarkand, the resident governor ___ all diplomatic treaties with the visiting Silk Road envoys.", "had ratified", "ratified", "has ratified", "ratifies", "在帝國使團抵達撒馬爾罕之時，當地的總督早就已經與來訪的絲路特使全數「批准簽署了」所有外交條約。", "By the time + 過去式 (arrived)，主要子句表示在此之前已完成，使用過去完成式 had ratified。", "By the time + 過去式，主要子句選過去完成式 had ratified。", "delegation", "/ˌdel.əˈɡeɪ.ʃən/", "代表團使節團", "ratify", "/ˈræt̬.ə.faɪ/", "批准認可簽署"),
        ("If the Roman legions ___ their tactical formations during the Battle of Teutoburg Forest, the catastrophic ambush might have been averted.", "had maintained", "maintained", "would maintain", "maintain", "假若羅馬軍團在條頓堡森林戰役期間「有維持住」其嚴密的戰術陣型，那場災難性的毀滅伏擊原本是有可能得以避免的。", "與過去事實相反的假設語氣：if 子句使用 had + p.p. (had maintained)，主要子句搭配 might have been averted。", "與過去事實相反假設：if 子句選 had maintained。", "legion", "/ˈliː.dʒən/", "軍團大軍眾多", "ambush", "/ˈæm.bʊʃ/", "伏擊埋伏"),
        ("Astronomers established that the binary star system ___ orbiting a supermassive black hole for millions of years prior to its eventual tidal disruption.", "had been", "is", "has been", "will be", "天文學家證實，該雙星系統在其最終遭遇潮汐瓦解毀滅之前，早已圍繞著一個超大質量黑洞「持續運行了」長達數百萬年之久。", "過去動作 (established) 前持續進行的動作，使用過去完成進行式/完成式 had been。", "過去時態呼應選 had been。", "binary", "/ˈbaɪ.ner.i/", "雙星的二元的", "tidal disruption", "/ˌtaɪ.dəl dɪsˈrʌp.ʃən/", "潮汐瓦解潮汐撕裂"),
        ("Prior to the implementation of the clean air accords, industrial chimneys ___ sulfur dioxide into the atmosphere with minimal regulatory oversight.", "had emitted", "emitted", "have emitted", "emit", "在清潔空氣公約正式落實推行之前，工業煙囪長期在極端缺乏監管規範的情況下向大氣中大量「排放」二氧化硫氣體。", "Prior to + 過去時間點，描述在此之前存在的長久過去狀態，使用過去完成式 had emitted 或一般過去式，但強調先後順序選 had emitted。", "強調發生在公約實施前選 had emitted。", "chimney", "/ˈtʃɪm.ni/", "煙囪煙道", "oversight", "/ˈoʊ.vɚ.saɪt/", "監管監督疏忽"),
        ("Had the emergency containment valve functioned properly, toxic chemical effluent ___ into the municipal watershed.", "would not have leaked", "did not leak", "would not leak", "had not leaked", "假若緊急密封隔離閥門當時有正常發揮功用，有毒化學污水廢液「就不會外洩流入」市區的集水區水系之中。", "倒裝省略 If 的過去虛擬假設 (Had S p.p.)，主要子句使用 would not have leaked。", "過去虛擬假設主要子句選 would not have leaked。", "containment", "/kənˈteɪn.mənt/", "密封遏制抑制", "effluent", "/ˈef.lu.ənt/", "污水廢液廢水"),
        ("By the dawn of the twentieth century, urbanization and agricultural expansion ___ almost all of the native tallgrass prairie in North America.", "had eradicated", "eradicated", "have eradicated", "eradicate", "到二十世紀初葉之時，都市化進程與農業拓荒開墾早就已經「徹底摧毀根絕了」北美幾乎所有的原生高草草原生態。", "By + 過去時間點 (dawn of the 20th century)，使用過去完成式 had eradicated。", "By + 過去時間點搭配過去完成式 had eradicated。", "eradicate", "/ɪˈræd.ɪ.keɪt/", "根除消滅滅絕", "prairie", "/ˈprer.i/", "大草原北美草原"),
        ("Archaeologists deduced that the subterranean catacombs ___ as ceremonial burial chambers centuries before being converted into military bunkers.", "had served", "serve", "have served", "were serving", "考古學家推斷，這處地下墓穴在被改建為軍事碉堡掩體數個世紀之前，早就已經「充當」舉行宗教儀式的安葬墓室之用。", "在過去被改建 (being converted) 數個世紀之前已存在，使用過去完成式 had served。", "過去更早階段選 had served。", "catacomb", "/ˈkæt̬.ə.koʊm/", "地下墓穴地下穴道", "bunker", "/ˈbʌŋ.kɚ/", "碉堡地堡掩體"),
        ("If the naval commander ___ the coded cryptographic warning, the fleet could have evaded the devastating submarine torpedo barrage.", "had decoded", "decoded", "would decode", "decodes", "如果海軍指揮官當時「有成功破解解密」那份加密密碼警報，艦隊原本是可以避開那場毀滅性的潛艦魚雷齊射攻擊的。", "與過去相反假設：if 子句選 had decoded。", "與過去相反假設條件句選 had decoded。", "cryptographic", "/ˌkrɪp.təˈɡræf.ɪk/", "密碼術的密碼編譯的", "barrage", "/bəˈrɑːʒ/", "彈幕齊射連續砲轟"),
        ("Historical archives confirm that the Renaissance polymath ___ over fifty empirical architectural designs before completing his seminal treatise in 1510.", "had drafted", "drafts", "has drafted", "was drafting", "歷史檔案證實，這位文藝復興時期的通才大師在於一五一○年完成其開創性專著之前，早已親自「起草了」五十多份實證建築設計手稿草圖。", "在 1510 年完成專著之前已完成繪製，使用過去完成式 had drafted。", "在過去時間點前已完成動作用 had drafted。", "treatise", "/ˈtriː.t̬ɪs/", "專著學術論文", "polymath", "/ˈpɑː.li.mæθ/", "通才博學家")
    ]),
    # 11. Modifier Placement: Dangling Participial Clauses & Misplaced Modifiers
    ("Modifier Placement: Dangling Modifiers", "學術思維", "C1-SAT11", [
        ("Having analyzed thousands of genomic sequences, ___.", "the computational biologists identified a conserved protein domain essential for DNA repair", "a conserved protein domain essential for DNA repair was identified by the computational biologists", "the identification of a conserved protein domain was achieved", "it was discovered that a protein domain facilitates DNA repair", "在分析了數千個基因組序列之後，「計算生物學家們成功辨識出了對 DNA 修復至關重要的一個保守蛋白質結構域」。", "現在分詞短語 Having analyzed... 的邏輯主詞必須是能主動執行分析動作的「計算生物學家 (computational biologists)」。", "分詞修飾語邏輯主詞一致：選 the computational biologists 開頭之選項。", "genomic", "/dʒəˈnoʊ.mɪk/", "基因組的染色體組的", "conserved", "/kənˈsɝːvd/", "保守的生物演化中保持不變的"),
        ("Constructed from interlocking basalt blocks without mortar, ___.", "the Inca fortress withstood severe earthquakes for centuries", "centuries of severe earthquakes failed to destroy the Inca fortress", "the architectural brilliance of the Inca fortress was demonstrated", "earthquakes could not dismantle the Inca fortress", "這座印加城堡由緊密嵌合的玄武岩石塊在未使用任何灰泥黏著劑的情況下砌築而成，「歷經數個世紀的強烈地震依然屹立不搖」。", "過去分詞短語 Constructed from... 的邏輯主詞必須是被砌築建造的實體建築「印加城堡 (the Inca fortress)」。", "過去分詞邏輯主詞選 the Inca fortress。", "basalt", "/bəˈsɑːlt/", "玄武岩", "fortress", "/ˈfɔːr.trəs/", "要塞城堡堡壘"),
        ("Peering through the electron microscope, ___.", "the virologist observed the hexagonal capsid of the novel bacteriophage", "the hexagonal capsid of the novel bacteriophage was observed by the virologist", "observations of the bacteriophage capsid were carefully recorded", "it was possible to discern the hexagonal structure of the virus", "透過電子顯微鏡凝視觀察，「病毒學家觀察到了這種新型噬菌體的六邊形二十面體衣殼結構」。", "Peering through... 的邏輯主詞必須是凝視顯微鏡的人「病毒學家 (the virologist)」。", "現在分詞修飾語邏輯主詞選 the virologist。", "virologist", "/vaɪˈrɑː.lə.dʒɪst/", "病毒學家", "capsid", "/ˈkæp.sɪd/", "病毒衣殼蛋白質外殼"),
        ("To accurately measure atmospheric greenhouse gas concentrations, ___.", "atmospheric scientists calibrate their airborne spectrometry instruments before every flight", "instruments for spectrometry are calibrated before every flight by atmospheric scientists", "calibration of the airborne spectrometry instruments is required", "it is necessary to calibrate airborne spectrometry instruments", "為了精確測量大氣溫室氣體濃度，「大氣科學家在每一次飛行科研任務前均會嚴密校準其機載光譜儀器」。", "不定詞短語 To accurately measure... 的邏輯主詞必須是執行測量動作的「大氣科學家 (atmospheric scientists)」。", "目的不定詞邏輯主詞選 atmospheric scientists。", "spectrometry", "/spekˈtrɑː.mə.tri/", "光譜測定法", "calibrate", "/ˈkæl.ə.breɪt/", "校準校正測量"),
        ("Although heavily damaged by centuries of maritime corrosion, ___.", "the bronze astrolabe retained delicate astronomical inscriptions that astounded the divers", "the divers were astounded by the delicate astronomical inscriptions on the bronze astrolabe", "inscriptions on the bronze astrolabe were still legible to the diving team", "it was still possible to read the astronomical markings on the astrolabe", "儘管遭受數個世紀以來海水腐蝕的嚴重侵害，「這件青銅星盤依然保留著令潛水員讚嘆不已的精美天文刻度銘文」。", "Although heavily damaged... 的邏輯受詞/主詞必須是遭受腐蝕的器物「青銅星盤 (the bronze astrolabe)」。", "讓步分詞邏輯主詞選 the bronze astrolabe。", "astrolabe", "/ˈæs.trə.leɪb/", "星盤古代天文觀測儀", "corrosion", "/kəˈroʊ.ʒən/", "腐蝕侵蝕"),
        ("After spending decades cataloging indigenous herbal remedies, ___.", "the ethnobotanist published a monumental compendium on rainforest pharmacopeia", "a monumental compendium on rainforest pharmacopeia was published by the ethnobotanist", "the publication of a monumental compendium on herbal remedies occurred", "it took decades for the herbal remedies to be compiled into a compendium", "在歷經數十年系統性採集與整理原住民草本藥方之後，「這位民族植物學家出版了一部有關熱帶雨林藥典的劃時代巨著」。", "After spending decades... 邏輯主詞為花費歲月整理資料的學者「the ethnobotanist」。", "動名詞邏輯主詞選 the ethnobotanist。", "ethnobotanist", "/ˌeθ.noʊˈbɑː.t̬ən.ɪst/", "民族植物學家", "pharmacopeia", "/ˌfɑːr.mə.kəˈpiː.ə/", "藥典生藥志"),
        ("Unearthed during highway construction in northern Greece, ___.", "an ancient Macedonian tomb containing gold jewelry was excavated by archaeologists", "archaeologists excavated an ancient Macedonian tomb containing gold jewelry", "gold jewelry was recovered from an ancient Macedonian tomb", "the discovery of an ancient Macedonian tomb astonished historians", "這座在希臘北部公路施工期間被出土發掘的「藏有黃金珠寶飾品的古代馬其頓古墓，由考古學家進行了保護性發掘」。", "Unearthed during... 邏輯主詞必須是被挖掘出土的古蹟「an ancient Macedonian tomb」。", "出土主詞選 an ancient Macedonian tomb。", "tomb", "/tuːm/", "古墓陵墓", "excavate", "/ˈek.skə.veɪt/", "發掘挖掘"),
        ("By combining satellite radar interferometry with terrestrial GPS data, ___.", "geophysicists mapped micro-subsidence across the metropolitan aquifer", "micro-subsidence across the metropolitan aquifer was mapped by geophysicists", "the mapping of micro-subsidence across the aquifer was completed", "it became feasible to detect millimeter-scale ground displacement", "藉由將衛星雷達干涉測量技術與地面 GPS 實測數據深度結合，「地球物理學家繪製出了整個都會區含水層地表的微幅沉陷地圖」。", "By combining... 邏輯主詞必須是進行數據融合分析的科研人員「geophysicists」。", "方式介系詞邏輯主詞選 geophysicists。", "interferometry", "/ˌɪn.t̬ɚ.fəˈrɑː.mə.tri/", "干涉測量術干涉法", "subsidence", "/səbˈsaɪ.dəns/", "下沉沉陷地層下陷"),
        ("Widely revered for her impassioned advocacy of universal suffrage, ___.", "the pioneering orator addressed crowds of thousands across the industrial north", "crowds of thousands were addressed by the pioneering orator across the industrial north", "addresses were delivered to crowds of thousands across the industrial north", "the industrial north welcomed speeches by the pioneering orator", "因對普遍普選權的慷慨激昂倡議而廣受社會尊崇，「這位先驅女性演說家在北方工業城鎮向成千上萬的群眾發表了鼓舞人心的演說」。", "Widely revered... 邏輯主詞必須是受人景仰的演說家「the pioneering orator」。", "受人尊崇邏輯主詞選 the pioneering orator。", "revere", "/rɪˈvɪr/", "崇敬敬佩", "suffrage", "/ˈsʌf.rɪdʒ/", "投票權參政權"),
        ("While hiking across the subarctic tundra, ___.", "the field geologists stumbled upon fossilized Cretaceous tree stumps", "fossilized Cretaceous tree stumps were discovered by the field geologists", "the discovery of Cretaceous fossils surprised the field team", "it was possible to observe fossilized tree stumps scattered across the permafrost", "在徒步穿越亞北極苔原凍原帶時，「田野地質學家意外偶然發現了白堊紀樹樁的石化化石標本」。", "While hiking... 邏輯主詞為徒步健行的地質學家「the field geologists」。", "健行者邏輯主詞選 the field geologists。", "tundra", "/ˈtʌn.drə/", "苔原凍土帶", "stump", "/stʌmp/", "樹樁殘端")
    ]),
    # 12. Pronoun-Antecedent Clarity: Ambiguous Reference & Person/Number Agreement
    ("Pronoun-Antecedent Agreement", "學術思維", "C1-SAT12", [
        ("Each of the newly established botanical reserves maintains ___ own dedicated gene bank to safeguard rare orchid germplasm.", "its", "their", "they're", "it's", "每一處新設立的植物保護區均維持著「其」專屬獨立的基因庫，以全力捍衛珍稀蘭花的種原遺傳資源。", "主詞為代名詞 Each（單數），修飾 reserves，所有格需用第三人稱單數中性其 its。", "代名詞單複數一致：Each... maintains its own...", "germplasm", "/ˈdʒɝːm.plæz.əm/", "種原遺傳資源生殖質", "safeguard", "/ˈseɪf.ɡɑːrd/", "保衛捍衛"),
        ("The committee members debated the controversial conservation policy for hours before finally casting ___ votes.", "their", "its", "her", "his", "委員會全體委員在針對這項充滿爭議的生態保育政策進行了長達數小時的激烈辯論之後，最終投下了「他們自己的」神聖選票。", "主詞為 committee members（複數委員個體），代名詞所有格使用複數 their。", "複數代名詞所有格選 their votes。", "cast", "/kæst/", "投射投票拋擲", "controversial", "/ˌkɑːn.trəˈvɝː.ʃəl/", "爭議性的"),
        ("Neither the chief archivist nor the manuscript preservationists could conceal ___ astonishment when the missing illuminated codex was found.", "their", "its", "his", "her", "當那部失蹤已久的彩繪抄本被奇蹟般尋獲時，無論是首席檔案館長抑或是古籍修復師們，都無法掩飾「他們的」極度震驚。", "Neither... nor... 結構中代名詞參照與靠近的名詞 (preservationists, 複數) 一致，選 their。", "代名詞就近一致原則：preservationists 為複數，選 their。", "conceal", "/kənˈsiːl/", "隱藏掩蓋隱瞞", "codex", "/ˈkoʊ.deks/", "古代抄本古書手抄本"),
        ("Every mammalian species inhabiting the polar alpine zone has evolved specialized metabolic adaptations to protect ___ from freezing temperatures.", "itself", "themselves", "oneself", "themself", "棲息於極地高山帶的每一種哺乳動物物種，都演化出了專門的代謝適應機制來保護「自身」免於冰點低溫凍傷。", "主詞為 Every species（單數物種），反身代名詞使用單數 itself。", "單數物種反身代詞選 itself。", "mammalian", "/məˈmeɪ.li.ən/", "哺乳動物的", "metabolic", "/ˌmet̬.əˈbɑː.lɪk/", "新陳代謝的代謝的"),
        ("A researcher conducting fieldwork among remote pastoralist communities must respect ___ indigenous customs and pastoral traditions.", "their", "its", "his or her", "one's", "在偏遠游牧部落社群進行田野調查的研究人員，必須嚴格尊重「他們的/這些社群的」原住民傳統風俗與游牧生活慣例。", "代名詞指涉名詞 communities（複數），所有格使用 their。", "代名詞指涉複數名詞 communities 選 their。", "pastoralist", "/ˌpæs.tɚ.əl.ɪst/", "游牧民牧民田園詩人", "indigenous", "/ɪnˈdɪdʒ.ə.nəs/", "本土的原生的當地的"),
        ("Neither of the proposed urban transit models achieved ___ primary sustainability benchmarks during preliminary simulations.", "its", "their", "theirs", "it's", "在初步電腦模擬過程中，兩種擬議的城市大眾運輸模型均未能達到「各自的/其」首要永續指標基準。", "Neither 作代名詞指兩者皆非時在正式文法中作單數，所有格使用 its。", "Neither of + 複數名詞接單數代名詞 its。", "benchmark", "/ˈbentʃ.mɑːrk/", "基準檢驗標準", "simulation", "/ˌsɪm.jəˈleɪ.ʃən/", "模擬虛擬仿真"),
        ("The university faculty voted to revise ___ promotion and tenure guidelines to place greater emphasis on interdisciplinary scholarship.", "its", "their", "they're", "it's", "該大學全體教授團/全校教職員集體投票通過，決議修訂「其」升等與終身聘審查準則，以對跨領域學術研究給予更高重視。", "faculty 作整體單一機構法人時在美式英語中常視為單數集合名詞，所有格選 its。", "集合名詞整體概念選 its。", "tenure", "/ˈten.jɚ/", "終身教職任期享有權", "interdisciplinary", "/ˌɪn.t̬ɚˈdɪs.ə.plɪn.er.i/", "跨學科的跨領域的"),
        ("If a student wishes to apply for the prestigious Rhodes Scholarship, ___ must demonstrate exceptional academic distinction and moral leadership.", "he or she", "they", "one", "you", "若一名學生希望申請享有盛譽的羅德獎學金，「他或她」必須展現出卓越不凡的學術成就與道德領導才能。", "先行詞為單數 a student，正式學術書面語代名詞選 he or she（或在現代文法中接受 singular they，但 SAT 傳統標準答案優先考查性別對稱單數 he or she）。", "單數先行詞主格選 he or she。", "prestigious", "/presˈtɪdʒ.əs/", "享有盛譽的名門的", "distinction", "/dɪˈstɪŋk.ʃən/", "卓越區別殊榮"),
        ("Both the European Space Agency and NASA have pledged ___ joint support for the upcoming deep-space asteroid deflection mission.", "their", "its", "his", "theirs", "歐洲太空總署與美國國家航空暨太空總署雙方均已鄭重承諾，將對即將啟動的深太空小行星防禦偏轉任務提供「他們的」聯合支援。", "Both A and B 為複數主詞，代名詞所有格使用 their。", "複數代名詞所有格選 their。", "asteroid", "/ˈæs.tə.rɔɪd/", "小行星小行星體", "deflection", "/dɪˈflek.ʃən/", "偏斜偏轉偏轉防禦"),
        ("The international coalition reiterated ___ commitment to enforcing humanitarian maritime corridors in the conflict zone.", "its", "their", "they're", "theirs", "該國際聯盟再次重申「其」在衝突地區落實人道主義海上走廊倡議的堅定承諾。", "coalition（聯盟、同盟）為單數名詞，代名詞所有格使用 its。", "單數實體所有格選 its。", "coalition", "/ˌkoʊ.əˈlɪʃ.ən/", "聯盟同盟聯合政府", "humanitarian", "/hjuːˌmæn.ɪˈter.i.ən/", "人道主義的人道救援的")
    ]),
    # 13. Parallelism: Correlative Conjunctions
    ("Parallelism: Correlative Conjunctions", "學術思維", "C1-SAT13", [
        ("The environmental regulation aims not only to reduce harmful carbon emissions ___ the transition toward decentralized solar energy grids.", "but also to accelerate", "but also accelerating", "and to accelerate", "as well as accelerate", "該項環境保護法規的宗旨，不僅在於大幅降低有害的碳排放，「而且還在於加速」朝向分散式太陽能電網的綠能轉型。", "not only to reduce... 與 but also to accelerate... 形成嚴格的不定詞對稱平行結構。", "平行對稱結構：not only to V... but also to V...", "decentralized", "/diːˈsen.trə.laɪzd/", "分散式的去中心化的", "grid", "/ɡrɪd/", "電網格子網格"),
        ("The anthropological study examined neither the economic trade networks of the village ___ religious iconography.", "nor its", "or its", "nor it's", "and its", "該人類學研究既未深入探討該村落的經濟貿易網絡，「也未曾剖析其」宗教圖像學象徵涵義。", "neither... nor... 固定關聯連詞對稱搭配，選 nor its。", "關聯連詞固定搭配：neither... nor...", "iconography", "/ˌaɪ.kəˈnɑː.ɡrə.fi/", "圖像學符號象徵學", "anthropological", "/ˌæn.θrə.pəˈlɑː.dʒɪ.kəl/", "人類學的"),
        ("The computational model successfully predicted both the trajectory of the asteroid ___ diameter within a ten-meter margin of error.", "and its", "as well as its", "along with its", "but also its", "該電腦計算模型成功預測了這顆小行星的運行軌道，「以及其」直徑大小（誤差範圍在十公尺以內）。", "both A and B 固定搭配，兩者均為名詞片語對稱，選 and its。", "固定關聯搭配：both A and B。", "trajectory", "/trəˈdʒek.tɚ.i/", "軌道軌跡飛行路線", "margin of error", "/ˌmɑːr.dʒɪn əv ˈer.ɚ/", "誤差範圍容許誤差"),
        ("The Renaissance treatise was celebrated whether for its revolutionary perspective techniques ___ mastery of classical anatomy.", "or for its", "and for its", "nor for its", "as well as", "這部文藝復興時期的專著備受讚譽，無論是因為其革命性的透視畫法技巧，「抑或是因為其對」古典解剖學的爐火純青掌握。", "whether for A or for B 介系詞片語嚴格對稱，選 or for its。", "平行對稱結構：whether for... or for...", "perspective", "/pɚˈspek.tɪv/", "透視法透視觀點", "anatomy", "/əˈnæt̬.ə.mi/", "解剖學骨骼構造"),
        ("The university committee evaluated the candidate not simply based on her publication volume ___ impact of her theoretical innovations.", "but also on the", "and on the", "but on the", "as well as", "大學評審委員會評估該候選人時，不僅僅根據其學術論文的發表數量，「而且還深入考量了其」理論創新所帶來的實質深遠衝擊影響力。", "not simply based on A but also on B 介系詞片語平行對稱，選 but also on the。", "對稱結構：not simply on A but also on B。", "theoretical", "/ˌθiː.əˈret̬.ɪ.kəl/", "理論的理論上的", "evaluation", "/ɪˌvæl.juˈeɪ.ʃən/", "評估評價考評"),
        ("The architectural design was lauded not only for its aesthetic minimalism ___ environmental sustainability in harsh desert climates.", "but also for its", "and also for", "but for its", "as well as", "該建築設計備受讚譽，不僅因其美學上的極簡主義風格，「而且也因其在」嚴酷沙漠氣候條件下所展現之環境永續性。", "not only for A but also for B 形成介系詞片語完美對稱，選 but also for its。", "平行對稱選 but also for its。", "aesthetic", "/esˈθet̬.ɪk/", "美學的美感的美術的", "minimalism", "/ˈmɪn.ə.məl.ɪ.zəm/", "極簡主義簡約風格"),
        ("The clinical researchers sought either to synthesize a novel antiviral compound ___ existing therapeutic inhibitors.", "or to optimize", "and to optimize", "or optimizing", "and optimizing", "臨床科研人員力求要麼人工合成出一種全新的抗病毒化合物，「要麼對」現有之抗病毒治療抑制劑進行最佳化改良。", "either to V or to V 不定詞嚴格平行對稱，選 or to optimize。", "不定詞平行對稱：either to V or to V。", "therapeutic", "/ˌθer.əˈpjuː.tɪk/", "治療的療效的", "inhibitor", "/ɪnˈhɪb.ə.t̬ɚ/", "抑制劑阻滯劑"),
        ("The museum curator organized the retrospective so as to highlight both the artist's early expressionist paintings ___ bronze sculptures from his final decades.", "and his late", "as well as late", "and also his late", "together with his", "美術館策展人精心籌備這場回顧展，旨在同時重點突顯該藝術家早期的表現主義畫作，「以及其」晚年最後數十年間所創作的青銅雕塑精品。", "both A and B 名詞短語嚴格對稱，選 and his late。", "名詞短語對稱：both the paintings and his sculptures。", "expressionist", "/ɪkˈspreʃ.ən.ɪst/", "表現主義的表現派的", "retrospective", "/ˌret.rəˈspek.tɪv/", "回顧展追溯的"),
        ("The historian argued that the ancient dynasty fell not because of barbarian invasions ___ severe prolonged drought and internal court corruption.", "but because of", "and because of", "but on account of", "rather due to", "該歷史學家主張，該古老王朝的覆亡並非因為蠻族外患入侵，「而是因為」持續多年的嚴重乾旱災異以及朝廷內部的貪腐潰爛。", "not because of A but because of B 原因介系詞短語嚴格對稱，選 but because of。", "原因介系詞短語對稱：not because of A but because of B。", "barbarian", "/bɑːrˈber.i.ən/", "野蠻人的異族的蠻族", "prolonged", "/prəˈlɑːŋd/", "持久的長期長年的"),
        ("The aerospace engineer confirmed that the spacecraft would neither exceed maximum launch mass ___ thermal thresholds during atmospheric reentry.", "nor violate", "or violate", "nor violating", "and violate", "航太工程師證實，該太空載具在重返大氣層階段，既不會超過最大發射質量上限，「也不會違背」防熱隔熱系統的耐熱極限值門檻。", "neither V nor V 原形動詞平行對稱，選 nor violate。", "動詞平行對稱：neither exceed... nor violate...", "reentry", "/riːˈen.tri/", "再入重返大氣層", "threshold", "/ˈθreʃ.hoʊld/", "門檻臨界點")
    ])
]
