# scripts/diag_builders/tier6_part2_data.py
# Subtopics 14-25 for Tier 6 (Digital SAT C1, IDs 1381-1500)

subtopics_14_to_25 = [
    # 14. Parallelism: Comparative Constructions (that of, those of, compared with)
    ("Parallelism: Comparative Constructions", "學術思維", "C1-SAT14", [
        ("The tensile strength of spider dragline silk is vastly superior to ___ synthetic nylon polymers.", "that of", "those of", "these of", "them of", "蜘蛛拖絲的抗拉抗張強度，遠遠優於「合成尼龍聚合物的抗拉強度」。", "比較對象平行對稱：比較的是 tensile strength（不可數單數名詞），使用代名詞 that of 替代，避免不當比較。", "比較級代名詞單數替代選 that of。", "tensile", "/ˈten.saɪl/", "張力的抗拉的", "dragline", "/ˈdræɡ.laɪn/", "拖絲蜘蛛牽引絲"),
        ("The acoustic adaptations of nocturnal barn owls are far more sophisticated than ___ diurnal raptors.", "those of", "that of", "which of", "them of", "夜行性倉鴞的聽覺聲學適應構造，遠比「晝行性猛禽的聽覺適應構造」更為複雜精妙。", "比較對象為複數名詞 acoustic adaptations，使用 those of 替代以維持嚴格對稱。", "比較級代名詞複數替代選 those of。", "diurnal", "/daɪˈɝː.nəl/", "晝行性的白晝的", "raptor", "/ˈræp.tɚ/", "猛禽肉食鳥類"),
        ("The carbon sequestration potential of coastal salt marshes exceeds ___ terrestrial boreal forests.", "that of", "those of", "them of", "this of", "沿海鹽沼濕地的碳封存潛力，超越了「內陸北方森林的碳封存潛力」。", "比較核心名詞為單數 sequestration potential，使用代名詞 that of 替代。", "比較級單數替代選 that of。", "sequestration", "/ˌsiː.kwesˈtreɪ.ʃən/", "封存隔離沒收", "boreal", "/ˈbɔːr.i.əl/", "北方的北極的"),
        ("The ceramic artifacts excavated at the Mohenjo-daro site exhibit glazing techniques comparable to ___ ancient Mesopotamian kilns.", "those of", "that of", "them of", "these of", "在摩亨佐-達羅遺址挖掘出土的陶器文物，展現出了堪與「古代美索不達米亞窯爐的施釉技藝」相媲美的精湛釉彩工藝。", "比較對象為複數名詞 glazing techniques，使用 those of 替代。", "複數比較替代選 those of。", "glazing", "/ˈɡleɪ.zɪŋ/", "上釉釉料裝玻璃", "kiln", "/kɪln/", "窯窯爐"),
        ("The orbital eccentricity of Pluto is considerably greater than ___ the eight major planets.", "that of", "those of", "which of", "this of", "冥王星的軌道離心率偏心率，顯著大於「太陽系八大行星的軌道偏心率」。", "比較對象為單數名詞 orbital eccentricity，使用 that of 替代。", "單數名詞比較替代選 that of。", "eccentricity", "/ˌek.senˈtrɪs.ə.t̬i/", "偏心率古怪離心率", "orbital", "/ˈɔːr.bɪ.t̬əl/", "軌道的軌跡的"),
        ("The wing pigmentation patterns of female monarch butterflies are often darker than ___ male counterparts.", "those of their", "that of their", "them of their", "which of their", "雌性黑脈金斑蝶的翅膀色素花紋，往往比「雄性個體的翅膀花紋」色澤更深。", "比較對象為複數名詞 wing pigmentation patterns，使用 those of their 替代。", "複數花紋比較選 those of their。", "pigmentation", "/ˌpɪɡ.mənˈteɪ.ʃən/", "色素沉著色澤", "counterpart", "/ˈkaʊn.t̬ɚ.pɑːrt/", "對應物相對應的人或事物"),
        ("The energy consumption of quantum annealing processors is fractionally lower than ___ classical supercomputers.", "that of", "those of", "them of", "which of", "量子退火處理器的整體能源消耗量，僅為「傳統超級電腦能耗」的極微小一部分。", "比較對象為不可數單數名詞 energy consumption，選 that of 替代。", "單數不可數代詞比較選 that of。", "annealing", "/əˈniː.lɪŋ/", "退火韌化退火算法", "fractionally", "/ˈfræk.ʃən.əl.i/", "微小地極少地"),
        ("The linguistic structures of Indigenous Amazonian languages differ markedly from ___ Indo-European origins.", "those of", "that of", "which of", "these of", "亞馬遜原住民族語言的語言學語法結構，顯著迥異於「印歐語系起源之語言的語法結構」。", "比較對象為複數名詞 linguistic structures，使用 those of 替代。", "複數結構比較選 those of。", "linguistic", "/lɪŋˈɡwɪs.tɪk/", "語言學的語言的", "markedly", "/ˈmɑːr.kɪd.li/", "顯著地明顯地"),
        ("The photosynthetic efficiency of C4 grasses in arid regions is substantially higher than ___ temperate C3 vegetation.", "that of", "those of", "them of", "this of", "乾旱地區 C4 禾本科植物的光合作用轉化效率，大幅顯著高於「溫帶 C3 植被的光合效率」。", "比較對象為單數名詞 photosynthetic efficiency，使用 that of 替代。", "單數效率比較選 that of。", "photosynthetic", "/ˌfoʊ.t̬oʊ.sɪnˈθet̬.ɪk/", "光合作用的光合的", "arid", "/ˈer.ɪd/", "乾旱的貧瘠的"),
        ("The legal doctrines of common law jurisdictions rely on judicial precedent to an extent far greater than ___ civil law codes.", "that of", "those of", "which of", "them of", "普通法法域的法律學說體系對司法判例的仰賴程度，遠遠超越了「大陸法系法典對判例的依賴程度」。", "比較對象為 an extent（程度，單數），使用 that of 替代以維持嚴格對稱。", "抽象程度單數比較選 that of。", "doctrine", "/ˈdɑːk.trɪn/", "學說教義法理", "precedent", "/ˈpres.ə.dent/", "先例判例判決先例")
    ]),
    # 15. Subjunctive & Conditional Moods in Formal Academic Prose
    ("Subjunctive & Conditional Moods", "學術思維", "C1-SAT15", [
        ("The ethics review board mandated that the clinical research team ___ all patient data prior to publication.", "anonymize", "anonymizes", "anonymized", "would anonymize", "倫理審查委員會強制要求，臨床科研團隊在發表論文之前必須將所有病患數據「全面進行匿名化處理」。", "mandate that 後接虛擬語氣從句，謂語動詞省略 should，一律使用原形動詞 anonymize。", "命令要求動詞虛擬語氣：that S + (should) + V原形。", "anonymize", "/əˈnɑː.nə.maɪz/", "使匿名進行匿名化處理", "mandate", "/ˈmæn.deɪt/", "命令授權強制要求"),
        ("The international treaty stipulates that each signatory nation ___ an independent oversight agency to monitor carbon emissions.", "establish", "establishes", "established", "would establish", "該國際條約明文規定，各簽署締約國必須「設立」一個獨立的監管機構來監測碳排放量。", "stipulate that 後接虛擬語氣從句，使用動詞原形 establish。", "條約法規要求從句動詞原形選 establish。", "signatory", "/ˈsɪɡ.nə.tɔːr.i/", "簽署國簽約方", "stipulate", "/ˈstɪp.jə.leɪt/", "約定明定載明"),
        ("Had the structural engineers ___ the dynamic wind resonance of the suspension bridge, the catastrophic oscillation could have been prevented.", "anticipated", "anticipate", "anticipates", "anticipating", "假若結構工程師當時「有預先料想到」懸索吊橋的動態風共振效應，那場災難性的劇烈晃動坍塌原本是可以防範避免的。", "Had S p.p. 倒裝虛擬假設，助動詞 Had 置於句首，動詞使用過去分詞 anticipated。", "Had S + p.p. 倒裝結構選 anticipated。", "resonance", "/ˈrez.ən.əns/", "共振共鳴回響", "oscillation", "/ˌɑː.səˈleɪ.ʃən/", "振盪擺動波動"),
        ("It is imperative that the lead archaeologist ___ immediate protective measures to prevent looters from desecrating the freshly uncovered necropolis.", "institute", "institutes", "instituted", "would institute", "當務之急是，首席考古學家必須立即「推行施行」緊急保護措施，以防盜墓者褻瀆破壞新出土的古代大墓地。", "It is imperative that 後接虛擬語氣，謂語動詞使用原形 institute。", "It is imperative that + V原形選 institute。", "imperative", "/ɪmˈper.ə.t̬ɪv/", "極其重要的當務之急的", "necropolis", "/neˈkrɑː.pəl.ɪs/", "大墓地古墓群"),
        ("Were the global mean temperature ___ by three degrees Celsius, polar ice sheets would experience irreversible collapse.", "to rise", "rose", "rises", "rising", "假若未來全球平均氣溫「萬一攀升」攝氏三度，極地冰原將遭遇不可逆轉的全面崩潰。", "Were S to V (表對未來極小可能實現的假設倒裝)，選 to rise。", "未來假設倒裝：Were S to V 選 to rise。", "mean", "/miːn/", "平均的平均值", "irreversible", "/ˌɪr.əˈvɝː.sə.bəl/", "不可逆的無法挽回的"),
        ("The university provost recommended that tenure criteria ___ to account for open-access digital scholarship.", "be expanded", "is expanded", "was expanded", "expands", "大學教務長提出建言，建議將終身教職評審標準予以「擴充擴展」，以將開放取用的數位學術成果納入考量。", "recommend that 後接被動虛擬語氣：(should) be expanded。", "被動虛擬語氣選 be expanded。", "provost", "/ˈproʊ.voʊst/", "教務長大學主管", "open-access", "/ˌoʊ.pənˈæk.ses/", "開放獲取的開放取用的"),
        ("If historical records ___ that the monarch signed the abdication proclamation under duress, contemporary legal interpretations would be fundamentally altered.", "were to confirm", "confirmed", "confirm", "confirms", "假若未來出土的歷史文獻檔案「果真證實」該君王是在遭受脅迫逼迫下簽署退位詔書，當代法學界之解釋將被從根本上徹底顛覆。", "對未來純理論假設：were to confirm 表假若萬一發生。", "假設語氣選 were to confirm。", "abdication", "/ˌæb.dəˈkeɪ.ʃən/", "退位放棄職權", "duress", "/duːˈres/", "脅迫強迫強壓"),
        ("The biosafety protocol insists that laboratory researchers ___ personal protective gear before entering the biocontainment facility.", "don", "dons", "donned", "would don", "生物安全協定規程嚴正堅持要求，實驗室科研人員在進入生物防護隔離設施之前，必須「穿戴妥當」個人安全防護裝備。", "insist that 後接原形動詞 don（穿上、配戴）。", "動詞原形選 don（穿戴）。", "don", "/dɑːn/", "穿上披上配戴", "biocontainment", "/ˌbaɪ.oʊ.kənˈteɪn.mənt/", "生物遏制生物防護"),
        ("Had the spacecraft’s heat shield ___ during atmospheric descent, the astronauts would have perished in the inferno.", "failed", "fail", "fails", "failing", "假若該太空飛船的防熱盾在重返大氣層下降期間「萬一不幸失效」，全體太空人早就喪生在漫天烈焰之中了。", "Had S p.p. 過去假設倒裝句，選 failed。", "過去虛擬倒裝選 Had S failed。", "inferno", "/ɪnˈfɝː.noʊ/", "地獄大火火海", "descent", "/dɪˈsent/", "下降血統世系"),
        ("It is crucial that each member of the field expedition ___ well-supplied with water filtration tablets before venturing into the desert.", "remain", "remains", "remained", "will remain", "至關緊要的是，野外考察隊的每一位隊員在踏入荒漠之前，都必須「始終備齊」充足的水質過濾淨水藥片。", "It is crucial that S + (should) remain 原形動詞。", "虛擬語氣原形動詞選 remain。", "filtration", "/fɪlˈtreɪ.ʃən/", "過濾濾過", "venture", "/ˈven.tʃɚ/", "冒險前往涉足冒險事業")
    ]),
    # 16. Central Ideas & Primary Thematic Claims in Scholarly Texts
    ("Central Ideas & Thematic Claims", "學術思維", "C1-SAT16", [
        ("The following text is adapted from a scholarly essay on Renaissance courtly culture. Which choice best states the main idea of the text? \nBaldassare Castiglione’s *The Book of the Courtier* (1528) famously introduced the concept of *sprezzatura*—a calculated nonchalance designed to conceal the immense effort underlying athletic and social accomplishments. While twentieth-century critics frequently dismissed this posture as mere superficial vanity, recent cultural historians have recognized *sprezzatura* as an indispensable survival mechanism in the treacherous, hyper-competitive courts of early modern Italy.", "Recent historical reassessments view *sprezzatura* not as trivial superficiality, but as an essential political and social survival strategy in Renaissance courts.", "*The Book of the Courtier* was primarily composed as an athletic training manual for young Italian aristocrats.", "Twentieth-century scholars correctly determined that Castiglione's philosophical theories lacked practical utility.", "Italian courtly life in the sixteenth century was devoid of political intrigue and social competition.", "閱讀文本總結中心論點：文本指出二十世紀評論家曾將其視為虛榮，但近期文化史學家體認到它是文藝復興危險宮廷中不可或缺的生存機制。", "主旨題：對比傳統誤解，點出當代重新評估的核心論點 (survival strategy)。", "主旨句精準涵蓋歷史重估與生存策略。", "nonchalance", "/ˌnɑːn.ʃəˈlɑːns/", "若無其事冷靜漠不關心", "treacherous", "/ˈtretʃ.ɚ.əs/", "危險陰險的背信棄義的"),
        ("The following text discusses deep-sea hydrothermal ecosystems. Which choice best states the primary claim of the author? \nFor decades, marine biologists operated under the assumption that all terrestrial and aquatic food webs were anchored exclusively in solar-driven photosynthesis. However, the 1977 discovery of chemosynthetic bacterial colonies at the Galapagos Rift disproved this dogma. By utilizing hydrogen sulfide emitted from geothermal vents to synthesize organic matter, these extremophiles proved that complex multicellular ecosystems can thrive in perpetual darkness without sunlight.", "Hydrothermal vent ecosystems demonstrated that biological life can sustain complex food webs independently of solar energy through chemosynthesis.", "Photosynthesis remains the only viable energetic mechanism capable of sustaining marine fauna.", "Hydrogen sulfide is an inherently toxic compound that precludes the development of multicellular life.", "Deep-sea ecosystems were first identified in the Atlantic Ocean during the early nineteenth century.", "文本主要主張：地熱噴口生態系統證明了生物生命能完全獨立於太陽能之外，透過化能合成作用維持複雜食物網。", "主旨主張題：打破光合作用唯一論，確立化能合成自主支撐食物網地位。", "主旨選項直擊 independent of solar energy 核心。", "chemosynthetic", "/ˌkiː.moʊ.sɪnˈθet̬.ɪk/", "化能合成的", "dogma", "/ˈdɑːɡ.mə/", "教條信條教理"),
        ("Which choice best summarizes the central argument of the historian regarding the printing press? \nWhile popular history credits Johannes Gutenberg's movable type printing press with instantaneously igniting the Protestant Reformation, archival evidence suggests a far more gradual transformation. For the first four decades following its invention, European presses predominantly manufactured traditional Latin liturgical texts and papal indulgences, reinforcing orthodox Catholic ecclesiastical authority rather than destabilizing it.", "The initial deployment of the printing press initially bolstered orthodox religious institutions rather than sparking immediate cultural upheaval.", "Gutenberg's invention was immediately adopted across Europe to challenge papal authority.", "The Protestant Reformation emerged entirely independent of changes in printing technology.", "The printing press was banned by European authorities for several decades after its introduction.", "文本論述主旨：古騰堡印刷術在發明初期的前四十年主要印製天主教拉丁文宗教經卷與贖罪券，鞏固了天主教正統權威，而非立即引發顛覆變革。", "主旨論點：印刷術最初被用以支持舊有宗教建制 (bolstered orthodox institutions)。", "主旨選項精準概括 initial deployment bolstered orthodox authority。", "liturgical", "/lɪˈtɝː.dʒɪ.kəl/", "禮拜儀式的宗教儀式的", "indulgence", "/ɪnˈdʌl.dʒəns/", "贖罪券放任沉溺"),
        ("Which choice best expresses the main theme of the literary critique? \nIn Mary Shelley’s *Frankenstein*, the creature’s tragic trajectory is not preordained by inherent biological malevolence; rather, his destructive fury is systematically provoked by universal human revulsion and profound social ostracism. Shelley’s gothic masterpiece thus operates as a poignant indictment of a society that judges morality solely through the superficial prism of physical aesthetics.", "The creature's violence in *Frankenstein* is a tragic consequence of societal cruelty and physical prejudice rather than innate depravity.", "Mary Shelley argued that scientific innovation inevitably leads to monstrous ethical catastrophes.", "The novel depicts the creature as an inherently evil being incapable of emotional vulnerability.", "Nineteenth-century British society universally embraced individuals who exhibited anatomical differences.", "文評核心觀點：怪物的毀滅性暴怒是由人類的排斥與社會放逐所系統性誘發，小說批判了以貌取人的社會殘酷。", "主旨句：悲劇根源在於社會殘酷與外貌偏見 (societal cruelty and physical prejudice)。", "主旨選項精準歸納 consequence of societal cruelty rather than innate depravity。", "ostracism", "/ˈɑː.strə.sɪz.əm/", "排斥排擠放逐", "malevolence", "/məˈnev.əl.əns/", "惡意怨恨狠毒"),
        ("Which choice best captures the central premise of the economic study? \nUrban economists have long debated whether high housing costs in major metropolitan hubs restrict regional economic dynamism. Examining thirty years of municipal labor data, Dr. Sarah Rossi demonstrates that prohibitive housing prices directly choke off internal geographic mobility. Workers can no longer afford to migrate to high-productivity cities, thereby dampening national aggregate productivity and exacerbating regional economic divergence.", "Exorbitant urban housing costs diminish overall national economic productivity by restricting the geographic mobility of labor.", "High-productivity cities automatically experience lower housing costs due to increased supply.", "Internal migration in modern economies has accelerated irrespective of local residential real estate costs.", "Regional economic divergence is solely caused by international trade imbalances rather than domestic factors.", "經濟學論文核心前提/主旨：都會區高昂房價阻礙了勞動力的地理流動性，進而抑制了國家總體生產力並加劇區域分化。", "主旨：高房價阻礙勞動力流動並損害總體生產力 (diminish productivity by restricting mobility)。", "主旨選項對應 Exorbitant housing costs diminish productivity...", "exorbitant", "/ɪɡˈzɔːr.bə.t̬ənt/", "過高的過分的昂貴的", "dampen", "/ˈdæm.pən/", "抑制減緩弄濕使沮喪")
    ]),
    # 17. Textual Evidence: Supporting or Undermining Scientific Hypotheses
    ("Textual Evidence: Hypotheses Support/Weaken", "學術思維", "C1-SAT17", [
        ("Paleoclimatologists hypothesize that a sudden injection of freshwater into the North Atlantic disrupted the Atlantic Meridional Overturning Circulation (AMOC) 8,200 years ago, triggering widespread Northern Hemisphere cooling. Which finding, if true, would most strongly support this hypothesis?", "Sediment cores from the North Atlantic dated to 8,200 years ago show massive meltwater deposits coinciding precisely with a sharp decline in deep-ocean nutrient ventilation.", "Fossilized pollen records indicate that tropical rainforests in South America expanded significantly during this period.", "Ice cores from Antarctica show a simultaneous period of anomalous warming across the Southern Ocean.", "Volcanic ash layers in Greenland ice sheets confirm a massive caldera eruption occurred exactly 8,200 years ago.", "哪一項發現最能強烈支持「淡水注入北大西洋阻斷大西洋經向翻轉環流 (AMOC) 導致冷卻」之假說？若北大西洋沉積物岩芯顯示在 8200 年前有大規模融水沉積且精準伴隨深海養分翻轉環流的驟降，則最直接支持環流受阻。", "支持假說題：需直接提供北大西洋淡水融水注入與深海洋流停滯之同步物質證據。", "核心支持證據選項含 meltwater deposits coinciding with decline in ocean ventilation。", "meridional", "/məˈrɪd.i.ən.əl/", "經向的子午線的", "ventilation", "/ˌven.t̬əlˈeɪ.ʃən/", "通風換氣深海流體交換"),
        ("Behavioral ecologists hypothesize that the intricate nocturnal bioluminescent flashes of *Photinus* fireflies function exclusively as species-specific courtship signals rather than predatory deterrents. Which observation, if true, would most directly undermine the researchers' hypothesis?", "Predatory nocturnal spiders and bats consistently avoid capturing *Photinus* fireflies as soon as the insects emit rhythmic bioluminescent flashes.", "Male and female *Photinus* fireflies exhibit distinct, highly coordinated pulse intervals during mating displays.", "Females of the genus *Photinus* remain perched motionless on foliage while signaling to patrolling males.", "Bioluminescent flash duration varies predictably with ambient nocturnal temperature fluctuations.", "哪項發現最直接「削弱/駁斥 (undermine)」研究人員「發光純粹是求偶信號而非防禦捕食者」之假說？若夜間捕食者蜘蛛和蝙蝠一看到發光就主動放棄捕食，直接證明其具有防禦捕食功能，駁斥了「純求偶」假說！", "削弱假說題：反駁 exclusively courtship，證明捕食者主動避開 (avoid capturing) 發光昆蟲。", "削弱證據選項：Predatory nocturnal spiders and bats avoid capturing upon flashes。", "bioluminescent", "/ˌbaɪ.oʊˌluː.məˈnes.ənt/", "生物發光的", "courtship", "/ˈkɔːrt.ʃɪp/", "求偶求愛求偶期"),
        ("Archaeologists hypothesize that the rapid abandonment of the Ancestral Puebloan settlement at Sand Canyon in the late thirteenth century was driven primarily by resource depletion resulting from an epic megadrought. Which discovery, if true, would most strongly support this hypothesis?", "Tree-ring dendrochronological analysis reveals decades of unprecedentedly severe regional drought beginning in 1276, coinciding with zooarchaeological evidence of severe malnutrition and skeletal stress.", "Ceramic artifacts found within the pueblo display intricate geometric iconography derived from neighboring Mesa Verde cultures.", "The structural masonry of Sand Canyon Pueblo exhibits defensive ramparts and towers erected along the canyon rim.", "Pollen samples show that domesticated maize continued to flourish in riverine valley bottoms throughout the fourteenth century.", "哪項發現最支持「特大乾旱導致資源枯竭促成遺址廢棄」假說？樹木年輪年代學揭露 1276 年起發生史無前例乾旱，且伴隨動物考古學遺存與骨骼嚴重營養不良之直接證據。", "支持氣候乾旱致廢棄假說：乾旱年代 (dendrochronological drought) + 人體骨骼營養不良 (malnutrition)。", "支持證據選項結合年輪乾旱與營養不良骸骨證據。", "dendrochronological", "/ˌden.droʊˌkrɑː.nəˈlɑː.dʒɪ.kəl/", "樹木年代學的樹輪學的", "malnutrition", "/ˌmæl.nuːˈtrɪʃ.ən/", "營養不良營養失調"),
        ("Cognitive linguists hypothesize that bilingual children develop superior executive inhibitory control compared to monolingual peers because they must constantly suppress an inactive language. Which result, if true, would most directly weaken the linguists' hypothesis?", "Bilingual and monolingual children perform identically on non-verbal Stroop interference and sorting tasks when controlling for socioeconomic status.", "Neuroimaging scans show heightened activation in the dorsolateral prefrontal cortex during language switching.", "Bilingual children acquire vocabulary in each language at a slightly slower pace during early toddlerhood.", "Monolingual children exhibit greater neural plasticity when exposed to novel phonemic contrasts.", "哪項發現最能「削弱 (weaken)」雙語兒童因抑制非活躍語言而發展出更卓越執行抑制控制能力的假說？若在控制社會經濟地位後，雙語與單語兒童在非語言干擾篩選任務上的表現「完全相同無差異」，則假說被直接削弱！", "削弱假說：證明雙語與單語在抑制控制上 perform identically（表現毫無差異）。", "削弱選項指出兩者在抑制控制測試上 perform identically。", "inhibitory", "/ɪnˈhɪb.ə.tɔːr.i/", "抑制的抑制性的", "monolingual", "/ˌmɑː.nəˈlɪŋ.ɡwəl/", "單語的單一語言的"),
        ("Astrophysicists hypothesize that the ultra-diffuse galaxy Dragonfly 44 is composed almost entirely of dark matter, with baryonic stars making up less than one percent of its total gravitational mass. Which observation, if confirmed, would most strongly support this hypothesis?", "The velocity dispersion of stars within Dragonfly 44 is exceptionally high, requiring immense invisible mass to prevent the galaxy from flying apart.", "High-resolution optical spectroscopy indicates that the stars in Dragonfly 44 are predominantly ancient, metal-poor red giants.", "Radio telescopes failed to detect neutral hydrogen emission lines within the interstellar medium of Dragonfly 44.", "Dragonfly 44 exhibits a regular, symmetrical elliptical morphology devoid of active star-forming regions.", "哪項觀測最能強烈支持 Dragonfly 44 幾乎全由暗物質組成的假說？星系內部恆星的速度瀰散度異常之高，必須有龐大不可見的暗物質質量才能提供足夠引力防止其四散瓦解！", "支持暗物質主導假說：恆星速度瀰散度極高 (velocity dispersion exceptionally high)，必須依賴隱形質量約束。", "天體物理支持選項：velocity dispersion requiring immense invisible mass。", "dispersion", "/dɪˈspɝː.ʒən/", "瀰散色散離散", "baryonic", "/ˌber.iˈɑː.nɪk/", "重子的常規物質的")
    ]),
    # 18. Quantitative Literacy: Interpreting Empirical Tables, Charts & Data Trends
    ("Quantitative Literacy: Data Trends", "學術思維", "C1-SAT18", [
        ("A research team measured the photosynthetic rate (micromoles of CO2 per square meter per second) of two crop species under varying ambient CO2 concentrations (parts per million, ppm). At 400 ppm, Crop A assimilated 22.4 units while Crop B assimilated 31.2 units. At 800 ppm, Crop A's assimilation rose to 38.6 units, whereas Crop B's assimilation increased only marginally to 33.1 units. Which choice best reflects the data presented?", "While Crop B exhibited superior photosynthetic assimilation at ambient atmospheric CO2 levels, Crop A demonstrated significantly greater responsiveness to elevated CO2 concentrations.", "Crop A outperformed Crop B across all tested carbon dioxide concentrations.", "Elevated carbon dioxide levels universally inhibited the photosynthetic assimilation rates of both tested crops.", "Crop B's photosynthetic assimilation rate doubled when the ambient concentration rose from 400 to 800 ppm.", "數據解讀：在 400 ppm 常態下，作物 B (31.2) 高於作物 A (22.4)；但在 800 ppm 高碳下，作物 A 激增至 38.6，而作物 B 僅微增至 33.1。因此作物 B 在常態下較佳，但作物 A 對高濃度 CO2 反應敏感度顯著更強。", "圖表數據綜合對比：常態 B 勝出，高碳 A 增幅巨大 (greater responsiveness)。", "數據對比選項精準反映 Crop B superior at ambient, Crop A greater responsiveness elevated。", "assimilate", "/əˈsɪm.ə.leɪt/", "吸收同化吸收轉化", "marginally", "/ˈmɑːr.dʒɪ.nəl.i/", "微小地勉強地邊際上"),
        ("Ecologists monitored the breeding pairs of three raptor species in a national park between 2010 and 2020: Osprey populations grew from 14 to 42 pairs; Peregrine Falcons grew from 6 to 18 pairs; Golden Eagles fluctuated between 8 and 10 pairs throughout the decade. Which claim is most directly supported by the data?", "While Osprey and Peregrine Falcon populations both tripled over the decade, the Golden Eagle population exhibited relative demographic stability.", "Golden Eagle populations experienced rapid demographic expansion exceeding that of Peregrine Falcons.", "Osprey populations declined precipitously following habitat fragmentation after 2015.", "All three surveyed raptor species exhibited linear demographic declines across the ten-year monitoring period.", "數據統計分析：魚鷹從 14 增至 42 對（增為三倍）；遊隼從 6 增至 18 對（增為三倍）；金雕則在 8 至 10 對間小幅浮動。因此魚鷹與遊隼皆成長三倍，而金雕族群維持相對穩定。", "數據分析題：14->42 (3倍), 6->18 (3倍), 8-10 (穩定)。選項完整囊括這兩項趨勢。", "數據結論選項：both tripled over the decade, Golden Eagle demographic stability。", "raptor", "/ˈræp.tɚ/", "猛禽猛禽類", "precipitously", "/prɪˈsɪp.ə.t̬əs.li/", "陡峭地險峻地急遽地"),
        ("Materials scientists measured the electrical resistivity (nano-ohm-meters) of four experimental copper alloys at 293 Kelvin: Alloy W registered 18.2; Alloy X registered 24.5; Alloy Y registered 16.8; Alloy Z registered 31.0. Lower resistivity indicates superior electrical conductivity. Which alloy is the most efficient electrical conductor?", "Alloy Y", "Alloy W", "Alloy X", "Alloy Z", "圖表數據逆向理解：電阻率 (resistivity) 越低代表導電性 (conductivity) 越高。數值最低者為 Alloy Y (16.8)，因此 Alloy Y 導電效能最佳。", "科學概念與數據對應：電阻率最低 = 導電性最佳。選數值最小者 Alloy Y。", "數據最小值判定選 Alloy Y (16.8)。", "resistivity", "/ˌriː.zɪsˈtɪv.ə.t̬i/", "電阻率電阻係數", "conductivity", "/ˌkɑːn.dʌkˈtɪv.ə.t̬i/", "傳導性導電率"),
        ("A marine survey documented coral bleaching prevalence across four reef sectors following a marine heatwave: Northern Sector (78% bleached), Central Sector (54% bleached), Southern Sector (22% bleached), Offshore Sector (12% bleached). Which statement is accurately substantiated by the survey findings?", "Bleaching severity demonstrated a pronounced inverse relationship with offshore proximity, and the Northern Sector was the most severely impacted.", "The Southern Sector exhibited the highest overall coral mortality rate among all surveyed zones.", "Offshore reefs experienced greater thermal stress and subsequent bleaching than inshore northern reefs.", "All four reef sectors suffered uniform coral bleaching rates exceeding fifty percent.", "數據規律概括：北部白化率最高 (78%)，中央 54%，南部 22%，離岸最低僅 12%。因此北部受創最重，且距離離岸越遠（近岸北部）白化越嚴重。", "數據趨勢：Northern Sector most severely impacted (78%)，且越向離岸越低。", "數據總結選項：Northern Sector most severely impacted...", "prevalence", "/ˈprev.əl.əns/", "普及盛行發生率", "substantiate", "/səbˈstæn.ʃi.eɪt/", "證實證明充實"),
        ("An archaeological dig classified recovered potsherds by temper material across three chronological strata: Layer 1 (early) contained 85% shell-tempered and 15% sand-tempered sherds; Layer 2 (middle) contained 50% of each; Layer 3 (late) contained 10% shell-tempered and 90% sand-tempered sherds. Which conclusion is most warranted by the stratigraphy?", "The artisans transitioned decisively from shell-tempered to sand-tempered ceramic fabrication methods over time.", "Sand-tempering was the primary ceramic technology utilized during the earliest settlement phase.", "Shell-tempered pottery completely disappeared prior to the deposition of Layer 2.", "Potsherd frequency decreased progressively across successive chronological strata.", "地層學數據時序趨勢分析：Layer 1 (85% 貝殼 -> 15% 砂) -> Layer 2 (各50%) -> Layer 3 (10% 貝殼 -> 90% 砂)。顯示工匠隨時間推移，製作工藝明顯由貝殼夾砂轉向砂質夾砂。", "年代時序數據趨勢：隨時間由 shell 轉向 sand (transitioned decisively)。", "趨勢結論選項：transitioned decisively from shell-tempered to sand-tempered...", "temper", "/ˈtem.pɚ/", "羼料調和劑脾氣", "stratigraphy", "/strəˈtɪɡ.rə.fi/", "地層學地層結構")
    ]),
    # 19. Cross-Textual Connections: Reconciling Conflicting Scholarly Viewpoints
    ("Cross-Textual Connections: Scholarly Debate", "學術思維", "C1-SAT19", [
        ("Text 1: Historian Jackson argues that the fall of the Western Roman Empire was an abrupt, catastrophic collapse caused primarily by barbarian invasions and military failure. \nText 2: Historian Ward-Perkins contends that rather than a sudden fall, the transition was a prolonged cultural transformation in which Roman administrative institutions gradually merged with Germanic customs over centuries. \nBased on the texts, how would Ward-Perkins (Text 2) most likely respond to Jackson’s argument (Text 1)?", "By arguing that Jackson exaggerates the suddenness and destructive finality of the imperial transition while ignoring institutional continuity.", "By agreeing that Roman political structures vanished overnight without leaving any trace in medieval law.", "By asserting that barbarian invasions had zero impact on the economic systems of the Mediterranean basin.", "By demonstrating that the Western Roman Empire actually expanded its territorial boundaries in the fifth century.", "雙篇觀點互聯：Text 1 主張羅馬帝國覆亡是突發且災難性的崩潰 (abrupt catastrophic collapse)；Text 2 主張是跨世紀體制融合的漫長演進 (prolonged transformation)。Ward-Perkins 會回應認為 Jackson 誇大了突發性與毀滅性終局，而忽略了體制的延續性。", "雙篇觀點對照：指責對方誇大突發性 (exaggerates the suddenness) 並忽略延續性 (ignoring continuity)。", "雙文交叉評析選項：exaggerates suddenness while ignoring institutional continuity。", "abrupt", "/əˈbrʌpt/", "突然的唐突的生硬的", "continuity", "/ˌkɑːn.təˈnuː.ə.t̬i/", "連續性持續性延續"),
        ("Text 1: Cognitive scientist Dr. Chen claims that young infants possess innate, domain-specific core knowledge of basic Newtonian physics, such as object permanence and gravity. \nText 2: Dr. Patel counters that infant looking-time experiments do not prove hardwired conceptual knowledge, but merely reflect generalized perceptual habituation to novel sensory stimuli. \nBased on the texts, how does Dr. Patel (Text 2) characterize the experimental evidence cited by Dr. Chen (Text 1)?", "As inconclusive behavioral responses driven by low-level perceptual processing rather than genuine conceptual understanding.", "As definitive proof confirming that human neonates understand complex mathematical physics.", "As fundamentally fraudulent data fabricated by biased researchers.", "As irrelevant to questions concerning cognitive development in early childhood.", "雙篇觀點互動：Chen 認為嬰兒注視時間實驗證明了天生具備物理概念知識 (innate core knowledge)；Patel 反駁注視時間只反映對新奇刺激的感官習慣化 (perceptual habituation)。因此 Patel 認為該證據只是低階知覺處理，而非真正的概念理解。", "雙篇批評焦點：將對方宣稱的概念理解降格為低階知覺反應 (perceptual processing)。", "交叉觀點選項：inconclusive responses driven by low-level perceptual processing。", "habituation", "/həˌbɪtʃ.uˈeɪ.ʃən/", "習慣化適應", "hardwired", "/ˌhɑːrdˈwaɪ.ɚd/", "天生的本能的硬編碼的"),
        ("Text 1: Proponents of geoengineering assert that injecting sulfur aerosols into the stratosphere is an urgent, cost-effective necessity to counteract global thermal runaway. \nText 2: Critics caution that solar radiation management could disrupt monsoon rainfall patterns, threatening food security for billions while failing to halt ocean acidification. \nBased on the texts, what would the author of Text 2 emphasize about the solution proposed in Text 1?", "It poses severe, asymmetrical ecological hazards that could destabilize agricultural systems worldwide.", "It is technically impossible to implement using contemporary aerospace launch platforms.", "It would instantly eliminate atmospheric greenhouse gas concentrations within six months.", "It is overwhelmingly endorsed by all international agricultural and environmental treaties.", "雙篇觀點互聯：Text 1 倡議向平流層注入硫氣溶膠是抑制暖化的緊急良方；Text 2 警告太陽輻射管理可能擾亂季風降雨引發全球糧食危機。Text 2 作者會強調 Text 1 的方案帶來了可能破壞全球農業體系的嚴重非對稱生態危害。", "雙篇批評：指出工程方案具有嚴重的生態危害 (asymmetrical ecological hazards)。", "交叉批評選項：poses severe asymmetrical ecological hazards destabilizing agriculture。", "aerosol", "/ˈer.ə.sɑːl/", "氣溶膠浮質氣霧劑", "acidification", "/əˌsɪd.ə.fəˈkeɪ.ʃən/", "酸化酸化作用"),
        ("Text 1: Literary scholar Green asserts that James Joyce's *Ulysses* represents the absolute zenith of high modernism, intentionally written exclusively for intellectual elites. \nText 2: Critic Bloom argues that despite its stylistic difficulty, *Ulysses* is fundamentally rooted in popular Irish humor, bawdy music-hall songs, and everyday working-class Dublin life. \nHow would Bloom (Text 2) most likely view Green’s interpretation (Text 1)?", "As overly narrow, since it overlooks the novel's profound engagement with vernacular culture and ordinary human experience.", "As entirely accurate in classifying the novel as an academic exercise detached from real life.", "As flawed because Green failed to identify the classical Homeric parallels within each chapter.", "As revolutionary because Green was the first scholar to appreciate the complexity of Joyce's prose.", "雙篇視角互聯：Green 認為《尤利西斯》純屬現代主義巔峰、專為知識精英而寫 (exclusively for intellectual elites)；Bloom 認為它深植於愛爾蘭大眾幽默與都柏林市井民俗生活。Bloom 會認為 Green 的觀點過於狹隘，忽略了其與民間口語文化和日常大眾經驗的深度契合。", "雙篇反駁：指責對方過於狹隘 (overly narrow)，忽略了大眾常民文化 (vernacular culture)。", "交叉評論選項：overly narrow, since it overlooks engagement with vernacular culture。", "zenith", "/ˈzen.ɪθ/", "頂點頂峰極盛之時", "bawdy", "/ˈbɑː.di/", "下流猥褻的粗俗滑稽的"),
        ("Text 1: Agronomist Diaz argues that organic farming methods are essential for biodiversity conservation and should entirely replace industrial synthetic chemical agriculture worldwide. \nText 2: Agronomist Miller contends that because organic farming requires up to forty percent more land to achieve equivalent yields, a total conversion would necessitate catastrophic global deforestation. \nBased on the texts, what point of contention exists between Diaz and Miller?", "Whether the land footprint required by organic farming offsets its localized ecological benefits on a global scale.", "Whether synthetic chemical fertilizers improve the taste of agricultural produce.", "Whether deforestation contributes to greenhouse gas emissions.", "Whether small-scale community gardens can survive in arid metropolitan environments.", "雙篇爭論焦點分析：Diaz 主張全面推行有機農業以保護生物多樣性；Miller 反駁有機耕作需要多出40%土地，全面推行會迫使大面積砍伐森林。兩者的核心爭論點在於：有機農業所需的土地佔用面積是否會在全球尺度上抵消其局部的生態效益。", "雙篇爭鳴爭點：土地佔用足跡是否抵消局部生態效益 (land footprint offsets ecological benefits)。", "核心爭鳴點選項：Whether the land footprint required offsets localized ecological benefits。", "agronomist", "/əˈɡrɑː.nə.mɪst/", "農學家農業專家", "footprint", "/ˈfʊt.prɪnt/", "足跡佔用空間面積")
    ]),
    # 20. Rhetorical Function: Analyzing the Purpose of a Targeted Sentence
    ("Rhetorical Function: Sentence Purpose", "學術思維", "C1-SAT20", [
        ("The author includes the sentence 'Consider, for example, the humble water strider' primarily to:", "introduce a concrete biological illustration of surface tension in aquatic locomotion", "challenge the mathematical laws governing fluid mechanics", "disprove the existence of hydrophobic microstructures on insect legs", "recount a personal childhood memory of observing pond wildlife", "句子修辭功能分析：作者在論述水的表面張力物理原理時，提及「以不起眼的水黽為例」，主要目的是引出一個具體的生物實例，藉以生動說明水生動物運動中的表面張力機制。", "修辭功能：舉出生物實例說明物理概念 (concrete biological illustration)。", "修辭功能選項：introduce a concrete biological illustration of surface tension...", "strider", "/ˈstraɪ.dɚ/", "闊步走的人水黽", "hydrophobic", "/ˌhaɪ.drəˈfoʊ.bɪk/", "疏水的疏水性的"),
        ("In the context of the passage, the primary rhetorical function of the highlighted rhetorical question is to:", "provoke the reader to question conventional assumptions regarding architectural durability", "demonstrate the author's personal indecision regarding aesthetic choices", "scold the reader for neglecting ancient historical preservation efforts", "summarize the statistical findings presented in the preceding paragraph", "修辭反問句功能題：作者在段落轉折處拋出「難道我們真以為鋼筋混凝土的壽命能超越羅馬水磨石嗎？」這句反問，旨在激發讀者反思並質疑當前有關現代建築耐久性的傳統迷思假定。", "修辭疑問句功能：激發反思質疑傳統假定 (provoke the reader to question assumptions)。", "修辭功能選項：provoke the reader to question conventional assumptions...", "durability", "/ˌdʊr.əˈbɪl.ə.t̬i/", "耐用性耐久力", "indecision", "/ˌɪn.dɪˈsɪʒ.ən/", "優柔寡斷猶豫不決"),
        ("The primary purpose of the author's reference to Galileo’s 1610 treatise *Sidereus Nuncius* is to:", "provide historical precedent for an empirical breakthrough that challenged established cosmology", "criticize the observational accuracy of early telescopic optics", "argue that seventeenth-century astronomers were unconcerned with planetary motion", "demonstrate that the Catholic Church immediately embraced heliocentric models", "歷史引用修辭功能題：作者引用伽利略 1610 年的專著《星際使者》，主要目的是提供一個歷史先例，佐證一項實證科學突破如何有力挑戰了當時根深蒂固的正統宇宙觀。", "歷史引用功能：提供歷史先例 (provide historical precedent for a breakthrough)。", "修辭功能選項：provide historical precedent for an empirical breakthrough...", "precedent", "/ˈpres.ə.dent/", "先例判例前例", "heliocentric", "/ˌhiː.li.oʊˈsen.trɪk/", "日心的日心說的"),
        ("The author mentions that 'the expedition consumed forty bags of flour per week' primarily to:", "vividly convey the immense logistical scale and resource demands of the polar journey", "criticize the explorers for reckless overconsumption during an emergency", "suggest that nutritional deficiencies caused the failure of the mission", "compare European baking techniques with indigenous culinary practices", "細節描寫修辭功能題：作者提及「探險隊每週消耗四十袋麵粉」，主要目的是生動傳達這場極地征程所面臨的龐大後勤補給規模與物資需求負擔。", "生活細節修辭：生動展示後勤規模與資源負擔 (convey the immense logistical scale)。", "修辭功能選項：vividly convey the immense logistical scale and resource demands...", "logistical", "/ləˈdʒɪs.tɪ.kəl/", "後勤的物流的運籌學的", "deficiency", "/dɪˈfɪʃ.ən.si/", "缺乏不足缺陷"),
        ("The author incorporates a direct quote from Chief Justice Marshall primarily in order to:", "anchor the legal argument in authoritative judicial jurisprudence", "refute the constitutionality of federal appellate jurisdiction", "entertain the audience with nineteenth-century rhetorical flourish", "expose ideological inconsistencies within the founding generation", "法學引述修辭功能題：作者在論述聯邦最高法院司法審查權時，直接引用馬歇爾大法官在馬伯利訴麥迪遜案中的判決原話，旨在將其法律論證奠基於權威的司法判例法理之上。", "名家引言功能：為法律論點確立權威法理基礎 (anchor argument in authoritative jurisprudence)。", "修辭功能選項：anchor the legal argument in authoritative judicial jurisprudence。", "jurisprudence", "/ˌdʒʊr.ɪsˈpruː.dəns/", "法學法理學法律哲學", "appellate", "/əˈpel.ət/", "上訴的上訴審理的")
    ]),
    # 21. Authorial Tone & Academic Stance: Skeptical, Dispassionate, or Vindictive
    ("Authorial Tone & Academic Stance", "學術思維", "C1-SAT21", [
        ("The author’s description of the cold fusion announcement as 'a sensationalist declaration built upon dubious calorimetric measurements' reflects a tone that is best characterized as:", "skeptical and dismissive", "reverent and celebratory", "whimsical and indifferent", "objective and admiring", "語氣態度題：作者將冷融合發布會形容為「建立在可疑熱量測量基礎上的聳人聽聞宣稱」，字裡行間充滿了質疑與斥責，最能體現出「懷疑且不屑/駁斥的」語氣。", "態度評判：sensationalist + dubious 體現 skeptical and dismissive（懷疑且不以為然）。", "語氣選項精準選 skeptical and dismissive。", "sensationalist", "/senˈseɪ.ʃən.əl.ɪst/", "聳人聽聞的追求轟動效應的", "calorimetric", "/ˌkæl.ə.rɪˈmet.rɪk/", "量熱的熱量測定的"),
        ("Throughout the botanical treatise, the author systematically presents empirical measurements, notes margin-of-error limitations, and avoids subjective hyperbole. The author's tone can best be described as:", "dispassionate and analytical", "derisive and confrontational", "fervent and emotional", "apologetic and uncertain", "學術語氣分析題：作者全篇系統性呈現實證測量數據、指陳誤差極限、完全避免主觀誇大修辭，這種語氣最貼切的描述為「冷靜客觀且條分縷析的 (dispassionate and analytical)」。", "客觀學術語氣：避免主觀修辭，專注數據 -> dispassionate and analytical。", "學術客觀語氣選項：dispassionate and analytical。", "dispassionate", "/dɪsˈpæʃ.ən.ət/", "冷靜的客觀的不帶偏見的", "hyperbole", "/haɪˈpɝː.bəl.i/", "誇張誇張法誇張語"),
        ("In discussing the rival historian’s methodology, the author writes: 'Dr. Gomez’s so-called archival discovery is merely a pedestrian rehash of well-worn secondary literature, betrayed by elementary paleographic blunders.' The author’s stance toward Dr. Gomez is best characterized as:", "scathing and contemptuous", "tactful and conciliatory", "neutral and dispassionate", "deferential and polite", "批判語氣題：作者稱對方的發現只不過是「老生常談的二手法資料的平庸炒冷飯，還暴露出極初級的古文字學低級錯誤」，態度顯得極為「嚴厲苛刻且輕蔑蔑視的 (scathing and contemptuous)」。", "強烈負面評論：pedestrian rehash + blunders -> scathing and contemptuous。", "批判態度選項：scathing and contemptuous。", "pedestrian", "/pəˈdes.tri.ən/", "平庸乏味的徒步的行人", "scathing", "/ˈskeɪ.ðɪŋ/", "嚴厲尖刻的體無完膚的"),
        ("When reflecting upon the profound complexity of gravitational wave astronomy, the author marvels at 'humanity’s astonishing capacity to detect ripples in the cosmic fabric smaller than a proton.' The tone of this passage is best described as:", "awed and appreciative", "cynical and suspicious", "flippant and humorous", "bored and detached", "讚嘆語氣題：作者讚嘆人類竟然具備「在宇宙時空結構中探測比質子還小的微弱漣漪的驚人能力」，字裡行間洋溢著「敬畏讚嘆且深懷感激欽佩的 (awed and appreciative)」情懷。", "敬畏讚美：marvels at astonishing capacity -> awed and appreciative。", "讚頌態度選項：awed and appreciative。", "proton", "/ˈproʊ.tɑːn/", "質子", "flippant", "/ˈflɪp.ənt/", "輕率的浮誇無禮的"),
        ("In addressing the ongoing scientific debate surrounding dark energy, the author writes: 'While competing cosmological hypotheses abound, definitive conclusions must await the next generation of space observatories.' The author's tone here is best described as:", "measured and prudent", "hostile and belligerent", "ecstatic and triumphant", "resigned and despairing", "審慎學術語氣題：作者面對暗能量爭論指出「雖然假說百家爭鳴，但最終定論仍需靜待下一代太空望遠鏡的觀測數據」，展現出「審慎沉穩且具備度量節制的 (measured and prudent)」學者態度。", "審慎態度：competing hypotheses abound + must await data -> measured and prudent。", "審慎態度選項：measured and prudent。", "prudent", "/ˈpruː.dənt/", "審慎的謹慎明智的", "belligerent", "/bəˈlɪdʒ.ɚ.ənt/", "好戰的挑釁的交戰的")
    ]),
    # 22. Idiomatic Prepositional Collocations in Formal Academic English
    ("Academic Prepositional Collocations", "學術思維", "C1-SAT22", [
        ("The newly formulated sociological model is predicated ___ the assumption that social capital mediates economic mobility.", "on", "in", "to", "at", "這套新構建的社會學理論模型，「建立在」社會資本能夠調解經濟流動性這一核心假說之基礎上。", "be predicated on/upon 為高階學術固定搭配，意為「基於…、建立在…的基礎之上」。", "學術搭配詞：be predicated on（基於、取決於）。", "predicate", "/ˈpred.ə.keɪt/", "斷定使基於謂語", "mobility", "/moʊˈbɪl.ə.t̬i/", "流動性流動能力"),
        ("The experimental methodology was designed to be impervious ___ external ambient temperature fluctuations.", "to", "with", "for", "against", "該套實驗方法論經過精密設計，旨在對外部環境周遭的溫度波動「免疫、不受其任何干擾影響」。", "be impervious to 為固定學術形容詞搭配，意為「不受…影響的、對…無動於衷的」。", "固定介系詞搭配：impervious to。", "impervious", "/ɪmˈpɝː.vi.əs/", "不受影響的不能滲透的", "fluctuation", "/ˌflʌk.tʃuˈeɪ.ʃən/", "波動起伏"),
        ("The museum curator took great care to ensure that the ancient tapestry was displayed in a manner consistent ___ international conservation standards.", "with", "to", "by", "of", "美術館策展人竭盡心力，務求確保這幅古代織錦壁毯的展陳陳列方式完全「符合/與…相一致」國際文物保護標準規範。", "be consistent with 為固定搭配，意為「與…相一致、符合」。", "固定介系詞搭配：consistent with。", "tapestry", "/ˈtæp.ə.stri/", "織錦壁毯掛毯", "conservation", "/ˌkɑːn.sɚˈveɪ.ʃən/", "文物保護保存"),
        ("The revolutionary philosophical tract served as a catalyst ___ widespread democratic political reform across the continent.", "for", "of", "to", "in", "這部革命性的哲學政治小冊子，成為了推動整個歐洲大陸廣泛民主政治改革的「催化劑/強大推動力」。", "serve as a catalyst for 為學術經典搭配，意為「充當…的催化劑」。", "固定介系詞搭配：catalyst for。", "tract", "/trækt/", "小冊子文章傳單", "catalyst", "/ˈkæt̬.əl.ɪst/", "催化劑促成因素"),
        ("Historians attribute the collapse of the coastal civilization not to foreign invasion, but ___ chronic prolonged environmental degradation.", "to", "for", "with", "by", "歷史學家將該沿海文明的覆亡原因歸咎於「長期持續的環境退化」，而非外敵的外患入侵。", "attribute A to B 為標準固定搭配，意為「將 A 歸因於 B」。", "動詞固定搭配：attribute A to B。", "chronic", "/ˈkrɑː.nɪk/", "慢性的長期的長年積習的", "degradation", "/ˌdeɡ.rəˈdeɪ.ʃən/", "退化損耗墮落"),
        ("The newly appointed ambassador was tasked ___ renegotiating the complex multilateral maritime fishing treaty.", "with", "for", "to", "by", "新獲任命的大使肩負重任，被正式「賦予任務負責」重新談判這份複雜的多邊海洋漁業公約條約。", "be tasked with + V-ing/名詞 為高頻固定片語，意為「被賦予…之任務」。", "被動片語：be tasked with doing something。", "multilateral", "/ˌmʌl.tiˈlæt̬.ɚ.əl/", "多邊的多國的", "renegotiate", "/ˌriː.nəˈɡoʊ.ʃi.eɪt/", "重新談判重新協商"),
        ("The genetic mutation confers an innate resistance ___ chloroquine in certain resistant strains of the malaria parasite.", "to", "with", "against", "for", "在某些具抗藥性的瘧原蟲抗性株中，該基因突變賦予了其對氯喹藥物的「天然抗藥性抵禦力」。", "confer resistance to 為生物醫藥經典搭配，意為「賦予對…的抵抗力」。", "固定搭配：confer resistance to...", "chloroquine", "/ˈklɔːr.ə.kwɪn/", "氯喹(抗瘧疾藥)", "parasite", "/ˈper.ə.saɪt/", "寄生蟲寄生生物"),
        ("The findings of the urban sociological study are congruent ___ previously established demographic patterns in Western Europe.", "with", "to", "for", "by", "該項都市社會學實證研究的發現，與先前在西歐研究所確立的人口統計學分佈模式「完全契合吻合」。", "be congruent with 為學術英語固定搭配，意為「與…相一致、契合相符」。", "學術形容詞搭配：congruent with。", "congruent", "/ˈkɑːŋ.ɡru.ənt/", "一致的相符的全等的", "demographic", "/ˌdem.əˈɡræf.ɪk/", "人口學的族群結構的"),
        ("The experimental results are indicative ___ a fundamental shift in the material’s crystalline atomic arrangement.", "of", "to", "with", "for", "該實驗數據結果「象徵表明了」該材料內部晶體原子排列結構發生了根本性的重大相變轉折。", "be indicative of 為高階學術搭配，意為「表明…、象徵…的跡象」。", "學術形容詞搭配：indicative of。", "crystalline", "/ˈkrɪs.təl.aɪn/", "晶體的結晶狀的", "indicative", "/ɪnˈdɪk.ə.t̬ɪv/", "象徵的指示的表明的"),
        ("The evolutionary biologist argued that anatomical vestigiality is compatible ___ Darwinian models of gradual natural selection.", "with", "to", "by", "for", "這位演化生物學家論證指出，解剖學上的器官退化痕跡現象，與達爾文漸進式自然選擇模型是「完全相容並蓄而不矛盾的」。", "be compatible with 為核心固定搭配，意為「與…相容相合」。", "固定介系詞搭配：compatible with。", "vestigiality", "/ˌves.tɪdʒ.iˈæl.ə.t̬i/", "器官退化痕跡性", "anatomical", "/ˌæn.əˈtɑː.mɪ.kəl/", "解剖學的解剖結構的")
    ]),
    # 23. Style & Conciseness: Eliminating Pleonastic Redundancies
    ("Style & Conciseness: Eliminating Redundancy", "學術思維", "C1-SAT23", [
        ("The archival documents reveal that the medieval guild masters met ___ to deliberate on apprentices' guild examinations.", "annually", "annually on an annual basis every year", "annually every single year", "each year on an annual cycle", "檔案文獻揭示，中世紀行會大師們「每年」定期集會，以審查學徒的行會資格檢定考試。", "annually 已包含「每年」之意，其他選項疊床架屋語意重複 (on an annual basis every year 等均為贅詞)，簡潔選 annually。", "學術文風簡潔性：剔除重複冗詞，單選副詞 annually。", "guild", "/ɡɪld/", "行會同業公會", "apprentice", "/əˈpren.t̬ɪs/", "學徒徒弟實習生"),
        ("The laboratory technicians confirmed that the two chemical solutions were ___ in chemical composition and molecular structure.", "identical", "completely identical and exactly the same", "identically duplicate twins", "identical copies of each other with no differences", "實驗室檢驗員證實，這兩種化學溶液在化學組成與分子結構上「完全相同」。", "identical 本身即代表「完全相同」，後方再加 exactly the same 或 no differences 皆屬語意重複之贅病，選 identical。", "簡潔性原則：identical 無需再加 exactly the same 等贅詞修飾。", "identical", "/aɪˈden.t̬ə.kəl/", "完全相同的同一的", "molecular", "/məˈlek.jə.lɚ/", "分子的"),
        ("The archeological team unearthed an ancient wall that had been ___ into three separate fragments.", "broken", "broken apart into pieces", "broken down into split pieces", "broken and smashed apart", "考古隊挖掘出了一道早已「斷裂破裂成」三個獨立碎塊的古代城牆殘垣。", "broken 已清楚表達破碎狀態，其他選項堆砌 apart into pieces 均為冗言贅字，最精煉純粹選 broken。", "簡潔選詞：broken 符合學術行文乾淨凝練標準。", "fragment", "/ˈfræɡ.mənt/", "碎片碎塊殘片", "unearthed", "/ʌnˈɝːθt/", "出土被發掘的"),
        ("The research paper concluded with a brief ___ of the experimental methodology.", "summary", "summary recapitulation", "summary that summarized the findings", "brief summary repetition", "該研究論文以對實驗方法論的簡短「總結摘要」作為收尾結語。", "summary 本身即是總結，若使用 summary that summarized 或 summary recapitulation 均屬同義反覆之語病，選 summary。", "剔除同義贅述：單一名詞 summary 最具學術規範。", "recapitulation", "/rɪˌkæp.ɪ.tʃəˈleɪ.ʃən/", "概括扼要重述", "methodology", "/ˌmeθ.əˈdɑː.lə.dʒi/", "方法學方法論"),
        ("The newly passed urban zoning ordinance will ___ in the upcoming calendar month.", "take effect", "take effect and become operational and functional", "take active legal effect into practical action", "take operative legal effect starting to work", "這項新審議通過的城市分區規劃法規，將於即將到來的下個月份「正式生效施行」。", "take effect 為法律與學術標準固定詞組，後續補充 become operational 等均為冗餘贅詞，選 take effect。", "商務與法律簡練原則：精簡片語 take effect。", "ordinance", "/ˈɔːr.dən.əns/", "條例法規法令", "zoning", "/ˈzoʊ.nɪŋ/", "分區制分區規劃"),
        ("The historical biographer noted that the statesman was a ___ speaker who swayed parliaments with his impassioned rhetoric.", "persuasive", "persuasive speaker capable of convincing people", "persuasive orator who persuaded listeners effectively", "convincing speaker full of persuasion", "歷史傳記作家指出，該政治家是一位「極具說服力的」演說家，常以其慷慨激昂的雄辯之詞折服國會議員。", "persuasive（具說服力的）之後再加 capable of convincing people 屬於典型的語意重疊贅詞，單用 persuasive 最為俐落。", "定語簡練原則：persuasive 單詞即精確表達說服力。", "biographer", "/baɪˈɑː.ɡrə.fɚ/", "傳記作家", "sway", "/sweɪ/", "左右動搖支配搖擺"),
        ("The astrophysicist explained that the celestial body had ___ around the supermassive black hole.", "completed an orbit", "completed a circular round orbit in a circle", "orbited around in a full complete 360-degree circle", "finished a revolving complete cycle of orbit", "天體物理學家解釋說，該天體早已圍繞超大質量黑洞「完成了一次完整公轉軌道」。", "completed an orbit 簡明精準，其他選項將 circular、round、in a circle 等重複堆砌，均為贅語，選 completed an orbit。", "科學論文簡約原則：completed an orbit 精準無冗詞。", "celestial", "/səˈles.tʃəl/", "天體的太空的天堂的", "orbit", "/ˈɔːr.bɪt/", "軌道繞軌道運行"),
        ("The committee members unanimously reached a ___ on the budget allocation.", "consensus", "unanimous consensus of agreement where everyone agreed", "consensus of unified mutual agreement", "consensus wherein all members were in total agreement", "委員會全體委員針對預算分配方案全體一致地「達成了共識」。", "consensus（共識）本身即蘊含眾人一致同意之意，再添 of agreement where everyone agreed 等純屬廢話冗詞，選 consensus。", "名詞規範：單用 consensus 避免語意反覆。", "consensus", "/kənˈsen.səs/", "共識一致意見", "allocation", "/ˌæl.əˈkeɪ.ʃən/", "分配撥給配給額"),
        ("The botanical expedition discovered an indigenous plant species that was ___ to the island.", "unique", "unique and found nowhere else in the world", "uniquely native and totally singular", "exclusive and solely unique", "該植物學考察隊發現了一種該島嶼所「獨有的」特有原生植物物種。", "unique to the island 意為「該島特有的」，再贅述 found nowhere else 或 totally singular 皆犯了贅字之大忌，選 unique。", "形容詞精確度：unique to 已完整表達獨特性。", "indigenous", "/ɪnˈdɪdʒ.ə.nəs/", "原生的本土的", "unique", "/juːˈniːk/", "獨特的特有的獨一無二的"),
        ("The company decided to ___ its older mainframe computing systems next quarter.", "retire", "retire and phase out and discontinue completely", "permanently retire and stop using forever", "retire away into obsolescence", "該跨國公司拍板決定，將於下個季度正式「汰除淘汰」其舊型大型主機電腦系統。", "retire 在科技軟硬體術語中即表示「退役、停用汰除」，其他選項之 phase out and discontinue 疊床架屋，選 retire。", "動詞精練原則：單一專業動詞 retire 取代冗長贅語。", "mainframe", "/ˈmeɪn.freɪm/", "大型主機中央處理系統", "obsolescence", "/ˌɑːb.səˈles.əns/", "過時淘汰荒廢")
    ]),
    # 24. Sentence Placement & Cohesive Flow in Expository Arguments
    ("Sentence Placement & Cohesive Flow", "學術思維", "C1-SAT24", [
        ("Where should the sentence 'These subterranean networks, known as mycorrhizae, facilitate mutualistic resource exchange' be placed in the paragraph? \n[1] Plants do not exist as isolated biological entities in forest ecosystems. [2] Beneath the soil, their roots intertwine intimately with vast webs of fungal hyphae. [3] In exchange for photosynthetic carbohydrates, the fungi supply nitrogen and phosphorus. [4] This hidden cooperation challenges traditional competitive models of evolution.", "After sentence 2", "After sentence 1", "After sentence 3", "After sentence 4", "篇章邏輯銜接題：句子指出「這些被稱為菌根的地下網絡促進了互利資源交換」，其中 'These subterranean networks' 明顯指涉前一句中的 'vast webs of fungal hyphae'（地下真菌菌絲網絡），且後一句緊接著解釋資源交換細節 (In exchange for carbohydrates... fungi supply nitrogen)。因此最理想位置在句 2 之後。", "指代詞銜接：These subterranean networks 承接句 2 的 webs of fungal hyphae，引出句 3 的資源交換。", "最佳銜接位置選 After sentence 2。", "mycorrhizae", "/ˌmaɪ.kəˈraɪ.ziː/", "菌根菌根真菌", "hyphae", "/ˈhaɪ.fiː/", "菌絲真菌絲"),
        ("Where should the sentence 'However, isotopic analysis of preserved dentition has overturned this pastoral assumption' be inserted? \n[1] For decades, anthropologists assumed that early hominids in the savannah consumed an exclusively frugivorous diet. [2] Microscopic microwear patterns on fossilized molars initially seemed to support this hypothesis. [3] Instead, the carbon isotope ratios demonstrate heavy reliance on tough C4 grasses and roots. [4] Consequently, our evolutionary ancestors were far more versatile opportunists than previously imagined.", "After sentence 2", "After sentence 1", "After sentence 3", "After sentence 4", "語意轉折插入題：句子以 However 開頭，指出「對保存牙齒的同位素分析推翻了這項食果假說」。句 1-2 描述過去的食果假說及其初步支持證據；句 3 以 Instead 開頭直接說明同位素分析揭示的真正草食根莖飲食。因此該轉折句必須置於句 2 之後、句 3 之前。", "轉折句銜接：推翻句 1-2 的傳統假說，引導句 3 的 Instead 實證數據，選 After sentence 2。", "最佳銜接位選 After sentence 2。", "dentition", "/denˈtɪʃ.ən/", "齒系齒列牙齒結構", "frugivorous", "/fruːˈdʒɪv.ɚ.əs/", "食果的以水果為食的"),
        ("Where should the sentence 'This gravitational anomaly, colloquially dubbed the Great Attractor, exerts an irresistible pull' be positioned? \n[1] Modern astrophysicists mapping the local universe detected an unexpected cosmic movement. [2] Tens of thousands of galaxies, including our own Milky Way, are drifting toward a specific region in the Centaurus cluster. [3] Obscured behind the dust of the Zone of Avoidance, its precise physical composition remains an enigma. [4] Future infrared and radio surveys aim to pierce this interstellar veil.", "After sentence 2", "After sentence 1", "After sentence 3", "After sentence 4", "指涉語流暢度分析：待插入句子以 'This gravitational anomaly'（這處引力異常體，俗稱巨引源）起手，精確對應句 2 中成千上萬星系正朝向半人馬座方向飄移的宏觀引力現象；隨後句 3 中的代名詞 'its precise physical composition' 剛好指稱這座巨引源。故最佳位置在句 2 之後。", "指涉銜接：承接句 2 的星系漂移現象，引導句 3 的 its physical composition，選 After sentence 2。", "最佳句子排序選 After sentence 2。", "anomaly", "/əˈnɑː.mə.li/", "異常反常畸變", "interstellar", "/ˌɪn.t̬ɚˈstel.ɚ/", "星際的星與星之間的"),
        ("Where should the sentence 'Without these specialized physiological adaptations, deep dives would inevitably cause lethal decompression sickness' be placed? \n[1] Marine mammals like the sperm whale descend to crushing depths exceeding two thousand meters. [2] To survive, they collapse their lungs intentionally, expelling air to avoid nitrogen absorption into the bloodstream. [3] Furthermore, high concentrations of myoglobin in their skeletal muscles store vast quantities of oxygen. [4] These combined mechanisms allow them to hunt giant squid in the abyssal zone for over an hour.", "After sentence 3", "After sentence 1", "After sentence 2", "After sentence 4", "邏輯總結功能句插入：待插入句 'Without these specialized physiological adaptations...'（如果沒有這些專門的生理適應機制，深潛將引發致命潛水夫病）。句 2 提到肺部塌陷，句 3 提到肌紅蛋白儲氧，兩者合稱為 these adaptations；且句 4 緊接著說 These combined mechanisms allow them...。因此置於句 3 之後最能起到承上啟下的反面強調作用。", "生理機制反面強調句：置於兩種適應機制 (句2, 句3) 描述之後，選 After sentence 3。", "最佳插入位置選 After sentence 3。", "decompression", "/ˌdiː.kəmˈpreʃ.ən/", "減壓去壓", "myoglobin", "/ˌmaɪ.oʊˈɡloʊ.bɪn/", "肌紅蛋白肌紅素"),
        ("Where should the sentence 'Chief among these archival treasures is a parchment manuscript dating to 1215' be inserted? \n[1] The British Library houses some of the most significant historical documents in the Western world. [2] Scholars from around the globe travel to London to inspect its rare codices and cartographic scrolls. [3] Bearing the royal seal of King John, the Magna Carta established the foundational constitutional principle that even monarchs are subject to the law. [4] It remains an enduring symbol of liberty across modern democracies.", "After sentence 2", "After sentence 1", "After sentence 3", "After sentence 4", "概念引導句銜接：待插入句提到「在這些檔案珍藏中，首屈一指的便是一份可追溯至 1215 年的羊皮紙手抄文獻」。句 2 提到全球學者前來查閱古抄本卷軸；句 3 緊接著描述「蓋有約翰國王御璽的大憲章 (Magna Carta) 奠定了君權受法律約束之憲政原則」。因此該句為句 3 大憲章的出場合理鋪陳引介，必須插在句 2 之後。", "文獻引入句：承接句 2 的文獻收藏，為句 3 的 Magna Carta 正式出場作鋪陳，選 After sentence 2。", "最佳句位銜接選 After sentence 2。", "parchment", "/ˈpɑːrtʃ.mənt/", "羊皮紙", "constitutional", "/ˌkɑːn.stəˈtuː.ʃən.əl/", "憲政的憲法的體質的")
    ]),
    # 25. Pragmatic Inference & Implicit Assumptions in Historical Humanities Texts
    ("Pragmatic Inference & Implicit Assumptions", "學術思維", "C1-SAT25", [
        ("The historian writes: 'While King James I commissioned the 1611 English translation of the Bible partly to standardize liturgical readings across the realm, his unspoken imperative was to curb the subversive, anti-monarchical marginal annotations found in the immensely popular Geneva Bible.' It can be reasonably inferred from this passage that the author believes:", "the King James Bible served an ideological agenda aimed at reinforcing royal political authority", "King James I had no genuine personal interest in religious translation or Christian doctrine", "the Geneva Bible was universally rejected by British Protestant congregations in the seventeenth century", "seventeenth-century English readers completely ignored marginal commentary in religious books", "語用推論題：作者指出詹姆士一世欽定版聖經表面上是統一度量儀式，但未言明的隱含目的在於遏制受歡迎的日內瓦聖經中反君主專制的旁註評論。由此可合理解讀出：作者認為欽定版聖經肩負著維護王室政治威權的意識形態目的。", "文本深度推論：遏制反君主言論 -> 具有維護王權的意識形態意圖 (ideological agenda reinforcing royal authority)。", "推論選項對應 served an ideological agenda aimed at reinforcing royal authority。", "subversive", "/səbˈvɝː.sɪv/", "顛覆性的破壞性的", "imperative", "/ɪmˈper.ə.t̬ɪv/", "當務之急緊迫命令必要條件"),
        ("A scholar notes: 'In her philosophical treaties, Sor Juana Inés de la Cruz couched her radical defense of women’s intellectual autonomy in deferential theological humility, repeatedly apologizing for her presumption even as she systematically dismantled patriarchal ecclesiastical dogma.' This passage most directly suggests that Sor Juana:", "tactically adopted conventional self-deprecating modesty to protect herself from institutional inquisitorial censorship", "genuinely believed that women were intellectually inferior to male clerics in biblical interpretation", "abandoned her scholarly pursuits as soon as religious authorities questioned her writings", "was unaware that her theological writings challenged the prevailing orthodoxies of the Spanish Viceroyalty", "人文歷史推論題：修女胡安娜在論辯女性求學權利時，將激進論述包裝在虔誠謙遜的自我貶抑文字中，一邊道歉一邊系統性瓦解父權教條。這強烈暗示她：策略性地運用傳統謙卑姿態，旨在保護自己免遭教會宗教裁判所的查禁迫害。", "修辭動機推論：謙恭表象與激進實質反差 -> 戰術性自保策略 (tactically adopted modesty to protect from censorship)。", "推論選項對應 tactically adopted modesty to protect from censorship。", "patriarchal", "/ˌpeɪ.triˈɑːr.kəl/", "父權制的男性統治的", "ecclesiastical", "/ɪˌkliː.ziˈæs.tɪ.kəl/", "基督教會的教職的"),
        ("The author remarks: 'The rapid industrialization of nineteenth-century Manchester produced unparalleled mechanical wealth, yet the life expectancy of factory laborers hovered below twenty-five years, prompting Alexis de Tocqueville to observe that from this foul drain the greatest stream of human industry flows out to fertilize the whole world, but here human nature is degraded and reduced to brutality.' What underlying premise informs Tocqueville’s observation?", "The spectacular macroeconomic progress of industrial capitalism was bought at the cost of catastrophic human exploitation.", "Manchester was the only city in Europe to benefit from the advent of the steam engine.", "Factory laborers in Britain universally refused to organize trade unions to ameliorate their conditions.", "Technological progress inevitably elevates the moral and physical well-being of the working classes.", "隱含前提推論題：托克維爾評論「從這條污穢骯髒的陰溝中，人類工業的最偉大洪流奔湧而出滋潤全世界，然而在此人類天性卻遭到徹底貶低退化為野蠻殘酷」。這段話背後的隱含核心前提是：工業資本主義令人炫目的宏觀經濟繁榮，是以災難性的人性殘酷剝削為巨大代價換取來的。", "核心前提推論：偉大工業財富 vs 人性退化野蠻 -> 繁榮建立在殘酷代價之上 (progress bought at cost of exploitation)。", "前提選項對應 macroeconomic progress bought at the cost of human exploitation。", "drain", "/dreɪn/", "排水溝陰溝消耗", "brutality", "/bruːˈtæl.ə.t̬i/", "野蠻殘暴獸性"),
        ("A literary critic writes: 'By having Jane Eyre vehemently declare her moral and spiritual equality to Mr. Rochester regardless of social class or gender, Charlotte Brontë did not merely author a compelling romantic dialogue; she fired a shot across the bow of Victorian patriarchal society.' It can be inferred that the critic regards Jane Eyre’s dialogue as:", "a subversive ideological challenge to contemporary socio-cultural hierarchies", "an endorsement of traditional aristocratic gender expectations", "a realistic transcription of actual historical conversations recorded in Yorkshire", "an unconvincing melodramatic contrivance that detracted from the novel's realism", "文學隱喻推論題：評論家指出簡愛宣告自己與羅徹斯特在靈魂與道德上的平等，「絕非僅是一段引人入勝的浪漫愛情對白，而是向維多利亞時代的父權社會猛烈開了一砲」。這說明評論家將其對白視為：對當時社會文化階層架構的顛覆性意識形態挑戰。", "隱喻推論：fired a shot across the bow -> subversive ideological challenge（顛覆性挑戰）。", "推論選項對應 a subversive ideological challenge to hierarchies。", "vehemently", "/ˈviː.ə.mənt.li/", "激烈地熱烈地慷慨激昂地", "patriarchal", "/ˌpeɪ.triˈɑːr.kəl/", "父權的家長制的"),
        ("The political historian writes: 'The Federalist Papers were published under the collective pseudonym *Publius*, effectively obscuring the diverse, and occasionally conflicting, private constitutional interpretations held by Hamilton, Madison, and Jay.' The author’s choice of the word 'obscuring' implies that:", "the facade of ideological consensus presented by the authors masked genuine underlying disagreements among them", "the authors intended for their political essays to remain permanently unread by the public", "Hamilton, Madison, and Jay held identical philosophical views on the scope of federal executive power", "the American public was unconcerned with the identity of the authors defending the new Constitution", "用詞深層暗示推論題：作者指出《聯邦黨人文集》以統一筆名 Publius 發表，有效地「掩蓋隱匿了 (obscuring)」漢密爾頓、麥迪遜與傑伊三人之間多樣且偶有衝突的私人憲法詮釋。使用 obscuring 暗示：文集所呈現的一致共識表象，遮掩了三位起草人之間真實存在的深層分歧。", "用詞潛在暗示：obscuring conflicting interpretations -> masked genuine underlying disagreements（掩飾了深層分歧）。", "推論選項對應 facade of consensus masked genuine underlying disagreements。", "pseudonym", "/ˈsuː.də.nɪm/", "筆名假名", "facade", "/fəˈsɑːd/", "正面外表偽裝虛假的外表")
    ])
]
