# scripts/diag_builders/tier5_part2_data.py
# Subtopics 16-25 for Tier 5

subtopics_16_to_25 = [
    # 16. 企業責任保險與全面風險評估 (Corporate Insurance & Risk Mitigation)
    ("企業責任保險與全面風險評估", "商務文法", "B2-U16", [
        ("The corporate liability policy provides comprehensive coverage against third-party property ___.", "damage", "damages", "damaging", "damaged", "這份企業責任保險保單，針對第三方財產遭受毀損之情況提供了周延之理賠保障。", "property damage 為保險法規標準專用片語，意為「財產毀損」（damage 此處作不可數名詞）。", "財產損害片語選 property damage。", "liability", "/ˌlaɪ.əˈbɪl.ə.t̬i/", "責任法律責任", "coverage", "/ˈkʌv.ɚ.ɪdʒ/", "保險理賠範圍覆蓋率"),
        ("The underwriter carefully assessed the manufacturing plant's fire risk profile prior to issuing the ___.", "policy", "politics", "policing", "polite", "保險核保人在正式出具保單之前，審慎評估了該工廠之火災風險狀況。", "insurance policy 為保險業界標準固定專有名詞，意為「保險單、保單」。", "保險單固定詞組選 policy。", "underwriter", "/ˈʌn.dɚˌraɪ.t̬ɚ/", "保險核保人承銷商", "policy", "/ˈpɑː.lə.si/", "保險單方針策略"),
        ("The enterprise established a crisis contingency fund to ___ against catastrophic supply chain shocks.", "hedge", "hedging", "hedged", "hedges", "該企業特別提撥設立了一筆危機應急儲備金，旨在對沖防禦災難性供應鏈衝擊之風險。", "不定詞 to 之後接動詞原形 hedge，搭配介系詞 against。", "不定詞後接動詞原形 hedge。", "contingency", "/kənˈtɪn.dʒən.si/", "應急事件突發狀況", "hedge", "/hedʒ/", "避險對沖防備"),
        ("The insurance claimant must submit proof of loss within ninety days of the ___.", "incident", "incidentally", "incidence", "incidental", "保險理賠申請人依法必須在意外事故發生後九十天之法定時限內，提送損失證明文件。", "名詞 incident 意為「意外事件、事故」，接在介系詞 of 之後。", "事故事件名詞選 incident。", "claimant", "/ˈkleɪ.mənt/", "保險索賠人申請人", "incident", "/ˈɪn.sə.dənt/", "事故事件插曲"),
        ("An annual insurance premium is paid in twelve equal monthly ___.", "installments", "installation", "installed", "installing", "這筆年度保險費分作十二期等額的每月分期付款進行扣繳。", "monthly installments 意為「每月分期付款金」，為金融分期標準用語。", "分期付款複數名詞選 installments。", "premium", "/ˈpriː.mi.əm/", "保險費溢價", "installment", "/ɪnˈstɑːl.mənt/", "分期付款之一期"),
        ("The risk management committee recommended diversifying our investments to minimize ___.", "exposure", "expose", "exposed", "exposing", "風險管理委員會強烈建議分散本公司之投資標的，以將潛在財務曝險降至最低。", "minimize exposure 為金融風險管理經典固定動賓搭配，意為「降低曝險程度」。", "降低曝險選 minimize exposure。", "diversify", "/daɪˈvɝː.sə.faɪ/", "使多元化分散投資", "exposure", "/ɪkˈspoʊ.ʒɚ/", "曝險接觸風險面"),
        ("The policyholder was fully ___ for all medical expenses incurred during the business trip.", "indemnified", "indemnify", "indemnifying", "indemnity", "該名被保險人在海外洽公出差期間所產生之一切醫療支出費用，均獲得了全額保險補償理賠。", "was fully indemnified 為被動語態，意為「獲得全額免責補償賠付」。", "被動補償選 was indemnified。", "policyholder", "/ˈpɑː.lə.siˌhoʊl.dɚ/", "被保險人投保人", "indemnify", "/ɪnˈdem.nə.faɪ/", "補償理賠保障免受損失"),
        ("The commercial insurer dispatched a forensic investigator to determine the root cause of the ___.", "collapse", "collapsed", "collapsing", "collapsible", "該商業保險公司緊急指派了一名火災與鑑識調查專家，以徹底釐清倉庫建築倒塌崩塌之根本肇因。", "名詞 collapse 意為「倒塌、崩塌」，接在介系詞 of 之後。", "名詞受詞選 collapse。", "forensic", "/fəˈren.zɪk/", "法醫的鑑識法庭的", "collapse", "/kəˈlæps/", "倒塌崩潰坍塌"),
        ("The deductible is the agreed amount that the insured party must pay before coverage ___.", "begins", "began", "beginning", "will begin", "所謂保險自負額，係指在保險公司正式啟動理賠之前，投保人依約必須先行自行承擔之約定金額。", "時間副詞子句 before 中，以現在式 begins 表未來發生的動作。", "時間副詞子句用現在式 begins。", "deductible", "/dɪˈdʌk.tə.bəl/", "自負額扣除額", "coverage", "/ˈkʌv.ɚ.ɪdʒ/", "保險覆蓋"),
        ("Cyber liability insurance has become indispensable due to the surge in ransomware ___.", "attacks", "attack", "attacking", "attacked", "由於勒索軟體惡意網路攻擊事件急遽暴增，資安責任保險如今已成為企業不可或缺之必備保障。", "ransomware attacks 意為「勒索病毒攻擊」，名詞修飾名詞構成立體複數。", "名詞複數選 attacks。", "indispensable", "/ˌɪn.dɪˈspen.sə.bəl/", "不可或缺的必需的", "ransomware", "/ˈræn.səm.wer/", "勒索軟體勒索病毒")
    ]),
    # 17. 商業策略談判與合夥互利協議 (Strategic Negotiations & Concession Bargaining)
    ("商業策略談判與合夥互利協議", "商務文法", "B2-U17", [
        ("The lead negotiator made a tactical ___ on pricing in exchange for longer contract terms.", "concession", "concede", "conceding", "concessional", "主談判代表在產品報價上做出了策略性讓步，以換取對方同意簽署更長年限的合約期程。", "make a concession 為商業談判高頻固定動賓搭配，意為「做出讓步妥協」。", "做出讓步搭配選 make a concession。", "negotiator", "/nəˈɡoʊ.ʃi.eɪ.t̬ɚ/", "談判代表協商者", "concession", "/kənˈseʃ.ən/", "讓步妥協"),
        ("After twelve grueling hours of intensive talks, the two CEOs reached an ___ in principle.", "agreement", "agree", "agreeing", "agreeable", "在經歷了長達十二個小時筋疲力竭的密集會談後，兩家企業執行長原則上達成了一致協議。", "reach an agreement in principle 意為「在原則上達成共識與協議」。", "達成協議名詞選 agreement。", "grueling", "/ˈɡruː.ə.lɪŋ/", "使人精疲力竭的嚴酷的", "in principle", "/ɪn ˈprɪn.sə.pəl/", "原則上大體上"),
        ("The buyers possessed significant bargaining ___ due to the presence of rival suppliers.", "leverage", "lever", "leveraging", "leveraged", "由於市場上存在多家實力相當的競爭供應商，買方在此次採購談判中掌握了巨大的議價籌碼優勢。", "bargaining leverage 為商務談判核心詞組，意為「議價優勢籌碼、談判槓桿」。", "談判籌碼選 leverage。", "bargaining", "/ˈbɑːr.ɡən.ɪŋ/", "議價談判討價還價", "leverage", "/ˈlev.ɚ.ɪdʒ/", "籌碼槓桿優勢"),
        ("Both parties engaged in mediation after reaching an unfortunate ___ over royalty fees.", "deadlock", "deadlocked", "deadlocking", "deadlocks", "在雙方針對技術授權專利權利金分潤問題陷入不幸僵局之後，雙方決定引入中立調解程序。", "reach a deadlock 為談判破局或僵局之經典搭配，意為「陷入僵局無解」。", "陷入僵局選 deadlock。", "mediation", "/ˌmiː.diˈeɪ.ʃən/", "調解居間斡旋", "deadlock", "/ˈded.lɑːk/", "僵局僵持不下"),
        ("The proposed partnership terms are mutually ___ to both technology companies.", "beneficial", "benefit", "beneficially", "beneficiary", "這份擬議中的策略合作結盟協議條款，對雙方高科技公司而言均互惠互利且極具戰略綜效。", "mutually beneficial 為商務合作經典片語，意為「互利互惠的、雙贏的」。", "互利互惠形容詞選 beneficial。", "mutually", "/ˈmjuː.tʃu.ə.li/", "互相地彼此地", "beneficial", "/ˌben.əˈfɪʃ.əl/", "有益的有利的"),
        ("The seller rejected the initial purchase bid and immediately issued a firm ___.", "counteroffer", "counter", "offering", "countered", "賣方當場正式否決拒絕了最初的收購出價，並隨即出具了一份態度堅決的還盤反要約。", "名詞 counteroffer 意為「還盤、反向還價」，作 issued 之受詞。", "反要約還價名詞選 counteroffer。", "reject", "/rɪˈdʒekt/", "否決拒絕", "counteroffer", "/ˈkaʊn.t̬ɚˌɑː.fɚ/", "還盤反要約反建議"),
        ("Both sides agreed to a temporary ___ in negotiations to consult with their boards.", "pause", "pausing", "paused", "pauser", "雙方一致同意在談判進程中暫時休會暫停協商，以便各自向各自的董事會進行請示諮詢。", "a temporary pause 意為「暫時的休止、暫停」。", "名詞選 pause。", "pause", "/pɑːz/", "暫停中止", "consult", "/kənˈsʌlt/", "諮詢商量"),
        ("Effective cross-cultural negotiation requires empathy and keen psychological ___.", "insight", "insightful", "insightfully", "insights", "卓有成效的跨文化國際商務談判，高度仰賴同理心以及敏銳深刻的心理學洞察力。", "psychological insight 意為「心理洞察力、敏銳洞察」，此處不可數或單數名詞抽象概念。", "洞察力名詞選 insight。", "cross-cultural", "/ˌkrɑːsˈkʌl.tʃɚ.əl/", "跨文化的", "insight", "/ˈɪn.saɪt/", "洞察力洞見"),
        ("The signing of the definitive joint venture pact was finalized during a press ___.", "conference", "confer", "conferring", "conferment", "雙方正式簽署具法律約束力之合資最終協議，是在一場盛大的全球外媒記者會上圓滿敲定。", "press conference 為標準固定名詞片語，意為「記者會、新聞發布會」。", "記者會固定詞組選 press conference。", "definitive", "/dɪˈfɪn.ə.t̬ɪv/", "最終確定的具權威性的", "pact", "/pækt/", "協定公約條約"),
        ("The trade delegation arrived in Geneva with a clear mandate to resolve all tariff ___.", "disputes", "dispute", "disputing", "disputed", "經貿代表團抵達日內瓦世界貿易組織總部，肩負著妥善化解所有關稅貿易爭端之明確法定授權。", "tariff disputes 意為「關稅爭端爭議」，複數名詞作 resolve 之受詞。", "關稅爭端名詞選 disputes。", "mandate", "/ˈmæn.deɪt/", "授權委託命令", "dispute", "/dɪˈspjuːt/", "爭議爭端糾紛")
    ]),
    # 18. 電子商務物流與多渠道全通路營運 (E-Commerce Fulfillment & Omnichannel Retailing)
    ("電子商務物流與多渠道全通路營運", "商務文法", "B2-U18", [
        ("The online marketplace automated its warehouse fulfillment center to expedite order ___.", "processing", "process", "processed", "processor", "該電子商務購物平台將其大型物流履約中心全面導入自動化，以大幅加速訂單處理流轉速度。", "order processing 為電商物流核心名詞片語，意為「訂單處理作業」。", "訂單處理名詞選 processing。", "fulfillment", "/fʊlˈfɪl.mənt/", "履約物流配送實現", "processing", "/ˈprɑː.ses.ɪŋ/", "處理加工辦理"),
        ("Customers receive an automated SMS notification with a real-time parcel tracking ___.", "number", "numeral", "numerous", "numbering", "消費者在商品寄出後會收到一則全自動簡訊通知，內附即時包裹物流追蹤貨態號碼。", "tracking number 為快遞包裹追蹤標準固定名詞詞組，意為「物流追蹤單號」。", "追蹤單號固定詞組選 number。", "notification", "/ˌnoʊ.t̬ə.fəˈkeɪ.ʃən/", "通知告示", "tracking number", "/ˈtræk.ɪŋ ˌnʌm.bɚ/", "追蹤單號貨態號碼"),
        ("The e-commerce platform experienced a significant decline in cart abandonment ___.", "rates", "rate", "rated", "rating", "該電商平台在優化結帳介面流程後，購物車未結帳放棄率出現了極其顯著的大幅下滑改善。", "cart abandonment rates 意為「購物車棄單率、未結帳流失率」。", "比率複數名詞選 rates。", "abandonment", "/əˈbæn.dən.mənt/", "拋棄放棄遺棄", "conversion", "/kənˈvɝː.ʒən/", "轉化轉化率"),
        ("Our omnichannel retail strategy seamlessly connects brick-and-mortar stores with our mobile ___.", "app", "application", "applied", "applicant", "我們所推動之全通路新零售策略，完美無縫串聯了實體門市店面與官方行動應用程式平台。", "mobile app 為行動應用程式最通俗標準商業詞組，意為「手機APP」。", "行動應用程式選 app。", "omnichannel", "/ˌɑːm.niˈtʃæn.əl/", "全通路的多元整合渠道的", "brick-and-mortar", "/ˌbrɪk.ənˈmɔːr.t̬ɚ/", "實體店面傳統門市的"),
        ("Customers may return unworn apparel for a full refund within thirty days of ___.", "delivery", "deliver", "delivered", "delivering", "顧客自包裹實際簽收送達當日起三十天之內，均可將全新未穿戴之服飾全額退貨退款。", "名詞 delivery 接在介系詞 of 之後，意為「簽收送達交付」。", "交付送達名詞選 delivery。", "apparel", "/əˈper.əl/", "服裝成衣衣著", "delivery", "/dɪˈlɪv.ɚ.i/", "遞送交付送達"),
        ("The retailer offers free shipping on domestic orders exceeding the seventy-five-dollar ___.", "threshold", "thresh", "thresholds", "threshing", "這家零售巨擘宣布，凡是境內本土配送訂單金額超過七十五美元門檻者，一律享有免運費優惠。", "threshold 意為「門檻、起徵點」，exceeding the threshold 為經典搭配。", "門檻名詞選 threshold。", "threshold", "/ˈθreʃ.hoʊld/", "門檻臨界點起點", "shipping", "/ˈʃɪp.ɪŋ/", "運費貨運配送"),
        ("A surge in holiday sales overwhelmed server capacity, causing a temporary platform ___.", "crash", "crashing", "crashed", "crasher", "年終節慶購物旺季期間訂單暴增徹底擠爆伺服器乘載上限，引發了電商平台的短暫當機故障。", "platform crash 意為「網站平台癱瘓當機」，作 causing 之受詞。", "系統癱瘓名詞選 crash。", "overwhelm", "/ˌoʊ.vɚˈwelm/", "淹沒擊潰使承受不住", "crash", "/kræʃ/", "當機故障暴跌"),
        ("Customer reviews provide invaluable feedback that helps improve future product ___.", "iterations", "iterate", "iterative", "iteratively", "廣大消費者的真實使用評價回饋提供了極珍貴之寶貴意見，有助於大幅改良未來產品的迭代版本。", "product iterations 意為「產品後續改版迭代更新」。", "產品迭代名詞選 iterations。", "invaluable", "/ɪnˈvæl.jə.bəl/", "無價的極為寶貴的", "review", "/rɪˈvjuː/", "評價評論複審"),
        ("The logistics company utilizes artificial intelligence algorithms to optimize last-mile ___.", "delivery", "deliver", "delivered", "deliverer", "該智慧物流公司廣泛運用人工智慧深度演算法，全力優化提升最後一哩路配送環節之投遞效率。", "last-mile delivery 為現代物流與電商核心專門名詞，意為「最後一哩路配送」。", "最後一哩路配送選 delivery。", "algorithm", "/ˈæl.ɡə.rɪ.ðəm/", "演算法計算規則", "last-mile", "/ˌlæst ˈmaɪl/", "最後一哩路的最後一公里的"),
        ("Retailers implement personalized product recommendations to boost average order ___.", "value", "values", "valuable", "valuation", "各大電商零售商全面引進個人化精準商品推薦系統，藉以顯著提高每一筆訂單之平均客單價金額。", "average order value (AOV) 為電商營運核心量化指標，意為「平均客單價」。", "客單價專有名詞選 value。", "recommendation", "/ˌrek.ə.menˈdeɪ.ʃən/", "推薦建議", "average order value", "/ˌæv.ɚ.ɪdʒ ˈɔːr.dɚ ˌvæl.juː/", "平均訂單金額客單價")
    ]),
    # 19. 專利發明專用權與智慧財產權授權 (Patent Infringement & Intellectual Property Licensing)
    ("專利發明專用權與智慧財產權授權", "商務文法", "B2-U19", [
        ("The tech giant filed a multi-million-dollar lawsuit alleging patent ___ against its competitor.", "infringement", "infringe", "infringing", "infringer", "該跨國科技巨擘正式向聯邦法院提起高達數百萬美元的專利侵權訴訟，指控其競爭對手非法侵權。", "patent infringement 為智慧財產權法律固定專門術語，意為「專利侵權」。", "專利侵權專有名詞選 infringement。", "lawsuit", "/ˈlɑː.suːt/", "訴訟起訴", "infringement", "/ɪnˈfrɪndʒ.mənt/", "侵害侵犯侵權行為"),
        ("Under the cross-licensing agreement, both pharmaceutical firms may utilize patented ___.", "compounds", "compound", "compounding", "compounded", "依據雙邊交互授權協議之規定，兩家跨國製藥企業均有權合法研發使用對方的專利化學化合物配方。", "形容詞 patented 修飾名詞 compounds，意為「受專利保護的化合物」。", "名詞複數選 compounds。", "cross-licensing", "/ˌkrɑːs ˈlaɪ.sən.sɪŋ/", "交互授權交叉許可", "compound", "/ˈkɑːm.paʊnd/", "化合物複合物複合詞"),
        ("The pharmaceutical startup was granted a twenty-year exclusive patent for its cancer ___.", "therapy", "therapist", "therapeutic", "therapeutically", "這家生物醫藥新創公司所自主研發的突破性癌症標靶療法，順利獲官方核准頒發長達二十年排他專利權。", "cancer therapy 為醫藥生技名詞片語，意為「癌症療法治療方案」。", "癌症療法名詞選 therapy。", "startup", "/ˈstɑːrt.ʌp/", "新創公司初創企業", "therapy", "/ˈθer.ə.pi/", "療法治療方案"),
        ("The proprietary source code is protected under international copyright ___.", "treaties", "treaty", "treating", "treatment", "該套自主研發之核心專有原始程式碼，完全受到國際版權著作權公約條約之嚴密法律保護。", "copyright treaties 為國際智財法規固定複數名詞，意為「著作權公約條約」。", "條約複數名詞選 treaties。", "proprietary", "/prəˈpraɪ.ə.ter.i/", "專有的專利的專利所有的", "treaty", "/ˈtriː.t̬i/", "條約公約協定"),
        ("Unauthorized reproduction or distribution of this multimedia content is strictly ___.", "prohibited", "prohibit", "prohibiting", "prohibition", "未事先取得書面授權而擅自重製、翻印或散布本多媒體影音內容者，依法一律嚴格禁止並究辦追訴。", "is strictly prohibited 為法律聲明標準被動語態搭配，意為「嚴格明令禁止」。", "嚴格禁止被動選 prohibited。", "reproduction", "/ˌriː.prəˈdʌk.ʃən/", "重製複製繁衍", "prohibit", "/prəˈhɪb.ɪt/", "禁止明令禁止"),
        ("The patent attorney advised the inventors to keep their discovery confidential prior to ___.", "filing", "filed", "file", "filer", "資深專利代理律師強烈建議發明人團隊，在正式向智財局遞件送件申請專利之前，務必嚴守機密絕不外洩。", "介系詞 prior to 之後接動名詞 filing，意為「在提送專利申請案之前」。", "介系詞後接動名詞 filing。", "inventor", "/ɪnˈven.t̬ɚ/", "發明人創造者", "confidential", "/ˌkɑːn.fəˈden.ʃəl/", "機密的保密的"),
        ("The licensor collects a quarterly five percent royalty on all net product ___.", "sales", "sale", "selling", "seller", "授權方依約每季度自該產品之所有扣除退貨後之淨銷售額中，按約定比率收取百分之五的專利權利金。", "net product sales 為商務財務標準詞組，意為「產品淨銷售總額」。", "銷售額複數名詞選 sales。", "licensor", "/ˈlaɪ.sən.sɔːr/", "授權人許可方", "royalty", "/ˈrɔɪ.əl.t̬i/", "權利金版稅版權費"),
        ("The trademark office refused registration because the proposed brand logo was deemed too ___.", "generic", "generically", "general", "generality", "商標審查局正式駁回了該註冊申請案，主因係認定該擬申請之品牌圖形識別標誌過於通用缺乏顯著性識別性。", "形容詞 generic 為商標法核心術語，意為「通用名稱的、不具顯著識別性的」。", "商標通用性形容詞選 generic。", "trademark", "/ˈtreɪd.mɑːrk/", "商標註冊標誌", "generic", "/dʒəˈner.ɪk/", "通用的未註冊商標的普適的"),
        ("To defend its trade secrets, the hedge fund requires all quantitative analysts to sign ___.", "NDAs", "NDA", "non-disclosure", "disclosing", "為全力捍衛其核心量化交易商業秘密，該對沖基金強制要求所有量化分析師入職時簽署保密協定協議書。", "NDAs (non-disclosure agreements) 為商務保密合約之標準法定簡稱複數。", "保密合約複數名詞選 NDAs。", "trade secret", "/ˈtreɪd ˌsiː.krət/", "商業機密業務祕密", "confidentiality", "/ˌkɑːn.fəˌden.ʃiˈæl.ə.t̬i/", "保密性"),
        ("The supreme court ruled that naturally occurring DNA sequences cannot be ___.", "patented", "patent", "patenting", "patentable", "最高法院全體法官一致做出具里程碑意義之司法判決，認定自然界中客觀存在之天然DNA基因序列不得申請專利。", "cannot be patented 為被動語態，意為「不得被授予專利權」。", "情態助動詞被動選 cannot be patented。", "ruling", "/ˈruː.lɪŋ/", "裁定司法判決", "patented", "/ˈpæt.ən.t̬ɪd/", "獲得專利認可的")
    ]),
    # 20. 企業永續治理與ESG環境社會標準 (Corporate Sustainability & ESG Compliance)
    ("企業永續治理與ESG環境社會標準", "商務文法", "B2-U20", [
        ("The multinational corporation committed to reducing its operational carbon ___ to net zero by 2040.", "footprint", "foot", "printing", "prints", "這家跨國大企業鄭重做出公開永續承諾，矢志在二○四○年之前將其營運碳足跡徹底降至淨零排放水準。", "carbon footprint 為環境科學與永續ESG全球核心標準名詞，意為「碳足跡」。", "碳足跡固定片語選 carbon footprint。", "commitment", "/kəˈmɪt.mənt/", "承諾奉獻投入", "carbon footprint", "/ˌkɑːr.bən ˈfʊt.prɪnt/", "碳足跡"),
        ("Institutional investors increasingly favor companies with robust environmental, social, and ___ practices.", "governance", "govern", "governing", "governmental", "國際大型機構投資法人日益青睞高度重視並落實環境保護、社會責任以及健全公司治理(ESG)之優質企業。", "environmental, social, and governance (ESG) 為全球永續投資唯一標準核心詞組。", "公司治理名詞選 governance。", "institutional", "/ˌɪn.stəˈtuː.ʃən.əl/", "機構的法人機構的", "governance", "/ˈɡʌv.ɚ.nəns/", "治理管治"),
        ("The newly constructed factory was certified as an exemplary LEED Platinum green ___.", "building", "builder", "build", "buildup", "這座甫竣工落成之嶄新現代化工廠，正式通過審核獲頒美國 LEED 白金級最高榮譽綠建築標章認證。", "green building 為環保綠建築之公認固定名詞片語，意為「綠建築」。", "綠建築名詞選 green building。", "exemplary", "/ɪɡˈzem.plɚ.i/", "模範的典範的", "building", "/ˈbɪl.dɪŋ/", "建築物大樓"),
        ("The corporate sustainability report adheres strictly to Global Reporting Initiative ___.", "standards", "standard", "standardize", "standardized", "該企業年度永續發展報告書之編撰，完全嚴格遵循國際全球永續報告倡議組織(GRI)所制定之權威編撰標準。", "GRI standards 為國際永續報導準則固定名詞，意為「GRI 準則標準」。", "準則標準複數名詞選 standards。", "sustainability", "/səˌsteɪ.nəˈbɪl.ə.t̬i/", "永續性永續發展", "standards", "/ˈstæn.dɚdz/", "標準準則規範"),
        ("Switching to renewable solar energy significantly reduced the plant's electricity ___.", "consumption", "consume", "consuming", "consumer", "工廠產線全面改採太陽能等再生綠色能源供電後，使得該廠整體用電度數與能源消耗量出現了顯著銳減。", "electricity consumption 意為「用電消耗總量」，作 reduced 之受詞。", "能源消耗名詞選 consumption。", "renewable", "/rɪˈnuː.ə.bəl/", "可再生的再生能源的", "consumption", "/kənˈsʌmp.ʃən/", "消耗用量消費"),
        ("The chemical manufacturer was heavily fined for violating municipal wastewater discharge ___.", "limits", "limited", "limiting", "limitation", "這家化學化工製造廠因非法嚴重超標排放工業污水廢水，遭到環保局處以重額罰款處分。", "discharge limits 為環境法規排放管制標準之固定名詞片語，意為「排放限值上限」。", "排放限值複數名詞選 limits。", "wastewater", "/ˈweɪstˌwɑː.t̬ɚ/", "廢水污水", "discharge", "/dɪsˈtʃɑːrdʒ/", "排放排出釋放"),
        ("Companies are held accountable by consumers for ensuring ethical sourcing throughout their ___.", "supply chains", "suppliers", "supply chain", "supplying", "現代消費者嚴格檢視各大品牌，要求其在橫跨全球之整體供應鏈體系中，必須全面百分之百落實道德採購準則。", "throughout their supply chains 意為「在整個供應鏈網絡各環節之中」。", "供應鏈名詞複數選 supply chains。", "accountable", "/əˈkaʊn.t̬ə.bəl/", "負有解釋責任的應負責的", "ethical sourcing", "/ˌeθ.ɪ.kəl ˈsɔːr.sɪŋ/", "道德採購負責任採購"),
        ("The board appointed an independent chief sustainability officer to oversee decarbonization ___.", "initiatives", "initiate", "initiating", "initiative", "董事會決議新設並延攬一位獨立永續長，全權統籌指揮與督導全集團之各項節能減碳與脫碳創新倡議行動。", "decarbonization initiatives 意為「減碳脫碳計畫倡議」，作 oversee 之受詞。", "倡議計畫複數名詞選 initiatives。", "decarbonization", "/diːˌkɑːr.bən.aɪˈzeɪ.ʃən/", "減碳去碳化脫碳", "initiative", "/ɪˈnɪʃ.ə.t̬ɪv/", "倡議新專案主導權"),
        ("The audit revealed that the apparel brand engaged in misleading environmental advertising, known as ___.", "greenwashing", "green", "whitewash", "washing", "獨立查核審計報告踢爆，該知名快時尚服飾品牌長期刊登誤導公眾之虛假環保宣傳廣告，即俗稱之「漂綠行為」。", "greenwashing 為全球永續環境治理經典術語，意為「漂綠（虛假環保宣傳）」。", "漂綠專有名詞選 greenwashing。", "misleading", "/ˌmɪsˈliː.dɪŋ/", "誤導的欺騙性的", "greenwashing", "/ˈɡriːnˌwɑː.ʃɪŋ/", "漂綠虛報環保"),
        ("Investment funds adhering to SRI guidelines exclude manufacturers of controversial ___.", "weapons", "weaponry", "weapon", "weaponless", "凡是嚴格恪遵社會責任投資(SRI)指導原則之基金，投資組合中一律嚴格剔除製造具爭議性武器之軍工軍火廠商。", "controversial weapons 為責任投資法規標準詞組，意為「具爭議性武器殺傷性軍火」。", "名詞複數選 weapons。", "adhere to", "/ədˈhɪr tuː/", "恪遵堅持遵守", "controversial", "/ˌkɑːn.trəˈvɝː.ʃəl/", "具爭議性的引起爭議的")
    ]),
    # 21. 企業公關危機與對外發言聲明 (Public Relations & Crisis Communication)
    ("企業公關危機與對外發言聲明", "商務文法", "B2-U21", [
        ("The official company spokesperson held a press conference to address allegations of accounting ___.", "fraud", "fraudulent", "fraudulently", "frauds", "公司官方指派對外發言人緊急召開國際記者會，嚴正回應社會各界針對會計做假帳涉嫌詐欺之指控。", "accounting fraud 為商務法律標準名詞詞組，意為「會計作假財務欺詐」。", "財務詐欺名詞選 fraud。", "spokesperson", "/ˈspoʊksˌpɝː.sən/", "官方發言人代言人", "fraud", "/frɑːd/", "詐欺舞弊欺詐罪"),
        ("Prompt and transparent communication is vital to mitigate reputational damage during a ___.", "crisis", "crises", "critical", "critique", "在爆發突發重大公共關係危機期間，唯有迅速且公開透明的溝通對話，方能有效遏止並淡化企業商譽損失。", "名詞 crisis 意為「危機、轉折關頭」，接在不定冠詞 a 之後作單數名詞。", "危機單數名詞選 crisis。", "transparent", "/trænˈspær.ənt/", "透明的坦誠的", "crisis", "/ˈkraɪ.sɪs/", "危機危急關頭"),
        ("The CEO issued an unreserved public apology to regain consumer confidence and ___.", "trust", "trustful", "trustingly", "trustworthy", "執行長親自發表毫無保留的公開誠懇致歉聲明，全力挽回廣大消費者的消費信心與長期品牌信任支持。", "對等連接詞 and 連接名詞 confidence，後方空格亦須使用名詞 trust。", "名詞對等選 trust。", "unreserved", "/ˌʌn.rɪˈzɝːvd/", "無保留的由衷坦率的", "trust", "/trʌst/", "信任信賴"),
        ("The public relations agency devised a damage ___ plan to contain negative viral rumors on social media.", "control", "controlling", "controlled", "controller", "這家專業危機公關顧問代理商迅速制定了一套損害控制停損計畫，全力圍堵社群網絡上的負面惡意謠言瘋傳擴散。", "damage control 為公關界核心固定名詞短語，意為「危機停損、損害控制處置」。", "危機停損片語選 damage control。", "contain", "/kənˈteɪn/", "圍堵遏制抑制", "damage control", "/ˈdæm.ɪdʒ kənˌtroʊl/", "損害控制危機處理"),
        ("The pharmaceutical company recalled thirty thousand bottles of medicine as a precautionary ___.", "measure", "measurement", "measurable", "measuring", "這家製藥公司秉持負責任態度，作為預防性安全防範處置措施，依法主動下架召回三萬瓶藥品標的物。", "precautionary measure 意為「預防措施、防範性處置」，作介系詞 as 之後受詞。", "預防措施名詞選 measure。", "precautionary", "/prɪˈkɑː.ʃən.er.i/", "預防性的防範未然的", "measure", "/ˈmeʒ.ɚ/", "措施手段辦法"),
        ("Journalists demanded that the corporation release an unedited transcript of the leaked phone ___.", "conversation", "converse", "conversing", "conversational", "各大主流媒體新聞記者一致嚴正要求，該跨國公司必須完整公開流出外洩通聯電話之原始未剪輯錄音逐字稿。", "phone conversation 意為「電話通話通聯對話」。", "名詞選 conversation。", "leaked", "/liːkt/", "洩漏的外洩的", "transcript", "/ˈtræn.skrɪpt/", "錄音逐字稿官方謄本"),
        ("The editorial board criticized the tech firm for attempting to shift blame onto its contract ___.", "workers", "working", "work", "workable", "報紙社論專欄嚴厲譴責該科技公司在出事之後，竟企圖把所有責任完全推諉轉嫁給其基層外包約聘派遣員工。", "contract workers 意為「約聘工、外包派遣勞工」。", "派遣員工複數名詞選 workers。", "editorial", "/ˌed.əˈtɔːr.i.əl/", "社論社評的", "shift blame", "/ʃɪft bleɪm/", "推諉卸責甩鍋"),
        ("Social media monitoring tools allow brand managers to gauge consumer sentiment in real ___.", "time", "timing", "timely", "times", "現代社群媒體輿情監測分析軟體工具，使品牌公關經理得以在分秒之間即時掌握並精準測量消費者之情緒傾向。", "in real time 為固定商務片語，意為「即時、同步實時地」。", "即時片語選 in real time。", "gauge", "/ɡeɪdʒ/", "測量評估測度", "sentiment", "/ˈsen.t̬ə.mənt/", "情緒觀點情感"),
        ("The corporation engaged in active philanthropy to rebuild goodwill within the local ___.", "community", "communal", "commune", "communicable", "該跨國集團積極投入在地基層慈善公益回饋活動，致力於在當地社區鄉里居民心目中重新重建良好企業聲譽善意。", "the local community 意為「在地社區、周邊群眾居民」。", "在地社區名詞選 community。", "philanthropy", "/fɪˈlæn.θrə.pi/", "慈善事業博愛慈善行為", "goodwill", "/ˌɡʊdˈwɪl/", "商譽善意好感"),
        ("The corporate communications director drafted a formal rebuttal to refute the defamatory ___.", "allegations", "allege", "alleged", "allegedly", "企業傳播溝通總監親自執筆起草了一份態度堅決的正式反駁聲明，逐條嚴正駁斥毫無根據之惡意誹謗不實指控。", "defamatory allegations 意為「誹謗性指控、惡意中傷誣指」。", "名詞複數選 allegations。", "rebuttal", "/rɪˈbʌt̬.əl/", "反駁抗辯駁斥", "defamatory", "/dɪˈfæm.ə.tɔːr.i/", "誹謗的名譽毀損的中傷的")
    ]),
    # 22. 經銷加盟特許與全球區域代理 (Franchising Agreements & Regional Distribution)
    ("經銷加盟特許與全球區域代理", "商務文法", "B2-U22", [
        ("The franchisor charges an initial franchise fee in addition to ongoing monthly royalty ___.", "payments", "pay", "paying", "payable", "連鎖加盟總部除向加盟主一次性收取初始加盟金外，按月另行定期收取持續性之營業加盟權利金分潤款項。", "royalty payments 意為「權利金給付、特許專利費繳納」。", "權利金支付款複數名詞選 payments。", "franchisor", "/ˈfræn.tʃaɪ.zɚ/", "加盟總部特許人", "royalty", "/ˈrɔɪ.əl.t̬i/", "權利金分潤專利費"),
        ("Under the dealership agreement, the distributor is granted exclusive sales rights within its designated ___.", "territory", "terror", "territorial", "territories", "依據雙邊經銷特許合約規定，該總經銷商獲全權授予在其指定劃分之地理銷售區域範圍內享有獨家專屬代理銷售權。", "designated territory 為商務分銷標準法規詞組，意為「指定專屬銷售責任區」。", "管轄區域單數名詞選 territory。", "dealership", "/ˈdiː.lɚ.ʃɪp/", "經銷權經銷商門市", "territory", "/ˈter.ə.tɔːr.i/", "領域責任區銷售範圍"),
        ("All franchisees must strictly comply with corporate operational manuals to maintain brand ___.", "consistency", "consistent", "consistently", "consist", "所有加盟店主必須嚴格恪遵總公司統一制定之營運手冊，以確保品牌在全球連鎖店之間保持高度一致性體驗。", "brand consistency 為連鎖加盟品牌核心專有名詞，意為「品牌一致性、跨店品質一致性」。", "品牌一致性名詞選 consistency。", "franchisee", "/ˌfræn.tʃaɪˈziː/", "加盟商被特許人", "consistency", "/kənˈsɪs.tən.si/", "一致性連貫性"),
        ("The master franchisee holds the exclusive right to sub-franchise restaurant locations across the entire ___.", "country", "countrywide", "countrify", "counties", "這名全權總代理特許商擁有排他專屬特權，得在該國全國範圍之內自由發展與轉授權開設次級連鎖加盟餐廳門市。", "across the entire country 意為「在全國各地範圍內」。", "單數國家名詞選 country。", "sub-franchise", "/ˌsʌbˈfræn.tʃaɪz/", "轉特許分特許加盟", "exclusive right", "/ɪkˌskluː.sɪv ˈraɪt/", "專屬排他權益"),
        ("The parent corporation supplies franchisees with standardized equipment and promotional ___.", "materials", "materialize", "materialistic", "material", "母公司定期統一為各連鎖加盟店供應標準化廚房硬體設施，以及當季最新統一印製之宣傳文宣廣告行銷材料物料。", "promotional materials 意為「宣傳文宣品、促銷物料資材」。", "宣傳文宣物料複數選 materials。", "standardized", "/ˈstæn.dɚ.daɪzd/", "標準化規範化的", "promotional materials", "/prəˈmoʊ.ʃən.əl məˈtɪr.i.əlz/", "促銷宣傳材料文宣"),
        ("Failure to maintain sanitary standards may result in immediate revocation of the franchise ___.", "license", "licensing", "licensed", "licensee", "任何加盟分店若未能維持法定最高衛生清潔標準，將可能面臨加盟特許營業執照遭總部立即吊銷撤銷之嚴厲懲處。", "revocation of the franchise license 意為「吊銷加盟營業特許授權」。", "特許執照名詞選 license。", "sanitary", "/ˈsæn.ə.ter.i/", "公共衛生的清潔衛生的", "revocation", "/ˌrev.əˈkeɪ.ʃən/", "撤銷吊銷廢止"),
        ("Prospective franchisees must demonstrate sufficient liquid net worth to qualify for site ___.", "approval", "approve", "approving", "approvingly", "有意加盟之潛在投資人，必須先行出具具備充裕變現性流動淨資產財力證明，方符合資格進入加盟設點審查通過程序。", "site approval 意為「店面設點審查核准通過」。", "審查通過名詞選 approval。", "liquid net worth", "/ˌlɪk.wɪd ˌnet ˈwɝːθ/", "流動淨資產速動淨值", "approval", "/əˈpruː.vəl/", "核准認可審批"),
        ("The contract specifies a mandatory five-year non-compete clause upon termination of the ___.", "partnership", "partner", "partnering", "partnered", "合約中明確白紙黑字規定，在雙方合作夥伴結盟關係終止解除後，受約人必須強制遵守長達五年的競業禁止限制條款。", "termination of the partnership 意為「合夥結盟合作關係之終止」。", "合夥關係名詞選 partnership。", "non-compete", "/ˌnɑːn.kəmˈpiːt/", "競業禁止的", "clause", "/klɑːz/", "條款條項"),
        ("The distributor was granted a sixty-day credit line to facilitate smooth inventory ___.", "turnover", "turn", "turning", "turnaround", "總代理商獲銀行與總部核批長達六十天的放帳融資額度，旨在有效促進貨物存貨順暢周轉流通與庫存去化速度。", "inventory turnover 為庫存供應鏈與會計核心名詞詞組，意為「存貨週轉率、庫存周轉」。", "存貨週轉名詞選 turnover。", "facilitate", "/fəˈsɪl.ə.teɪt/", "促進使順暢便利", "turnover", "/ˈtɝːnˌoʊ.vɚ/", "週轉率營業額離職率"),
        ("Disputes arising between franchisors and franchisees are routinely referred to commercial ___.", "arbitration", "arbitrate", "arbitrary", "arbitrator", "加盟連鎖總部與個別加盟店主之間所衍生之各項商務法律爭議，依慣例均一律提交由中立之商業仲裁公斷程序審理裁判。", "commercial arbitration 意為「商業仲裁公斷」，為跨國與加盟法規固定詞組。", "商業仲裁名詞選 arbitration。", "routinely", "/ruːˈtiːn.li/", "常規地按慣例地", "arbitration", "/ˌɑːr.bəˈtreɪ.ʃən/", "仲裁公斷裁決")
    ]),
    # 23. 員工在職培訓與專業職能晉升 (Corporate Training, Upskilling & Career Development)
    ("員工在職培訓與專業職能晉升", "商務文法", "B2-U23", [
        ("The human resources department launched a comprehensive upskilling program to enhance digital ___.", "literacy", "literal", "literally", "literate", "人力資源部全面啟動了一項規模宏大之在職技能升級培訓計畫，旨在全面深化全體同仁之數位素養與科技應用能力。", "digital literacy 為現代數位轉型核心教育詞組，意為「數位素養與應用能力」。", "數位素養名詞選 literacy。", "upskilling", "/ˈʌpˌskɪl.ɪŋ/", "技能提升在職進修", "literacy", "/ˈlɪt̬.ɚ.ə.si/", "識字能力素養運用能力"),
        ("Employees who demonstrate exceptional leadership qualities are identified for accelerated ___.", "promotion", "promote", "promoting", "promotional", "在工作崗位上展現出卓越卓越領導統御特質之績優員工，將獲拔擢列入快速破格升遷晉升培育名單。", "accelerated promotion 意為「快速破格晉升升遷」。", "晉升升職名詞選 promotion。", "exceptional", "/ɪkˈsep.ʃən.əl/", "卓越不凡的非凡的", "promotion", "/prəˈmoʊ.ʃən/", "升遷晉升提拔促銷"),
        ("The corporate executive coaching initiative is tailored ___ to each manager's specific development needs.", "specifically", "specific", "specificity", "specification", "這套專為企業高階主管量身打造之一對一教練輔導專案，完全係針對每位經理人獨特之職涯發展需求量身客製化擬定。", "副詞 specifically 修飾過去分詞 tailored，表示「專門特定地客製化」。", "副詞修飾動詞選 specifically。", "tailor", "/ˈteɪ.lɚ/", "量身打造客製化", "coaching", "/ˈkoʊ.tʃɪŋ/", "教練輔導專業指導"),
        ("Participation in the mandatory anti-harassment seminar is required for all newly hired ___.", "personnel", "personal", "personality", "personally", "依法令強制規定，所有新進錄取之全體正職員工，均必須全員出席並完成職場防範性騷擾防治專題研習訓練課程。", "all newly hired personnel 意為「所有新進員工全體同仁（集合名詞）」。", "全體員工選 personnel。", "mandatory", "/ˈmæn.də.tɔːr.i/", "法定的強制的義務性的", "personnel", "/ˌpɝː.sənˈel/", "全體員工全體人員"),
        ("Senior mentors provide continuous guidance to help entry-level associates cultivate critical ___.", "skills", "skillful", "skillfully", "skilled", "資深職場導師在日常工作中提供持續不斷之悉心指導，熱忱協助基層新進同仁扎實培養不可或缺之核心職場關鍵職能技能。", "cultivate critical skills 意為「培養關鍵技能核心能力」。", "技能複數名詞選 skills。", "mentor", "/ˈmen.tɔːr/", "導師良師益友", "cultivate", "/ˈkʌl.tə.veɪt/", "培養栽培耕作"),
        ("Employees are granted up to five paid days per annum to attend approved professional ___.", "conferences", "confer", "conferring", "conferment", "公司福利規章賦予每位全職員工每年享有長達五天全薪公假，得以自由報名公假出席經公司核准之外部專業學術研討大會。", "professional conferences 意為「專業學術研討會年會」。", "研討大會複數名詞選 conferences。", "per annum", "/pɚ ˈæn.əm/", "每年按年計算", "conference", "/ˈkɑːn.fɚ.əns/", "研討大會大型會議"),
        ("The online learning portal offers self-paced courses designed to accommodate demanding work ___.", "schedules", "scheduled", "scheduling", "schedulers", "公司數位線上學習學習平台特別提供自主掌握進度之自主學習課程，其設計巧思專為彈性配合員工繁忙之高壓工作日程排程。", "demanding work schedules 意為「緊湊繁重的工作日程日程表」。", "工作排程複數名詞選 schedules。", "self-paced", "/ˌselfˈpeɪst/", "自主控制進度的自主步調的", "demanding", "/dɪˈmæn.dɪŋ/", "高要求的費力的繁重的"),
        ("Cross-departmental job shadowing provides employees with broader insight into organizational ___.", "workflows", "work", "worker", "workable", "跨部門的在職影子實習見習見習計畫，讓同仁能以更宏觀全貌的視角深入洞悉整個企業組織架構運作之作業流程流轉機制。", "organizational workflows 意為「組織業務工作流程」。", "工作流程複數名詞選 workflows。", "job shadowing", "/ˈdʒɑːb ˌʃæd.oʊ.ɪŋ/", "影子實習崗位見習", "workflow", "/ˈwɝːk.floʊ/", "工作流程作業流"),
        ("Successful completion of the credentialing exam entitles the candidate to industry-recognized ___.", "certification", "certify", "certified", "certifying", "順利通過各科資格考評鑑測試合格後，該名優秀考生即有權依法獲頒廣獲全球產業界權威認可之專業執業資格證書。", "industry-recognized certification 意為「產業界公認認證資格」。", "專業認證名詞選 certification。", "credentialing", "/krəˈden.ʃəl.ɪŋ/", "證照審查資歷認證", "certification", "/ˌsɝː.t̬ə.fəˈkeɪ.ʃən/", "認證檢定合格證書"),
        ("The talent retention committee recommended establishing clearer pathways for career ___.", "advancement", "advance", "advancing", "advanced", "企業內部人才留任委員會提出建言，強烈建議高層應為基層與中階員工建立更透明清晰、有跡可循的職涯晉升發展路徑。", "career advancement 為職場人資經典名詞短語，意為「職涯晉升晉級、職涯發展」。", "職涯升遷名詞選 advancement。", "retention", "/rɪˈten.ʃən/", "留任留存保留", "advancement", "/ədˈvæns.mənt/", "前進提升晉升")
    ]),
    # 24. 遠距協作技術與混合辦公模式 (Hybrid Workforce, Telecommunications & Collaboration)
    ("遠距協作技術與混合辦公模式", "商務文法", "B2-U24", [
        ("The multinational bank adopted a hybrid model requiring employees to be in the office three days per ___.", "week", "weekly", "weekend", "weekday", "這家跨國投資銀行正式實施混合彈性辦公模式，強制規範所有全職員工每週必須至少親自進辦公室實體上班三天。", "three days per week 為表示頻率之標準固定商務用法，意為「每週三天」。", "時間頻率片語選 per week。", "hybrid model", "/ˈhaɪ.brɪd ˌmɑː.dəl/", "混合辦公模式虛實結合模式", "week", "/wiːk/", "週星期"),
        ("Virtual meeting participants are requested to mute their microphones when not actively ___.", "speaking", "spoken", "speak", "speaks", "在召開線上遠距視訊會議期間，敬請全體與會來賓在未輪到自己主動發言說話之時，主動將麥克風設為靜音以維持通話品質。", "when not actively speaking 為狀語從句省略主詞 be 動詞的分詞短語，主動發言使用 speaking。", "分詞短語主動發言選 speaking。", "virtual", "/ˈvɝː.tʃu.əl/", "虛擬的線上的", "microphone", "/ˈmaɪ.krə.foʊn/", "麥克風話筒"),
        ("Remote work arrangements have significantly reduced corporate expenditures on commercial office ___.", "space", "spacing", "spaced", "spacious", "全面推動遠距居家上班彈性政策，大幅顯著降低了企業每年在租賃商業辦公室硬體空間所耗費之龐大租金支出。", "commercial office space 為不動產與企業支出標準名詞短語，意為「商業辦公空間（不可數名詞）」。", "辦公空間名詞選 space。", "expenditure", "/ɪkˈspen.də.tʃɚ/", "支出開銷經費", "space", "/speɪs/", "空間場所"),
        ("To facilitate remote collaboration, the enterprise invested in enterprise-grade video conferencing ___.", "software", "soft", "softly", "softness", "為大幅提升遠距跨國協同溝通工作效率，該集團斥巨資採購導入企業最高安全等級之遠距視訊會議應用軟體系統。", "video conferencing software 為不可數名詞片語，意為「視訊會議軟體」。", "軟體不可數名詞選 software。", "conferencing", "/ˈkɑːn.fɚ.ən.sɪŋ/", "召開會議視訊會議", "software", "/ˈsɑːft.wer/", "軟體系統程式"),
        ("The IT department implemented a zero-trust network architecture to safeguard remote ___.", "connections", "connect", "connected", "connecting", "資訊安全工程處全面架構導入「零信任(Zero-Trust)」網路防禦體系，嚴密捍衛所有外部遠端連線通道之資安防護。", "remote connections 意為「遠端連線登入」，作 safeguard 之受詞。", "遠端連線複數名詞選 connections。", "zero-trust", "/ˌzɪr.oʊˈtrʌst/", "零信任架構的", "connection", "/kəˈnek.ʃən/", "連線連動聯結"),
        ("Team members utilize cloud-based productivity suites to collaborate on documents in real ___.", "time", "timing", "timely", "times", "全體專案小組成員廣泛利用雲端協作生產力工具套件，在同一份文件上進行即時秒級多人同步線上編輯與研討修正。", "in real time 意為「即時同步地、實時地」。", "即時片語選 in real time。", "productivity", "/ˌproʊ.dʌkˈtɪv.ə.t̬i/", "生產力工作效能", "suite", "/swiːt/", "套裝軟體套件"),
        ("Working from home has granted employees unprecedented flexibility in balancing personal and professional ___.", "commitments", "commit", "committed", "committing", "居家遠距辦公賦予了員工前所未見的高度彈性自由，使能從容平衡兼顧家庭個人事務與職場工作職責之雙重承諾承擔。", "personal and professional commitments 意為「個人家庭與職業工作之承擔事項責任」。", "職責承諾複數名詞選 commitments。", "unprecedented", "/ʌnˈpres.ə.den.t̬ɪd/", "史無前例的前所未有的", "commitment", "/kəˈmɪt.mənt/", "承諾承擔義務責任事項"),
        ("The company established ergonomic equipment subsidies to assist employees setting up home ___.", "offices", "office", "officially", "officer", "公司特別提撥專款設立了人體工學辦公設備補助款，全力實質資助員工在自家住宅內部建置舒適安全之居家個人辦公室。", "home offices 意為「居家個人工作辦公室空間」。", "居家辦公室複數選 offices。", "ergonomic", "/ˌɝː.ɡəˈnɑː.mɪk/", "人體工學的", "subsidy", "/ˈsʌb.sə.di/", "補助金津貼"),
        ("Asynchronous communication allows distributed global teams to coordinate across different time ___.", "zones", "zone", "zoning", "zoned", "非同步跨時差溝通工作模式，使分散在全球各大洲的跨國遠距團隊得以跨越不同時區限制，順暢推進各項業務運作。", "time zones 為地理與國際商務標準名詞詞組，意為「時區」。", "時區複數名詞選 zones。", "asynchronous", "/eɪˈsɪŋ.krə.nəs/", "非同步的不同時的", "time zone", "/ˈtaɪm ˌzoʊn/", "時區時差區"),
        ("Managers evaluate remote workers based on measurable outcomes rather than sheer hours spent at a ___.", "desk", "desktop", "deskbound", "desks", "現代化前瞻主管評鑑遠距同仁之標準，完全聚焦於實質可量化之成果產出品質，而非虛浮地緊盯同仁在辦公桌前枯坐了多少工時。", "hours spent at a desk 意為「坐在辦公桌前的工時時數」。", "辦公桌單數名詞選 desk。", "measurable", "/ˈmeʒ.ɚ.ə.bəl/", "可量化的可測量的", "outcome", "/ˈaʊt.kʌm/", "成果產出結局")
    ]),
    # 25. 內部稽核機制與反貪腐法規遵循 (Internal Audits, Anti-Corruption & Regulatory Compliance)
    ("內部稽核機制與反貪腐法規遵循", "商務文法", "B2-U25", [
        ("The whistleblower hotline allows employees to report fraudulent activities with complete ___.", "anonymity", "anonymous", "anonymously", "anonymities", "公司特別建置之吹哨者通報專線，使全體同仁在向稽核室檢舉違法舞弊財務不法情事時，個人身分能獲得百分之百之絕對匿名保障。", "with complete anonymity 意為「在完全匿名的保護狀態下」。", "介系詞後接名詞 anonymity。", "whistleblower", "/ˈwɪs.əlˌbloʊ.ɚ/", "吹哨者內部揭弊者", "anonymity", "/ˌæn.əˈnɪm.ə.t̬i/", "匿名無名隱姓埋名"),
        ("The compliance officer conducts periodic anti-bribery training to ensure adherence to the Foreign Corrupt ___ Act.", "Practices", "Practice", "Practicing", "Practitioner", "法遵主管定期舉辦防範行賄貪腐之專題法規遵循教育訓練，以確保全體海外外派同仁完全嚴格遵守美國《海外反腐敗法》(FCPA)。", "Foreign Corrupt Practices Act (FCPA) 為國際反腐敗核心法規之官方全稱法定專有名詞。", "法律名詞大寫專有選 Practices。", "adherence", "/ədˈhɪr.əns/", "堅持恪遵依從", "Practices", "/ˈpræk.tɪs.ɪz/", "常規行為法規"),
        ("Independent auditors scrutinized all ledger entries to verify the integrity of the financial ___.", "statements", "statement", "stating", "stated", "外部獨立會計審計師逐筆嚴格檢視總分類帳上之每一筆會計分錄，以查核確認企業全年度財務報表之真實公允性與完整誠信性。", "financial statements 為會計財務報表之標準固定複數名詞詞組，意為「財務報表」。", "財務報表複數名詞選 statements。", "scrutinize", "/ˈskruː.t̬ən.aɪz/", "仔細審查嚴密檢查", "financial statement", "/faɪˌnæn.ʃəl ˈsteɪt.mənt/", "財務報表"),
        ("Any executive found guilty of insider trading will face severe statutory ___ including imprisonment.", "penalties", "penalty", "penal", "penalizing", "任何涉嫌內線交易內幕買賣並經司法機關判決有罪定讞之高階經理人，均將面臨包括徒刑牢獄在內之極嚴厲法定刑事民事制裁處罰。", "statutory penalties 意為「法定處罰制裁刑責」，作 face 之受詞。", "懲罰處罰複數名詞選 penalties。", "insider trading", "/ˌɪn.saɪ.dɚ ˈtreɪ.dɪŋ/", "內線交易內幕交易", "penalty", "/ˈpen.əl.ti/", "處罰刑罰違約金"),
        ("The corporation implemented strict internal controls to prevent unauthorized disbursement of corporate ___.", "funds", "fund", "funded", "funding", "該跨國集團全面落實了滴水不漏之嚴密內部控制防弊機制，旨在嚴防任何人擅自未經核准越權挪用或撥付企業公款公費資金。", "corporate funds 意為「企業營運資金、公款」，作 disbursement of 之受詞。", "公款資金複數名詞選 funds。", "disbursement", "/dɪsˈbɝːs.mənt/", "撥款支出發放", "funds", "/fʌndz/", "資金款項經費"),
        ("The regulatory agency imposed a hefty fine on the financial institution for systemic compliance ___.", "failures", "fail", "failed", "failing", "金管監督主管機關針對該大型金融機構所存在之系統性法規遵循重大疏失漏洞，依法從重開出了鉅額行政裁罰罰款處分。", "compliance failures 意為「法規遵循疏失破口、合規失敗」。", "合規失敗複數名詞選 failures。", "impose", "/ɪmˈpoʊz/", "課徵強加處以", "failure", "/ˈfeɪ.ljɚ/", "失靈疏失失敗未履行"),
        ("All prospective suppliers must undergo rigorous anti-money-laundering screening prior to onboarding ___.", "approval", "approve", "approving", "approved", "所有有意申請成為合格供應商之外部廠商，在正式取得入冊核准資格之前，均必須依法接受最嚴苛之反洗錢背景資格過濾審查。", "onboarding approval 意為「入職或供應商入冊核准審批」。", "審批名詞選 approval。", "anti-money-laundering", "/ˌæn.ti ˈmʌn.i ˌlɑːn.dɚ.ɪŋ/", "反洗錢打擊洗錢的", "screening", "/ˈskriː.nɪŋ/", "審查篩檢排查"),
        ("The board of directors established an independent oversight committee tasked with reviewing executive ___.", "compensation", "compensate", "compensating", "compensatory", "公司董事會特別依法設立了一座高規格獨立監察審議委員會，全權專責定期深入審查與評定全體高階主管之薪酬獎金結構政策。", "executive compensation 為公司治理核心名詞詞組，意為「高階主管薪酬待遇」。", "高管薪酬名詞選 compensation。", "oversight", "/ˈoʊ.vɚ.saɪt/", "監管監督失察", "compensation", "/ˌkɑːm.penˈseɪ.ʃən/", "薪酬報酬補償"),
        ("A comprehensive audit trail is automatically generated to log every transaction and record ___.", "alteration", "alter", "altered", "altering", "系統會全自動生成一套周延完整的數位稽核軌跡紀錄檔，巨細靡遺詳實記錄每一筆帳務交易過程以及所有歷史紀錄之修改更動細節。", "record alteration 意為「紀錄變更修改篡改」，接在 and 後方作 log 之受詞。", "變更修改名詞選 alteration。", "audit trail", "/ˈɑː.dɪt ˌtreɪl/", "稽核軌跡查核追蹤線索", "alteration", "/ˌɑːl.təˈreɪ.ʃən/", "變更修改改動"),
        ("The ethics committee reaffirmed its zero-tolerance policy regarding bribery and corporate ___.", "corruption", "corrupt", "corrupting", "corruptly", "企業倫理道德委員會在年會中嚴正重申，本集團對任何行賄受賄與貪污腐敗行為，堅決貫徹零容忍絕對不寬貸之強硬方針態度。", "corporate corruption 意為「企業貪腐貪瀆舞弊」，作 regarding 之受詞。", "企業貪腐名詞選 corruption。", "reaffirm", "/ˌriː.əˈfɝːm/", "重申再次確認", "corruption", "/kəˈrʌp.ʃən/", "貪腐腐敗受賄")
    ])
]
