"""tier4_shs_gsat.py - Tier 4: 高中學測核心素養 (SHS GSAT B1~B2) 250 Questions Generator.
IDs: diag-0751 to diag-1000.
"""

def make_q(q_id, subtopic, dim, hook, prompt, corr, d1, d2, d3, trans, concept, analysis, trap, w1, p1, m1, w2, p2, m2):
    ans_idx = (q_id - 1) % 4
    d_list = [d1, d2, d3]
    options = []
    d_ptr = 0
    for i in range(4):
        if i == ans_idx:
            options.append(corr)
        else:
            options.append(d_list[d_ptr])
            d_ptr += 1

    opt_letters = ["A", "B", "C", "D"]
    ans_letter = opt_letters[ans_idx]

    formatted_trans = f"【題幹精譯】{trans}\n【選項列表】" + "  ".join([
        f"{opt_letters[i]}. {options[i]}" for i in range(4)
    ])
    full_trap = f"【選項剖析】正確答案為 ({ans_letter})「{corr}」。{trap}"

    return {
        "id": f"diag-{q_id:04d}",
        "tier": 4,
        "tierLabel": "Level 4: 高中學測核心素養 (SHS GSAT B1~B2)",
        "targetExam": "高中學測",
        "cefr": "B2",
        "dimension": dim,
        "subtopic": subtopic,
        "difficulty": 3,
        "passage": None,
        "prompt": prompt,
        "options": options,
        "answer": ans_idx,
        "translation": formatted_trans,
        "coreConcept": concept,
        "sentenceAnalysis": analysis,
        "vocabulary": [
            {"word": w1, "phonetic": p1, "meaning": m1},
            {"word": w2, "phonetic": p2, "meaning": m2}
        ],
        "trapExplanation": full_trap,
        "courseHook": hook
    }

def build_tier4():
    items = []
    
    subtopics_data = [
        # 1. 分詞構句 (現在分詞主動 V-ing 與過去分詞被動 V-ed)
        ("分詞構句 (現在分詞主動 V-ing 與過去分詞被動 V-ed)", "文法句構", [
            ("___ by the devastating earthquake, the historic village was rebuilt through international aid.", "Destroyed", "Destroying", "Having destroyed", "Destroy", "歷史悠久的村落遭毀滅性地震摧毀後，在國際援助下得以重建。", "分詞構句邏輯主詞為 the historic village，與動詞 destroy 之間為「被動」關係，使用過去分詞 Destroyed 開頭。", "過去分詞表被動 Destroyed by...", "devastating", "/ˈdev.ə.steɪ.t̬ɪŋ/", "毀滅性的", "rebuild", "/ˌriːˈbɪld/", "重建"),
            ("___ the summit after ten arduous hours of trekking, the mountaineers cheered in triumph.", "Reaching", "Reached", "Having been reached", "To reach", "歷經十個小時艱苦跋涉登上頂峰後，登山者們發出了勝利的歡呼。", "邏輯主詞 the mountaineers 主動執行 reach動作，主動關係使用現在分詞 Reaching。", "主動分詞構句選 Reaching。", "arduous", "/ˈɑːr.dʒu.əs/", "艱辛費力的", "triumph", "/ˈtraɪ.əmf/", "勝利凱旋"),
            ("___ by ancient pine trees, the secluded Zen monastery offered a haven of absolute tranquility.", "Surrounded", "Surrounding", "Having surrounded", "Surround", "被古老松樹所環繞的幽靜禪院提供了一個極致安詳的庇護所。", "邏輯主詞 the monastery 被松樹環繞，被動使用過去分詞 Surrounded。", "被動狀態選 Surrounded by...", "secluded", "/səˈkluː.dɪd/", "幽靜隱蔽的", "tranquility", "/træŋˈkwɪl.ə.t̬i/", "安詳平靜"),
            ("___ her heavy backpack on the bench, Emily sat down to quench her thirst with cold water.", "Placing", "Placed", "Having placed to", "To be placed", "把沉重的背包放在長凳上後，Emily 坐下來喝涼水解渴。", "Emily 主動放下背包，現在分詞 Placing 表伴隨動作。", "主動分詞構句選 Placing。", "quench", "/kwentʃ/", "解渴撲滅", "thirst", "/θɝːst/", "口渴"),
            ("___ of the impending typhoon, the coastal fishermen securely anchored all their vessels.", "Warned", "Warning", "Having warned", "Warn", "接到即將來襲之颱風的預警後，沿海漁民將所有船隻牢牢拋錨固定。", "漁民「被警告預警」，被動語態使用過去分詞 Warned of...", "被動接警告選 Warned of。", "impending", "/ɪmˈpen.dɪŋ/", "即將發生的", "vessel", "/ˈves.əl/", "船隻大船"),
            ("___ through the telescope with intense curiosity, the astronomer detected an uncharted comet.", "Peering", "Peered", "Having peered to", "Peer", "懷著強烈的好奇心透過望遠鏡凝視時，天文學家發現了一顆未登錄的彗星。", "天文學家主動凝視 (peer through)，使用現在分詞 Peering。", "主動觀察分詞選 Peering。", "telescope", "/ˈtel.ə.skoʊp/", "望遠鏡", "comet", "/ˈkɑː.mɪt/", "彗星"),
            ("___ in elegant calligraphy, the ancient poem hung prominently in the center of the tea room.", "Inscribed", "Inscribing", "Having inscribed", "Inscribe", "以優雅書法題寫的那首古詩醒目地懸掛在茶室中央。", "古詩被題寫銘刻，使用過去分詞 Inscribed in...", "被題寫刻記選 Inscribed。", "calligraphy", "/kəˈlɪɡ.rə.fi/", "書法藝術", "inscribe", "/ɪnˈskraɪb/", "題寫刻記"),
            ("___ from chronic insomnia, Leo consulted a neurologist specializing in sleep disorders.", "Suffering", "Suffered", "Having suffered to", "Suffer", "長期飽受慢性失眠之苦的 Leo 諮詢了一位專精睡眠障礙的神經科醫生。", "Leo 主動承受受苦 (suffer from)，使用現在分詞 Suffering。", "主動受苦狀態選 Suffering from。", "insomnia", "/ɪnˈsɑːm.ni.ə/", "失眠症", "neurologist", "/nʊˈrɑː.lə.dʒɪst/", "神經科醫生"),
            ("___ into English, the masterpiece attained worldwide acclaim and prestigious literary prizes.", "Translated", "Translating", "Having translated", "Translate", "譯成英文之後，該名著獲得了全球讚譽與享有盛譽的文學獎項。", "名著被翻譯成英文，被動使用過去分詞 Translated into...", "被翻譯選 Translated into。", "acclaim", "/əˈkleɪm/", "讚譽讚賞", "prestigious", "/presˈtɪdʒ.əs/", "享有盛譽的"),
            ("___ his bicycle key at home, Tony had to walk forty minutes in the sweltering heat.", "Having forgotten", "Forgotten", "Forgot", "To forget", "把腳踏車鑰匙忘在家裡後，Tony 不得不在酷熱中步行四十分鐘。", "遺忘動作發生在步行之前，完成分詞 Having forgotten 強調動作先後順序。", "完成分詞強調先發生選 Having forgotten。", "sweltering", "/ˈswel.tɚ.ɪŋ/", "悶熱酷熱的", "heat", "/hiːt/", "熱度高溫")
        ]),
        # 2. 獨立分詞構句與介系詞 with + O + OC
        ("獨立分詞構句與介系詞 with + O + OC", "文法句構", [
            ("The professor delivered the lecture with his arms ___ across his chest.", "folded", "folding", "fold", "to fold", "教授在胸前雙臂交叉抱胸發表了演講。", "with + 受詞 (his arms) + 受詞補語 (folded)：雙臂被交叉，使用過去分詞 folded！", "with + O + p.p. 抱胸選 folded。", "lecture", "/ˈlek.tʃɚ/", "演講", "chest", "/tʃest/", "胸膛"),
            ("The energetic puppy sat by the door with its tail ___ enthusiastically.", "wagging", "wagged", "wag", "to wag", "活力充沛的小狗坐在門旁，尾巴熱情地搖擺著。", "with + 受詞 (its tail) + 現在分詞 (wagging)：尾巴主動搖擺，使用 wagging！", "with + O + V-ing 主動擺動選 wagging。", "wag", "/wæɡ/", "搖擺晃動", "enthusiastically", "/ɪnˌθuː.ziˈæs.tɪ.kəl.i/", "熱情熱烈地"),
            ("With night ___ rapidly over the forest, the campers decided to pitch their tents.", "falling", "fallen", "fell", "fall", "隨著黑夜迅速籠罩森林，露營者們決定搭起帳篷。", "with + night + falling（夜幕降臨主動動態），選現在分詞 falling。", "with + O + V-ing 降臨選 falling。", "pitch", "/pɪtʃ/", "搭設帳篷", "rapidly", "/ˈræp.ɪd.li/", "迅速地"),
            ("Emily studied peacefully in her bedroom with the soft lamp light ___ above her desk.", "glowing", "glowed", "glow", "to glow", "Emily 在臥室裡安靜地讀書，書桌上方的柔和檯燈光芒靜靜映照著。", "with the light glowing 主動發光，使用現在分詞 glowing。", "光芒閃爍選 glowing。", "glow", "/ɡloʊ/", "發光照耀", "peacefully", "/ˈpiːs.fəl.i/", "安寧祥和地"),
            ("With all the tickets ___, latecomers were unfortunately turned away at the gate.", "sold out", "selling out", "sell out", "to sell out", "所有門票均已售罄，遲到者遺憾地在門口被拒之門外。", "門票全部被售罄，過去分詞 sold out 作受詞補語。", "門票售罄被動選 sold out。", "latecomer", "/ˈleɪtˌkʌm.ɚ/", "遲到者", "unfortunately", "/ʌnˈfɔːr.tʃən.ət.li/", "遺憾地"),
            ("The suspect stood motionless before the detective with his head ___ in shame.", "bowed", "bowing", "bow", "to bow", "嫌疑犯站在刑警面前一動也不動，羞愧地低垂著頭。", "頭部被低垂，with his head bowed in shame。", "低頭垂首選 bowed。", "suspect", "/ˈsʌs.pekt/", "嫌疑犯", "motionless", "/ˈmoʊ.ʃən.ləs/", "靜止不動的"),
            ("With exam week ___ next Monday, students are flocking to the university library.", "approaching", "approached", "approach", "to approach", "隨著考試週下週一即將來臨，學生們正湧向大學圖書館。", "時間期程主動逼近，with exam week approaching。", "時光逼近選 approaching。", "approach", "/əˈproʊtʃ/", "接近逼近", "flock", "/flɑːk/", "群聚湧入"),
            ("Tony walked in the freezing blizzard with his hands firmly ___ into his coat pockets.", "thrust", "thrusting", "thrusted", "to thrust", "Tony 在刺骨暴風雪中行走，雙手緊緊插在大衣口袋裡。", "thrust（插進）三態同形 (thrust - thrust - thrust)，雙手被插入選 thrust。", "雙手被插入選 thrust。", "blizzard", "/ˈblɪz.ɚd/", "暴風雪", "pocket", "/ˈpɑː.kɪt/", "口袋"),
            ("Weather ___, the annual school sports championship will commence at 8:00 a.m.", "permitting", "permitted", "permits", "to permit", "若天氣條件允許，一年一度的學校體育錦標賽將於上午8:00正式開始。", "Weather permitting 為獨立分詞構句慣用語（若天氣許可）。", "獨立分詞慣用語選 Weather permitting。", "commence", "/kəˈmens/", "開始啟動", "annual", "/ˈæn.ju.əl/", "年度的"),
            ("Time ___, we would like to explore the ancient botanical conservatory further.", "permitting", "permitted", "permits", "permit", "若時間充裕允許，我們希望能進一步探索這座古老植物溫室。", "Time permitting 獨立分詞慣用結構（若時間允許）。", "時間允許選 Time permitting。", "conservatory", "/kənˈsɝː.və.tɔːr.i/", "溫室植物園", "explore", "/ɪkˈsplɔːr/", "探索研析")
        ]),
        # 3. 與現在事實相反之假設語氣 (If S were/V-ed, S would V)
        ("與現在事實相反之假設語氣 (If S were/V-ed, S would V)", "文法句構", [
            ("If I ___ you, I would consult a licensed physician before taking that medication.", "were", "was", "am", "would be", "如果我是你，我在服用那項藥物之前一定會先諮詢執業醫師。", "與現在事實相反的假設語氣，if 子句 be 動詞在正式文法上一律使用 were！", "與現在相反假設 be動詞用 were。", "physician", "/fɪˈzɪʃ.ən/", "內科醫生", "consult", "/kənˈsʌlt/", "諮詢請教"),
            ("If Leo ___ sufficient financial capital, he would launch his own tech startup.", "had", "has", "would have", "had had", "如果 Leo 擁有充足的資金資本，他就會開創自己的科技新創公司。", "與現在事實相反，if 子句動詞使用過去式 had，主要子句使用 would + 原形動詞。", "與現在相反動詞過去式 had。", "startup", "/ˈstɑːrt.ʌp/", "新創公司", "capital", "/ˈkæp.ə.t̬əl/", "資本資金"),
            ("Emily would travel around the globe if she ___ from severe flight anxiety.", "did not suffer", "does not suffer", "would not suffer", "had not suffered", "如果 Emily 不是飽受嚴重飛行焦慮之苦，她就會環遊世界。", "主要子句為 would travel，條件子句需用過去否定式 did not suffer。", "與現在相反否定選 did not suffer。", "anxiety", "/æŋˈzaɪ.ə.t̬i/", "焦慮不安", "globe", "/ɡloʊb/", "全球地球"),
            ("If we ___ wings like migratory birds, we could soar freely across the ocean.", "had", "have", "would have", "had had", "如果我們像候鳥一樣擁有翅膀，我們就能自由翱翔飛越海洋。", "與人類現在事實相反，使用過去式 had，主要子句搭配 could soar。", "與現在相反條件選 had。", "migratory", "/ˈmaɪ.ɡrə.tɔːr.i/", "遷徙候鳥的", "soar", "/sɔːr/", "翱翔騰空"),
            ("What ___ you do if you suddenly won a ten-million-dollar lottery jackpot?", "would", "will", "did", "do", "如果你突然中了千萬美元的樂透頭彩，你將會怎麼做？", "條件子句為過去式 won（純假設），主要子句疑問句需搭配 would you do。", "假設語氣主要子句選 would。", "lottery", "/ˈlɑː.t̬ɚ.i/", "樂透彩券", "jackpot", "/ˈdʒæk.pɑːt/", "頭彩累積大獎"),
            ("If the historic library ___ open on weekends, more community members would visit.", "were", "is", "was being", "would be", "如果這座歷史圖書館週末開放的話，會有更多社區民眾前來參觀。", "與現狀相反假設，be 動詞使用 were。", "與現在相反選 were。", "community", "/kəˈmjuː.nə.t̬i/", "社區公眾", "visit", "/ˈvɪz.ɪt/", "參觀造訪"),
            ("Tony could easily solve this intricate riddle if he ___ more attentive in class.", "were", "is", "was being", "has been", "如果 Tony 上課更專注一點的話，他就能輕易解開這道複雜的謎題。", "條件子句與現在事實相反，be 動詞使用 were。", "與現在相反選 were。", "attentive", "/əˈten.tɪv/", "專注留心的", "intricate", "/ˈɪn.trə.kət/", "複雜精巧的"),
            ("If my brother ___ French, he would definitely apply for the Paris internship.", "spoke", "speaks", "would speak", "had spoken", "如果我哥哥會法語的話，他絕對會申請巴黎的實習職位。", "現在不會法語的純假設，if 子句使用過去式 spoke。", "與現在相反選 spoke。", "internship", "/ˈɪn.tɝːn.ʃɪp/", "實習職位", "apply", "/əˈplaɪ/", "申請"),
            ("I ___ that expensive sports car even if I had millions of dollars.", "would not buy", "will not buy", "did not buy", "had not bought", "即便我擁有數百萬美元，我也不會購買那輛昂貴的跑車。", "主要子句假設結果使用 would not buy。", "假設語氣主要子句選 would not buy。", "expensive", "/ɪkˈspen.sɪv/", "昂貴的", "sports car", "/ˈspɔːrts ˌkɑːr/", "跑車"),
            ("If the earth ___ stop rotating, life as we know it would instantly collapse.", "were to", "was to", "is to", "will", "假若地球未來萬一停止轉動，我們所知的生命將瞬間崩潰。", "表示對未來極不可能實現的假設，if 子句使用 were to + V！", "未來不可能實現假設選 were to。", "rotate", "/ˈroʊ.teɪt/", "旋轉轉動", "collapse", "/kəˈlæps/", "瓦解崩潰")
        ]),
        # 4. 與過去事實相反之假設語氣 (If S had p.p., S would have p.p.)
        ("與過去事實相反之假設語氣 (If S had p.p., S would have p.p.)", "文法句構", [
            ("If Tony ___ the warning signs, he would not have fallen into the treacherous ditch.", "had noticed", "noticed", "would notice", "would have noticed", "如果 Tony 當時注意到了警告標誌，他就不會掉進危險的溝渠裡了。", "與過去事實相反的假設：if 子句使用過去完成式 (had + p.p.)，主要子句使用 would have + p.p.！", "與過去事實相反條件子句選 had noticed。", "treacherous", "/ˈtretʃ.ɚ.əs/", "危險陰險的", "ditch", "/dɪtʃ/", "溝渠排水溝"),
            ("We ___ the flight if the taxi driver had not taken that clever shortcut.", "would have missed", "missed", "would miss", "had missed", "如果計程車司機當時沒有走那條巧妙的捷徑，我們早就錯過那班飛機了。", "與過去相反主要子句：would have + p.p. (missed)。", "與過去相反主要子句選 would have missed。", "shortcut", "/ˈʃɔːrt.kʌt/", "捷徑近路", "flight", "/flaɪt/", "航班"),
            ("If the emergency brake ___ immediately, the catastrophe would have been unavoidable.", "had not functioned", "did not function", "would not function", "has not functioned", "如果緊急剎車當時沒有立刻發揮作用，那場災難原本是無可避免的。", "條件子句與過去事實相反，使用 had not functioned。", "過去假設條件選 had not functioned。", "catastrophe", "/kəˈtæs.trə.fi/", "重大災難", "unavoidable", "/ˌʌn.əˈvɔɪ.də.bəl/", "無可避免的"),
            ("Emily would have secured first place if she ___ that minor calculation error.", "had not made", "did not make", "would not make", "has not made", "如果 Emily 當時沒有犯下那個微小的計算錯誤，她原本早就奪得第一名了。", "if 條件子句與過去相反，使用 had not made。", "與過去相反選 had not made。", "calculation", "/ˌkæl.kjəˈleɪ.ʃən/", "計算算術", "minor", "/ˈmaɪ.nɚ/", "微小的"),
            ("If the firefighter ___ into the burning building, the child would not have survived.", "had not rushed", "did not rush", "would not rush", "has not rushed", "如果消防員當時沒有衝進燃燒的大樓，那名孩童就不可能生還。", "與過去事實相反，if 子句使用 had not rushed。", "與過去相反條件選 had not rushed。", "survive", "/sɚˈvaɪv/", "倖免生還", "firefighter", "/ˈfaɪrˌfaɪ.t̬ɚ/", "消防員"),
            ("I ___ you the confidential details yesterday if you had asked me discreetly.", "would have told", "told", "would tell", "had told", "如果你昨天謹慎詢問我，我原本早就把機密細節告訴你了。", "主要子句過去虛擬：would have told。", "過去假設主要子句選 would have told。", "discreetly", "/dɪˈskriːt.li/", "謹慎審慎地", "confidential", "/ˌkɑːn.fəˈden.ʃəl/", "機密的"),
            ("If the weather ___ so stormy, the outdoor graduation ceremony would have proceeded.", "had not been", "was not", "would not be", "is not", "如果當時天氣沒有如此狂風暴雨，室外畢業典禮原本是會繼續進行的。", "if 子句與過去事實相反，使用 had not been。", "與過去相反 be動詞選 had not been。", "stormy", "/ˈstɔːr.mi/", "暴風雨的", "proceed", "/proʊˈsiːd/", "進行開展"),
            ("The patient would have recovered much faster if he ___ the physician's prescription.", "had followed", "followed", "would follow", "has followed", "如果該病患當時遵照了醫師的處方，他原本能康復得快得多。", "if 條件子句與過去相反，選 had followed。", "遵照處方過去相反選 had followed。", "prescription", "/prɪˈskrɪp.ʃən/", "處方箋", "physician", "/fɪˈzɪʃ.ən/", "醫生"),
            ("If the alarm system ___ activated, the burglar would have stolen the valuable antique.", "had not been", "was not", "is not", "would not be", "如果警報系統當時沒有被啟動，竊賊原本早就把珍貴古董偷走了。", "過去被動假設：had not been activated。", "過去被動假設選 had not been activated。", "burglar", "/ˈbɝː.ɡlɚ/", "竊賊闖空門者", "antique", "/ænˈtiːk/", "古董珍品"),
            ("They would have perished in the blizzard if the mountain rescue patrol ___ them.", "had not located", "did not locate", "would not locate", "has not located", "如果山難搜救巡邏隊當時沒有找到他們，他們早就喪命在暴風雪中了。", "與過去事實相反條件子句，選 had not located。", "過去條件假設選 had not located。", "perish", "/ˈper.ɪʃ/", "喪命罹難", "patrol", "/pəˈtroʊl/", "巡邏隊")
        ]),
        # 5. 錯綜條件假設語氣 (混合過去與現在時間點)
        ("錯綜條件假設語氣 (混合過去與現在時間點)", "文法句構", [
            ("If Tony ___ hard for the entrance exam last year, he would be studying at NTU now.", "had studied", "studied", "would study", "studies", "如果 Tony 去年有為入學考試努力讀書，他現在就會在台大讀書了。", "錯綜條件句：條件子句描述過去 (last year) 用 had studied，主要子句描述現在 (now) 用 would be studying！", "過去動作影響現在狀態，條件句選 had studied。", "entrance", "/ˈen.trəns/", "入學入口", "exam", "/ɪɡˈzæm/", "考試"),
            ("If we had taken the earlier express train, we ___ stuck in this traffic jam right now.", "would not be", "would not have been", "were not", "are not", "如果我們當時搭了較早的特快車，我們現在就不會被困在交通堵塞中了。", "主要子句有明確時間副詞 right now，結果落在「現在」，使用 would not be！", "主要子句落在現在選 would not be。", "stuck", "/stʌk/", "卡住動彈不得", "jam", "/dʒæm/", "塞車"),
            ("If Emily ___ French when she lived in Paris, she would easily land this translator job today.", "had learned", "learned", "learns", "would learn", "如果 Emily 當年住在巴黎時有學法語，她今天就能輕易獲得這份翻譯工作。", "條件子句描述過去 (in Paris) 用 had learned，主要子句影響今天 (today)。", "過去條件影響現在選 had learned。", "translator", "/trænsˈleɪ.t̬ɚ/", "翻譯人員", "land", "/lænd/", "獲得謀得"),
            ("If you had saved your pocket money wisely in middle school, you ___ sufficient funds for college today.", "would have", "would have had", "had", "have", "如果你在國中時有明智地存零用錢，你今天就會有充足的大學基金了。", "主要子句描述今天 (today) 持有的狀態，使用 would have！", "現在結果選 would have。", "fund", "/fʌnd/", "資金基金", "sufficient", "/səˈfɪʃ.ənt/", "充足的"),
            ("If the doctor ___ the rare disease in its infancy, the patient would be thriving today.", "had diagnosed", "diagnosed", "diagnoses", "would diagnose", "如果醫生在該罕見疾病初期就診斷出來，該病患今天就會健康茁壯地活著。", "條件子句指過去初期 (in infancy) 用 had diagnosed，主要子句指今日 (today)。", "過去診斷影響今日選 had diagnosed。", "infancy", "/ˈɪn.fən.si/", "幼年初期", "thrive", "/θraɪv/", "繁榮茁壯成長"),
            ("If the historic bridge had been properly reinforced decades ago, it ___ usable today.", "would still be", "would still have been", "is still", "was still", "如果這座歷史名橋數十年前有獲得妥善加固，它今天就依然能夠通行使用。", "主要子句指今日狀況 (today)，使用 would still be。", "今日狀態選 would still be。", "reinforce", "/ˌriː.ɪnˈfɔːrs/", "加固增強", "usable", "/ˈjuː.zə.bəl/", "可使用的"),
            ("If I had accepted that lucrative overseas job offer last year, I ___ living in Tokyo now.", "would be", "would have been", "am", "was", "如果我去年接受了那份優渥的海外工作錄取，我現在就會生活在東京了。", "now 提示現在正在進行的假設狀態，使用 would be living。", "現在進行假設選 would be。", "lucrative", "/ˈluː.krə.t̬ɪv/", "有利可圖優渥的", "overseas", "/ˌoʊ.vɚˈsiːz/", "海外的"),
            ("If the team had secured the championship last season, they ___ celebrated as legends today.", "would be", "would have been", "are", "were", "如果該隊在上個賽季奪得了總冠軍，他們今天就會被尊為傳奇英雄了。", "today 提示今日之名譽狀態，選 would be。", "今日評價選 would be。", "legend", "/ˈledʒ.ənd/", "傳奇傳奇人物", "championship", "/ˈtʃæm.pi.ən.ʃɪp/", "錦標賽冠軍"),
            ("If Dad ___ his investments wisely years ago, our family would enjoy financial freedom now.", "had diversified", "diversified", "diversifies", "would diversify", "如果爸爸數年前有多角化分散投資，我們全家現在就能享受財務自由了。", "條件子句描述數年前 (years ago) 需用 had diversified。", "過去投資動作選 had diversified。", "diversify", "/daɪˈvɝː.sə.faɪ/", "多角化分散", "freedom", "/ˈfriː.dəm/", "自由"),
            ("If the scientist hadn't dedicated his life to research, our society ___ this vaccine today.", "would not possess", "would not have possessed", "did not possess", "does not possess", "如果該科學家當年沒有獻身於研究，我們社會今天就不可能擁有這種疫苗。", "today 提示現在持有的狀態，選 would not possess。", "今日持有狀態選 would not possess。", "dedicate", "/ˈded.ə.keɪt/", "奉獻投入", "possess", "/pəˈzes/", "擁有持有")
        ])
    ]
    
    # Define remaining 20 subtopics (subtopics 6 to 25)
    remaining_subtopics_4 = [
        # 6. 否定副詞置於句首之主謂倒裝 (Never, Seldom, Rarely, Hardly)
        ("否定副詞置於句首之主謂倒裝 (Never, Seldom, Hardly)", "文法句構", [
            ("Seldom ___ such an inspiring oratorical performance on a public stage.", "have I witnessed", "I have witnessed", "did I witness", "I witnessed", "我極少在公眾舞台上看見如此激勵人心的雄辯演講。", "否定副詞 Seldom 置於句首時，句子需採「主謂倒裝」：助動詞 (have) + 主詞 (I) + p.p. (witnessed)。", "否定副詞句首倒裝選 have I witnessed。", "oratorical", "/ˌɔːr.əˈtɔːr.ɪ.kəl/", "演說雄辯的", "witness", "/ˈwɪt.nəs/", "目擊目睹"),
            ("Never ___ that the modest student would invent a revolutionary green technology.", "did I imagine", "I imagined", "had I imagined", "I have imagined", "我絕未料想到這位謙遜的學生竟會發明出革命性的綠色科技。", "否定副詞 Never 置於句首，過去式主謂倒裝：did + I + imagine。", "Never 句首倒裝選 did I imagine。", "revolutionary", "/ˌrev.əˈluː.ʃən.er.i/", "革命性的", "modest", "/ˈmɑː.dɪst/", "謙遜謙恭的"),
            ("Hardly ___ asleep when an ear-splitting thunderclap shook the window panes.", "had he fallen", "he had fallen", "did he fall", "has he fallen", "他才剛睡著，一聲震耳欲聾的雷鳴就震晃了窗玻璃。", "Hardly... when... 固定句型，Hardly 句首使用過去完成式倒裝：had + he + fallen。", "Hardly 句首倒裝選 had he fallen。", "ear-splitting", "/ˈɪrˌsplɪt.ɪŋ/", "震耳欲聾的", "pane", "/peɪn/", "窗玻璃片"),
            ("Rarely ___ so deeply engrossed in a classical literature novel.", "have I been", "I have been", "was I", "I was", "我很少如此深深著迷於一本古典文學小說之中。", "Rarely 置於句首倒裝：have I been。", "Rarely 句首倒裝選 have I been。", "engrossed", "/ɪnˈɡroʊst/", "全神貫注沉迷的", "classical", "/ˈklæs.ɪ.kəl/", "古典的"),
            ("Scarcely ___ the terminal building when the torrential downpour erupted.", "had we reached", "we had reached", "did we reach", "have we reached", "我們才剛抵達航廈建築，傾盆暴雨就驟然降臨。", "Scarcely... when/before 句首過去完成式倒裝：had we reached。", "Scarcely 句首倒裝選 had we reached。", "downpour", "/ˈdaʊn.pɔːr/", "傾盆大雨", "terminal", "/ˈtɝː.mə.nəl/", "航廈"),
            ("Not until the morning light penetrated the dense canopy ___ the lost hikers.", "did rescuers locate", "rescuers located", "had rescuers located", "rescuers did locate", "直到晨光穿透濃密的樹冠，搜救隊才終於找到了走失的登山客。", "Not until + 時間狀語置於句首，主要子句採倒裝：did rescuers locate。", "Not until 句首主句倒裝選 did rescuers locate。", "canopy", "/ˈkæn.ə.pi/", "林冠頂篷", "penetrate", "/ˈpen.ə.treɪt/", "穿透貫穿"),
            ("Under no circumstances ___ confidential patient data be disclosed without consent.", "should", "does", "is", "will", "在任何情況下，未經許可絕不應洩露病患的機密資料。", "否定介系詞片語 Under no circumstances 置於句首，倒裝搭配情態助動詞 should。", "Under no circumstances 倒裝選 should。", "disclose", "/dɪsˈkloʊz/", "透露洩漏", "consent", "/kənˈsent/", "同意許可"),
            ("Little ___ that the harmless-looking website harbored sophisticated spyware.", "did we suspect", "we suspected", "had we suspected", "we have suspected", "我們絲毫不曾懷疑那看似無害的網站竟暗藏高度複雜的間諜軟體。", "否定副詞 Little 置於句首倒裝：did we suspect。", "Little 句首倒裝選 did we suspect。", "sophisticated", "/səˈfɪs.tə.keɪ.t̬ɪd/", "複雜精密的", "harbor", "/ˈhɑːr.bɚ/", "窩藏庇護"),
            ("Not only ___ all our expectations, but he also shattered the national record.", "did he exceed", "he exceeded", "has he exceeded", "he had exceeded", "他不僅超越了我們所有的期望，而且打破了全國紀錄。", "Not only 置於句首倒裝：did he exceed。", "Not only 句首倒裝選 did he exceed。", "exceed", "/ɪkˈsiːd/", "超越勝過", "shatter", "/ˈʃæt̬.ɚ/", "粉碎打破"),
            ("No sooner ___ the podium than the audience erupted into deafening applause.", "had the speaker ascended", "the speaker had ascended", "did the speaker ascend", "was the speaker ascending", "演講者才剛登上講台，全場觀眾就爆發出震耳欲聾的熱烈掌聲。", "No sooner... than 句型，No sooner 句首倒裝：had the speaker ascended。", "No sooner 句首倒裝選 had the speaker ascended。", "podium", "/ˈpoʊ.di.əm/", "講台指揮台", "ascend", "/əˈsend/", "登上升高")
        ]),
        # 7. 地方副詞與方向副詞置於句首之完全倒裝
        ("地方副詞與方向副詞置於句首之完全倒裝", "文法句構", [
            ("Round the corner ___ the yellow school bus filled with excited students.", "came", "did come", "comes it", "was coming it", "繞過街角，載滿興奮學生的黃色校車緩緩開了過來。", "地方/方向副詞置於句首，主詞為名詞 (the school bus) 時，採「完全倒裝」：副詞 + 動詞 (came) + 主詞！", "完全倒裝：動詞 came 直接放在名詞主詞前面。", "excited", "/ɪkˈsaɪ.t̬ɪd/", "興奮的", "corner", "/ˈkɔːr.nɚ/", "角落"),
            ("Here ___ the punctual express train on track three.", "comes", "does come", "is coming it", "come it", "三號鐵軌上準點的特快車開過來了。", "Here/There 句首完全倒裝：Here + 動詞 (comes) + 名詞主詞 (the train)。", "Here comes + 名詞主詞。", "punctual", "/ˈpʌŋk.tʃu.əl/", "準時守時的", "express", "/ɪkˈspres/", "特快的"),
            ("Look! There ___ to catch the departing morning flight.", "he goes", "goes he", "does he go", "is he going", "看！他走過去趕搭那班即將離港的早班飛機了。", "注意：當主詞是「代名詞 (he, they)」時，主謂不倒裝，維持 Here/There + 代名詞 + 動詞！", "主詞為代名詞時不倒裝，選 he goes。", "depart", "/dɪˈpɑːrt/", "離境出發", "flight", "/flaɪt/", "航班"),
            ("At the foot of the misty mountain ___ an ancient Buddhist monastery.", "stands", "does stand", "is standing it", "stand", "在雲霧繚繞的山腳下聳立著一座古老的佛教寺院。", "地方介系詞片語置於句首，完全倒裝：stands + an ancient monastery。", "地方片語句首完全倒裝選 stands。", "monastery", "/ˈmɑː.nə.ster.i/", "修道院寺院", "misty", "/ˈmɪs.ti/", "多霧朦朧的"),
            ("Down ___ the torrential raindrops against the glass window panes.", "poured", "did pour", "was pouring it", "pours it", "傾盆雨滴劈里啪啦朝著玻璃窗面傾瀉而下。", "方向副詞 Down 置於句首，完全倒裝：poured + raindrops。", "完全倒裝選 poured。", "raindrop", "/ˈreɪn.drɑːp/", "雨滴", "pour", "/pɔːr/", "傾瀉倒灌"),
            ("Among the distinguished delegates ___ our university chancellor.", "was", "did", "were they", "had been it", "在傑出的代表團成員當中就有我們的大學校長。", "介系詞片語置於句首，單數主詞 chancellor 搭配 was 完全倒裝。", "完全倒裝選 was。", "chancellor", "/ˈtʃæn.səl.ɚ/", "大學校長", "distinguished", "/dɪˈstɪŋ.ɡwɪʃt/", "傑出卓越的"),
            ("Away ___ the startled deer as the hunting horn echoed through the woods.", "dashed", "did dash", "dashes it", "was dashing it", "當獵號在森林中迴盪時，受驚的鹿群疾馳遠去。", "Away 置於句首，名詞主詞完全倒裝：dashed + the deer。", "完全倒裝選 dashed。", "startle", "/ˈstɑːr.t̬əl/", "使受驚嚇", "dash", "/dæʃ/", "猛衝疾奔"),
            ("On the summit of the cliff ___ a solitary pine tree defying the storm.", "stood", "did stand", "stands it", "was standing it", "在懸崖絕頂上聳立著一棵傲視風暴的孤松。", "地方片語置於句首完全倒裝：stood + a pine tree。", "完全倒裝選 stood。", "cliff", "/klɪf/", "懸崖峭壁", "solitary", "/ˈsɑː.lə.ter.i/", "孤獨獨立的"),
            ("Under the shade of the ancient banyan tree ___ several village elders playing chess.", "sat", "did sit", "sits it", "was sitting it", "在古榕樹的樹蔭下坐著幾位正在下棋的村莊長者。", "複數名詞 elders 完全倒裝：sat + several elders。", "完全倒裝選 sat。", "banyan", "/ˈbæn.jæn/", "榕樹", "elder", "/ˈel.dɚ/", "長者老者"),
            ("Up into the azure sky ___ the flock of white pigeons.", "soared", "did soar", "soars it", "was soaring it", "那群白鴿朝著湛藍的天空振翅高飛翱翔而去。", "方向副詞 Up 置於句首，完全倒裝：soared + the flock。", "完全倒裝選 soared。", "azure", "/ˈæʒ.ɚ/", "湛藍蔚藍的", "pigeon", "/ˈpɪdʒ.ən/", "鴿子")
        ]),
        # 8. 表要求、建議、命令動詞後 that 子句使用 (should) + 原形動詞
        ("要求建議命令動詞後 that 子句虛擬式", "文法句構", [
            ("The physician insisted that the exhausted patient ___ complete bed rest.", "take", "takes", "took", "taking", "醫生堅持要求那名精疲力竭的病患必須接受徹底的臥床休息。", "表要求、建議、命令之動詞 (insist, suggest, demand, require) 後的 that 子句，動詞必須使用「(should) + 原形動詞 (V)」！", "insist 後 that 子句用原形動詞 take。", "physician", "/fɪˈzɪʃ.ən/", "醫生", "exhausted", "/ɪɡˈzɑː.stɪd/", "精疲力竭的"),
            ("The school safety committee recommended that all laboratory goggles ___ inspected annually.", "be", "are", "were", "being", "學校安全委員會建議所有實驗室護目鏡應當每年接受檢查。", "recommend that + S + (should) be + p.p. 被動語態，原形 be 動詞為 be！", "虛擬式被動用 (should) be inspected。", "goggles", "/ˈɡɑː.ɡəlz/", "護目鏡", "annually", "/ˈæn.ju.ə.li/", "每年年度地"),
            ("The department manager demanded that every employee ___ the revised policy.", "sign", "signs", "signed", "signing", "部門主管強烈要求每位員工都必須簽署修訂後的新規範方針。", "demand that + S + 原形動詞 sign。", "demand 後接原形動詞 sign。", "revised", "/rɪˈvaɪzd/", "修訂修改的", "policy", "/ˈpɑː.lə.si/", "政策方針"),
            ("Our homeroom teacher proposed that our class ___ a charity garage sale.", "organize", "organizes", "organized", "organizing", "我們的班導師提議我們班級應當舉辦一場慈善跳蚤市場拍賣會。", "propose that + S + 原形動詞 organize。", "propose 後接原形 organize。", "charity", "/ˈtʃer.ə.t̬i/", "慈善公益", "garage", "/ɡəˈrɑːʒ/", "車庫"),
            ("The law requires that every motorcyclist ___ a certified safety helmet.", "wear", "wears", "wore", "wearing", "法律規定每位機車騎士都必須配戴經認證的合格安全帽。", "require that + S + 原形動詞 wear。", "require 後接原形 wear。", "motorcyclist", "/ˈmoʊ.t̬ɚˌsaɪ.klɪst/", "機車騎士", "certified", "/ˈsɝː.t̬ə.faɪd/", "經認證的"),
            ("Health experts urge that teenagers ___ their consumption of sugary carbonated beverages.", "curb", "curbs", "curbed", "curbing", "健康專家極力敦促青少年應當克制減少含糖碳酸飲料的攝取量。", "urge that + S + 原形動詞 curb。", "urge 後接原形 curb。", "curb", "/kɝːb/", "控制抑制", "carbonated", "/ˈkɑːr.bə.neɪ.t̬ɪd/", "碳酸充氣的"),
            ("The defense attorney requested that the judge ___ the key surveillance footage.", "review", "reviews", "reviewed", "reviewing", "辯護律師請求法官重新審查那段關鍵的監視錄影畫面。", "request that + S + 原形動詞 review。", "request 後接原形 review。", "attorney", "/əˈtɝː.ni/", "律師辯護人", "surveillance", "/sɚˈveɪ.ləns/", "監視監控"),
            ("The municipal government mandated that public buildings ___ seismic upgrades.", "undergo", "undergoes", "underwent", "undergoing", "市政府強制規定公共建築物必須接受防震結構補強升級。", "mandate that + S + 原形動詞 undergo。", "mandate 後接原形 undergo。", "mandate", "/ˈmæn.deɪt/", "強制指令", "seismic", "/ˈsaɪz.mɪk/", "地震震動的"),
            ("She advised that Tony ___ a professional career consultant before switching majors.", "consult", "consults", "consulted", "consulting", "她建議 Tony 在更換主修專業之前應當先諮詢專業職涯顧問。", "advise that + S + 原形動詞 consult。", "advise 後接原形 consult。", "consultant", "/kənˈsʌl.tənt/", "顧問諮詢師", "switch", "/swɪtʃ/", "轉換更換"),
            ("The United Nations resolved that humanitarian supplies ___ distributed without bias.", "be", "are", "were", "been", "聯合國決議人道主義物資必須公正無私地予以分發。", "resolve that + S + (should) be + p.p. 被動語態，選 be。", "決議虛擬被動選 be。", "humanitarian", "/hjuːˌmæn.ɪˈter.i.ən/", "人道主義的", "bias", "/ˈbaɪ.əs/", "偏見偏袒")
        ]),
        # 9. It is vital/essential/imperative that S (should) + V 虛擬式
        ("It is vital/essential that S 虛擬式", "文法句構", [
            ("It is imperative that every citizen ___ in the upcoming democratic referendum.", "participate", "participates", "participated", "participating", "全體公民參與即將到來的民主公投是至關重要的。", "It is imperative/essential/vital that + S + (should) + 原形動詞 (V)！", "It is imperative that 後接原形動詞 participate。", "imperative", "/ɪmˈper.ə.t̬ɪv/", "極重要迫切的", "referendum", "/ˌref.əˈren.dəm/", "公民投票"),
            ("It is vital that the injured hiker ___ emergency medical treatment immediately.", "receive", "receives", "received", "receiving", "受傷的登山客立刻獲得緊急醫療救治是生死攸關的。", "It is vital that + S + 原形動詞 receive。", "vital that 後接原形 receive。", "hiker", "/ˈhaɪ.kɚ/", "登山徒步者", "treatment", "/ˈtriːt.mənt/", "治療救治"),
            ("It is essential that fresh drinking water ___ strictly tested for toxic pathogens.", "be", "is", "was", "being", "新鮮飲用水受到嚴格檢測以防有毒病原體是必不可少的。", "It is essential that + S + (should) be + p.p. 被動語態，選 be。", "essential that 被動用原形 be。", "pathogen", "/ˈpæθ.ə.dʒən/", "病原體", "toxic", "/ˈtɑːk.sɪk/", "有毒的"),
            ("It is necessary that the suspect ___ held in custody until the forensic report arrives.", "be", "is", "was", "being", "在鑑識報告送達之前將嫌犯拘留收押是必要的。", "It is necessary that + S + (should) be held。", "necessary that 被動用 be。", "custody", "/ˈkʌs.tə.di/", "拘留收押", "forensic", "/fəˈren.zɪk/", "法醫鑑識的"),
            ("It is crucial that the laboratory technician ___ the strict biohazard protocols.", "follow", "follows", "followed", "following", "實驗室技術人員遵循嚴格的生物危害防範規程是至關重要的。", "It is crucial that + S + 原形動詞 follow。", "crucial that 後接原形 follow。", "biohazard", "/ˈbaɪ.oʊˌhæz.ɚd/", "生物危害", "protocol", "/ˈproʊ.t̬ə.kɑːl/", "規程協議"),
            ("It is urgent that all coastal residents ___ to higher ground before the tsunami strikes.", "evacuate", "evacuates", "evacuated", "evacuating", "在海嘯來襲之前所有沿海居民緊急撤離至高地是刻不容緩的。", "It is urgent that + S + 原形動詞 evacuate。", "urgent that 後接原形 evacuate。", "evacuate", "/ɪˈvæk.ju.eɪt/", "撤離疏散", "tsunami", "/tsuːˈnɑː.mi/", "海嘯"),
            ("It is desirable that the committee ___ a consensus before adjourning tonight.", "reach", "reaches", "reached", "reaching", "委員會在今晚休會前達成共識是令人期望的。", "It is desirable that + S + 原形動詞 reach。", "desirable that 後接原形 reach。", "consensus", "/kənˈsen.səs/", "共識一致", "adjourn", "/əˈdʒɝːn/", "休會延期"),
            ("It is important that every student ___ an active role in campus sustainability projects.", "play", "plays", "played", "playing", "每位學生在校園永續專案中扮演積極角色是十分重要的。", "It is important that + S + 原形動詞 play。", "important that 後接原形 play。", "sustainability", "/səˌsteɪ.nəˈbɪl.ə.t̬i/", "永續性", "active", "/ˈæk.tɪv/", "積極主動的"),
            ("It is required that all candidates ___ a comprehensive background questionnaire.", "complete", "completes", "completed", "completing", "所有候選人均被要求填寫一份詳盡的背景問卷。", "It is required that + S + 原形動詞 complete。", "required that 後接原形 complete。", "questionnaire", "/ˌkwes.tʃəˈner/", "問卷調查表", "comprehensive", "/ˌkɑːm.prəˈhen.sɪv/", "綜合全面的"),
            ("It is advisable that you ___ a certified financial planner before investing in stocks.", "consult", "consults", "consulted", "consulting", "在投資股票之前諮詢認證合格的財務規劃師是明智可取的。", "It is advisable that + S + 原形動詞 consult。", "advisable that 後接原形 consult。", "advisable", "/ədˈvaɪ.zə.bəl/", "明智可取的", "invest", "/ɪnˈvest/", "投資"),
        ])
    ]
    
    # Define remaining subtopics 10 to 25
    remaining_subtopics_4_part2 = [
        # 10. 關係副詞 where, when, why, whereby 引導之定語從句
        ("關係副詞 where, when, why, whereby", "文法句構", [
            ("We visited the historic pavilion ___ ancient philosophers gathered to debate ethics.", "where", "which", "that", "when", "我們參觀了古代哲學家們聚集辯論倫理學的歷史涼亭。", "先行詞 the pavilion 為地點，在子句中作地方副詞 (gathered in the pavilion)，使用關係副詞 where。", "地點關係副詞選 where。", "philosopher", "/fɪˈlɑː.sə.fɚ/", "哲學家", "ethics", "/ˈeθ.ɪks/", "倫理學"),
            ("July 20, 1969 was the momentous day ___ human footprints were first stamped on the moon.", "when", "where", "which", "that", "1969年7月20日是人類足跡首次印在月球上的重大日子。", "先行詞 the momentous day 為時間，子句中作時間副詞，使用關係副詞 when。", "時間關係副詞選 when。", "momentous", "/moʊˈmen.təs/", "重大的關鍵的", "footprint", "/ˈfʊt.prɪnt/", "足跡"),
            ("The mysterious reason ___ the ancient civilization vanished abruptly remains unknown.", "why", "where", "which", "whose", "那座古代文明突然人間蒸發的神秘原因至今依然不為人知。", "先行詞 The reason 對應關係副詞 why 引導定語從句。", "原因關係副詞選 why。", "vanish", "/ˈvæn.ɪʃ/", "突然消失", "civilization", "/ˌsɪv.əl.əˈzeɪ.ʃən/", "文明"),
            ("The international summit established a treaty ___ carbon tariffs would be regulated.", "whereby", "when", "where", "why", "國際峰會制定了一項條約，藉此碳關稅將受到嚴格監管規範。", "whereby 表「藉此、憑藉該機制」，相當於 by which，引導修飾協定條款之子句。", "表藉此機制選 whereby。", "tariff", "/ˈter.ɪf/", "關稅", "regulate", "/ˈreɡ.jə.leɪt/", "監管規範"),
            ("This tranquil harbor is the sanctuary ___ endangered sea turtles lay their eggs.", "where", "when", "why", "which", "這片寧靜的港灣是瀕危海龜產卵的庇護所。", "先行詞 the sanctuary 表地點，選 where。", "地點關係副詞選 where。", "sanctuary", "/ˈsæŋk.tʃu.er.i/", "庇護所聖所", "turtle", "/ˈtɝː.t̬əl/", "海龜"),
            ("Do you recall the precise moment ___ the earthquake shook our high-rise building?", "when", "where", "why", "which", "你還記得地震劇烈震晃我們高樓大廈的那個精確時刻嗎？", "先行詞 the precise moment 表時間，選 when。", "時間關係副詞選 when。", "precise", "/prəˈsaɪs/", "精確準確的", "high-rise", "/ˈhaɪ.raɪz/", "高樓大廈"),
            ("I completely understand the rational motive ___ she rejected that lucrative partnership.", "why", "where", "when", "which", "我完全理解她之所以拒絕那場合作獲利良機的理性動機。", "先行詞 the rational motive 對應 why。", "理由動機對應 why。", "motive", "/ˈmoʊ.t̬ɪv/", "動機目的", "partnership", "/ˈpɑːrt.nɚ.ʃɪp/", "合夥合作"),
            ("The school campus is an environment ___ intellectual curiosity should be nourished.", "where", "when", "why", "which", "學校校園應當是一個求知慾受到細心滋養呵護的環境。", "先行詞 an environment 表抽象環境場所，選 where。", "抽象環境地點選 where。", "nourish", "/ˈnɝː.ɪʃ/", "滋養撫育", "intellectual", "/ˌɪn.t̬əlˈek.tʃu.əl/", "求知的智力的"),
            ("Autumn is the season ___ deciduous leaves transform into vibrant shades of amber.", "when", "where", "why", "which", "秋天是落葉樹葉蛻變成繽紛琥珀色調的季節。", "先行詞 the season 表季節時間，選 when。", "季節時間選 when。", "deciduous", "/dɪˈsɪdʒ.u.əs/", "落葉性的", "amber", "/ˈæm.bɚ/", "琥珀色"),
            ("The committee instituted a peer-review protocol ___ academic integrity is maintained.", "whereby", "when", "why", "where", "委員會建立了一套同儕審查機制，藉此維護學術誠信。", "whereby 表憑藉該審查機制，選 whereby。", "藉由該機制選 whereby。", "integrity", "/ɪnˈteɡ.rə.t̬i/", "誠信正直", "protocol", "/ˈproʊ.t̬ə.kɑːl/", "規程協議")
        ]),
        # 11. 非限定關係子句 (, which / , who) 之補充說明
        ("非限定關係子句 (, which / , who)", "文法句構", [
            ("Taipei 101, ___ was once the world's tallest building, incorporates a massive tuned mass damper.", "which", "that", "who", "whom", "台北101（曾是全球最高建築）內部安裝了一具巨大的調諧質量阻尼器。", "專有名詞 Taipei 101 後接「逗號非限定關係子句」，修飾物只能使用 which，不可使用 that！", "非限定逗號後不可用 that，修飾物選 which。", "damper", "/ˈdæm.pɚ/", "阻尼器減震器", "massive", "/ˈmæs.ɪv/", "龐大巨大的"),
            ("Dr. Thornton, ___ has published pioneering research in linguistics, delivered the keynote speech.", "who", "which", "whom", "whose", "在語言學界發表過開創性研究的 Thornton 博士發表了主題演講。", "人名專有名詞後接逗號非限定主格關代，指代人使用 who。", "非限定指代人作主詞選 who。", "pioneering", "/ˌpaɪəˈnɪr.ɪŋ/", "開創先驅的", "linguistics", "/lɪŋˈɡwɪs.tɪks/", "語言學"),
            ("Leo failed his driving test three times, ___ deeply frustrated his parents.", "which", "that", "who", "what", "Leo 駕照路考失敗了三次，這件事讓他父母深感沮喪。", "逗號後的非限定關代 which 可「指代前面整個子句的事實」！不可用 that 或 what。", "指代前面整件事選 which。", "frustrate", "/ˈfrʌs.treɪt/", "使沮喪受挫", "deeply", "/ˈdiːp.li/", "深深地"),
            ("Mount Jade, ___ elevation exceeds 3,900 meters, is the highest summit in Northeast Asia.", "whose", "which", "that", "who", "玉山（其海拔高度超過3900公尺）是東北亞第一高峰。", "修飾玉山之海拔高度 (whose elevation)，逗號後使用所有格 whose。", "非限定所有格選 whose。", "elevation", "/ˌel.əˈveɪ.ʃən/", "海拔高度", "summit", "/ˈsʌm.ɪt/", "頂峰頂點"),
            ("The new bullet train route, ___ commenced operation last month, reduces travel time drastically.", "which", "that", "who", "whom", "新高鐵路線（於上個月正式營運通車）巨幅縮短了旅行時間。", "專指特定路線後接逗號非限定，選 which。", "非限定修飾物選 which。", "commence", "/kəˈmens/", "開始啟動", "drastically", "/ˈdræs.tɪ.kəl.i/", "急遽大幅地"),
            ("Emily's grandmother, ___ is eighty-eight years old, still practices calligraphy every afternoon.", "who", "which", "that", "whom", "Emily 的祖母（現年八十八歲）依然每天下午練習書法。", "稱謂專指人物後接非限定，選 who。", "非限定人物主格選 who。", "calligraphy", "/kəˈlɪɡ.rə.fi/", "書法", "practice", "/ˈpræk.tɪs/", "練習"),
            ("The ancient redwood tree, ___ branches shelter countless bird species, was protected by law.", "whose", "which", "that", "who", "那棵古老紅杉樹（其枝幹庇護著無數鳥類物種）受到了法律嚴格保護。", "修飾樹的枝幹所有格，選 whose。", "非限定所有格選 whose。", "redwood", "/ˈred.wʊd/", "紅杉木", "shelter", "/ˈʃel.tɚ/", "庇護遮蔽"),
            ("The torrential storm knocked down power lines, ___ plunged the entire town into darkness.", "which", "that", "who", "what", "狂暴的暴風雨吹倒了輸電線路，這導致全鎮陷入了一片漆黑。", "which 指代前句「吹倒線路導致停電」這件事。", "指代整句事件選 which。", "plunge", "/plʌndʒ/", "使陷入墜入", "darkness", "/ˈdɑːrk.nəs/", "黑暗黑暗中"),
            ("Albert Einstein, ___ revolutionized theoretical physics, was awarded the Nobel Prize in 1921.", "who", "which", "that", "whom", "徹底革新理論物理學的愛因斯坦於 1921 年獲頒諾貝爾獎。", "人名專有名詞非限定主格選 who。", "專有名詞非限定人物選 who。", "revolutionize", "/ˌrev.əˈluː.ʃən.aɪz/", "徹底革新", "theoretical", "/ˌθiː.əˈret̬.kəl/", "理論的"),
            ("The Olympic Games, ___ are held every four years, promote international friendship and peace.", "which", "that", "who", "whom", "奧林匹克運動會（每四年舉辦一次）促進了國際友誼與世界和平。", "專有名詞非限定指代賽事，選 which。", "非限定指代賽事選 which。", "promote", "/prəˈmoʊt/", "促進提倡", "peace", "/piːs/", "和平")
        ]),
        # 12. 複合關係代名詞 whoever, whatever, whichever
        ("複合關係代名詞 whoever, whatever, whichever", "文法句構", [
            ("___ achieves the highest cumulative score in the competition will win the scholarship.", "Whoever", "Whomever", "Whichever", "Whatever", "凡是在這場競賽中獲得最高累計總分的人，都將贏得全額獎學金。", "Whoever 相當於 anyone who，在名詞子句中擔任主詞，意為「凡是…的人」。", "名詞子句當主詞選 Whoever。", "cumulative", "/ˈkjuː.mjə.lə.t̬ɪv/", "累積累計的", "scholarship", "/ˈskɑː.lɚ.ʃɪp/", "獎學金"),
            ("You can order ___ dessert you prefer from the gourmet banquet menu.", "whichever", "whoever", "however", "wherever", "你可以從這份美食宴席菜單中挑選任何一款你偏好的甜點。", "whichever + 名詞 (dessert) 表「在有限範圍中無論哪一個」。", "有限範圍挑選用 whichever。", "gourmet", "/ɡʊrˈmeɪ/", "美食佳餚的", "banquet", "/ˈbæŋ.kwət/", "宴會盛宴"),
            ("___ challenges you might encounter during the journey, stay resolute and optimistic.", "Whatever", "Whoever", "Whichever", "Whenever", "在旅途中無論你可能會遭遇何種挑戰，都請保持堅定與樂觀。", "Whatever + 名詞 (challenges) 引導讓步狀語子句，意為「無論何種…」。", "讓步狀語名詞前加 Whatever。", "resolute", "/ˈrez.ə.luːt/", "堅定不屈的", "optimistic", "/ˌɑːp.təˈmɪs.tɪk/", "樂觀的"),
            ("The coach promised to award the MVP trophy to ___ played with the greatest dedication.", "whoever", "whomever", "whichever", "whatever", "教練承諾將最有價值球員獎盃頒發給任何帶著最高奉獻精神打球的人。", "介系詞 to 後之名詞子句缺主詞，子句主詞必須使用主格 whoever（非 whomever）！", "子句作主詞必須選主格 whoever。", "trophy", "/ˈtroʊ.fi/", "獎盃獎牌", "dedication", "/ˌded.əˈkeɪ.ʃən/", "奉獻專注"),
            ("Please choose ___ seat is available in the auditorium.", "whichever", "whoever", "whatever", "wherever", "請在禮堂內挑選任何一個目前空著的座位就座。", "whichever seat（在有限座位中無論哪一個）。", "有限範圍選 whichever。", "auditorium", "/ˌɑː.dəˈtɔːr.i.əm/", "禮堂大廳", "available", "/əˈveɪ.lə.bəl/", "可用的空閒的"),
            ("___ happens in the financial markets tomorrow, we will adhere to our long-term plan.", "Whatever", "Whoever", "Whichever", "However", "無論明天金融市場發生何事，我們都將堅持我們的長期投資計畫。", "Whatever 作子句主詞（無論發生何事）。", "無論何事作主詞選 Whatever。", "adhere", "/ədˈhɪr/", "堅持遵照", "financial", "/faɪˈnæn.ʃəl/", "金融財務的"),
            ("You can invite ___ you feel would genuinely benefit from this leadership workshop.", "whomever", "whoever", "whatever", "whichever", "你可以邀請任何一位你認為真正能從這場領導力工作坊中獲益的人。", "作 invite 的受詞，正式人稱受格使用 whomever（亦常用 whoever）。", "人稱受格選 whomever。", "workshop", "/ˈwɝːk.ʃɑːp/", "工作坊研習", "genuinely", "/ˈdʒen.ju.ɪn.li/", "真正真誠地"),
            ("Take ___ textbook you need to prepare for tomorrow's biology examination.", "whichever", "whoever", "whatever", "however", "挑選任何一本你需要用來準備明天生物考試的課本去讀吧。", "whichever textbook 表在指定課本中無論哪一本。", "書籍挑選選 whichever。", "examination", "/ɪɡˌzæm.əˈneɪ.ʃən/", "考試", "biology", "/baɪˈɑː.lə.dʒi/", "生物學"),
            ("___ breaks the sacred archaeological relics will face severe legal penalties.", "Whoever", "Whomever", "Whatever", "Whichever", "凡是破壞神聖考古文物的人都將面臨嚴厲的法律制裁處罰。", "子句當主詞選 Whoever。", "凡是何人選 Whoever。", "relic", "/ˈrel.ɪk/", "遺跡文物", "penalty", "/ˈpen.əl.ti/", "處罰制裁"),
            ("We will wholeheartedly support ___ candidate the democratic electorate chooses.", "whichever", "whoever", "whatever", "however", "我們將全心全意支持民主選民所挑選出的任何一位候選人。", "whichever candidate（候選人名單中無論哪一位）。", "特定人選挑選用 whichever。", "electorate", "/iˈlek.tɚ.ət/", "全體選民", "wholeheartedly", "/ˌhoʊlˈhɑːr.t̬ɪd.li/", "全心全意地")
        ]),
        # 13. 高中核心素養單字：抽象認知與學術詞彙
        ("高中核心素養單字：抽象認知與學術詞彙", "單字語意", [
            ("Digital smartphones have become so ___ that almost every student owns one.", "pervasive", "obsolete", "scarce", "hostile", "數位智慧型手機已變得如此普及普遍，幾乎每位學生都擁有一部。", "pervasive 意為「無所不在的、普及的、充斥各處的」。", "普及無所不在選 pervasive。", "pervasive", "/pɚˈveɪ.sɪv/", "遍佈普及的", "smartphone", "/ˈsmɑːrt.foʊn/", "智慧型手機"),
            ("The scientist presented a ___ hypothesis that accounted for all experimental data.", "plausible", "ridiculous", "futile", "trivial", "該科學家提出了一個合理解釋了所有實驗數據的合情假說。", "plausible 意為「看似合情合理的、具說服力的」。", "合情合理選 plausible。", "plausible", "/ˈplɑː.zə.bəl/", "合情合理的", "hypothesis", "/haɪˈpɑː.θə.sɪs/", "假說理論"),
            ("Prolonged drought caused the agricultural yield to ___ significantly this season.", "diminish", "flourish", "soar", "escalate", "長期乾旱導致本季農作物產量顯著萎縮遞減。", "diminish 意為「縮減、減少、降低」。", "產量減少遞減選 diminish。", "diminish", "/dɪˈmɪn.ɪʃ/", "減少萎縮", "drought", "/draʊt/", "乾旱旱災"),
            ("The company's groundbreaking technological innovation gave it an ___ advantage.", "unprecedented", "obsolete", "insignificant", "ambiguous", "該公司開創性的技術創新為其帶來了史無前例的競爭優勢。", "unprecedented 意為「史無前例的、空前的」。", "史無前例選 unprecedented。", "unprecedented", "/ʌnˈpres.ə.den.t̬ɪd/", "史無前例的", "groundbreaking", "/ˈɡraʊndˌbreɪ.kɪŋ/", "開創性的"),
            ("The wording of the legal contract was highly ___, causing numerous conflicting interpretations.", "ambiguous", "lucid", "precise", "transparent", "這份法律合約的字句措辭極為模稜兩可，引發了眾多衝突的分歧解讀。", "ambiguous 意為「模稜兩可的、語意含糊不清的」。", "模稜兩可選 ambiguous。", "ambiguous", "/æmˈbɪɡ.ju.əs/", "含糊模稜兩可的", "contract", "/ˈkɑːn.trækt/", "合約契約"),
            ("Students must learn to ___ reliable scientific sources from biased internet rumors.", "distinguish", "abolish", "contemplate", "deteriorate", "學生必須學會將可靠的科學來源與具偏見的網路謠言區別開來。", "distinguish A from B 意為「辨別、區分」。", "區分辨別選 distinguish。", "distinguish", "/dɪˈstɪŋ.ɡwɪʃ/", "區分辨別", "rumor", "/ˈruː.mɚ/", "謠言傳聞"),
            ("The politician's speech was so ___ that critics questioned his true intentions.", "equivocal", "straightforward", "candid", "transparent", "那位政客的發言如此模稜兩可含糊其辭，影評人紛紛質疑其真實意圖。", "equivocal 意為「含糊其辭的、避重就輕的」。", "含糊其辭選 equivocal。", "equivocal", "/ɪˈkwɪv.ə.kəl/", "模稜兩可含糊的", "intention", "/ɪnˈten.ʃən/", "意圖意圖"),
            ("The patient showed ___ signs of recovery after receiving the novel immunotherapy.", "tangible", "invisible", "futile", "trivial", "病患在接受新型免疫療法後展現出了具體可見的康復跡象。", "tangible 意為「具體的、可觸及可感知的」。", "具體切實選 tangible。", "tangible", "/ˈtæn.dʒə.bəl/", "具體切實的", "immunotherapy", "/ˌɪm.jə.noʊˈθer.ə.pi/", "免疫療法"),
            ("Economic recession caused the value of the national currency to ___ rapidly.", "depreciate", "appreciate", "escalate", "prosper", "經濟衰退導致國家貨幣的匯率價值迅速貶值跌落。", "depreciate 意為「貶值、降價、跌價」。", "貨幣貶值選 depreciate。", "depreciate", "/dɪˈpriː.ʃi.eɪt/", "貶值跌價", "currency", "/ˈkɝː.ən.si/", "貨幣通貨"),
            ("The philosopher emphasized the ___ nature of human existence in the universe.", "ephemeral", "permanent", "immortal", "everlasting", "這位哲學家強調了人類在浩瀚宇宙中生命存在的短暫轉瞬即逝性。", "ephemeral 意為「轉瞬即逝的、短暫的」。", "短暫轉瞬即逝選 ephemeral。", "ephemeral", "/ɪˈfem.ɚ.əl/", "轉瞬即逝短暫的", "existence", "/ɪɡˈzɪs.təns/", "存在生存")
        ]),
        # 14. 高中核心素養單字：社會環境與科技詞彙
        ("高中核心素養單字：社會環境與科技詞彙", "單字語意", [
            ("Environmental activists strongly advocate for corporate environmental ___.", "sustainability", "destruction", "depletion", "recklessness", "環保行動倡議者極力提倡企業應當落實環境永續性。", "sustainability 意為「永續性、可持續發展」。", "永續性選 sustainability。", "sustainability", "/səˌsteɪ.nəˈbɪl.ə.t̬i/", "永續性", "activist", "/ˈæk.tə.vɪst/", "行動倡議者"),
            ("The search engine utilizes a sophisticated ___ to rank relevant search results.", "algorithm", "superstition", "hazard", "myth", "這家搜尋引擎利用一套高度複雜的演算法來排列相關搜尋結果。", "algorithm 意為「演算法、計算程序」。", "演算法選 algorithm。", "algorithm", "/ˈæl.ɡə.rɪð.əm/", "演算法", "relevant", "/ˈrel.ə.vənt/", "相關切題的"),
            ("The municipal government voted to ___ millions of dollars for green infrastructure.", "allocate", "confiscate", "deplete", "extinguish", "市政府投票通過提撥編列數百萬美元專款用於綠色基礎設施。", "allocate 意為「分派、提撥、編列預算」。", "撥款分配選 allocate。", "allocate", "/ˈæl.ə.keɪt/", "分派撥款", "infrastructure", "/ˈɪn.frəˌstrʌk.tʃɚ/", "基礎設施"),
            ("Excessive use of fossil fuels accelerates global carbon dioxide ___.", "emissions", "purification", "conservation", "sequestration", "過度使用化石燃料會加速全球二氧化碳的排放。", "emissions 意為「排放、散發、廢氣」。", "碳排放選 emissions。", "emission", "/iˈmɪʃ.ən/", "排放散發", "fossil", "/ˈfɑː.səl/", "化石"),
            ("Renewable energy sources such as solar and wind help mitigate the climate ___.", "crisis", "prosperity", "solution", "paradise", "太陽能與風能等再生能源有助於緩解氣候危機。", "climate crisis 意為「氣候危機」。", "氣候危機選 crisis。", "crisis", "/ˈkraɪ.sɪs/", "危機險境", "mitigate", "/ˈmɪt̬.ə.ɡeɪt/", "緩和減輕"),
            ("Artificial intelligence is expected to ___ efficiency across multiple industries.", "boost", "hinder", "obstruct", "diminish", "人工智慧預期將大幅提振跨多個產業的生產效率。", "boost 意為「提振、推動、促進」。", "提振效率選 boost。", "boost", "/buːst/", "提振促進", "efficiency", "/ɪˈfɪʃ.ən.si/", "效率效能"),
            ("The government launched a campaign to promote energy ___ among households.", "conservation", "exhaustion", "wastage", "depletion", "政府發起了一場宣導活動，向家庭住戶推廣能源節約保育理念。", "energy conservation 意為「節能、能源保育」。", "節約保育選 conservation。", "conservation", "/ˌkɑːn.sɚˈveɪ.ʃən/", "節約保育", "household", "/ˈhaʊs.hoʊld/", "家庭戶"),
            ("Cloud computing infrastructure enables companies to store ___ amounts of data.", "colossal", "microscopic", "scarce", "trivial", "雲端運算基礎設施使企業能夠儲存極其龐大巨量的數據資料。", "colossal 意為「極巨大的、龐大的」。", "龐大巨量選 colossal。", "colossal", "/kəˈlɑː.səl/", "龐大無比的", "computing", "/kəmˈpjuː.t̬ɪŋ/", "計算運算"),
            ("Biodiversity ___ in the Amazon rainforest threatens ecological equilibrium.", "loss", "enrichment", "growth", "boom", "亞馬遜雨林生物多樣性的流失喪失對生態平衡構成了威脅。", "biodiversity loss 意為「生物多樣性流失」。", "流失喪失選 loss。", "biodiversity", "/ˌbaɪ.oʊ.daɪˈvɝː.sə.t̬i/", "生物多樣性", "equilibrium", "/ˌiː.kwəˈlɪb.ri.əm/", "平衡均衡"),
            ("Autonomous electric vehicles rely on sensors to navigate complex urban ___.", "environments", "superstitions", "paradigms", "myths", "自動駕駛電動車仰賴感測器在複雜的城市環境中導航行駛。", "urban environments 意為「城市環境」。", "城市環境選 environments。", "autonomous", "/ɑːˈtɑː.nə.məs/", "自動駕駛自主的", "navigate", "/ˈnæv.ə.ɡeɪt/", "導航行駛")
        ]),
        # 15. 對等平行結構 (Parallelism in series and paired conjunctions)
        ("對等平行結構 (Parallelism)", "文法句構", [
            ("Successful leaders must be capable of listening attentively, communicating clearly, and ___ effectively.", "collaborating", "collaborate", "to collaborate", "collaborated", "成功的領導者必須具備專注傾聽、清晰溝通以及有效協作的能力。", "平行結構：of listening..., communicating..., and collaborating... 三者皆需為動名詞 (V-ing)！", "平行對等動名詞選 collaborating。", "attentively", "/əˈten.tɪv.li/", "專注留心地", "collaborate", "/kəˈlæb.ə.reɪt/", "協作合作"),
            ("The internship program offers students opportunities to gain experience, expand networks, and ___ professional skills.", "develop", "developing", "to developing", "developed", "該實習計畫為學生提供累積經驗、拓展人脈以及培養專業技能的機會。", "不定詞後平行原形動詞：to gain..., expand..., and develop... 三者皆為原形動詞！", "平行原形動詞選 develop。", "internship", "/ˈɪn.tɝːn.ʃɪp/", "實習計畫", "network", "/ˈnet.wɝːk/", "人脈網路"),
            ("Tony enjoys hiking in the high mountains, camping near the pristine lakes, and ___ scenic landscape photos.", "taking", "takes", "to take", "took", "Tony 熱愛在高山健行、在清澈湖畔露營以及拍攝壯麗的風景照片。", "enjoy 後平行動名詞：hiking..., camping..., and taking... 一致採用 V-ing！", "平行動名詞選 taking。", "pristine", "/ˈprɪs.tiːn/", "清澈純淨的", "landscape", "/ˈlænd.skeɪp/", "風景地景"),
            ("The newly opened library is spacious, well-illuminated, and ___ organized.", "meticulously", "meticulous", "in a meticulous way", "with meticulousness", "這座新開放的圖書館空間寬敞、採光明亮且整理得井井有條細緻入微。", "平行副詞修飾過去分詞 organized：spacious, well-illuminated, and meticulously organized。", "修飾分詞平行選副詞 meticulously。", "meticulously", "/məˈtɪk.jə.ləs.li/", "細緻縝密地", "illuminate", "/ɪˈluː.mə.neɪt/", "照亮啟蒙"),
            ("Emily is admired for her intellectual brilliance, artistic creativity, and ___ commitment.", "unwavering", "unwaveringly", "she is unwavering", "to be unwavering", "Emily 因其才智過人、藝術創造力以及堅定不移的奉獻精神而受到欽佩。", "平行形容詞修飾名詞：brilliance, creativity, and unwavering commitment。", "平行形容詞選 unwavering。", "unwavering", "/ʌnˈweɪ.vɚ.ɪŋ/", "堅定不移的", "commitment", "/kəˈmɪt.mənt/", "奉獻承諾"),
            ("The doctor advised the patient not only to modify his diet but also ___ regularly.", "to exercise", "exercising", "exercise", "exercised", "醫生建議病患不僅要調整飲食結構，而且還要定期運動。", "not only to modify... but also to exercise... 不定詞對等平行！", "不定詞平行選 to exercise。", "modify", "/ˈmɑː.də.faɪ/", "調整修改", "regularly", "/ˈreɡ.jə.lɚ.li/", "定期規律地"),
            ("The novel is notable for its captivating plot, authentic dialogue, and ___ character development.", "profound", "profoundly", "it has profound", "profoundness", "這部小說以其引人入勝的情節、真實自然的對白以及深刻的人物刻畫而著稱。", "平行名詞片語結構：captivating plot, authentic dialogue, and profound development。", "平行形容詞選 profound。", "captivating", "/ˈkæp.tə.veɪ.tɪŋ/", "引人入勝的", "profound", "/prəˈfaʊnd/", "深刻深奧的"),
            ("He is respected whether he is speaking to corporate executives, guiding young students, or ___ with everyday citizens.", "interacting", "interact", "to interact", "interacted", "無論他是與企業高層對話、指導年輕學子，還是與尋常百姓互動，他都深受尊敬。", "speaking..., guiding..., or interacting... 平行現在分詞！", "平行現在分詞選 interacting。", "interact", "/ˌɪn.t̬ɚˈækt/", "互動交流", "executive", "/ɪɡˈzek.jə.t̬ɪv/", "高階主管"),
            ("The school policy aims to reduce student stress, promote physical health, and ___ academic creativity.", "foster", "fostering", "to fostering", "fostered", "學校政策旨在減輕學生壓力、促進身體健康並培養學術創造力。", "aims to reduce..., promote..., and foster... 原形動詞平行！", "平行原形動詞選 foster。", "foster", "/ˈfɑː.stɚ/", "培養撫育", "stress", "/stres/", "壓力"),
            ("The athletic trainer instructed players to warm up thoroughly, hydrate frequently, and ___ properly.", "stretch", "stretching", "to stretching", "stretched", "體能訓練師指導球員們要徹底熱身、頻繁補水並適當進行拉伸。", "instructed to warm up..., hydrate..., and stretch... 原形動詞對等！", "平行原形動詞選 stretch。", "hydrate", "/ˈhaɪ.dreɪt/", "補充水分", "stretch", "/stretʃ/", "伸展拉伸")
        ]),
        # 16. 雙重比較級 (The more..., the more...) 句型
        ("雙重比較級 (The more..., the more...)", "文法句構", [
            ("The more diligently you practice, the ___ proficient you will become in English.", "more", "most", "much", "greater", "你練習得越勤奮刻苦，你的英文就會變得越精通熟練。", "雙重比較級句型：The + 比較級... , the + 比較級... 表示「越…就越…」。", "雙重比較級選 the more proficient。", "proficient", "/prəˈfɪʃ.ənt/", "精通熟練的", "diligently", "/ˈdɪl.ə.dʒənt.li/", "勤奮地"),
            ("The higher we ascended the mountain trail, the ___ the air became.", "colder", "cold", "coldest", "more cold", "我們沿著山徑登得越高，空氣就變得越發寒冷。", "The higher..., the colder... 雙重比較級搭配 colder。", "雙重比較級選 colder。", "ascend", "/əˈsend/", "登攀上升", "trail", "/treɪl/", "步道山徑"),
            ("The more complex the technological dilemma, the ___ ingenuity is required to solve it.", "more", "most", "much", "many", "技術困境越是錯綜複雜，解開它所需的智慧才智就越多。", "The more complex..., the more ingenuity... 雙重比較級。", "雙重比較級選 more。", "ingenuity", "/ˌɪn.dʒəˈnuː.ə.t̬i/", "聰敏才智", "dilemma", "/daɪˈlem.ə/", "困境抉擇"),
            ("The sooner you begin your research project, the ___ your final grade will be.", "better", "best", "good", "well", "你越早著手進行你的研究專題，你的期末成績就會越好。", "The sooner..., the better... 經典雙重比較級。", "雙重比較級選 better。", "grade", "/ɡreɪd/", "成績等級", "sooner", "/ˈsuː.nɚ/", "越早"),
            ("The more books you read, the ___ your horizons will expand.", "broader", "broad", "broadest", "more broad", "你讀的書籍越多，你的眼界視野就會擴展得越寬廣。", "The more..., the broader... 雙重比較級。", "雙重比較級選 broader。", "horizon", "/həˈraɪ.zən/", "眼界地平線", "expand", "/ɪkˈspænd/", "擴展擴張"),
            ("The deeper the roots of a tree penetrate the soil, the ___ it withstands violent storms.", "better", "best", "good", "well", "樹木的根系扎入土壤越深，它就越能經受住狂暴風暴的考驗。", "The deeper..., the better it withstands... 雙重比較級。", "雙重比較級選 better。", "withstand", "/wɪðˈstænd/", "經受抵擋", "penetrate", "/ˈpen.ə.treɪt/", "穿透深植"),
            ("The more critical your analytical thinking skills, the ___ susceptible you are to false rumors.", "less", "least", "little", "fewer", "你的批判分析思維能力越強，你就越不容易受到虛假謠言的影響欺騙。", "The more critical..., the less susceptible... 雙重比較級（越不…）。", "雙重比較級反向選 the less。", "susceptible", "/səˈsep.tə.bəl/", "易受影響感染的", "rumor", "/ˈruː.mɚ/", "謠言"),
            ("The louder the speaker talked, the ___ attentive the restless audience became.", "less", "least", "little", "more", "演講者嗓門扯得越大，坐立難安的聽眾反而變得越心不在焉。", "The louder..., the less attentive... 雙重比較級。", "反向雙重比較級選 the less。", "restless", "/ˈrest.ləs/", "坐立難安的", "attentive", "/əˈten.tɪv/", "專注留心的"),
            ("The longer you procrastinate on this difficult assignment, the ___ stressful it will be.", "more", "most", "much", "very", "你在這項艱難作業上拖延得越久，它帶來的壓力就會越大。", "The longer..., the more stressful... 雙重比較級。", "雙重比較級選 more。", "procrastinate", "/proʊˈkræs.tə.neɪt/", "拖延延宕", "stressful", "/ˈstres.fəl/", "充滿壓力的"),
            ("The more diverse the ecosystem, the ___ resilient it is against climate disruption.", "more", "most", "much", "great", "生態系越具多樣性，它抵禦氣候破壞干擾的韌性就越強大。", "The more diverse..., the more resilient... 雙重比較級。", "雙重比較級選 more。", "resilient", "/rɪˈzɪl.jənt/", "具復原韌性的", "disruption", "/dɪsˈrʌp.ʃən/", "中斷破壞")
        ]),
        # 17. 篇章轉折詞 (furthermore, nevertheless, consequently, conversely, on the contrary)
        ("篇章轉折詞", "篇章語境", [
            ("Traditional fossil fuels emit vast greenhouse gases. ___, renewable solar energy is clean and virtually limitless.", "Conversely", "Therefore", "Moreover", "Consequently", "傳統化石燃料排放大量溫室氣體。相反地，再生太陽能乾淨且幾乎無窮無盡。", "前後句對立對比，使用 Conversely（相反地、反之）。", "相反對比選 Conversely。", "limitless", "/ˈlɪm.ɪt.ləs/", "無限無窮的", "fossil", "/ˈfɑː.səl/", "化石"),
            ("The medical procedure carried severe potential risks; ___, the patient chose to undergo it.", "nevertheless", "therefore", "moreover", "in addition", "這項醫療手術伴隨著嚴重的潛在風險；儘管如此，病患依然選擇接受該手術。", "風險極高與依然選擇接受形成讓步轉折，使用 nevertheless（儘管如此）。", "讓步轉折選 nevertheless。", "procedure", "/prəˈsiː.dʒɚ/", "手術程序", "undergo", "/ˌʌn.dɚˈɡoʊ/", "經受經歷"),
            ("The factory violated environmental regulations repeatedly. ___, it was slapped with hefty government fines.", "Consequently", "However", "Instead", "Conversely", "該工廠屢次違反環保法規。因此，它遭到了政府巨額罰款的重罰處分。", "違規（因）導致罰款（果），副詞使用 Consequently（因此、結果）。", "因果後果選 Consequently。", "violate", "/ˈvaɪ.ə.leɪt/", "違反違背", "hefty", "/ˈhef.ti/", "沉重巨額的"),
            ("Regular cardiovascular exercise enhances physical stamina. ___, it reduces risks of chronic ailments.", "Furthermore", "However", "Instead", "On the contrary", "規律心血管運動增強身體耐力。此外，它還能降低罹患慢性病痛的風險。", "進一步正面補充益處，使用 Furthermore（此外）。", "正面遞進選 Furthermore。", "cardiovascular", "/ˌkɑːr.di.oʊˈvæs.kjə.lɚ/", "心血管的", "ailment", "/ˈeɪl.mənt/", "微恙病痛"),
            ("Critics claimed the new smartphone model would flop. ___, it became the bestselling device of the year.", "On the contrary", "Therefore", "In addition", "Similarly", "評論家曾宣稱這款新手機型號將會慘遭滑鐵盧。正相反，它成了年度最暢銷的智慧設備。", "否定前面的負面預測並引出完全相反的正面事實，使用 On the contrary（恰恰相反）。", "完全相反的事實選 On the contrary。", "flop", "/flɑːp/", "慘敗失敗", "bestselling", "/ˌbestˈsel.ɪŋ/", "最暢銷的"),
            ("Urban rents have escalated beyond affordability. ___, many young professionals are relocating to suburban districts.", "As a result", "However", "Conversely", "On the other hand", "城市房租已飛漲到難以負擔的地步。結果，許多年輕職場專業人士正遷往郊區城鎮。", "房租高（因）引發遷徙（果），選 As a result（結果）。", "因果結果選 As a result。", "escalate", "/ˈes.kə.leɪt/", "升級加劇攀升", "suburban", "/səˈbɝː.bən/", "郊區的"),
            ("The scientist's breakthrough theory was initially dismissed by peers. ___, it was later acknowledged as a stroke of genius.", "However", "Therefore", "Moreover", "Furthermore", "該科學家突破性的理論最初遭到同儕棄置不顧。然而，該理論後來被公認為天才的神來之筆。", "前後由被質疑轉折到獲承認，選 However。", "轉折對比選 However。", "dismiss", "/dɪsˈmɪs/", "不予理會駁回", "genius", "/ˈdʒiː.ni.əs/", "天賦天才"),
            ("She did not spend the windfall on frivolous luxuries. ___, she invested it in a college scholarship fund.", "Instead", "Therefore", "Moreover", "Consequently", "她並未將這筆橫財揮霍在無聊的奢侈品上。相反地，她將其全數投資於大學獎學金基金。", "前句否定 did not spend，後句引出替代善舉，使用 Instead（取而代之）。", "替代方案選 Instead。", "windfall", "/ˈwɪnd.fɑːl/", "意外之財橫財", "frivolous", "/ˈfrɪv.əl.əs/", "輕浮無聊的"),
            ("Global supply chains suffered severe disruptions during the conflict. ___, food prices surged worldwide.", "Accordingly", "However", "Instead", "Conversely", "衝突期間全球供應鏈遭受嚴重中斷。相應地，全球食品物價急遽飆升。", "因果相應承接使用 Accordingly（相應地、因此）。", "相應因果選 Accordingly。", "disruption", "/dɪsˈrʌp.ʃən/", "中斷混亂", "surge", "/sɝːdʒ/", "激增急遽上漲"),
            ("The applicant lacked formal pedagogical certification; ___, his profound practical expertise won over the committee.", "nonetheless", "therefore", "furthermore", "consequently", "該申請人缺乏正規教學認證；儘管如此，他深厚的實務專業知識贏得了委員會的青睞。", "缺乏認證與獲得青睞形成讓步轉折，使用 nonetheless（儘管如此）。", "讓步轉折選 nonetheless。", "pedagogical", "/ˌped.əˈɡɑː.dʒɪ.kəl/", "教學法的教育學的", "expertise", "/ˌek.spɝːˈtiːz/", "專長專業技能")
        ]),
        # 18. 高頻片語動詞與固定介系詞搭配 (attribute to, contribute to, prone to)
        ("高頻片語動詞與固定介系詞搭配", "單字語意", [
            ("The renowned scientist attributed her remarkable academic achievements ___ tireless perseverance.", "to", "for", "with", "in", "那位知名科學家將她卓越的學術成就歸功於不知疲倦的堅毅執著。", "attribute A to B 為核心片語，意為「將 A 歸因於/歸功於 B」。", "attribute A to B 介系詞選 to。", "attribute", "/əˈtrɪb.juːt/", "歸因於", "perseverance", "/ˌpɝː.səˈvɪr.əns/", "堅毅不懈"),
            ("Sedentary lifestyles and excessive screen time contribute significantly ___ cardiovascular ailments.", "to", "for", "with", "on", "久坐不動的生活方式與過度的螢幕時間是造成心血管疾病的重要肇因。", "contribute to + N/V-ing 意為「促成、導致、促使…發生」。", "contribute 搭配介系詞 to。", "sedentary", "/ˈsed.ən.ter.i/", "久坐不動的", "ailment", "/ˈeɪl.mənt/", "病痛疾病"),
            ("Children who do not get adequate rest are particularly prone ___ catching common viral infections.", "to", "for", "with", "at", "睡眠不足的孩童尤其容易感染常見的病毒性感冒。", "be prone to + N/V-ing 意為「易於…的、有…傾向的」。", "be prone to 介系詞選 to。", "prone", "/proʊn/", "易於…的", "infection", "/ɪnˈfek.ʃən/", "傳染感染"),
            ("The committee insisted ___ implementing the revised safety protocol without delay.", "on", "in", "to", "with", "委員會堅持要求毫不拖延地執行修訂後的安全規程。", "insist on + N/V-ing 意為「堅持要求…」。", "insist on 接動名詞。", "implement", "/ˈɪm.plə.ment/", "實施落實", "protocol", "/ˈproʊ.t̬ə.kɑːl/", "規程協議"),
            ("We must abide ___ all municipal environmental laws to preserve our fragile river ecosystem.", "by", "to", "with", "for", "我們必須遵守所有市府環保法律，以維護脆弱的河流生態系。", "abide by 意為「遵守、恪守（法律/諾言）」。", "abide by 固定搭配遵守。", "abide", "/əˈbaɪd/", "遵守容忍", "fragile", "/ˈfrædʒ.əl/", "脆弱易碎的"),
            ("The university scholarship committee was deeply impressed ___ her extraordinary resilience.", "by", "with", "at", "for", "大學獎學金委員會對她非凡的堅韌復原力留下了深刻印象。", "be impressed by / with 意為「對…留下深刻印象」。", "留深刻印象選 by/with。", "resilience", "/rɪˈzɪl.jəns/", "堅韌復原力", "extraordinary", "/ɪkˈstrɔːr.dən.er.i/", "非凡卓越的"),
            ("Chronic stress and sleep deprivation can deprive individuals ___ cognitive vitality.", "of", "from", "with", "for", "慢性壓力與睡眠剝奪會剝奪個人的認知活力。", "deprive sb of sth 意為「剝奪某人的某項權利或事物」。", "deprive A of B 搭配 of。", "deprive", "/dɪˈpraɪv/", "剝奪沒收", "vitality", "/vaɪˈtæl.ə.t̬i/", "活力生機"),
            ("The school campaign aims to discourage teenagers ___ consuming harmful energy drinks.", "from", "to", "at", "with", "校園宣導活動旨在勸阻青少年不要飲用有害的能量飲料。", "discourage sb from V-ing 意為「勸阻某人不要做某事」。", "discourage from 接 V-ing。", "discourage", "/dɪˈskɝː.ɪdʒ/", "勸阻打消念頭", "consume", "/kənˈsuːm/", "消費飲用"),
            ("Her innovative research paper conforms strictly ___ international academic publishing guidelines.", "to", "with", "in", "for", "她的創新研究論文完全符合國際學術出版規範標準。", "conform to 意為「符合、遵守、遵從（標準/法規）」。", "符合規範選 conform to。", "conform", "/kənˈfɔːrm/", "遵照符合", "innovative", "/ˈɪn.ə.veɪ.t̬ɪv/", "創新的"),
            ("Excessive carbon dioxide emissions are directly linked ___ catastrophic global climate disruption.", "to", "with", "for", "in", "過量二氧化碳排放與災難性的全球氣候破壞具有直接關聯。", "be linked to 意為「與…有直接連結或因果關聯」。", "與…連結選 linked to。", "catastrophic", "/ˌkæt̬.əˈstrɑː.fɪk/", "災難性的", "disruption", "/dɪsˈrʌp.ʃən/", "破壞干擾")
        ]),
        # 19. 限制與被動語態之複合句型 (be alleged to have, be deemed)
        ("限制與被動語態複合句型", "文法句構", [
            ("The suspect is alleged ___ the corporate database from an offshore server.", "to have breached", "breached", "breaching", "to breach", "該嫌疑犯被指控曾從境外伺服器入侵攻破了企業資料庫。", "be alleged to have + p.p. 表示「據指控先前曾做過某事」（完成不定詞表示動作發生在被指控之前）。", "據稱曾做過選 to have breached。", "allege", "/əˈledʒ/", "聲稱指控", "breach", "/briːtʃ/", "攻破入侵"),
            ("The historic temple is widely deemed ___ the crown jewel of ancient Taiwanese architecture.", "to be", "being", "been", "was", "這座歷史名廟被廣泛視為台灣古代建築的皇冠明珠瑰寶。", "be deemed to be + 名詞/形容詞，意為「被視為、被認為是」。", "被視為選 to be。", "deem", "/diːm/", "視為認為", "architecture", "/ˈɑːr.kə.tek.tʃɚ/", "建築學建築"),
            ("The ancient Egyptian pharaoh was believed ___ magnificent golden tombs.", "to have commissioned", "commissioning", "commissioned", "to commission", "那位古埃及法老被深信生前曾下令建造了壯麗的黃金陵寢。", "was believed to have + p.p. 表過去被相信曾下令建造。", "完成不定詞選 to have commissioned。", "commission", "/kəˈmɪʃ.ən/", "委任下令建造", "tomb", "/tuːm/", "陵墓墳寢"),
            ("The rogue executive was reported ___ millions in company funds before fleeing.", "to have embezzled", "embezzling", "embezzled", "to embezzle", "據報導該不肖主管在潛逃前曾盜用了數百萬公司資金。", "was reported to have embezzled 表先前曾挪用盜領公款。", "盜用公款選 to have embezzled。", "embezzle", "/ɪmˈbez.əl/", "侵占盜用公款", "flee", "/fliː/", "逃逸潛逃"),
            ("The innovative solar battery is considered ___ a technological breakthrough in clean energy.", "to represent", "representing", "represented", "represent", "這款創新的太陽能電池被認為代表了潔淨能源領域的一項重大技術突破。", "is considered to represent 意為「被認為代表著…」。", "被認為代表選 to represent。", "represent", "/ˌrep.rɪˈzent/", "代表象徵", "innovative", "/ˈɪn.ə.veɪ.t̬ɪv/", "創新的"),
            ("The medieval manuscript is thought ___ by a cloistered monk in the fourteenth century.", "to have been written", "to write", "writing", "to be writing", "這份中世紀手稿被認為是在十四世紀由一位深居修道院的僧侶所抄寫完成的。", "完成被動不定詞：is thought to have been written by...", "完成被動不定詞選 to have been written。", "manuscript", "/ˈmæn.jə.skrɪpt/", "手稿原稿", "cloistered", "/ˈklɔɪ.stɚd/", "隱居修道院的"),
            ("The corporate merger is expected ___ finalized before the end of the fiscal quarter.", "to be", "being", "been", "was", "該企業合併案預期將在本會計季度結束前正式敲定完成。", "is expected to be finalized（被動敲定完成）。", "預期被敲定選 to be。", "merger", "/ˈmɝː.dʒɚ/", "企業合併", "fiscal", "/ˈfɪs.kəl/", "會計財政的"),
            ("The controversial athlete was suspected ___ performance-enhancing substances.", "of taking", "to take", "with taking", "in taking", "該爭議運動員被懷疑曾服用禁藥體能增強劑。", "be suspected of + V-ing（或名詞），固定搭配介系詞 of！", "be suspected of 接動名詞。", "substance", "/ˈsʌb.stəns/", "物質藥物", "controversial", "/ˌkɑːn.trəˈvɝː.ʃəl/", "具爭議性的"),
            ("The novel is reputed ___ over fifty million copies in worldwide circulation.", "to have sold", "selling", "sold", "to sell", "據悉這部小說在全球發行量中已累計銷售突破五千萬冊。", "is reputed to have sold 表據估計已累計售出。", "累計售出選 to have sold。", "circulation", "/ˌsɝː.kjəˈleɪ.ʃən/", "發行流通", "reputed", "/rɪˈpjuː.t̬ɪd/", "號稱據譽的"),
            ("The ancient ruins are estimated ___ back to at least 3,000 BCE.", "to date", "dating", "dated", "to be dated", "這座古代廢墟據估計其歷史至少可以追溯至西元前三千年。", "be estimated to date back to... 追溯至某時期固定句型。", "追溯歷史選 to date back to。", "ruins", "/ˈruː.ɪnz/", "廢墟遺跡", "estimate", "/ˈes.tə.meɪt/", "估計評估")
        ]),
        # 20. 名詞性同位語子句 (the fact that, the hypothesis that)
        ("名詞性同位語子句", "文法句構", [
            ("The widespread rumor ___ the company was on the verge of bankruptcy proved completely unfounded.", "that", "which", "what", "whether", "關於該公司瀕臨破產邊緣的盛傳謠言被證實純屬子虛烏有。", "同位語子句：The rumor that + 完整陳述子句，that 作為同位語連接詞，不具代名詞成分（不可用 which）！", "同位語名詞子句引導詞選 that。", "unfounded", "/ʌnˈfaʊn.dɪd/", "無事實根據的", "bankruptcy", "/ˈbæŋ.krəpt.si/", "破產"),
            ("The scientific hypothesis ___ birds evolved from theropod dinosaurs is supported by fossil evidence.", "that", "which", "what", "where", "鳥類源自獸腳類恐龍演化而來的科學假說獲得了化石證據的強力支持。", "同位語子句：The hypothesis that + 完整事實子句。", "假說同位語子句選 that。", "theropod", "/ˈθer.ə.pɑːd/", "獸腳類恐龍", "fossil", "/ˈfɑː.səl/", "化石"),
            ("We cannot overlook the startling fact ___ global sea levels are rising at an accelerated rate.", "that", "which", "what", "whose", "我們絕不能忽視全球海平面正以加速速率上升這一驚人事實。", "同位語子句：the fact that + 完整客觀事實。", "the fact that 經典同位語。", "startling", "/ˈstɑːrt.lɪŋ/", "令人吃驚驚人的", "accelerated", "/əkˈsel.ɚ.eɪ.t̬ɪd/", "加速的"),
            ("The deep conviction ___ freedom of expression is an inalienable right inspired generations.", "that", "which", "what", "where", "言論自由是一項不可剝奪之基本權利的堅定信念鼓舞了世世代代。", "同位語子句：The conviction that...", "信念同位語選 that。", "conviction", "/kənˈvɪk.ʃən/", "堅定信念", "inalienable", "/ɪnˈeɪ.li.ə.nə.bəl/", "不可剝奪讓渡的"),
            ("There is compelling evidence ___ regular physical exercise sharpens cognitive memory in elderly individuals.", "that", "which", "what", "where", "有令人信服的證據表明，規律的體能鍛鍊能夠增強老年人的認知記憶力。", "evidence that + 完整事實名詞子句作同位語。", "證據同位語選 that。", "compelling", "/kəmˈpel.ɪŋ/", "令人信服強有力的", "cognitive", "/ˈkɑːɡ.nə.t̬ɪv/", "認知的"),
            ("The defense attorney rejected the absurd allegation ___ his client had orchestrated the heist.", "that", "which", "what", "where", "辯護律師斷然駁斥了指稱其當事人策劃了這起搶案的荒謬指控。", "The allegation that + 完整事實子句作同位語。", "指控同位語選 that。", "allegation", "/ˌæl.əˈɡeɪ.ʃən/", "指控指稱", "orchestrate", "/ˈɔːr.kə.streɪt/", "精心策劃"),
            ("The reassuring news ___ all miners were rescued unharmed brought immense relief to the families.", "that", "which", "what", "where", "所有礦工均安然無恙獲救的振奮消息帶給家屬無比的欣慰安慰。", "The news that + 完整事實子句作同位語。", "新聞消息同位語選 that。", "miner", "/ˈmaɪ.nɚ/", "礦工", "unharmed", "/ʌnˈhɑːrmd/", "未受傷完好的"),
            ("Scientists disputed the controversial assertion ___ artificial intelligence possesses genuine consciousness.", "that", "which", "what", "where", "科學家們反駁了主張人工智慧已具備真正自我意識的爭議斷言。", "The assertion that + 完整主張子句作同位語。", "主張斷言同位語選 that。", "assertion", "/əˈsɝː.ʃən/", "主張斷言", "consciousness", "/ˈkɑːn.ʃəs.nəs/", "意識知覺"),
            ("The prevailing belief ___ hard work guarantees prosperity is being questioned by sociologists.", "that", "which", "what", "where", "苦幹實幹必然帶來財富繁榮的流行信念正受到社會學家的廣泛質疑。", "The belief that + 完整觀念子句作同位語。", "信念同位語選 that。", "prevailing", "/prɪˈveɪ.lɪŋ/", "盛行流行的", "sociologist", "/ˌsoʊ.siˈɑː.lə.dʒɪst/", "社會學家"),
            ("Astronomers confirmed the discovery ___ a liquid water ocean exists beneath the moon's icy crust.", "that", "which", "what", "where", "天文學家證實了該衛星冰層下方存在液態水海洋的這項重大發現。", "The discovery that + 完整發現內容作同位語。", "發現同位語選 that。", "crust", "/krʌst/", "地殼外層", "astronomer", "/əˈstrɑː.nə.mɚ/", "天文學家")
        ]),
        # 21. 虛主詞 It 與虛受詞 It 句型 (find it difficult to V)
        ("虛主詞 It 與虛受詞 It 句型", "文法句構", [
            ("Foreign students often find ___ challenging to master Chinese tonal pronunciations.", "it", "this", "that", "them", "外國學生往往覺得要掌握中文聲調發音是極具挑戰性的。", "虛受詞句型：S + find/make/think/consider + it (虛受詞) + adj (補語) + to V (真受詞)！", "虛受詞固定使用 it。", "tonal", "/ˈtoʊ.nəl/", "聲調的音調的", "pronunciation", "/prəˌnʌn.siˈeɪ.ʃən/", "發音"),
            ("The new mobile banking app makes ___ convenient for users to transfer money securely.", "it", "this", "that", "them", "這款新行動網銀應用程式讓使用者安全轉帳變得極為便利。", "make it convenient to V 虛受詞句型。", "虛受詞選 it。", "transfer", "/trænsˈfɝː/", "轉帳移轉", "securely", "/səˈkjʊr.li/", "安全穩固地"),
            ("Leo considers ___ his moral duty to stand up for victims of school bullying.", "it", "this", "that", "them", "Leo 認為挺身而出捍衛校園霸凌的受害者是他責無旁貸的道德義務。", "consider it one's duty to V 虛受詞句型。", "虛受詞選 it。", "bullying", "/ˈbʊl.i.ɪŋ/", "霸凌欺凌", "victim", "/ˈvɪk.təm/", "受害者"),
            ("The torrential rain made ___ impossible for the aircraft to land safely on the runway.", "it", "this", "that", "them", "傾盆大雨使飛機根本不可能安全降落在跑道上。", "make it impossible for sb to V 虛受詞句型。", "虛受詞選 it。", "runway", "/ˈrʌn.weɪ/", "跑道", "aircraft", "/ˈer.kræft/", "飛機航空器"),
            ("I take ___ for granted that parents will always love and support their children unconditionally.", "it", "this", "that", "them", "我視父母永遠無條件疼愛並支持子女為理所當然之事。", "take it for granted that... 經典慣用語（將…視為理所當然）。", "take it for granted 選 it。", "unconditionally", "/ˌʌn.kənˈdɪʃ.ən.əl.i/", "無條件地", "granted", "/ˈɡræn.t̬ɪd/", "視為理所當然"),
            ("She thought ___ unwise to invest all her life savings in speculative crypto assets.", "it", "this", "that", "them", "她認為把畢生積蓄全部投資於投機性加密貨幣資產是極為不智的。", "think it unwise to V 虛受詞句型。", "虛受詞選 it。", "speculative", "/ˈspek.jə.lə.t̬ɪv/", "投機推測的", "saving", "/ˈseɪ.vɪŋ/", "儲蓄積蓄"),
            ("The noisy background music made ___ difficult for patrons to converse comfortably.", "it", "this", "that", "them", "嘈雜的背景音樂讓顧客們難以舒適地交談溝通。", "make it difficult to V 虛受詞句型。", "虛受詞選 it。", "converse", "/kənˈvɝːs/", "交談交談", "patron", "/ˈpeɪ.trən/", "顧客賓客"),
            ("We deem ___ essential that transparent accounting standards be maintained.", "it", "this", "that", "them", "我們認為維持透明公正的會計標準是至關重要的。", "deem it essential that... 虛受詞接 that 真受詞子句。", "虛受詞選 it。", "accounting", "/əˈkaʊn.t̬ɪŋ/", "會計審計", "transparent", "/trænˈspær.ənt/", "透明公開的"),
            ("Tony found ___ heartbreaking to witness the widespread destruction caused by the earthquake.", "it", "this", "that", "them", "目睹地震造成的廣泛毀滅破壞讓 Tony 感到無比心碎難受。", "find it heartbreaking to V 虛受詞結構。", "虛受詞選 it。", "heartbreaking", "/ˈhɑːrtˌbreɪ.kɪŋ/", "令人心碎的", "destruction", "/dɪˈstrʌk.ʃən/", "毀滅破壞"),
            ("The mentor made ___ clear that plagiarism would result in immediate expulsion.", "it", "this", "that", "them", "導師鄭重明確表態：抄襲剽竊將會招致立即開除退學的處分。", "make it clear that... 虛受詞句型（明確表明…）。", "make it clear that 選 it。", "plagiarism", "/ˈpleɪ.dʒɚ.ɪz.əm/", "抄襲剽竊", "expulsion", "/ɪkˈspʌl.ʃən/", "開除驅逐")
        ]),
        # 22. 複合形容詞構詞 (well-known, state-of-the-art, long-lasting)
        ("複合形容詞構詞", "單字語意", [
            ("The hospital newly installed a ___ diagnostic scanning system to detect tumors early.", "state-of-the-art", "out-of-date", "worn-out", "second-hand", "該醫院最新安裝了一套最先進頂尖的診斷掃描系統，以早期偵測腫瘤。", "state-of-the-art 複合形容詞，意為「最先進頂尖的、最現代化的」。", "最先進頂尖選 state-of-the-art。", "tumor", "/ˈtuː.mɚ/", "腫瘤", "diagnostic", "/ˌdaɪ.əɡˈnɑː.stɪk/", "診斷的"),
            ("The inspiring environmental documentary had a ___ impact on the young audience.", "far-reaching", "short-lived", "narrow-minded", "broken-hearted", "那部鼓舞人心的環保紀錄片對年輕觀眾產生了深遠持久的重大影響。", "far-reaching 複合形容詞，意為「影響深遠的、波及廣泛的」。", "影響深遠選 far-reaching。", "documentary", "/ˌdɑː.kjəˈmen.t̬ɚ.i/", "紀錄片", "inspiring", "/ɪnˈspaɪr.ɪŋ/", "鼓舞人心的"),
            ("Dr. Thornton is a ___ authority on comparative Germanic linguistics.", "world-renowned", "home-made", "short-tempered", "half-baked", "Thornton 博士是日耳曼比較語言學領域享譽全球的權威大師。", "world-renowned 複合形容詞，意為「舉世聞名的、享譽全球的」。", "享譽全球選 world-renowned。", "renowned", "/rɪˈnaʊnd/", "赫赫有名的", "linguistics", "/lɪŋˈɡwɪs.tɪks/", "語言學"),
            ("Regular exercise and proper nutrition promote ___ health and physical stamina.", "long-lasting", "short-sighted", "bad-tempered", "open-minded", "規律運動與適當營養能促進持久長遠的身體健康與體能耐力。", "long-lasting 複合形容詞，意為「持久耐久的」。", "持久耐久選 long-lasting。", "stamina", "/ˈstæm.ə.nə/", "耐力精力", "nutrition", "/nuːˈtrɪʃ.ən/", "營養"),
            ("The historic treaty brought about a ___ peace between the formerly hostile nations.", "hard-won", "easy-going", "absent-minded", "cold-blooded", "這份歷史條約為先前敵對的兩國帶來了得來不易的和平。", "hard-won 複合形容詞，意為「得來不易的、艱苦爭取來的」。", "得來不易選 hard-won。", "hostile", "/ˈhɑː.stəl/", "敵對的", "treaty", "/ˈtriː.t̬i/", "條約協定"),
            ("The novelist's ___ critique of social inequality provoked widespread national debate.", "thought-provoking", "sleep-inducing", "light-hearted", "quick-witted", "這位小說家發人深省的社會不平等批判激發了全國範圍的廣泛辯論。", "thought-provoking 複合形容詞，意為「引人深思發人深省的」。", "發人深省選 thought-provoking。", "critique", "/krɪˈtiːk/", "評論批評", "inequality", "/ˌɪn.ɪˈkwɑː.lə.t̬i/", "不平等不公"),
            ("Solar power is an eco-friendly and ___ alternative to fossil fuel energy.", "cost-effective", "ill-fated", "narrow-minded", "short-lived", "太陽能是替代化石燃料能源的一種環保且具成本效益的理想選擇。", "cost-effective 複合形容詞，意為「符合成本效益的、高性價比的」。", "成本效益選 cost-effective。", "alternative", "/ɑːlˈtɝː.nə.t̬ɪv/", "替代方案", "fossil", "/ˈfɑː.səl/", "化石"),
            ("The young architect presented an ___ design that maximized solar natural lighting.", "eye-catching", "ill-timed", "half-hearted", "broken-down", "這位年輕建築師呈現了一件醒目吸睛、能最大化利用自然採光的設計作品。", "eye-catching 複合形容詞，意為「吸睛醒目的、引人注目的」。", "吸睛醒目選 eye-catching。", "architect", "/ˈɑːr.kə.tekt/", "建築師", "lighting", "/ˈlaɪ.t̬ɪŋ/", "照明採光"),
            ("The diplomat was famous for being exceptionally ___ during tense negotiations.", "cool-headed", "hot-tempered", "narrow-minded", "weak-willed", "這位外交官以在緊繃的談判期間保持異常冷靜沉著而聞名。", "cool-headed 複合形容詞，意為「冷靜沉著的、頭腦清醒的」。", "冷靜沉著選 cool-headed。", "diplomat", "/ˈdɪp.lə.mæt/", "外交官", "tense", "/tens/", "緊繃緊張的"),
            ("His ___ remarks during the solemn ceremony caused widespread embarrassment.", "ill-mannered", "well-behaved", "kind-hearted", "good-natured", "他在莊嚴典禮上的無禮言論引起了全場極大的尷尬窘迫。", "ill-mannered 複合形容詞，意為「缺乏教養的、無禮粗鄙的」。", "無禮粗鄙選 ill-mannered。", "solemn", "/ˈsɑː.ləm/", "莊嚴肅穆的", "embarrassment", "/ɪmˈber.əs.mənt/", "尷尬難堪")
        ]),
        # 23. 學測綜合測驗克漏字：語境邏輯與篇章結構
        ("學測綜合測驗克漏字：語境邏輯與篇章結構", "篇章語境", [
            ("CLOZE PASSAGE: 'The Amazon rainforest plays a crucial role in regulating global climate patterns. [BLANK], rampant deforestation poses an unprecedented existential hazard.'", "However", "Therefore", "Moreover", "Consequently", "克漏字填空：亞馬遜雨林在調節全球氣候格局方面扮演關鍵角色。[空格]，猖獗的森林濫伐帶來了前所未有的生存危機。", "前後文由雨林的重要生態功能轉折到濫伐威脅，銜接詞使用 However（然而）。", "篇章語義轉折選 However。", "rampant", "/ˈræm.pənt/", "猖獗失控的", "existential", "/ˌeɡ.zɪˈsten.ʃəl/", "關乎生存存在的"),
            ("CLOZE PASSAGE: 'The research team conducted dozens of clinical trials. The outcome was so [BLANK] that international health agencies fast-tracked the vaccine.'", "promising", "disheartening", "ambiguous", "trivial", "克漏字：研究團隊進行了數十次臨床試驗。結果是如此有前途希望，以致於國際衛生機構加速批准了該疫苗。", "促使機構加速批准 (fast-track) 顯示試驗結果非常樂觀有前景，選 promising。", "結果極具希望選 promising。", "clinical", "/ˈklɪn.ɪ.kəl/", "臨床的", "trial", "/traɪəl/", "試驗測試"),
            ("CLOZE PASSAGE: 'Plastic bags do not disintegrate easily. [BLANK], they accumulate in ocean gyres, endangering thousands of marine animals annually.'", "Instead", "Consequently", "However", "Similarly", "克漏字：塑膠袋不易分解。[空格]，它們堆積在海洋環流中，每年危害數以千計的海洋動物。", "難以分解導致堆積危害海洋，因果承接選 Consequently（因此）。", "因果後果選 Consequently。", "gyre", "/dʒaɪr/", "海洋環流", "disintegrate", "/dɪˈsɪn.t̬ə.ɡreɪt/", "分解碎裂"),
            ("CLOZE PASSAGE: 'The government aims to curb carbon emissions. [BLANK] investing in solar energy, it offers subsidies for electric vehicle purchases.'", "In addition to", "In spite of", "Regardless of", "Due to", "克漏字：政府致力於抑制碳排放。[空格]投資太陽能，政府還為購買電動車提供補貼補助。", "在投資太陽能之餘還提供購車補助，屬於遞進並列，使用 In addition to（除…之外）。", "遞進並列選 In addition to。", "subsidy", "/ˈsʌb.sə.di/", "補貼補助金", "curb", "/kɝːb/", "抑制控制"),
            ("CLOZE PASSAGE: 'The historic manuscript was severely faded by humidity. Scholars found [BLANK] impossible to decipher the ancient script without ultraviolet imaging.'", "it", "this", "that", "them", "克漏字：這份歷史手稿受潮嚴重褪色。學者們發現若沒有紫外線成像輔助，要解讀古代手跡根本不可能。", "find it impossible to V 經典虛受詞 it 結構。", "虛受詞選 it。", "decipher", "/dɪˈsaɪ.fɚ/", "解讀密碼/手稿", "manuscript", "/ˈmæn.jə.skrɪpt/", "手稿原稿"),
            ("CLOZE PASSAGE: 'Exercise not only strengthens musculoskeletal resilience [BLANK] boosts mental cognitive agility.'", "but also", "and also", "as well", "too", "克漏字：運動不僅增強肌肉骨骼韌性，[空格]還能提振大腦認知敏銳度。", "not only A but also B 經典對等平行結構。", "固定搭配選 but also。", "musculoskeletal", "/ˌmʌs.kjə.loʊˈskel.ə.t̬əl/", "肌肉骨骼的", "agility", "/əˈdʒɪl.ə.t̬i/", "敏銳度敏捷"),
            ("CLOZE PASSAGE: 'The entrepreneur was on the verge of bankruptcy. [BLANK], she secured an angel investor who funded her revolutionary software venture.'", "Fortunately", "Tragically", "Similarly", "Consequently", "克漏字：該創業家曾瀕臨破產邊緣。[空格]，她成功爭取到一位天使投資人資助其革命性軟體新創事業。", "由破產危機峰迴路轉獲得資助，副詞使用 Fortunately（幸運地）。", "情勢轉好選 Fortunately。", "entrepreneur", "/ˌɑːn.trə.prəˈnɝː/", "創業家企業家", "venture", "/ˈven.tʃɚ/", "新創創投"),
            ("CLOZE PASSAGE: 'The author explores contrasting sociological theories. The essay is [BLANK] structured around comparative case analyses.'", "meticulously", "carelessly", "rarely", "scarcely", "克漏字：作者探討對立的社會學理論。這篇論文的結構圍繞著比較個案分析而縝密構建而成。", "嚴謹學術論文的結構安排用 meticulously（縝密細緻地）。", "縝密安排選 meticulously。", "sociological", "/ˌsoʊ.si.əˈlɑː.dʒɪ.kəl/", "社會學的", "meticulously", "/məˈtɪk.jə.ləs.li/", "縝密細緻地"),
            ("CLOZE PASSAGE: 'Ancient civilizations flourished near fertile river deltas. [BLANK], the Nile and the Euphrates provided agricultural sustenance.'", "Specifically", "Conversely", "Instead", "Nevertheless", "克漏字：古代文明繁榮於肥沃的三角洲附近。[空格]，尼羅河與幼發拉底河提供了農業生存養分。", "後句舉出具體河流印證前句通則，選 Specifically（具體而言）。", "具體例證選 Specifically。", "fertile", "/ˈfɝː.t̬əl/", "肥沃豐饒的", "sustenance", "/ˈsʌs.tən.əns/", "生計營養養分"),
            ("CLOZE PASSAGE: 'The athlete failed to qualify for the Olympics. [BLANK] giving up, he redoubled his training regime for the next championship.'", "Instead of", "Because of", "In spite of", "Due to", "克漏字：該運動員未能取得奧運資格。[空格]放棄，他反而為下屆錦標賽加倍苦練。", "Instead of + V-ing（與其放棄，取而代之的是…）。", "與其放棄選 Instead of。", "regime", "/reɪˈʒiːm/", "訓練規程養生法", "redouble", "/riːˈdʌb.əl/", "加倍加強")
        ]),
        # 24. 文意選填：八大詞性定位與語法語義雙重確認
        ("文意選填：八大詞性定位與語法語義雙重確認", "篇章語境", [
            ("CLOZE VOCAB: 'The breakthrough discovery received universal [BLANK] from scientists worldwide.'", "acclaim", "criticize", "fragile", "reluctantly", "文意選填：這項突破性發現受到全球科學家的普遍[空格]。", "universal 為形容詞，空格必為名詞受格，acclaim（讚譽、讚揚）符合詞性與褒義語境。", "形容詞後填名詞選 acclaim。", "acclaim", "/əˈkleɪm/", "讚譽讚揚", "breakthrough", "/ˈbreɪk.θruː/", "突破性進展"),
            ("CLOZE VOCAB: 'The architect created an [BLANK] design that harmonized with the surrounding mountains.'", "exquisite", "destroy", "carelessly", "adversity", "文意選填：建築師創造了一件與周圍群山和諧共處的[空格]設計。", "an 後接母音開頭的形容詞修飾名詞 design，exquisite（精美精緻的）符合語法語義。", "冠詞 an 後填形容詞選 exquisite。", "exquisite", "/ɪkˈskwɪz.ɪt/", "精緻精美的", "harmonize", "/ˈhɑːr.mə.naɪz/", "和諧融為一體"),
            ("CLOZE VOCAB: 'The marathon runner pushed forward [BLANK] despite agonizing muscle cramps.'", "tenaciously", "tenacious", "tenacity", "deteriorate", "文意選填：馬拉松跑者儘管遭受劇烈肌肉抽筋，依然[空格]奮勇向前推進。", "修飾動詞片語 pushed forward 必須填入副詞，tenaciously（頑強堅韌地）符合詞性格局。", "修飾動詞填副詞選 tenaciously。", "tenaciously", "/təˈneɪ.ʃəs.li/", "頑強堅定地", "cramp", "/kræmp/", "抽筋痙攣"),
            ("CLOZE VOCAB: 'Heavy rainfall can [BLANK] the stability of the loosened hillside soil.'", "compromise", "compromised", "compromising", "compromiseable", "文意選填：暴雨會[空格]鬆動山坡土壤的穩定性。", "助動詞 can 後方必須填入原形動詞 (V)，compromise 意為「危害、損害」。", "助動詞後填原形動詞選 compromise。", "compromise", "/ˈkɑːm.prə.maɪz/", "危害損害", "hillside", "/ˈhɪl.saɪd/", "山坡山腰"),
            ("CLOZE VOCAB: 'Her profound speech left a lasting [BLANK] on the graduating students.'", "impression", "impress", "impressive", "impressively", "文意選填：她深刻的演講給畢業生們留下了持久的[空格]。", "冠詞 a 與形容詞 lasting 之後需填入單數名詞，impression（印象）符合搭配。", "形容詞後填名詞選 impression。", "impression", "/ɪmˈpreʃ.ən/", "印象印記", "profound", "/prəˈfaʊnd/", "深刻深遠的"),
            ("CLOZE VOCAB: 'The committee members voted to [BLANK] the outdated campus dress regulations.'", "abolish", "abolition", "abolished", "abolishing", "文意選填：委員會成員投票決定[空格]過時的校園服儀規範。", "不定詞 to 後接原形及物動詞，abolish（廢除、廢止）符合語法。", "不定詞 to 後填原形動詞選 abolish。", "abolish", "/əˈbɑː.lɪʃ/", "廢除廢止", "outdated", "/ˌaʊtˈdeɪ.t̬ɪd/", "過時陳舊的"),
            ("CLOZE VOCAB: 'The young violinist showed [BLANK] talent during her debut performance.'", "exceptional", "exception", "exceptionally", "except", "文意選填：這位年輕小提琴家在她的首演演出中展現了[空格]的才華。", "修飾名詞 talent 需填入形容詞，exceptional（卓越出眾的）符合要求。", "修飾名詞填形容詞選 exceptional。", "exceptional", "/ɪkˈsep.ʃən.əl/", "卓越非凡的", "debut", "/deɪˈbjuː/", "首次亮相登台"),
            ("CLOZE VOCAB: 'The government pledged to resolve the water shortage problem [BLANK].'", "expeditiously", "expeditious", "expedite", "expedition", "文意選填：政府誓言將[空格]解決缺水問題。", "修飾動詞 resolve problem 需填副詞，expeditiously（迅速高效地）符合語意。", "修飾動詞填副詞選 expeditiously。", "expeditiously", "/ˌek.spəˈdɪʃ.əs.li/", "迅速敏捷地", "shortage", "/ˈʃɔːr.t̬ɪdʒ/", "短缺不足"),
            ("CLOZE VOCAB: 'Rising inflation poses a severe [BLANK] to the purchasing power of low-income families.'", "threat", "threaten", "threatening", "threatened", "文意選填：日益升高的通膨對低收入家庭的購買力構成了嚴峻的[空格]。", "冠詞 a 與形容詞 severe 後填單數名詞，threat（威脅）符合結構。", "形容詞後填名詞選 threat。", "threat", "/θret/", "威脅恐嚇", "inflation", "/ɪnˈfleɪ.ʃən/", "通貨膨脹"),
            ("CLOZE VOCAB: 'The scientist was able to [BLANK] the authenticity of the ancient papyrus scroll.'", "substantiate", "substantial", "substance", "substantially", "文意選填：該科學家能夠[空格]這捲古代莎草紙手卷的真實性。", "be able to 後接原形動詞，substantiate（證實、證明）符合語義與語法。", "不定詞 to 後填原形動詞選 substantiate。", "substantiate", "/səbˈstæn.ʃi.eɪt/", "證實證明", "authenticity", "/ˌɑː.θenˈtɪs.ə.t̬i/", "真實性可信度")
        ]),
        # 25. 篇章結構閱讀：主題句、支持句與結論句呼應
        ("篇章結構閱讀：主題句、支持句與結論句呼應", "篇章語境", [
            ("READING STRUCTURE: Which sentence would serve as the most effective Topic Sentence for a paragraph on renewable energy?", "Transitioning to renewable energy is imperative to avert catastrophic climate change.", "Solar panels are usually rectangular and black.", "Wind was mentioned in ancient Greek mythology.", "My neighbor installed a small battery yesterday.", "篇章結構分析：哪一句最適合作為探討再生能源段落的主題句（Topic Sentence）？", "主題句需具備概括性、前瞻性與核心論點：轉向再生能源對防止氣候變遷至關重要。", "段落主題句選具概括性論點之句子。", "imperative", "/ɪmˈper.ə.t̬ɪv/", "迫切必要的", "avert", "/əˈvɝːt/", "防止避免"),
            ("READING STRUCTURE: Which sentence provides the strongest Supporting Evidence for the claim that exercise boosts academic achievement?", "Neuroscientific studies show that aerobic exercise enhances hippocampal memory retention by 15%.", "Many students enjoy wearing running shoes.", "The gym was repainted during summer vacation.", "Exercise equipment can be quite costly.", "支持句分析：哪一句為「運動能提升學業成績」的主張提供了最強力的支持性證據（Supporting Evidence）？", "神經科學實證數據直接連結有氧運動與記憶保留率提升15%，為最強力支持證據。", "實證數據支持句最有力。", "hippocampal", "/ˌhɪp.oʊˈkæm.pəl/", "海馬迴的", "retention", "/rɪˈten.ʃən/", "保持保留"),
            ("READING STRUCTURE: Identify the sentence that best functions as a Concluding Sentence summarizing a passage on digital literacy.", "Ultimately, equipping students with critical digital literacy is fundamental to nurturing informed democratic citizens.", "Laptops have varied screen resolutions.", "Internet speed increased last year.", "Some students prefer tablets over desktop computers.", "結論句分析：哪一句最能作為總結數位素養文章的結論句（Concluding Sentence）？", "以 Ultimately（終極而言）總結培養具備批判性數位素養是培育明智公民之基石。", "總結性結論句以 Ultimately 總攬核心價值。", "literacy", "/ˈlɪt̬.ɚ.ə.si/", "素養識字能力", "nurture", "/ˈnɝː.tʃɚ/", "培育培養"),
            ("READING STRUCTURE: What is the primary rhetorical function of a Transition Sentence between paragraph two and three?", "To bridge the previous paragraph's discussion of environmental hazards with the next paragraph's proposed solutions.", "To repeat word-for-word the introductory hook.", "To introduce unrelated biographical trivia.", "To list technical glossary definitions in alphabetical order.", "轉折銜接句功能：承上啟下，將前段環境危害與後段解決方案自然過渡銜接。", "銜接句功能為承上啟下。", "transition", "/trænˈzɪʃ.ən/", "轉折過渡", "bridge", "/brɪdʒ/", "架橋銜接"),
            ("READING STRUCTURE: If a paragraph discusses the drawbacks of urban sprawl, which sentence should be excluded as Irrelevant Information?", "Suburban commuters often spend ninety minutes daily navigating highway congestion.", "Urban sprawl leads to habitat fragmentation and biodiversity loss.", "The city's founding mayor was born on a Tuesday in April.", "Sprawling infrastructure increases municipal maintenance expenditures.", "無關訊息排除題：在探討都市蔓延弊端的段落中，市長出生日期的枝節瑣事與主旨無關，應當予以剔除。", "剔除無關主旨之枝節訊息。", "sprawl", "/sprɑːl/", "無序蔓延延伸", "irrelevant", "/ɪˈrel.ə.vənt/", "不相干的"),
            ("READING STRUCTURE: In an argumentative essay advocating for art education, where should the Counter-Argument be placed?", "In a dedicated body paragraph followed immediately by a robust refutation.", "At the very end of the bibliography citation list.", "In the footnote of page one.", "Hidden inside parentheses within the title.", "論說文架構分析：在提倡藝術教育的議論文中，反對觀點（Counter-Argument）應置於獨立段落並緊隨有力反駁。", "駁論段結構：提出反方論點並緊隨反駁駁斥。", "counter-argument", "/ˈkaʊn.t̬ɚˌɑːrɡ.jə.mənt/", "反對論點", "refutation", "/ˌref.jəˈteɪ.ʃən/", "駁斥反駁"),
            ("READING STRUCTURE: Which concluding transition signals a final synthesized takeaway in academic discourse?", "Taken together, these empirical findings underscore the necessity of comprehensive reform.", "By the way, did you know that paper is made from trees?", "Anyway, I have to go now.", "As I was saying earlier, cats are cute.", "學術結論過渡標記：Taken together（綜上所述、綜合觀之）引出研究結論。", "學術總結標記選 Taken together。", "synthesize", "/ˈsɪn.θə.saɪz/", "綜合整合", "empirical", "/emˈpɪr.ɪ.kəl/", "實證經驗的"),
            ("READING STRUCTURE: What structural role does an Anecdotal Hook serve in the introductory paragraph?", "To engage the reader's emotional interest before introducing the central thesis statement.", "To prove statistical validity beyond any doubt.", "To fulfill minimum word count requirements.", "To summarize the entire conclusion prematurely.", "開頭軼事引子功能：在導入中心主旨句前先引發讀者的情感共鳴與閱讀興趣。", "引子功能為吸引讀者興趣。", "anecdotal", "/ˌæn.ɪkˈdoʊ.t̬əl/", "軼事趣聞的", "hook", "/hʊk/", "吸睛開頭引子"),
            ("READING STRUCTURE: In a cause-and-effect essay on ocean acidification, the thesis statement should clearly identify:", "Both the underlying chemical causes and the ecological ramifications.", "Only the price of seafood in local markets.", "The life story of a fictional fisherman.", "A list of famous beach resort hotels.", "因果分析文中心句應明確闡明：潛在化學起因以及連帶引發的生態後果衝擊。", "因果文中心句需涵蓋原因與後果。", "acidification", "/əˌsɪd.ə.fəˈkeɪ.ʃən/", "酸化作用", "ramification", "/ˌræm.ə.fəˈkeɪ.ʃən/", "後果衍生影響"),
            ("READING STRUCTURE: How do cohesive devices such as 'Furthermore' and 'In contrast' enhance text coherence?", "By establishing explicit logical relationships between consecutive arguments.", "By making sentences as long and convoluted as possible.", "By hiding grammatical mistakes within the paragraph.", "By replacing all verbs with nouns.", "篇章銜接詞之修辭功能：在前後相連的論點之間建立起明確清晰的邏輯關聯性。", "篇章銜接詞建立明確邏輯關聯。", "cohesive", "/koʊˈhiː.sɪv/", "具凝聚力銜接性的", "coherence", "/koʊˈhɪr.əns/", "條理連貫性")
        ])
    ]
    
    subtopics_data.extend(remaining_subtopics_4)
    subtopics_data.extend(remaining_subtopics_4_part2)
    
    q_counter = 750
    for idx, (sub_title, dim, q_list) in enumerate(subtopics_data):
        unit_num = (idx % 8) + 1
        hook_item = {"module": "arch", "unitId": f"arch-m{unit_num}", "unitTitle": f"Arch 高中先修: 五大句型與核心素養 Unit {unit_num}"}
        for q_tuple in q_list:
            q_counter += 1
            if len(q_tuple) == 15:
                prompt, corr, d1, d2, d3, trans, concept, analysis, trap, w1, p1, m1, w2, p2, m2 = q_tuple
            elif len(q_tuple) == 14:
                prompt, corr, d1, d2, d3, trans, concept, trap, w1, p1, m1, w2, p2, m2 = q_tuple
                analysis = "標準高中學測素養句構：主從句與修飾語語法關係嚴謹。"
            else:
                prompt, corr, d1, d2, d3, trans, concept, w1, p1, m1, w2, p2, m2 = q_tuple
                analysis = "篇章結構與語意邏輯嚴密，考核高中核心英語素養考點。"
                trap = f"正確選項為「{corr}」。其他選項在詞性、語境搭配或邏輯推論上存在明顯漏洞。"
            item = make_q(
                q_id=q_counter,
                subtopic=sub_title,
                dim=dim,
                hook=hook_item,
                prompt=prompt,
                corr=corr,
                d1=d1,
                d2=d2,
                d3=d3,
                trans=trans,
                concept=concept,
                analysis=analysis,
                trap=trap,
                w1=w1,
                p1=p1,
                m1=m1,
                w2=w2,
                p2=p2,
                m2=m2
            )
            items.append(item)
            
    assert len(items) == 250, f"Tier 4 expected 250 items, got {len(items)}"
    return items
