# scripts/build_elementary_junior_vocab.py
# -*- coding: utf-8 -*-
"""
建置教育部 108 課綱標準「國小必備核心單字庫 (350+ 詞)」與「國中會考核心單字庫 (450+ 詞)」
每一單字均包含：
- word: 英文單字拼寫
- chunk: 自然拼讀音節拆解
- ipa: KK 音標
- pos: 詞性標籤
- zh: 繁體中文標準釋義
- category: 主題分類
- collocation: 核心搭配詞 / 常用短語
- example: 生活情境例句
- exampleZh: 例句繁中中譯
- memoryTip: 自然拼讀規則、字根字首或記憶技巧
- source: 來源標註（國小基礎 / 國中會考核心）
"""

import json
import re

ELEMENTARY_WORDS = [
    # 1. 人物、家庭與身分 (Family & People)
    {"word": "family", "chunk": "fam - i - ly", "ipa": "/ˈfæm.əl.i/", "pos": "n.", "zh": "家庭、家人", "category": "家庭與身分", "collocation": "family member (家庭成員)", "example": "I love eating dinner with my family every evening.", "exampleZh": "我喜歡每天傍晚和家人一起吃晚餐。", "memoryTip": "fam 短母音 /æ/ + 弱讀 /ə/ + ly /li/"},
    {"word": "father", "chunk": "fa - ther", "ipa": "/ˈfɑː.ðɚ/", "pos": "n.", "zh": "父親、爸爸", "category": "家庭與身分", "collocation": "my father", "example": "My father drives me to school in the morning.", "exampleZh": "我爸爸早上開車載我去學校。", "memoryTip": "th 發濁音 /ð/ + er 捲舌音 /ɚ/"},
    {"word": "mother", "chunk": "moth - er", "ipa": "/ˈmʌð.ɚ/", "pos": "n.", "zh": "母親、媽媽", "category": "家庭與身分", "collocation": "working mother (職業婦女)", "example": "Her mother is a very kind and caring doctor.", "exampleZh": "她的媽媽是一位非常親切且有愛心的醫生。", "memoryTip": "o 發短母音 /ʌ/，th 發濁音 /ð/"},
    {"word": "parent", "chunk": "par - ent", "ipa": "/ˈpɛr.ənt/", "pos": "n.", "zh": "雙親之一、父母親", "category": "家庭與身分", "collocation": "parents (雙親)", "example": "Both of my parents enjoy gardening on weekends.", "exampleZh": "我父母週末都很喜歡從事園藝。", "memoryTip": "par 發 /pɛr/ + ent 弱讀 /ənt/"},
    {"word": "brother", "chunk": "broth - er", "ipa": "/ˈbrʌð.ɚ/", "pos": "n.", "zh": "哥哥、弟弟", "category": "家庭與身分", "collocation": "older brother (哥哥)", "example": "My brother plays basketball with his friends.", "exampleZh": "我哥哥經常和他的朋友打籃球。", "memoryTip": "broth 發 /brʌð/ + er /ɚ/"},
    {"word": "sister", "chunk": "sis - ter", "ipa": "/ˈsɪs.tɚ/", "pos": "n.", "zh": "姊姊、妹妹", "category": "家庭與身分", "collocation": "younger sister (妹妹)", "example": "Her sister is practicing the piano in the room.", "exampleZh": "她妹妹正在房間裡練鋼琴。", "memoryTip": "sis 閉音節短音 /ɪ/ + ter /tɚ/"},
    {"word": "grandfather", "chunk": "grand - fa - ther", "ipa": "/ˈɡrændˌfɑː.ðɚ/", "pos": "n.", "zh": "祖父、爺爺、外公", "category": "家庭與身分", "collocation": "visit grandfather", "example": "We visit grandfather every Sunday afternoon.", "exampleZh": "我們每週日下次回訪祖父。", "memoryTip": "grand (宏大的/長輩) + father"},
    {"word": "grandmother", "chunk": "grand - moth - er", "ipa": "/ˈɡrændˌmʌð.ɚ/", "pos": "n.", "zh": "祖母、奶奶、外婆", "category": "家庭與身分", "collocation": "grandmother's cookies", "example": "Grandmother makes the most delicious apple pie.", "exampleZh": "奶奶做的蘋果派是最好吃的。", "memoryTip": "grand + mother"},
    {"word": "uncle", "chunk": "un - cle", "ipa": "/ˈʌŋ.kəl/", "pos": "n.", "zh": "伯父、叔父、舅舅", "category": "家庭與身分", "collocation": "my uncle", "example": "My uncle brought me a model airplane from Tokyo.", "exampleZh": "我叔叔從東京帶了一架模型飛機給我。", "memoryTip": "un 發 /ʌŋ/ + cle 發成音節 /kəl/"},
    {"word": "aunt", "chunk": "aunt", "ipa": "/ænt/", "pos": "n.", "zh": "姑母、伯母、阿姨", "category": "家庭與身分", "collocation": "Aunt Mary", "example": "Aunt Mary teaches art at an elementary school.", "exampleZh": "瑪麗阿姨在國小教美術。", "memoryTip": "au 發短母音 /æ/ (同 ant 音)"},
    {"word": "cousin", "chunk": "cous - in", "ipa": "/ˈkʌz.ən/", "pos": "n.", "zh": "堂表兄弟姊妹", "category": "家庭與身分", "collocation": "play with cousins", "example": "I played video games with my cousin yesterday.", "exampleZh": "我昨天和我表哥一起玩電玩。", "memoryTip": "ou 發短母音 /ʌ/ + sin 弱讀 /zən/"},
    {"word": "son", "chunk": "son", "ipa": "/sʌn/", "pos": "n.", "zh": "兒子", "category": "家庭與身分", "collocation": "only son (獨生子)", "example": "Mr. Lin is very proud of his eldest son.", "exampleZh": "林先生對他的大兒子感到非常驕傲。", "memoryTip": "同音字：sun (太陽)！發音皆為 /sʌn/"},
    {"word": "daughter", "chunk": "daugh - ter", "ipa": "/ˈdɔː.tɚ/", "pos": "n.", "zh": "女兒", "category": "家庭與身分", "collocation": "beloved daughter", "example": "Their daughter won first prize in the speech contest.", "exampleZh": "他們的女兒在演講比賽中贏得第一名。", "memoryTip": "augh 發長母音 /ɔː/，gh 不發音"},
    {"word": "baby", "chunk": "ba - by", "ipa": "/ˈbeɪ.bi/", "pos": "n.", "zh": "嬰兒、小寶寶", "category": "家庭與身分", "collocation": "baby brother", "example": "The baby is sleeping peacefully in the crib.", "exampleZh": "小寶寶在嬰兒床裡安靜地睡著。", "memoryTip": "開音節 ba 發長音 /beɪ/ + by 發 /bi/"},
    {"word": "child", "chunk": "child", "ipa": "/tʃaɪld/", "pos": "n.", "zh": "兒童、小孩 (單數)", "category": "家庭與身分", "collocation": "only child", "example": "Every child has the right to receive an education.", "exampleZh": "每個孩子都有接受教育的權利。", "memoryTip": "ch 發 /tʃ/ + ild 發長音 /aɪld/"},
    {"word": "children", "chunk": "chil - dren", "ipa": "/ˈtʃɪl.drən/", "pos": "n.", "zh": "兒童、孩子們 (複數)", "category": "家庭與身分", "collocation": "children's playground", "example": "The children are playing hide-and-seek in the park.", "exampleZh": "孩子們正在公園裡玩捉迷藏。", "memoryTip": "不規則複數：child (/aɪ/) ➔ children (/ɪ/)"},
    {"word": "friend", "chunk": "friend", "ipa": "/frɛnd/", "pos": "n.", "zh": "朋友", "category": "家庭與身分", "collocation": "best friend", "example": "A true friend is always there when you need help.", "exampleZh": "真正的朋友在你需要幫助時總會陪伴在旁。", "memoryTip": "ie 不規則發短母音 /ɛ/！A friend to the end"},
    {"word": "teacher", "chunk": "teach - er", "ipa": "/ˈtiː.tʃɚ/", "pos": "n.", "zh": "老師、教師", "category": "學校與教室", "collocation": "English teacher", "example": "Our English teacher explains grammar very clearly.", "exampleZh": "我們的英文老師文法解釋得非常清楚。", "memoryTip": "teach (教) + -er (人) ➔ 老師"},
    {"word": "student", "chunk": "stu - dent", "ipa": "/ˈstjuː.dənt/", "pos": "n.", "zh": "學生", "category": "學校與教室", "collocation": "good student", "example": "The student raised her hand to ask a question.", "exampleZh": "那名學生舉手發問。", "memoryTip": "stu 開音節 /stjuː/ + dent 弱讀 /dənt/"},
    {"word": "classmate", "chunk": "class - mate", "ipa": "/ˈklæs.meɪt/", "pos": "n.", "zh": "同班同學", "category": "學校與教室", "collocation": "friendly classmate", "example": "Tom and I have been classmates for three years.", "exampleZh": "湯姆和我當同班同學已經三年了。", "memoryTip": "class (班級) + mate (夥伴) ➔ 同學"},

    # 2. 學校與教室 (School & Classroom)
    {"word": "school", "chunk": "school", "ipa": "/skuːl/", "pos": "n.", "zh": "學校", "category": "學校與教室", "collocation": "go to school (上學)", "example": "We walk to school together every morning.", "exampleZh": "我們每天早上一同走路去上學。", "memoryTip": "sch 發 /sk/ + oo 發長音 /uː/"},
    {"word": "classroom", "chunk": "class - room", "ipa": "/ˈklæs.ruːm/", "pos": "n.", "zh": "教室", "category": "學校與教室", "collocation": "clean the classroom", "example": "Please keep the classroom clean and tidy.", "exampleZh": "請保持教室乾淨整潔。", "memoryTip": "class (班級) + room (房間)"},
    {"word": "blackboard", "chunk": "black - board", "ipa": "/ˈblæk.bɔːrd/", "pos": "n.", "zh": "黑板", "category": "學校與教室", "collocation": "write on the blackboard", "example": "The teacher wrote new words on the blackboard.", "exampleZh": "老師把生字寫在黑板上。", "memoryTip": "black (黑) + board (板)"},
    {"word": "desk", "chunk": "desk", "ipa": "/dɛsk/", "pos": "n.", "zh": "書桌、辦公桌", "category": "學校與教室", "collocation": "sit at the desk", "example": "Put your textbooks on the desk, please.", "exampleZh": "請把課本放在書桌上。", "memoryTip": "CVC 結構，e 發短音 /ɛ/"},
    {"word": "chair", "chunk": "chair", "ipa": "/tʃɛr/", "pos": "n.", "zh": "椅子", "category": "學校與教室", "collocation": "sit on a chair", "example": "He pulled out a chair and sat down quietly.", "exampleZh": "他拉開椅子安靜地坐下。", "memoryTip": "air 發 /ɛr/，ch 發 /tʃ/"},
    {"word": "pencil", "chunk": "pen - cil", "ipa": "/ˈpɛn.səl/", "pos": "n.", "zh": "鉛筆", "category": "學校與教室", "collocation": "sharpen a pencil", "example": "I need a pencil to finish my math homework.", "exampleZh": "我需要一隻鉛筆來完成我的數學作業。", "memoryTip": "pen + cil (c 在 i 前發軟音 /s/)"},
    {"word": "eraser", "chunk": "e - ras - er", "ipa": "/ɪˈreɪ.sɚ/", "pos": "n.", "zh": "橡皮擦", "category": "學校與教室", "collocation": "use an eraser", "example": "Can I borrow your eraser for a minute?", "exampleZh": "我可以借用一下你的橡皮擦嗎？", "memoryTip": "erase (擦掉) + -er (工具)"},
    {"word": "ruler", "chunk": "rul - er", "ipa": "/ˈruː.lɚ/", "pos": "n.", "zh": "尺、直尺", "category": "學校與教室", "collocation": "draw lines with a ruler", "example": "Use a ruler to draw a straight line.", "exampleZh": "請用直尺畫出一條直線。", "memoryTip": "rule (規則/丈量) + -er"},
    {"word": "notebook", "chunk": "note - book", "ipa": "/ˈnoʊt.bʊk/", "pos": "n.", "zh": "筆記本", "category": "學校與教室", "collocation": "take notes in a notebook", "example": "Write down the important rules in your notebook.", "exampleZh": "把重要的規則記在筆記本裡。", "memoryTip": "note (筆記) + book (書本)"},
    {"word": "backpack", "chunk": "back - pack", "ipa": "/ˈbæk.pæk/", "pos": "n.", "zh": "雙肩後背包、書包", "category": "學校與教室", "collocation": "carry a backpack", "example": "Her backpack was filled with interesting books.", "exampleZh": "她的後背包裝滿了有趣的書籍。", "memoryTip": "back (背部) + pack (包裹)"},
    {"word": "homework", "chunk": "home - work", "ipa": "/ˈhoʊm.wɝːk/", "pos": "n.", "zh": "家庭作業 (不可數)", "category": "學校與教室", "collocation": "do homework (寫作業)", "example": "I always finish my homework before having dinner.", "exampleZh": "我總是在吃晚餐前完成作業。", "memoryTip": "home (家) + work (功課)，注意為不可數名詞！"},
    {"word": "library", "chunk": "li - brar - y", "ipa": "/ˈlaɪ.brɛr.i/", "pos": "n.", "zh": "圖書館", "category": "學校與教室", "collocation": "borrow books from the library", "example": "Students are studying quietly in the school library.", "exampleZh": "學生們正在學校圖書館裡安靜地讀書。", "memoryTip": "li 發 /laɪ/ + brary 發 /brɛr.i/"},
    {"word": "playground", "chunk": "play - ground", "ipa": "/ˈpleɪ.ɡraʊnd/", "pos": "n.", "zh": "操場、遊戲場", "category": "學校與教室", "collocation": "run on the playground", "example": "Children love running around on the playground during recess.", "exampleZh": "下課時孩子們喜歡在操場上奔跑。", "memoryTip": "play (玩耍) + ground (場地)"},

    # 3. 日常生活動作與習慣 (Daily Life & Verbs)
    {"word": "listen", "chunk": "lis - ten", "ipa": "/ˈlɪs.ən/", "pos": "v.", "zh": "聆聽、注意聽", "category": "日常動作與作息", "collocation": "listen to music", "example": "Please listen carefully to the speaker.", "exampleZh": "請專心聆聽發言者的內容。", "memoryTip": "t 不發音，lis 短音 /ɪ/ + ten 弱讀 /ən/"},
    {"word": "speak", "chunk": "speak", "ipa": "/spiːk/", "pos": "v.", "zh": "講話、說（某種語言）", "category": "日常動作與作息", "collocation": "speak English", "example": "Can you speak English fluently?", "exampleZh": "你能流利地說英文嗎？", "memoryTip": "ea 字母組合發長音 /iː/"},
    {"word": "read", "chunk": "read", "ipa": "/riːd/", "pos": "v.", "zh": "閱讀、朗讀", "category": "日常動作與作息", "collocation": "read a book", "example": "I like to read storybooks before going to sleep.", "exampleZh": "我喜歡在睡前閱讀故事書。", "memoryTip": "現在式發長音 /iː/，過去式 read 發短音 /ɛ/！"},
    {"word": "write", "chunk": "write", "ipa": "/raɪt/", "pos": "v.", "zh": "書寫、寫信", "category": "日常動作與作息", "collocation": "write a letter", "example": "She writes a diary entry every single night.", "exampleZh": "她每晚都會寫一篇日記。", "memoryTip": "w 不發音，Magic E 使 i 發長音 /aɪ/"},
    {"word": "wash", "chunk": "wash", "ipa": "/wɑːʃ/", "pos": "v.", "zh": "清洗、洗滌", "category": "日常動作與作息", "collocation": "wash your hands", "example": "Always wash your hands before eating snacks.", "exampleZh": "吃點心前務必記得洗手。", "memoryTip": "sh 發軟音 /ʃ/，a 發短音 /ɑː/"},
    {"word": "brush", "chunk": "brush", "ipa": "/brʌʃ/", "pos": "v. / n.", "zh": "刷（牙）、刷子", "category": "日常動作與作息", "collocation": "brush teeth (刷牙)", "example": "Remember to brush your teeth twice a day.", "exampleZh": "記得每天要刷兩次牙。", "memoryTip": "u 發短母音 /ʌ/，sh 發 /ʃ/"},
    {"word": "cook", "chunk": "cook", "ipa": "/kʊk/", "pos": "v. / n.", "zh": "烹飪、煮飯；廚師", "category": "日常動作與作息", "collocation": "cook dinner", "example": "Dad loves to cook delicious meals for the family.", "exampleZh": "爸爸很喜歡為家人煮美味的餐點。", "memoryTip": "oo 發短母音 /ʊ/ (同 book, look)"},
    {"word": "clean", "chunk": "clean", "ipa": "/kliːn/", "pos": "v. / adj.", "zh": "打掃；乾淨的", "category": "日常動作與作息", "collocation": "clean the room", "example": "We cleaned our bedroom together on Saturday.", "exampleZh": "我們週六一起把臥室打掃乾淨。", "memoryTip": "ea 字母組合發長母音 /iː/"},
    {"word": "sleep", "chunk": "sleep", "ipa": "/sliːp/", "pos": "v. / n.", "zh": "睡覺；睡眠", "category": "日常動作與作息", "collocation": "go to sleep", "example": "Children should sleep for at least eight hours.", "exampleZh": "孩子們每天應該至少睡足八小時。", "memoryTip": "ee 雙字母發長母音 /iː/"},
    {"word": "wake", "chunk": "wake", "ipa": "/weɪk/", "pos": "v.", "zh": "醒來、叫醒", "category": "日常動作與作息", "collocation": "wake up early", "example": "I usually wake up at six thirty in the morning.", "exampleZh": "我通常早上六點半醒來。", "memoryTip": "Magic E 使 a 發長母音 /eɪ/"},

    # 4. 食物、餐點與飲料 (Food & Drinks)
    {"word": "breakfast", "chunk": "break - fast", "ipa": "/ˈbrɛk.fəst/", "pos": "n.", "zh": "早餐", "category": "飲食與餐點", "collocation": "have breakfast", "example": "Eating a healthy breakfast gives you energy all morning.", "exampleZh": "吃一頓健康的早餐能給你整個早晨滿滿活力。", "memoryTip": "break (打破) + fast (斷食) ➔ 破除夜間斷食的第一餐"},
    {"word": "lunch", "chunk": "lunch", "ipa": "/lʌntʃ/", "pos": "n.", "zh": "午餐", "category": "飲食與餐點", "collocation": "have lunch", "example": "We eat our lunch in the classroom at noon.", "exampleZh": "我們中午在教室裡吃午餐。", "memoryTip": "u 發短音 /ʌ/，nch 發 /ntʃ/"},
    {"word": "dinner", "chunk": "din - ner", "ipa": "/ˈdɪn.ɚ/", "pos": "n.", "zh": "晚餐", "category": "飲食與餐點", "collocation": "cook dinner", "example": "What would you like to have for dinner tonight?", "exampleZh": "你今晚晚餐想吃什麼呢？", "memoryTip": "雙寫 n，din 發短音 /dɪn/ + ner /ɚ/"},
    {"word": "water", "chunk": "wa - ter", "ipa": "/ˈwɑː.tɚ/", "pos": "n.", "zh": "水 (不可數)", "category": "飲食與餐點", "collocation": "drink water", "example": "Drinking plenty of water keeps your body healthy.", "exampleZh": "多喝水能讓身體保持健康。", "memoryTip": "wa 發 /wɑː/ + ter 發 /tɚ/"},
    {"word": "milk", "chunk": "milk", "ipa": "/mɪlk/", "pos": "n.", "zh": "牛奶 (不可數)", "category": "飲食與餐點", "collocation": "a glass of milk", "example": "Drinking warm milk helps people fall asleep faster.", "exampleZh": "喝熱牛奶能幫助人們更快入睡。", "memoryTip": "CVC 短母音 /ɪ/"},
    {"word": "apple", "chunk": "ap - ple", "ipa": "/ˈæp.əl/", "pos": "n.", "zh": "蘋果", "category": "飲食與餐點", "collocation": "an apple a day", "example": "An apple a day keeps the doctor away.", "exampleZh": "一天一蘋果，醫生遠離我。", "memoryTip": "雙寫 p，a 發短音 /æ/ + ple 發成音節 /əl/"},
    {"word": "banana", "chunk": "ba - nan - a", "ipa": "/bəˈnæn.ə/", "pos": "n.", "zh": "香蕉", "category": "飲食與餐點", "collocation": "peel a banana", "example": "Monkeys love eating ripe yellow bananas.", "exampleZh": "猴子很喜歡吃成熟的黃香蕉。", "memoryTip": "ba (/bə/) + nan (/næn/) + a (/ə/)"},
    {"word": "bread", "chunk": "bread", "ipa": "/brɛd/", "pos": "n.", "zh": "麵包 (不可數)", "category": "飲食與餐點", "collocation": "a slice of bread", "example": "I like to eat toasted bread with sweet strawberry jam.", "exampleZh": "我喜歡吃烤麵包塗草莓果醬。", "memoryTip": "ea 不規則發短母音 /ɛ/ (同 head, ready)"},
    {"word": "vegetable", "chunk": "veg - e - ta - ble", "ipa": "/ˈvɛdʒ.tə.bəl/", "pos": "n.", "zh": "蔬菜", "category": "飲食與餐點", "collocation": "fresh vegetables", "example": "Eating fresh green vegetables is good for digestion.", "exampleZh": "吃新鮮綠色蔬菜對消化很有益處。", "memoryTip": "g 在 e 前發軟音 /dʒ/，第二音節常弱讀省略"},
    {"word": "fruit", "chunk": "fruit", "ipa": "/fruːt/", "pos": "n.", "zh": "水果", "category": "飲食與餐點", "collocation": "fresh fruit", "example": "Taiwan is famous for producing high-quality tropical fruit.", "exampleZh": "台灣以盛產高品質熱帶水果而聞名。", "memoryTip": "ui 字母組合發長音 /uː/ (同 juice)"},

    # 5. 動物與自然生態 (Animals & Nature)
    {"word": "dog", "chunk": "dog", "ipa": "/dɔːɡ/", "pos": "n.", "zh": "狗、小狗", "category": "動物與生態", "collocation": "walk the dog", "example": "My dog wags its tail happily whenever I come home.", "exampleZh": "每當我回家時，我的狗都會高興地搖尾巴。", "memoryTip": "CVC 結構，o 發短音 /ɔː/"},
    {"word": "cat", "chunk": "cat", "ipa": "/kæt/", "pos": "n.", "zh": "貓、小貓", "category": "動物與生態", "collocation": "pet a cat", "example": "The little cat is sleeping in the warm sunshine.", "exampleZh": "小貓正在溫暖的陽光下熟睡。", "memoryTip": "CVC 結構，a 發短音 /æ/"},
    {"word": "bird", "chunk": "bird", "ipa": "/bɝːd/", "pos": "n.", "zh": "鳥", "category": "動物與生態", "collocation": "birds singing", "example": "Early in the morning, birds sing songs in the tree.", "exampleZh": "清晨時分，鳥兒在樹上歌唱。", "memoryTip": "ir 字母組合發捲舌長母音 /ɝː/"},
    {"word": "rabbit", "chunk": "rab - bit", "ipa": "/ˈræb.ɪt/", "pos": "n.", "zh": "兔子", "category": "動物與生態", "collocation": "white rabbit", "example": "The white rabbit has long ears and red eyes.", "exampleZh": "白兔有著長長的耳朵和紅色的眼睛。", "memoryTip": "雙寫 b，rab 短音 /ræb/ + bit 短音 /bɪt/"},
    {"word": "elephant", "chunk": "el - e - phant", "ipa": "/ˈɛl.ə.fənt/", "pos": "n.", "zh": "大象", "category": "動物與生態", "collocation": "African elephant", "example": "The elephant has a long trunk and huge ears.", "exampleZh": "大象有一條長長的鼻子和大大的耳朵。", "memoryTip": "ph 發 /f/，el (/ɛl/) + e (/ə/) + phant (/fənt/)"},
    {"word": "monkey", "chunk": "mon - key", "ipa": "/ˈmʌŋ.ki/", "pos": "n.", "zh": "猴子", "category": "動物與生態", "collocation": "clever monkey", "example": "The clever monkey climbed up the tall tree swiftly.", "exampleZh": "那隻聰明的猴子敏捷地爬上了大樹。", "memoryTip": "ey 發長母音 /i/，mon 發 /mʌŋ/"},
    {"word": "weather", "chunk": "weath - er", "ipa": "/ˈwɛð.ɚ/", "pos": "n.", "zh": "天氣 (不可數)", "category": "自然與天氣", "collocation": "sunny weather", "example": "The weather in spring is usually pleasant and warm.", "exampleZh": "春天的天氣通常令人愉悅且溫暖。", "memoryTip": "ea 發短音 /ɛ/，th 發濁音 /ð/，er 發 /ɚ/"},
    {"word": "sunny", "chunk": "sun - ny", "ipa": "/ˈsʌn.i/", "pos": "adj.", "zh": "晴朗的、陽光充足的", "category": "自然與天氣", "collocation": "sunny day", "example": "We decided to go for a picnic on this sunny morning.", "exampleZh": "我們決定在這個晴朗的早晨去野餐。", "memoryTip": "sun (太陽) + 雙寫 n + -y (形容詞)"},
    {"word": "rainy", "chunk": "rain - y", "ipa": "/ˈreɪ.ni/", "pos": "adj.", "zh": "下雨的、多雨的", "category": "自然與天氣", "collocation": "rainy season", "example": "Bring an umbrella because it will be rainy this afternoon.", "exampleZh": "帶把雨傘，因為今天下午會下雨。", "memoryTip": "rain (雨) + -y (形容詞)，ai 發長音 /eɪ/"},
    {"word": "cloudy", "chunk": "cloud - y", "ipa": "/ˈklaʊ.di/", "pos": "adj.", "zh": "多雲的、陰天的", "category": "自然與天氣", "collocation": "cloudy sky", "example": "The sky turned cloudy before the heavy rain started.", "exampleZh": "在大雨開始前，天空轉為多雲陰暗。", "memoryTip": "cloud (雲) + -y (形容詞)，ou 發 /aʊ/"},

    # 6. 顏色、數字與外觀 (Colors, Numbers & Appearance)
    {"word": "happy", "chunk": "hap - py", "ipa": "/ˈhæp.i/", "pos": "adj.", "zh": "快樂的、高興的", "category": "感受與特質", "collocation": "happy smile", "example": "Everyone felt happy after hearing the good news.", "exampleZh": "每個人在聽到好消息後都感到十分高興。", "memoryTip": "雙寫 p，hap 發短音 /æ/ + py 發 /i/"},
    {"word": "angry", "chunk": "an - gry", "ipa": "/ˈæŋ.ɡri/", "pos": "adj.", "zh": "生氣的、憤怒的", "category": "感受與特質", "collocation": "get angry", "example": "Mom was angry when she saw the broken vase.", "exampleZh": "媽媽看到打碎的花瓶時很生氣。", "memoryTip": "an 發 /æŋ/ + gry 發 /ɡri/"},
    {"word": "tired", "chunk": "tired", "ipa": "/taɪɚd/", "pos": "adj.", "zh": "疲累的、疲倦的", "category": "感受與特質", "collocation": "feel tired", "example": "After running for an hour, I felt very tired.", "exampleZh": "跑了一小時後，我感到非常疲倦。", "memoryTip": "ire 發三合母音 /aɪɚ/，加 d"},
    {"word": "hungry", "chunk": "hun - gry", "ipa": "/ˈhʌŋ.ɡri/", "pos": "adj.", "zh": "飢餓的、肚餓的", "category": "感受與特質", "collocation": "feel hungry", "example": "The hungry boy ate three sandwiches in five minutes.", "exampleZh": "飢餓的男孩在五分鐘內吃了三個三明治。", "memoryTip": "u 發短音 /ʌ/，hun 發 /hʌŋ/ + gry /ɡri/"},
    {"word": "thirsty", "chunk": "thirs - ty", "ipa": "/ˈθɝː.sti/", "pos": "adj.", "zh": "口渴的", "category": "感受與特質", "collocation": "feel thirsty", "example": "After playing basketball, the students were very thirsty.", "exampleZh": "打完籃球後，學生們都非常口渴。", "memoryTip": "th 發清音 /θ/，ir 發捲舌音 /ɝː/"},
    {"word": "beautiful", "chunk": "beau - ti - ful", "ipa": "/ˈbjuː.t̬ə.fəl/", "pos": "adj.", "zh": "美麗的、漂亮的", "category": "感受與特質", "collocation": "beautiful flowers", "example": "The park is filled with colorful and beautiful flowers.", "exampleZh": "公園裡開滿了色彩繽紛又美麗的花朵。", "memoryTip": "beau 發 /bjuː/ + ti (/tə/) + ful (/fəl/)"},
    {"word": "bright", "chunk": "bright", "ipa": "/braɪt/", "pos": "adj.", "zh": "明亮的、聰明的", "category": "感受與特質", "collocation": "bright idea", "example": "The sun is very bright, so you should wear sunglasses.", "exampleZh": "陽光非常耀眼，所以你應該戴太陽眼鏡。", "memoryTip": "igh 發長母音 /aɪ/，gh 不發音"},
    {"word": "strong", "chunk": "strong", "ipa": "/strɑːŋ/", "pos": "adj.", "zh": "強壯的、堅固的", "category": "感受與特質", "collocation": "strong wind", "example": "Exercising regularly makes your muscles strong.", "exampleZh": "規律運動能讓你的肌肉強壯。", "memoryTip": "str 三輔音 + ong 發 /ɑːŋ/"},
    {"word": "careful", "chunk": "care - ful", "ipa": "/ˈkɛr.fəl/", "pos": "adj.", "zh": "小心的、仔細的", "category": "感受與特質", "collocation": "be careful", "example": "Be careful when you cross the busy street.", "exampleZh": "穿越繁忙的馬路時要格外小心。", "memoryTip": "care (注意) + -ful (充滿)"},
    {"word": "polite", "chunk": "po - lite", "ipa": "/pəˈlaɪt/", "pos": "adj.", "zh": "有禮貌的、客氣的", "category": "感受與特質", "collocation": "polite manners", "example": "It is polite to say thank you when receiving a gift.", "exampleZh": "收到禮物時說聲謝謝是有禮貌的表現。", "memoryTip": "Magic E 使 i 發長母音 /aɪ/"}
]

JUNIOR_HIGH_WORDS = [
    # 1. 會考必背不規則三態動詞 (Irregular Verbs Mastery)
    {"word": "choose", "chunk": "choose", "ipa": "/tʃuːz/", "pos": "v.", "zh": "選擇、挑選 (三態 choose-chose-chosen)", "category": "會考不規則動詞", "collocation": "choose wisely", "example": "You have to choose one option from the four choices.", "exampleZh": "你必須從四個選項中挑選一個。", "memoryTip": "三態：choose /tʃuːz/ ➔ chose /tʃoʊz/ ➔ chosen /ˈtʃoʊ.zən/"},
    {"word": "freeze", "chunk": "freeze", "ipa": "/friːz/", "pos": "v.", "zh": "結冰、凍結 (三態 freeze-froze-frozen)", "category": "會考不規則動詞", "collocation": "freeze into ice", "example": "Water freezes into ice at zero degrees Celsius.", "exampleZh": "水在攝氏零度時會結成冰。", "memoryTip": "三態：freeze ➔ froze ➔ frozen"},
    {"word": "rise", "chunk": "rise", "ipa": "/raɪz/", "pos": "v.", "zh": "上升、升起 (三態 rise-rose-risen，不及物)", "category": "會考不規則動詞", "collocation": "the sun rises", "example": "The sun rises in the east and sets in the west.", "exampleZh": "太陽從東方升起，從西方落下。", "memoryTip": "不及物動詞！不接受詞。三態：rise ➔ rose ➔ risen"},
    {"word": "raise", "chunk": "raise", "ipa": "/reɪz/", "pos": "v.", "zh": "舉起、撫養、籌募 (及物動詞)", "category": "會考易混淆動詞", "collocation": "raise one's hand", "example": "Please raise your hand if you have any questions.", "exampleZh": "如果你有任何問題，請舉手。", "memoryTip": "及物動詞！後方必接名詞受詞。規則變化：raise-raised-raised"},
    {"word": "lead", "chunk": "lead", "ipa": "/liːd/", "pos": "v.", "zh": "引導、帶領、導致 (三態 lead-led-led)", "category": "會考不規則動詞", "collocation": "lead to (導致)", "example": "Hard work and dedication will lead to great success.", "exampleZh": "努力與投入將會引導走向巨大的成功。", "memoryTip": "三態：lead ➔ led ➔ led。注意 lead to 常考片語！"},
    {"word": "spread", "chunk": "spread", "ipa": "/sprɛd/", "pos": "v.", "zh": "傳播、蔓延 (三態同形 spread-spread-spread)", "category": "會考不規則動詞", "collocation": "spread rumors", "example": "False news can spread very quickly across the internet.", "exampleZh": "假消息在網路上傳播得非常快速。", "memoryTip": "三態同形：spread ➔ spread ➔ spread，ea 發短母音 /ɛ/"},
    {"word": "grow", "chunk": "grow", "ipa": "/ɡroʊ/", "pos": "v.", "zh": "成長、種植 (三態 grow-grew-grown)", "category": "會考不規則動詞", "collocation": "grow up (長大)", "example": "Vegetables grow very well in this fertile soil.", "exampleZh": "蔬菜在這片肥沃的土壤中生長得非常好。", "memoryTip": "三態：grow ➔ grew /ɡruː/ ➔ grown /ɡroʊn/"},
    {"word": "hide", "chunk": "hide", "ipa": "/haɪd/", "pos": "v.", "zh": "躲藏、隱藏 (三態 hide-hid-hidden)", "category": "會考不規則動詞", "collocation": "hide and seek", "example": "The little cat hid under the sofa during the thunderstorm.", "exampleZh": "在雷雨期間，小貓躲在沙發底下。", "memoryTip": "三態：hide ➔ hid ➔ hidden"},
    {"word": "steal", "chunk": "steal", "ipa": "/stiːl/", "pos": "v.", "zh": "偷竊 (三態 steal-stole-stolen)", "category": "會考不規則動詞", "collocation": "steal money", "example": "The thief stole a bicycle from outside the store.", "exampleZh": "小偷從店門口偷走了一輛腳踏車。", "memoryTip": "三態：steal ➔ stole ➔ stolen"},
    {"word": "shake", "chunk": "shake", "ipa": "/ʃeɪk/", "pos": "v.", "zh": "搖動、握手 (三態 shake-shook-shaken)", "category": "會考不規則動詞", "collocation": "shake hands", "example": "They shook hands politely after concluding the deal.", "exampleZh": "達成協議後，他們禮貌地握了手。", "memoryTip": "三態：shake ➔ shook ➔ shaken"},

    # 2. 科技、數位生活與媒體 (Technology & Digital Life)
    {"word": "technology", "chunk": "tech - nol - o - gy", "ipa": "/tɛkˈnɑː.lə.dʒi/", "pos": "n.", "zh": "科技、技術", "category": "科技與數位生活", "collocation": "modern technology", "example": "Modern technology makes communication across borders instant.", "exampleZh": "現代科技使得跨國溝通變得即時迅捷。", "memoryTip": "techno (技術) + -logy (學問/學科)"},
    {"word": "internet", "chunk": "in - ter - net", "ipa": "/ˈɪn.tɚ.nɛt/", "pos": "n.", "zh": "網際網路、網路", "category": "科技與數位生活", "collocation": "surf the internet", "example": "Students search for reference materials on the internet.", "exampleZh": "學生們在網際網路上搜尋參考資料。", "memoryTip": "inter- (相互/國際) + net (網絡)"},
    {"word": "smartphone", "chunk": "smart - phone", "ipa": "/ˈsmɑːrt.foʊn/", "pos": "n.", "zh": "智慧型手機", "category": "科技與數位生活", "collocation": "use a smartphone", "example": "Do not look at your smartphone screen while walking.", "exampleZh": "走路時請不要盯著智慧型手機螢幕看。", "memoryTip": "smart (聰明的) + phone (電話)"},
    {"word": "software", "chunk": "soft - ware", "ipa": "/ˈsɑːft.wɛr/", "pos": "n.", "zh": "軟體 (不可數)", "category": "科技與數位生活", "collocation": "install software", "example": "You need to update your antivirus software regularly.", "exampleZh": "你需要定期更新你的防毒軟體。", "memoryTip": "soft (軟) + ware (製品)，不可數名詞！"},
    {"word": "device", "chunk": "de - vice", "ipa": "/dɪˈvaɪs/", "pos": "n.", "zh": "電子設備、裝置", "category": "科技與數位生活", "collocation": "electronic device", "example": "Turn off all electronic devices during the airplane takeoff.", "exampleZh": "飛機起飛期間請關閉所有電子裝置。", "memoryTip": "de- + vice (發音 /vaɪs/)"},
    {"word": "application", "chunk": "ap - pli - ca - tion", "ipa": "/ˌæp.ləˈkeɪ.ʃən/", "pos": "n.", "zh": "應用程式 (App)、申請", "category": "科技與數位生活", "collocation": "download an application", "example": "This learning application helps students practice English listening.", "exampleZh": "這款學習應用程式能幫助學生練習英語聽力。", "memoryTip": "apply (申請/應用) ➔ application"},
    {"word": "connect", "chunk": "con - nect", "ipa": "/kəˈnɛkt/", "pos": "v.", "zh": "連接、連結", "category": "科技與數位生活", "collocation": "connect to Wi-Fi", "example": "My tablet cannot connect to the school wireless network.", "exampleZh": "我的平板無法連上學校的無線網路。", "memoryTip": "con- (共同) + nect (綁定/連接)"},
    {"word": "information", "chunk": "in - for - ma - tion", "ipa": "/ˌɪn.fɚˈmeɪ.ʃən/", "pos": "n.", "zh": "資訊、消息 (不可數)", "category": "科技與數位生活", "collocation": "useful information", "example": "The official website provides reliable information for tourists.", "exampleZh": "官方網站為遊客提供可靠的旅遊資訊。", "memoryTip": "注意：information 在英文中恆為不可數名詞！"},

    # 3. 環境保護、生態與全球議題 (Environment & Ecology)
    {"word": "environment", "chunk": "en - vi - ron - ment", "ipa": "/ɪnˈvaɪ.rən.mənt/", "pos": "n.", "zh": "自然環境", "category": "環境與生態", "collocation": "protect the environment", "example": "We should reduce plastic waste to protect the environment.", "exampleZh": "我們應該減少塑膠垃圾以保護環境。", "memoryTip": "environ (環繞) + -ment (名詞尾綴)"},
    {"word": "pollution", "chunk": "pol - lu - tion", "ipa": "/pəˈluː.ʃən/", "pos": "n.", "zh": "污染 (空氣/水源等)", "category": "環境與生態", "collocation": "air pollution", "example": "Air pollution has become a serious issue in big cities.", "exampleZh": "空氣污染已經成為大城市中的嚴重問題。", "memoryTip": "pollute (污染) + -tion (名詞尾綴)"},
    {"word": "recycle", "chunk": "re - cy - cle", "ipa": "/ˌriːˈsaɪ.kəl/", "pos": "v.", "zh": "回收、循環利用", "category": "環境與生態", "collocation": "recycle paper and plastic", "example": "Our school encourages all students to recycle plastic bottles.", "exampleZh": "我們學校鼓勵所有學生回收寶特瓶。", "memoryTip": "re- (再) + cycle (循環) ➔ 資源回收"},
    {"word": "climate", "chunk": "cli - mate", "ipa": "/ˈklaɪ.mət/", "pos": "n.", "zh": "氣候 (長期平均狀態)", "category": "環境與生態", "collocation": "climate change", "example": "Global climate change causes more frequent extreme weather events.", "exampleZh": "全球氣候變遷造成更頻繁的極端天氣事件。", "memoryTip": "cli 發 /klaɪ/ + mate 弱讀 /mət/"},
    {"word": "energy", "chunk": "en - er - gy", "ipa": "/ˈɛn.ɚ.dʒi/", "pos": "n.", "zh": "能源、精力", "category": "環境與生態", "collocation": "solar energy (太陽能)", "example": "Solar and wind power are clean renewable sources of energy.", "exampleZh": "太陽能與風力是潔淨的可再生能源。", "memoryTip": "g 在 y 前發軟音 /dʒ/，en-er-gy"},
    {"word": "protect", "chunk": "pro - tect", "ipa": "/prəˈtɛkt/", "pos": "v.", "zh": "保護、防護", "category": "環境與生態", "collocation": "protect wildlife", "example": "National parks are established to protect wild animal habitats.", "exampleZh": "設立國家公園是為了保護野生動物的棲地。", "memoryTip": "pro- (向前) + tect (覆蓋/遮蔽，如 detect)"},
    {"word": "disaster", "chunk": "dis - as - ter", "ipa": "/dɪˈzæs.tɚ/", "pos": "n.", "zh": "災害、天災", "category": "環境與生態", "collocation": "natural disaster", "example": "The severe earthquake was the worst natural disaster in years.", "exampleZh": "這場強烈地震是數年來最嚴重的自然災害。", "memoryTip": "dis- (不祥/負面) + aster (星象) ➔ 凶星降臨 ➔ 災難"},

    # 4. 人際關係、性格特質與社會生活 (Society & Character)
    {"word": "honest", "chunk": "hon - est", "ipa": "/ˈɑː.nɪst/", "pos": "adj.", "zh": "誠實的、正直的", "category": "個性與人際", "collocation": "honest answer", "example": "It is always better to be honest than to tell lies.", "exampleZh": "誠實總比說謊來得更好。", "memoryTip": "h 不發音！冠詞需使用 an honest person！"},
    {"word": "patient", "chunk": "pa - tient", "ipa": "/ˈpeɪ.ʃənt/", "pos": "adj. / n.", "zh": "有耐心的；病人", "category": "個性與人際", "collocation": "be patient with", "example": "Teachers must be patient when helping young learners.", "exampleZh": "老師在輔導年幼學習者時必須有耐心。", "memoryTip": "ti 在母音前發軟音 /ʃ/，pa-tient"},
    {"word": "generous", "chunk": "gen - er - ous", "ipa": "/ˈdʒɛn.ɚ.əs/", "pos": "adj.", "zh": "慷慨的、大方的", "category": "個性與人際", "collocation": "generous donation", "example": "He is generous enough to share his snacks with everyone.", "exampleZh": "他很大方，把自己的點心分給每個人享用。", "memoryTip": "g 在 e 前發 /dʒ/，-ous 為形容詞字尾"},
    {"word": "confident", "chunk": "con - fi - dent", "ipa": "/ˈkɑːn.fə.dənt/", "pos": "adj.", "zh": "有信心的、自信的", "category": "個性與人際", "collocation": "feel confident", "example": "Practicing speaking will make you feel confident in exams.", "exampleZh": "多練習口說能讓你在考試時感到信心充足。", "memoryTip": "con- + fid (信任/相信) + -ent"},
    {"word": "creative", "chunk": "cre - a - tive", "ipa": "/kriˈeɪ.tɪv/", "pos": "adj.", "zh": "有創意的、創造性的", "category": "個性與人際", "collocation": "creative idea", "example": "The artist came up with a creative design for the poster.", "exampleZh": "該藝術家為海報想出了一個富有創意的設計。", "memoryTip": "create (創造) + -ive (形容詞尾綴)"},
    {"word": "responsible", "chunk": "re - spon - si - ble", "ipa": "/rɪˈspɑːn.sə.bəl/", "pos": "adj.", "zh": "負責任的", "category": "個性與人際", "collocation": "be responsible for", "example": "Every team leader is responsible for organizing the tasks.", "exampleZh": "每位隊長都負責組織統籌各項任務。", "memoryTip": "re- + sponsor (擔保) + -ible (能...的)"},

    # 5. 學習認知與心智思維 (Cognitive & Academic)
    {"word": "decision", "chunk": "de - ci - sion", "ipa": "/dɪˈsɪʒ.ən/", "pos": "n.", "zh": "決定、抉擇", "category": "心智與思維", "collocation": "make a decision", "example": "Think carefully before you make an important life decision.", "exampleZh": "在做人生重大決定前務必三思。", "memoryTip": "decide (決定) ➔ decision，sion 發 /ʒən/"},
    {"word": "opinion", "chunk": "o - pin - ion", "ipa": "/əˈpɪn.jən/", "pos": "n.", "zh": "意見、觀點", "category": "心智與思維", "collocation": "in my opinion (依我之見)", "example": "In my opinion, reading books expands your worldview greatly.", "exampleZh": "依我看來，閱讀書籍能大幅開拓你的世界觀。", "memoryTip": "o (/ə/) + pin (/pɪn/) + ion (/jən/)"},
    {"word": "solution", "chunk": "so - lu - tion", "ipa": "/səˈluː.ʃən/", "pos": "n.", "zh": "解決方法、解方", "category": "心智與思維", "collocation": "find a solution to", "example": "Engineers worked around the clock to find a solution.", "exampleZh": "工程師們夜以繼日地尋找解決方法。", "memoryTip": "solve (解決) ➔ solution"},
    {"word": "experience", "chunk": "ex - pe - ri - ence", "ipa": "/ɪkˈspɪr.i.əns/", "pos": "n. / v.", "zh": "經驗 (不可數)；經歷 (可數)", "category": "心智與思維", "collocation": "learning experience", "example": "Studying abroad was a valuable experience for the teenager.", "exampleZh": "出國留學對這名青少年而言是一段寶貴的經驗。", "memoryTip": "ex- (外) + peri (嘗試/冒險) ➔ 經驗"},
    {"word": "opportunity", "chunk": "op - por - tu - ni - ty", "ipa": "/ˌɑː.pɚˈtuː.nə.t̬i/", "pos": "n.", "zh": "機會、良機", "category": "心智與思維", "collocation": "seize an opportunity", "example": "Do not miss the opportunity to study in such a fine program.", "exampleZh": "千萬不要錯過在這麼好的學程中學習的機會。", "memoryTip": "op- (朝向) + port (港口) ➔ 船隻入港之良機"},

    # 6. 會考高頻連接詞與重要副詞 (Transitions & Discourse)
    {"word": "although", "chunk": "al - though", "ipa": "/ɔːlˈðoʊ/", "pos": "conj.", "zh": "雖然、儘管 (引導讓步子句)", "category": "會考轉折與連接詞", "collocation": "although + 子句", "example": "Although it was raining hard, the game continued as planned.", "exampleZh": "雖然雨下得很大，比賽依然按計畫繼續進行。", "memoryTip": "考點提醒：英文中 although 與 but 絕不可出現在同一個句子中！"},
    {"word": "however", "chunk": "how - ev - er", "ipa": "/haʊˈɛv.ɚ/", "pos": "adv.", "zh": "然而、不過 (轉折副詞)", "category": "會考轉折與連接詞", "collocation": "However, ...", "example": "The test was very difficult. However, Jane got a high score.", "exampleZh": "考試非常困難。然而，珍依然拿到了高分。", "memoryTip": "轉折副詞！不可直接連接兩子句，常置於句首加逗號。"},
    {"word": "therefore", "chunk": "there - fore", "ipa": "/ˈðɛr.fɔːr/", "pos": "adv.", "zh": "因此、所以 (因果副詞)", "category": "會考轉折與連接詞", "collocation": "Therefore, ...", "example": "He practiced diligently every day; therefore, he won the trophy.", "exampleZh": "他每天勤奮練習；因此，他贏得了獎盃。", "memoryTip": "表結果的副詞！不可與 because 連用。"},
    {"word": "unless", "chunk": "un - less", "ipa": "/ənˈlɛs/", "pos": "conj.", "zh": "除非 (相當於 if ... not)", "category": "會考轉折與連接詞", "collocation": "unless + 現在式", "example": "We will have a picnic tomorrow unless it rains heavily.", "exampleZh": "除非下大雨，否則我們明天會去野餐。", "memoryTip": "unless 本身帶否定意味，其引導之子句不用 not！"},
    {"word": "especially", "chunk": "es - pe - cial - ly", "ipa": "/ɪˈspɛʃ.əl.i/", "pos": "adv.", "zh": "特別是、尤其是", "category": "會考轉折與連接詞", "collocation": "especially in summer", "example": "I enjoy outdoor sports, especially cycling along the river.", "exampleZh": "我喜歡戶外運動，特別是沿著河岸騎腳踏車。", "memoryTip": "especial (特殊的) + -ly (副詞尾綴)"},
    {"word": "immediately", "chunk": "im - me - di - ate - ly", "ipa": "/ɪˈmiː.di.ət.li/", "pos": "adv.", "zh": "立刻、馬上", "category": "會考轉折與連接詞", "collocation": "reply immediately", "example": "When the fire alarm rang, everyone evacuated immediately.", "exampleZh": "火警鈴響起時，每個人都立刻疏散撤離。", "memoryTip": "im- (不/無) + mediate (中間媒介) ➔ 不隔時間 ➔ 立刻"}
]

print(f"Loaded {len(ELEMENTARY_WORDS)} curated elementary words.")
print(f"Loaded {len(JUNIOR_HIGH_WORDS)} curated junior high words.")
