const {chromium}=require('C:/Users/User/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=path.resolve('dist');const report={date:'2026-10-10',checks:[],errors:[]};
const cards=JSON.parse(fs.readFileSync('dist/mnemonics/cards.json','utf8'));assert.equal(cards.length,1000);assert.equal(new Set(cards.map(c=>c.word)).size,1000);
for(const c of cards){assert.ok(c.cue&&c.scene&&c.icon&&c.arpabet&&c.sounds,c.word);assert.ok(fs.statSync(`dist/mnemonics/audio/${c.word}.mp3`).size>1000,c.word);assert.ok(c.audio.end>c.audio.start);assert.ok(/^[ɑæʌɔaʊɪbdðɛɝefɡhijklmnoʊprsʃtθuvwjzʒŋɚə /]+$/u.test(c.sounds),c.word);}
report.checks.push({distinctCards:1000,mp3Files:1000,written:cards.filter(c=>c.kind==='編寫聯想').length});
const server=http.createServer((req,res)=>{let p=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(p!==root&&!p.startsWith(root+path.sep)){res.writeHead(403);res.end();return;}if(fs.existsSync(p)&&fs.statSync(p).isDirectory())p=path.join(p,'index.html');fs.readFile(p,(err,data)=>{if(err){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.mjs':'text/javascript','.js':'text/javascript','.css':'text/css','.json':'application/json','.mp3':'audio/mpeg'})[path.extname(p)]||'application/octet-stream');res.end(data);});});
(async()=>{await new Promise(resolve=>server.listen(8092,'127.0.0.1',resolve));const browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage();page.on('pageerror',e=>report.errors.push(e.message));
for(const width of [320,390,768,1280]){await page.setViewportSize({width,height:900});await page.goto('http://127.0.0.1:8092/mnemonics/');await page.locator('.word-card').first().waitFor();assert.equal(await page.locator('.word-card').count(),12);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow ${width}`);await page.locator('#search').fill('俺不能死');assert.equal(await page.locator('.word-card').count(),1);assert.equal(await page.locator('h2').innerText(),'ambulance');assert.equal(await page.locator('.answer').isVisible(),false);await page.locator('[data-reveal]').click();await page.getByText('救護車',{exact:true}).waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`QA-mnemonics-${width}-2026-10-10.png`,fullPage:true});report.checks.push({width,search:true,reveal:true,overflow:false});}
await page.locator('[data-play]').click();await page.waitForFunction(()=>document.querySelector('[data-play]').getAttribute('aria-pressed')==='true');
await page.waitForFunction(()=>document.querySelector('[data-play]').getAttribute('aria-pressed')==='false');
assert.ok(!(await page.locator('#notice').innerText()).includes('無法'));report.checks.push({realBrowserMp3:'ambulance decoded, played and ended'});
// Decode a short, middle and last word as well, without a speech API stub.
for(const word of [cards[1].word,cards[500].word,cards[999].word]){const result=await page.evaluate(async word=>{const a=new Audio(`audio/${word}.mp3`);await new Promise((resolve,reject)=>{a.onloadedmetadata=resolve;a.onerror=reject;});return {duration:a.duration};},word);assert.ok(result.duration>0&&result.duration<15);report.checks.push({word,decodedDuration:result.duration});}
await page.locator('.custom summary').click();await page.locator('textarea').fill('俺不能死！ <img src=x onerror=alert(1)>');await page.locator('[data-save]').click();assert.ok(await page.locator('.cue').innerText().then(x=>x.includes('<img')));assert.equal(await page.locator('.cue img').count(),0);
await page.reload();await page.locator('.word-card').first().waitFor();await page.locator('#search').fill('ambulance');await page.locator('[data-reveal]').click();assert.ok((await page.locator('.cue').innerText()).includes('俺不能死！'));await page.locator('[data-grade][data-correct="false"]').click();assert.ok((await page.locator('.word-card .status').last().innerText()).includes('已練習 1 次'));await page.locator('#review').selectOption('due');assert.equal(await page.locator('.word-card').count(),0);await page.evaluate(()=>{const k='eq-mnemonics-v1',d=JSON.parse(localStorage.getItem(k));d.progress['fc-el-0552'].due=Date.now()-1;localStorage.setItem(k,JSON.stringify(d));});await page.reload();await page.locator('.word-card').first().waitFor();await page.locator('#review').selectOption('due');assert.equal(await page.locator('.word-card').count(),1);report.checks.push({customPersists:true,escaped:true,reviewDue:true});
await page.locator('#review').selectOption('all');await page.locator('#kind').selectOption('自動聲音聯想草稿');assert.equal(await page.locator('.word-card').count(),12);await page.locator('#next').click();assert.equal(await page.locator('#page').innerText(),'2 / 78 頁');await page.locator('#kind').selectOption('編寫聯想');assert.ok((await page.locator('#count').innerText()).startsWith('67 /'));report.checks.push({pagination:true,typeFilter:true});
await page.locator('#import').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({version:1,custom:{'fc-el-0552':'新口訣'},progress:{}}))});await page.getByText('已合併匯入備份。').waitFor();await page.locator('#search').fill('ambulance');await page.locator('[data-reveal]').click();assert.equal(await page.locator('.cue').innerText(),'新口訣');const download=page.waitForEvent('download');await page.locator('#export').click();assert.equal((await download).suggestedFilename(),'english-quest-mnemonics-backup.json');report.checks.push({backupImportExport:true});
const decoded=await page.evaluate(async words=>{const ctx=new AudioContext(),results=[];let next=0;await Promise.all(Array.from({length:8},async()=>{while(next<words.length){const word=words[next++];const r=await fetch(`audio/${word}.mp3`);if(!r.ok)throw Error(word);const b=await ctx.decodeAudioData(await r.arrayBuffer());const samples=b.getChannelData(0);let peak=0;for(let i=0;i<samples.length;i+=32)peak=Math.max(peak,Math.abs(samples[i]));if(b.duration<=0||peak<.001)throw Error('empty audio '+word);results.push({word,duration:b.duration});}}));await ctx.close();return results;},cards.map(c=>c.word));assert.equal(decoded.length,1000);report.checks.push({allMp3Decoded:1000,nonSilent:1000});
await page.setViewportSize({width:320,height:900});await page.locator('#search').fill('');await page.locator('#kind').selectOption('');for(let n=0;n<84;n++){assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`all-card page ${n}`);if(n<83)await page.locator('#next').click();}assert.equal(await page.locator('.word-card').count(),4);report.checks.push({allCardsNarrowLayout:1000,pages:84});
assert.deepEqual(report.errors,[]);fs.writeFileSync('QA-MNEMONICS-2026-10-10.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();server.close();})().catch(e=>{console.error(e);server.close();process.exit(1);});
